### ISSUE TITLE
First and last names on registration form is disabled

### ISSUE THREAD

**Issue by lauweijie** [SparkDevNetwork/Rock#4989] opened 2022-04-27 04:30 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words

![Screenshot](https://user-images.githubusercontent.com/2845328/165439963-6dec68ae-e1ea-4665-9753-8daf06da33eb.png)

### Description

First and last names should be editable when registrant is not in the same family as logged in user.

### Steps to Reproduce

1. Go to https://rock.rocksolidchurchdemo.com/web/event-registrations?RegistrationTemplateId=3
2. Set "Registrants In Same Family" to "Ask" and "Show Family Members" to "Yes"
3. Go to https://rocksolidchurchdemo.com/Registration?RegistrationInstanceId=1 and click "Next"
4. Select "None of the above" for "Registrant is in the same immediate family as"

**Expected behavior:**

First and last names should be blanked out and editable.

**Actual behavior:**

First and last names are populated to the current logged in user and are the fields are disabled.

**Additional edge cases:**

1. Click on "Alisha Marble" for "Registrant is in the same immediate family as"
2. Observe that "Family Member to Register" is defaulted to blank but First and Last names are populated to Alisha Marble and disabled; to make those fields editable, one has to select "Alisha Marble" or any other item in the list before reselecting the blank option

![Screenshot](https://user-images.githubusercontent.com/2845328/165440801-02890cf6-e930-465b-8d02-a30a0ca6b5ff.png)

### Versions

* **Rock Version:** Rock McKinley 13.3 (1.13.3.1)
* **Client Culture Setting:** en-SG

**Comment by bmurphy-dev** [comment] 2022-04-27 10:02
This may be a dupe of [https://github.com/SparkDevNetwork/Rock/issues/4942](url) fixed in v13.4

**Comment by crayzd92** [comment] 2022-04-27 15:18
Closing as a duplicate of https://github.com/SparkDevNetwork/Rock/issues/4942

**Closed by crayzd92** 2022-04-27 15:18 UTC
