### ISSUE TITLE
Dynamic Data block does not honor checkboxes when sending to Merge Template or exporting to Excel

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#3054] opened 2018-06-11 18:28 UTC
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
From Chris Funk in [Slack ](https://rockrms.slack.com/archives/C0AFERQ7M/p1528488184000135):

Checked rows in a Dynamic Data block grid are ignored when using the "Merge Template" or "Export to Excel" buttons.

This is inconsistent with the behavior on Group Viewer grids, Data View grids, Report grids, and Dynamic Report grids, where only the checked people are used on the merge template or included in the export.

It is also inconsistent with the behavior of the "Communicate" button, the "Merge People" button, and the "Bulk Update" button on the same Dynamic Data block; using these other buttons only applies the action to the checked rows.

### Steps to Reproduce
1. Create a Dynamic Data block that returns at least a Person Id column (called "Id"). Ensure that "Person Report" is selected in the block configuration

On the demo server, I used the following query:

```
SELECT
    p.[Id]
    ,p.[FirstName] + ' ' + p.[LastName] "Person"
    ,g.[Name] "Group"
FROM
    [GroupMember] gm
    INNER JOIN [Group] g ON gm.[GroupId] = g.[Id] AND g.[Name] = 'Gilbert Group'
    INNER JOIN [Person] p ON p.[Id] = gm.[PersonId]
```

which results in a grid with (6) people in it.

1. Select a subset of these individuals. I selected only Brian Gilbert and Wendy Gilbert, for instance.
1. Click the "Merge Template" or "Export to Excel" button

**Expected behavior:**

Only the checked rows (2 in my above example) should be passed to the Merge Template or exported to Excel.

**Actual behavior:**

In both cases, the resulting data includes the complete grid (6 people) rather than only the selected data (2 people).

### Versions
* **Rock Version:** [7.3, 7.4 beta]
* **Client Culture Setting:** [EN-US]

**Comment by ethan-sparkdevnetwork** [comment] 2018-07-02 16:35
Excel and merge template now follow the checkboxes for all grids using a DataTable as the source.

**Comment by tscrip** [comment] 2019-03-18 13:48
Can you guys confirm this change was not pulled out of Rock 8.6? I am seeing this exact issue on 8.6.

**Comment by ethan-sparkdevnetwork** [comment] 2019-03-27 23:27
Unable to reproduce this issue. I did find an IOOR exception when the displayed number of rows in the grid is smaller than the dataset. This is fixed in https://github.com/SparkDevNetwork/Rock/commit/bfe2373f4329993b06be803469d8caf57258339a

Sent rockchat IM to Tyler asking for more info on how he got the error.

**Closed** 2019-04-17 17:22 UTC
Labels: Fixed in v8.8, Priority: Low, Status: Available, Status: Confirmed, Topic: Reporting, Type: Bug, x-Fixed in v8.1
