### ISSUE TITLE
Adding an Attribute to an Event Detail - shows duplicate drop downs for multiple calendars that causes exception

### ISSUE THREAD

**Issue by winmastr** [SparkDevNetwork/Rock#3042] opened 2018-06-05 19:02 UTC
When creating an Event Item, If you select Multiple Calendars and have an Attribute Value field associated, when selecting the Attribute Panel, it displays a Selection ability for both or all Calendars that have been selected. If the user thinks they need to select the same attribute for both calendars, an exception for requiring unique ids is created. Exception is noted below. Selecting the attribute ONCE for one calendar, does place it on both so the UI shouldn't display the attribute selector twice (in this instance)

Version 7.4

![<a href="https://user-images.githubusercontent.com/24417039/40997408-2dc6b9c6-68ca-11e8-8109-495e6bdef499.jpg">https://user-images.githubusercontent.com/24417039/40997408-2dc6b9c6-68ca-11e8-8109-495e6bdef499.jpg</a> attribute!UNITO-UNDERSCORE!dup]()
[[https://github.com/SparkDevNetwork/Rock/files/2073647/attrbute_excep.txt](https://github.com/SparkDevNetwork/Rock/files/2073647/attrbute_excep.txt) attrbute_excep.txt ]()

**Comment by winmastr** [comment] 2018-06-12 16:04
Anything new on this? I'm not sure that all post get core team follow up.

**Comment by cabal95** [comment] 2018-06-12 16:10
@winmastr Since this is a 7.4 report and most people are not on 7.4 it might take a while for somebody to be able to test and replicate this.  It would also help if you included _exact_ steps to replicate the problem starting with "login to rock and then...".

**Comment by winmastr** [comment] 2018-06-12 16:36
Thank you Daniel for the response. 
Going to Event Calendar page. 1) Select Public, select EDIT 2)Select Event attribute Panel 3) ADD Department Category Attribute (It is a Defined Value Type with a list of Depts). Save the Change.
4) Open Internal Calendar. Follow the same steps as outlined above.
  When you then go to add a new Event Item to Calendar, and select both public and internal calendar by checkmark, the exception attached above happens.

**Comment by cabal95** [comment] 2018-06-12 16:39
If I am understanding your steps, then what you are seeing would be expected behavior. A single entity cannot have multiple attributes with the same key, and it sounds like defining two attributes with the same key and trying to apply them both to the same entity (event). Those are two separate attributes, so you would need to give them separate key values (and I would recommend separate names as well for clarity).

The system cannot merge those attributes into one, even though that is your intention, because they are two distinct attributes in the database so it has to treat them as such.

**Comment by winmastr** [comment] 2018-06-12 16:43
Actually, if you select the attribute for one calendar only, it automatically exists in the other one that is checked (not requiring you to select in a separate action step for both).

**Comment by winmastr** [comment] 2018-06-12 16:43
Actually, if you select the attribute for one calendar only, it automatically exists in the other one that is checked (not requiring you to select in a separate action step for both).

**Comment by jonedmiston** [comment] 2023-09-09 07:26
Closing as the behavior of attributes on event calendars will soon be changing where this will no longer be an issue. Targeting v17 for this update.

**Closed by jonedmiston** 2023-09-09 07:26 UTC
Labels: Type: Bug, Topic: UI
