### ISSUE TITLE
Group Registration Obsidian Block Allowing Registration without Information

### ISSUE THREAD

**Issue by deenamaher** [SparkDevNetwork/Rock#6013] opened 2024-09-18 14:54 UTC
### Description

We have an Obsidian Full Group Registration block allowing registrants to register without entering any information.

![Blank Form](https://github.com/user-attachments/assets/b4f84624-e6d7-4cc2-a47b-da6c398c3a05)

### Actual Behavior

First Name, Last Name, and Email are all required fields within this Group Registration block. However, I am able to leave all fields completely blank and still register for this group. Person registered without information shows up as a blank pending member of the group within the Group Viewer.

![Registration Success](https://github.com/user-attachments/assets/dc247ddb-edbe-42f9-b127-befd3dcdfb97)
![Group List](https://github.com/user-attachments/assets/9552da93-b105-4e6f-b75e-59774a5945b5)
![Blank Person Detail](https://github.com/user-attachments/assets/de4c34bc-7de0-4620-9bd0-4b30707e6c71)

### Expected Behavior

The Group Registration block should prevent people from registering if the required fields are left blank.

### Steps to Reproduce

- Go to People > Group Viewer and create a new group for testing
- Go to Admin Tools > CMS Configuration > Pages and create a new page
- Click "Add Block to Zone"
- Make the Block Type "Group Registration" and link it to the test group
- Visit the page by clicking the page url in the template
- Delete any information auto-filled in the Group Registration and click "Register."
- Registration for the group will be successful

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.5, 16.5 Demo Server, 16.6 Beta Server

### Client Culture Setting

en-US

**Comment by chead4** [comment] 2024-09-18 15:41
@deenamaher Thank you for reporting your first issue!  After reviewing the issue, I'm happy to share that the issue has been  resolved in v16.7 with [[commit](https://github.com/SparkDevNetwork/Rock/commit/0bf36f7f62bcdcf30b69507657475a46a9d87d73)]. Since the issue is resolved, I will go ahead and close the issue.

**Closed by chead4** 2024-09-18 15:41 UTC
