### ISSUE TITLE
Cleanup Job Timing Out On Orphaned Matrix Attributes

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4740] opened 2021-07-12 14:58 UTC
### Description

We recently started implementing some Connection Requests that integrate with Workflows and use Matrix attributes heavily. Naturally in the process of developing such Connections/Workflows you end up creating and deleting a lot of request and WF instances. 

We noticed that soon after we started our development, the nightly Rock Cleanup job started warning us about not being able to clean up orphaned attribute values. Specifically, the job shows this

![image](https://user-images.githubusercontent.com/3903408/125308083-3a20ea80-e2f6-11eb-8582-5ee39a8c89a3.png)

and the exception generated looks like this

![image](https://user-images.githubusercontent.com/3903408/125308973-fb3f6480-e2f6-11eb-9ac6-55a8984570d7.png)

The line 1129 in the cleanup job code referenced in the exception is this section:

![image](https://user-images.githubusercontent.com/3903408/125309188-2924a900-e2f7-11eb-82e1-abc7743ff9d2.png)

so it definitely has something to do with cleanup up orphaned matrix attributes.

### Steps to Reproduce

Unknown. All we did was create some Connection Requests that have attributes of type Matrix, that workflows then manipulate via Entity Attribute Set actions. In the course of developing these connection/workflows we obviously deleted some requests and workflow instances. 

**Expected behavior:**

Cleanup job would complete without error. 

**Actual behavior:**

It throws an exception related to cleaning up orphaned matrix attributes. I did find this old issue https://github.com/SparkDevNetwork/Rock/issues/4127 but that seems to be purely related to a timeout, whereas this issue seems different as it's specific to matrix attributes.

### Versions

* **Rock Version:** 12.3

**Comment by cwomack** [comment] 2021-07-14 23:25
@JimMichael I tried seeing if this timeout for the Rock Cleanup job was tied to your previous issue submissions ([#4738](https://github.com/SparkDevNetwork/Rock/issues/4738) and [#4739](https://github.com/SparkDevNetwork/Rock/issues/4739)) due to the unused/orphaned attributes that were created... but my Rock Cleanup had no issue with them. 

Even adding a Matrix as a _Field Type_ within a Connection Request Attribute (at the opportunity level), making a new Connection Request with said attributes given values, and subsequently deleting that Connection Opportunity (similar to Issue 4738) didn't reproduce the issue.  Rock Cleanup ran just fine.  Wondering if this is closer the workflow side of things than the Connection Requests.  Any progress on isolating it on your side?

**Comment by JimMichael** [comment] 2021-07-14 23:34
We have not been able to further isolate the issue. I too don’t think it’s directly related to my other issues, because the job ran fine when we had matrix attributes *defined*… it only started acting up when we started creating them and deleting connection  requests and WF instances that use them. 

I did notice a recent comment from @nairdo on this rated commit https://github.com/SparkDevNetwork/Rock/commit/bd382ca9f64e254175a26019c12f6ebdce4fb557

Is that just a coincidence? Because it sure sounds like there are still failure modes of the job particularly for orgs with lots of attributes and matrices. (Like us). Maybe our recent addition of matrix attributes just pushed us over some timeout threshold we’ve never hit before?

**Comment by JimMichael** [comment] 2021-07-21 16:56
@cwomack @nairdo Per this commit conversation https://github.com/SparkDevNetwork/Rock/commit/bd382ca9f64e254175a26019c12f6ebdce4fb557 I tried the newer query Nick mentions and it ran in 1 sec on my system and returned 105 rows (all of them appearing to be the new matrix attributes we've been "orphaning" during development.) 

But that query just returns rows and doesn't actually clean up anything, so I assume it's just part of a bigger query that does the actual deletions? Not sure how to proceed here, or if this is even being considered a bug? As it stands, we haven't been able to complete the cleanup job for a few weeks now.

**Comment by JimMichael** [comment] 2021-07-21 21:23
Just as an additional data point, I ran what I assume is the *current* query https://github.com/SparkDevNetwork/Rock/blob/bd382ca9f64e254175a26019c12f6ebdce4fb557/Rock/Model/AttributeMatrixService.Partial.cs against my test instance (full copy of production) and it took **20 min, 45 sec** to return the same 105 rows the https://github.com/SparkDevNetwork/Rock/commit/bd382ca9f64e254175a26019c12f6ebdce4fb557#commitcomment-53386405 query handles in 1 second. 

Wowzers. I guess that at least proves that this is a performance issue with the SQL and not something else weird with our db.

**Comment by nairdo** [comment] 2021-07-26 16:29
> But that query just returns rows and doesn't actually clean up anything, so I assume it's just part of a bigger query that does the actual deletions?

Yes, this was previously used in the RockCleanup job, but due to some things we discovered during those tests in that [bd382ca discussion](https://github.com/SparkDevNetwork/Rock/commit/bd382ca9f64e254175a26019c12f6ebdce4fb557#commitcomment-53843830) we have dropped that part from the job via https://github.com/SparkDevNetwork/Rock/commit/18d4be9a66af469eb27bbba6c32826051a5f24c1 which will be in v12.5.

**Closed by nairdo** 2021-07-26 16:29 UTC
