### ISSUE TITLE
Power Bi Report Viewer - Missing Navigation Pane and Right Pane

### ISSUE THREAD

**Issue by randyjreed** [SparkDevNetwork/Rock#3887] opened 2019-09-08 18:26 UTC
### Description
When using the PowerBI Report Viewer Block since the V9 upgrade the Navigation Pane and the Right Pane is missing from the viewer. If i edit the block settings they will both show up until the page is refreshed.

### Steps to Reproduce
1. Have a PowerBI account registered.
1. Add Power Bi Report Viewer Block to page and seclect your info
1. Refresh page
1. See missing navigation and side pane.

**Expected behavior:**

Pre upgrade these were visible.

**Actual behavior:**

No navigation pane or side pane are visible.

### Versions
* **Rock Version:** [Rock McKinley 9.1 (1.9.1.3)]
* **Client Culture Setting:** [en-US]

**Comment by cabal95** [comment] 2019-09-09 18:21
Debbie noted on chat that they are seeing this same problem, so marking as confirmed.

> Yes, the tabs come if you go back into your block settings and back out, but then are gone the next time you open the reports.

**Comment by debbiethurston** [comment] 2019-09-09 19:53
![BI_TabsMissing](https://user-images.githubusercontent.com/31704449/64562009-f637b580-d319-11e9-9a6e-4a0f019fe983.jpg)
![BI_Tabs](https://user-images.githubusercontent.com/31704449/64562015-f932a600-d319-11e9-9e24-abca07a788f7.jpg)

**Comment by debbiethurston** [comment] 2019-09-18 12:12
I understand why this was marked as a low priority, but it has caused our leadership to slip in confidence in Rock and has asked that we go back to the old way of reporting (Excel spreadsheet). Executives are not tolerant users nor are they casual users.  When they get a feature, they expect that it works as they were shown. Sigh

**Comment by nairdo** [comment] 2019-09-18 15:52
@debbiethurston Don't loose confidence or hope!  We actually treat all bugs as needing to be fixed (regardless of priority). We just triage them so we can make the best use of the limited developer/QA/etc resources at our disposal.  All patients in the hospital will be dealt with. :)

**Comment by MichaelAllen** [comment] 2019-09-19 16:50
@debbiethurston I don't have access to a PowerBI server to do any testing on this, but based on the code, I think I see an issue. 
Can you post the url of the iframe that block is generating when the menus are not showing up, vs when they are? (In Chrome: Right click > View Frame Source) Feel free to redact your server url, I am just interested in the url parameters.)

**Comment by debbiethurston** [comment] 2019-09-19 16:58
Not:  view-source:
https://app.powerbi.com/reportEmbed?reportId=3eaa324d-2607-4756-b452-a35997965e89&groupId=ab186a5b-d24c-4201-b1d0-ce088b57a622&w=2&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly9XQUJJLVVTLUVBU1QtQS1QUklNQVJZLXJlZGlyZWN0LmFuYWx5c2lzLndpbmRvd3MubmV0In0%3D&filterPaneEnabled=false&navContentPaneEnabled=false

Showing: view-source:
https://app.powerbi.com/reportEmbed?reportId=3eaa324d-2607-4756-b452-a35997965e89&groupId=ab186a5b-d24c-4201-b1d0-ce088b57a622&w=2&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly9XQUJJLVVTLUVBU1QtQS1QUklNQVJZLXJlZGlyZWN0LmFuYWx5c2lzLndpbmRvd3MubmV0In0%3D

**Comment by MichaelAllen** [comment] 2019-09-19 17:51
All right, so it does appear to be the issue I saw. The block is only reading the settings for showing the filter and nav panes when the block settings are opened, not when the page is loaded. 

I will work on a pull request to fix this issue, and hopefully that will make it into 9.3. But in the meantime, here is a quick fix if you are comfortable making a small change to a core block. 

You will need to edit `RockWeb/Blocks/Reporting/PowerBiReportViewer.ascx.cs`. (It is a good idea to make a copy of the file before the change in case something does not work as expected)

You will want to replace this (Should be lines 223-225):
```c#
hfReportEmbedUrl.Value = GetAttributeValue( "ReportUrl" ) +
        ( cbSettingPowerBIRightPane.Checked ? "" : "&filterPaneEnabled=false" ) +
        ( cbSettingPowerBINavPane.Checked ? "" : "&navContentPaneEnabled=false" );
```

With this:
```c#
hfReportEmbedUrl.Value = GetAttributeValue( "ReportUrl" );
```

This change will cause the block to ignore those settings, and always show the filter and nav panes.

Since this is just a block change, it won't trigger a restart. But you may need to clear the cache to see the results.

**Comment by debbiethurston** [comment] 2019-09-19 19:26
Mike, thank you so very much.  Eddie was able to make that change and it
did in fact fix the problem.  I have already gone to our executive pastor
and demonstrated that the reports work again.  I so very much appreciate
you sending the fix.

**Comment by randyjreed** [comment] 2019-09-19 20:08
This worked perfectly. Thank you.

**Closed** 2019-09-19 20:14 UTC
Labels: Fixed in v9.3, Priority: Low, Status: Available, Status: Confirmed, Topic: Metrics, Type: Bug
