### ISSUE TITLE
Event Registrations still showing a Balance Due

### ISSUE THREAD

**Issue by nathanp** [SparkDevNetwork/Rock#4016] opened 2019-12-03 20:27 UTC
### Description

I'm having an issue with Event Registration payments that I don't think we were having before upgrading to v9.4.
We have quite a few events where we only want payment per family, not per registrant.

My workaround so far has been to create a "family registration fee" and automatically apply discounts based on the number of registrants.

The problem we are facing now, though, is that Rock is still showing a Balance Due after registration and it is confusing people.

[Screenshot 1](https://chat.rockrms.com/file-upload/qkuHbkM7NazMRQiwn/FamilyRegistrationFeept1.PNG?download)
[Screenshot 2](https://chat.rockrms.com/file-upload/YrxqKSPG9JN9yokRz/FamilyRegistrationFeept2.PNG?download)
[Screenshot 3](https://chat.rockrms.com/file-upload/BDjgMCgDypfaQHS45/FamilyRegistrationFeept3.PNG?download)

Any ideas?

### Steps to Reproduce

1. Create event registration with a single Fee.
2. Create discounts that will automatically apply based on the number of registrants (e.g. if 4 people are registering, automatically apply the "FAMILY4" discount so that only one fee is applied).
3. Register for the event with multiple registrants.

**Expected behavior:** 

The fee is paid and no balance is due.

**Actual behavior:** 

Rock is still showing a Balance Due after registration and it is confusing people.

### Versions

* **Rock Version:** 9.4  
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1172836336379251">FamilyRegistrationFeept3.PNG</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1172836336379252">FamilyRegistrationFeept2.PNG</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1172836336379253">FamilyRegistrationFeept1.PNG</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1182490579289098">image.png</a>

**Comment by nathanp** [comment] 2019-12-16 18:09
More detailed steps to reproduce on the Demo site:

### Creating the Event Registration Template
1. Go to Tools -> **Event Registration**
2. Create a new Registration Template
3. Under "_Details_", I have the following settings:
   - Group Type: **General Group**
   - Group Member Role: **Member**
   - Group Member Status: **Active**
   - Allow Multiple Registrants: **Yes**
   - Registrants in the Same Family: **Ask**
   - Show Family Members: **Yes**
   - Registrar Options: **Prompt for Registrar**
4. Under "_Set Cost On_" I have the Cost and Minimum Initial Payment set to 0.00
5. For the Registration Form, I only have 3 Person Fields: _First Name_, _Last Name_, _Email_
6. No Registration Attributes
7. Under Fees, I have one fee.
   - Name: **Family Registration Fee**
   - Options: **Single**
   - Cost: **$5.00**
   - Is Required: **Yes**
   - Discount Applies: **Yes**
   - Is Active: **Yes**
8. Under Discounts, I have manually created discounts such as the following:
   - **FAM2** (Discount Type: Amount; Discount Amount: **$5.00**; Auto Apply Discount: Yes; Maximum Registrants: 1; Minimum Registrants: **2**)
   - **FAM3** (Discount Type: Amount; Discount Amount: **$10.00**; Auto Apply Discount: Yes; Maximum Registrants: 1; Minimum Registrants: **3**)
   - **FAM4** (Discount Type: Amount; Discount Amount: **$15.00**; Auto Apply Discount: Yes; Maximum Registrants: 1; Minimum Registrants: **4**)

Then create a Registration Instance and calendar item linked to the Registration Instance following the standard Rock Documentation.

### Experience the error
1. Go to the Calendar on the External Rock site
2. Find the Event and click on it
3. Click Register
4. In this example, try registering 4 people to get the FAM4 discount
5. At the **Review Registration** screen, you should see _The discount code 'FAM4' was automatically applied._
6. Under **Description**, you should see the Discount as being $-15.00 and the Total Cost as being $5.00
7. Complete payment.
8. On the **Congratulations** screen, you will see the following summary at the bottom:
   - Total Cost: $20.00
   - Discounted Cost: $15.00
   - Paid $5.00
   - Balance Due: $10.00 **(this is the error, should be $0)**

### View on the Backend
1. Under Tools->Event Registration, click on the Registration Instance
2. Under **Registrations**, you will see that your registration that you just completed says **Total Cost: $15.00** and **Balance Due: $10.00**. 

Balance Due should be $0.

I've created this on the Rock Demo site at https://rock.rocksolidchurchdemo.com/page/414?EventOccurrenceId=5 (I know this will only be up for a while but if you see this in time you can test without having to go through all the steps)

**Comment by cabal95** [comment] 2019-12-16 18:30
Confirmed on pre-alpha site.  Just to note for reproduction testing, the Discount Codes are in descending order (from top to bottom: FAM4, FAM3, FAM2).  Tested with Test Gateway.

![image](https://user-images.githubusercontent.com/1119863/70932620-02a16d80-1fef-11ea-9fcf-1a08030e5333.png)

**Comment by ethan-sparkdevnetwork** [comment] 2020-06-02 18:11
@nathanp 
Hello Nathan. Discounts are applied per registrant but there is an inconsistency with how that is handled. Since your discount is larger that the amount that is charged per person it exposed this inconsistency. This will be fixed in the near future.

The good news is you can correct it now with a small change to how you have the discounts setup. Since discounts are applied to each registrant the discount amount should be $5.00. Since we want it to apply to every registrant except one the Max Registrants number should be one less than the Min Registrants number. And since the first valid discount is the one that is applied they will need to be ordered from greatest number of registrants to smallest. I have added some screenshots for clarification.

![FeesAndDiscounts](https://user-images.githubusercontent.com/35315117/83553891-c68c9700-a4c0-11ea-840c-8735b2fe81eb.png)

Then the summary screen will look like this:
![ApplicationFrameHost_lPaLHl2rNr](https://user-images.githubusercontent.com/35315117/83554000-f2a81800-a4c0-11ea-8757-4ed12d7f7804.png)

And the success screen will look like this:
![ApplicationFrameHost_OqihMpCYRh](https://user-images.githubusercontent.com/35315117/83554055-05bae800-a4c1-11ea-9e17-a3ff9f103f62.png)

**Closed** 2020-07-01 23:02 UTC
Labels: Fixed in v11.1, Status: Confirmed, Topic: Event Registration, Topic: Finance, Type: Bug
