### ISSUE TITLE
Mispelled Merge Tag in editors with Merge Field insertion support.

### ISSUE THREAD

**Issue by ctkbellingham** [SparkDevNetwork/Rock#5340] opened 2023-03-12 21:38 UTC
### Please go through all the tasks below

- [ ] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

The "Current Person" Attribute Merge Tags are misspelled as "UrrentPerson", which breaks the Lava Output.

![Screen Shot 2023-03-12 at 2 37 04 PM](https://user-images.githubusercontent.com/127696404/224575215-d49152c8-ab9c-40b4-9e24-2032f81f6b04.png)

### Expected Behavior

Output "CurrentPerson"

### Actual Behavior

Outputs "UrrentPerson"

### Steps to Reproduce

Go to Power Tools < Lava Tester < Merge Tags < "Current Person" < Attribute

### Rock Version

13.7

### Client Culture Setting

en-US

**Comment by bmurphy-dev** [comment] 2023-03-13 16:02
Confirmed in v13.7, also in 14.1, and 15.0 prealpha.
This happens **anywhere** there is a CurrentPerson lava merge field selection available such as the HTML block.
The issue of resolving these merge field tags is deeper.

**Comment by nate-steil** [comment] 2023-03-13 20:39
Can confirm this is happening in my v13.6 production and v13.7 test environment as well

**Comment by TheArkChurch** [comment] 2023-03-14 04:13
The lava tester is a plugin and any issues should be reported in this [repository](https://github.com/CentralAZ/Rock-CentralAZ/wiki/Utility--Lava-Tester)

**Comment by bmurphy-dev** [comment] 2023-03-14 12:57
@TheArkChurch this is deeper and effects the lava tag library/dictionary somewhere. i can't track it down. but it seems to be when calling the Rock.Lava.LavaHelper.GetCommonMergeField which the LavaTester and HTML Content Detail block both do. Probably other areas that use this same call: [https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Cms/HtmlContentDetail.ascx.cs#L819-L833](https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Cms/HtmlContentDetail.ascx.cs#L819-L833)
[https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Cms/HtmlContentDetail.ascx.cs#L630-L650](https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Cms/HtmlContentDetail.ascx.cs#L630-L650)
![image](https://user-images.githubusercontent.com/73124289/225005469-1d820d89-7b06-407c-b643-74db717716eb.png)
![image](https://user-images.githubusercontent.com/73124289/225005491-55cb5685-dfd5-430a-bc35-bed86c441353.png)

CAZ uses same call: [https://github.com/CentralAZ/Rock-CentralAZ/blob/central-develop/RockWeb/Plugins/com_centralaz/Utility/LavaTester.ascx.cs#L48](https://github.com/CentralAZ/Rock-CentralAZ/blob/central-develop/RockWeb/Plugins/com_centralaz/Utility/LavaTester.ascx.cs#L48)
[https://github.com/CentralAZ/Rock-CentralAZ/blob/central-develop/RockWeb/Plugins/com_centralaz/Utility/LavaTester.ascx.cs#L106](https://github.com/CentralAZ/Rock-CentralAZ/blob/central-develop/RockWeb/Plugins/com_centralaz/Utility/LavaTester.ascx.cs#L106)

**Comment by bmurphy-dev** [comment] 2023-03-14 13:04
I'd also point out, that at some point the Lava Tester became included in core without the need to install the plugin from the shop.
Also I checked and this effects everyone and the core repo as far back as v11.3 up to and including prealpha 15.0

**Comment by TheArkChurch** [comment] 2023-03-14 15:34
> I'd also point out, that at some point the Lava Tester became included in core without the need to install the plugin from the shop. Also I checked and this effects everyone and the core repo as far back as v11.3 up to and including prealpha 15.0

Well that piece of information slipped by me. I'm glad it's in core now.

**Comment by cabal95** [comment] 2023-03-14 16:06
@bmurphy-dev I just double checked because I thought I had lost my mind, but the Lava Tester is not in core. So people will still need to install it from the plugin shop.

But as you say, the issue is in the core wysiwyg editor rather than the Lava Tester itself. I will update the issue description to clarify.

**Closed** 2023-09-12 03:54 UTC
Labels: Type: Bug, Status: Confirmed, Topic: Lava, Fixed in v16.1
