### ISSUE TITLE
Workflows: "Add Action" expands all lists of action attributes

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#1656] opened 2016-07-28 21:52 UTC
v5.1 (unknown if new bug or not)

I have a workflow with a number of actions. Each action has at least one action attribute. When I click the "Add Action" button, once the orange "working" bubble goes away, all of the lists of action attributes are expanded. This is not visible if the action is collapsed, but is visible for any expanded activities (for instance, if I'm trying to match actions from one activity to another) and the attribute lists do show as expanded if I later expand one of the collapsed activities.

It's not a big deal but is a bit of a pain if I'm trying to keep things compact while working on the workflow. If I collapse something it should stay collapsed :wink:

**[Update: Steps to reproduce:]**

1. Start a new workflow
1. Add a single Activity Attribute to the default `Start` activity.
1. Collapse the `Attributes` pane on the `Start` activity.
1. Click `Add Action` in the `Start` activity
1. Observe that above the new first action, the Attributes pane has expanded again

**Comment by arranf** [comment] 2017-09-09 06:13
@mikejed Are you still experiencing this?

**Comment by mikejed** [comment] 2018-03-14 19:35
Going through some old reports here.

Yes, this is still happening as of v7.3 and prealpha v8

Man, 2016 was a long time ago; reading my butchering of the terms is painful. Let me clarify and provide a repeatable process here:

Steps to reproduce:
1. Start a new workflow
2. Add a single Activity Attribute to the default `Start` activity.
3. Collapse the `Attributes` pane on the `Start` activity.
4. Click `Add Action` in the `Start` activity
5. Observe that above the new first action, the Attributes pane has expanded again

**Comment by TheArkChurch** [comment] 2023-07-25 04:32
This "bug" is still present in v16.0 (pre alpha). I believe that the cause of this is located here https://github.com/SparkDevNetwork/Rock/blob/1b1ed7511d00aaeef1a36e153dace4fd35ff64d9/RockWeb/Blocks/WorkFlow/WorkflowTypeDetail.ascx.cs#L1641.

**Comment by jonedmiston** [comment] 2023-09-09 06:00
Since this is a fairly minor bug and so old I'm going to close this and we'll address it when we re-create the block in Obsidian.

**Closed by jonedmiston** 2023-09-09 06:00 UTC
Labels: Type: Bug, Status: Confirmed, Topic: UI, Priority: Low, Topic: Workflows, x-bugapalooza: Low
