### ISSUE TITLE
If All Members of Family are Deceased, Giving Analytics shows Duplicates of Contribution

### ISSUE THREAD

**Issue by tscrip** [SparkDevNetwork/Rock#2848] opened 2018-03-05 22:13 UTC
### Prerequisites ###

* [X ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description ###

According to Rock standards, when a family member passes away, you are supposed to move them into their own family. When you are migrating data from one system to another, this standard step can often times be missed. As a result, financial information can become inaccurate. When you are moving thousands of people, sometimes you want to validate $ before you start splitting people into their own families.

In addition to this, there is no Rock standard if BOTH people end up deceased.

### Steps to Reproduce ###

1. Make a family with two adults
1. Make sure the giving group is configured (them in the same group)
1. Make a contribution
1. View Contribution in Giving Analytics (notice how it is in the HOH's name?)
1. Make HOH deceased
1. View Contribution in Giving Analytics (now the contribution shows under the next MOST alive person)
1. Mark the lone survivor as deceased
1. View Contribution in Giving Analytics (notice how you have duplicate contribution?) 
1. Now, pull a Lazarus and bring the HOH back to life
1. Go into Giving Analytics (notice how the HOH is now the only person listed for the contribution)

**Expected behavior:**

If both adults in a family are alive, it should use the person that is HOH.

If one adult is deceased, it should use the alive person.

If the other person became deceased, it should use the original HOH for the family.

**Actual behavior:**

The C# code is looking at the deceased flag. It looks like if both people are deceased, it is using both people instead of one of the other.

### Versions ###

* **Rock Version:** 7.1, 7.3
* **Client Culture Setting:** en-US

**Comment by jsw-austin** [comment] 2019-10-24 21:25
Well, what I'm finding in the demo site is actually different than what was reported in version 7.1 and 7.3.  What I'm showing in step 6 is that the giving analytics show up for both people in the family (effectively doubling the total of gifts in the giving analytics)

![Screen Shot 2019-10-24 at 4 21 19 PM](https://user-images.githubusercontent.com/7400184/67526409-53918700-f67a-11e9-9f4e-723216425f4e.png)

After marking the lone survivor deceased, both gifts still show up even though in the batch, and the contribution history, there's only $1500 given:

![Screen Shot 2019-10-24 at 4 24 21 PM](https://user-images.githubusercontent.com/7400184/67526610-be42c280-f67a-11e9-9ddc-3a9c9dbbe264.png)

![Screen Shot 2019-10-24 at 4 25 01 PM](https://user-images.githubusercontent.com/7400184/67526651-d9153700-f67a-11e9-806a-7800a4c2412c.png)

**Comment by courtneycooksey** [comment] 2022-01-11 14:30
@nairdo I've been digging into this a bit, I believe I figured out what the issue is...or at least a solution that seems to be working. When the HOH dies, the other spouse is changed to have their Person Id in the GivingLeaderId field in the person table to replace the deceased HOH. If they also pass away, that value is not getting updated back to the HOH which is why both show up in the Giving Analytics report. In my testing when the spouse dies before the HOH the report still functions properly only showing the HOH and not both members of the family. 
So a possibly solution could be to check when someone is marked inactive for reason of deceased and the rest of their household is also deceased you could make sure if their giving is combined they don't have multiple GivingLeaderIds. Thoughts?

**Comment by courtneycooksey** [comment] 2022-01-11 14:37
It also looks like it doesn't matter if both people are deceased or not, when the HOH dies and the remaining spouse GivingLeaderId is updated, both are showing on the Giving Analytics report.

**Comment by jonedmiston** [comment] 2023-09-26 05:42
Fixed by not filtering out deceased people but sorting by the deceased status. This will need rigorous testing.

**Closed by jonedmiston** 2023-09-26 05:42 UTC
Labels: Type: Bug, Status: Confirmed, Topic: Finance, Fixed in v16.1
