### ISSUE TITLE
Workflow Single Select Field Behavior

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#1627] opened 2016-07-14 23:12 UTC
When setting up a workflow, some of the single select fields are set to be drop down lists. But when trying to filter those fields when managing the workflow, they default to check boxes. Is there a way to change that behavior?

**Comment by arranf** [comment] 2016-08-11 07:00
May be related to #1037

**Comment by arranf** [comment] 2018-06-13 13:50
I can't reproduce this on 8.0 so I'm closing it.

**Closed by arranf** 2018-06-13 13:50 UTC
Labels: Topic: UI, Type: Enhancement
