### ISSUE TITLE
Mixed casing breaks per-site routes

### ISSUE THREAD

**Issue by Tschrock** [SparkDevNetwork/Rock#3204] opened 2018-08-23 14:57 UTC
### Description

We've been having a lot of trouble with routes for our new website going to the wrong site. After some investigation, it looks like it's caused by another site which uses capitalized versions of the same routes.

### Steps to Reproduce

1. Create a route on site 1 of `testroute`
1. Create a route on site 2 of `TestRoute`

**Expected behavior:**

Both routes work correctly and take you to the right page for the site you're on. (So `site1.com/testroute` and `site2.com/testroute` go to to different pages)

**Actual behavior:**

Both `site1.com/testroute` and `site2.com/testroute` take you to the same page on site 1. 

### Versions

* **Rock Version:** 7.5, prealpha
* **Client Culture Setting:** en-US

**Comment by Tschrock** [comment] 2018-08-23 17:27
Sorry for the confusion, I did mean option A

So `site1.com/testroute` and `site2.com/testroute` both go to the same page on site 1

**Comment by cabal95** [comment] 2018-08-23 17:29
And you want `site2.com/testroute` to be treated as if they typed `site2.com/TestRoute` correct?

**Comment by Tschrock** [comment] 2018-08-23 17:36
That's correct, they should behave case-insensitive like usual

**Comment by Tschrock** [comment] 2018-08-23 17:45
So, to make sure everything is clear:

On my first site:
- The site's url is `site1.com`
- I have a page on that site with a route of `TestRoute`
- I can currently get to that page from:
   - `site1.com/testroute`
   - `site1.com/TestRoute`
   - `site1.com/TeStRoUtE`

On my second site:
 - The site's url is `site2.com`
- I have a page on that site with a route of `testroute`
- I should be able to access it from any of these, but they actually go to the page on site 1:
   - `site2.com/testroute`
   - `site2.com/TestRoute`
   - `site2.com/TeStRoUtE`

**Comment by ethan-sparkdevnetwork** [comment] 2018-10-03 20:50
I have not been able to reproduce this issue on 8.5. Here is the setup I am using:
1.	OS
  a.	Added www.rockinternal.com 127.0.0.1 to host file
  b.	Added www.rockexternal.com 127.0.0.1 to host file
2.	IIS
  a.	Created website in IIS with binding www.rockinternal.com and pointed to the RockWeb folder.
  b.	Created website in IIS with binding www.rockexternal.com and pointed to the RockWeb folder.
  c.	Assigned each site to its own app pool.
3.	Rock
  a.	Added domain www.rockinternal.com to the RockRMS site.
  b.	Added domain www.rockexternal.com to the External Website.
  c.	Created a page under Internal Homepage called "Internal Test Page".
  d.	Added HTML block to Internal Test page with repeated text "This is the Internal Test Page."
  e.	Added Route "TestPage"
  f.	Created a page under External Homepage called "External Test Page"
  g.	Added HTML block to External Testpage with repeated text "This is the external Test Page."
  h.	Added Route "testpage"

Test results:
The correct page loads for the domain regardless of casing.
Tried the route on each domain from different pages (e.g. opened an internal page on the external domain and then going to the testpage route). No issues were found.

Is there anything else you can tell me about your setup?

**Comment by Tschrock** [comment] 2018-10-04 17:58
I'm not sure what the difference could be, my steps are about the same (but debugging from visual studio instead of an IIS server). On our production server we do have some `*` bindings set up, but the problem shows up for named sites too. 

Hosts file:

```
127.0.0.1       externaltest.newpointe.org
127.0.0.1       internaltest.newpointe.org
127.0.0.1       otherwebsite.com
```

Site Settings:

| Name | Domain(s) |
| ------ | ---------- |
| External Website | `externaltest.newpointe.org, otherwebsite.com` |
| Rock RMS | `internaltest.newpointe.org, localhost` |

Page Settings:

| Page | Route |
| ----- | ------ |
| External Website > External Test Page | `testroute` |
| Rock RMS > Internal Test Page | `TestRoute` |

Results:
`externaltest.newpointe.org/testroute`, `internaltest.newpointe.org/testroute`, and `otherwebsite.com/testroute` all go to the same page on the internal site.

And a picture of the issue and setup:
![virtualbox_2018-10-04_13-01-23](https://user-images.githubusercontent.com/2406499/46493010-3672e780-c7dd-11e8-84b8-f39c18917113.png)

**Comment by ethan-sparkdevnetwork** [comment] 2018-10-04 23:32
We are not able to reproduce the issue here, or find in the code how casing would change the route behavior. If anyone can identify the cause we are open to a pull request. :-)

**Comment by GerhardPowell** [comment] 2018-10-31 23:28
Fixed in https://github.com/SparkDevNetwork/Rock/commit/6bed7e92e09ee34b93f1922ee9eac0ef6553664d

**Closed by GerhardPowell** 2018-10-31 23:28 UTC
Labels: Fixed in v8.5, Status: Available, Status: Confirmed, Type: Bug
