### ISSUE TITLE
Recipient Preference Communication Approval

### ISSUE THREAD

**Issue by jcjones37** [SparkDevNetwork/Rock#4141] opened 2020-03-01 22:17 UTC
### Description
When a communication approval comes through to the people listed as 'communication approvers' and the communication was selected as "Recipient Preference"... the approver will select "View Communication" but the webpage that shows the communication will not show the message details.  (message details show just fine when the user selects Email or SMS)

### Steps to Reproduce
1. Set yourself as the communication approver
1. Have another user create a communication to a group of people that exceeds the block settings.
1. When you receive the communication approval request, click "View Communication"
1. Click Message Details 

v9.4:
![image](https://user-images.githubusercontent.com/383807/76026635-68b1d880-5eec-11ea-898b-9bda808490f5.png)

pre-alpha-release:
![image](https://user-images.githubusercontent.com/383807/76026338-cbef3b00-5eeb-11ea-865c-2238400de4d1.png)

**Expected behavior:**

I would expect the details of the message to appear here.
--phone number or email the message is coming from
--the text of the message

**Actual behavior:**

nothing shows up here.

### Versions
* **Rock Version:** [9.4]
* **Client Culture Setting:** [en-US]

**Comment by nairdo** [comment] 2020-03-05 21:23
@jcjones37 Are you saying you don't see any details (such as what the screenshot I added above shows)? or, are you saying you are not seeing the **SMS information** / details under the `Message Details`?

**Comment by jcjones37** [comment] 2020-03-08 17:18
@nairdo thank you for the clarification. Sorry about that. I do not see any details. and this only happens when someone selects "Recipient Preference". I attached an image here as to what that looks like for us.

<img width="1043" alt="Screen Shot 2020-03-08 at 13 18 28" src="https://user-images.githubusercontent.com/41912840/76167734-57143f00-613f-11ea-8043-968a3b6b58aa.png">

**Comment by nairdo** [comment] 2020-04-01 22:15
@jcjones37 One of our developers was able to reproduce the issue in Rock v9.4 and confirmed that it has been fixed in unreleased v9.5 (and later v10.x versions), because the Communication Detail block has been substantially reworked with this (and later) commits:
https://github.com/SparkDevNetwork/Rock/commit/6014f7a3bb46e0480e544ed8ae9dd56b2634cc79

Please feel free to reopen if you encounter this issue while on Rock v10.x.

**Closed by nairdo** 2020-04-01 22:15 UTC
Labels: Fixed in v9.5, Status: Available, Topic: Communications
