### ISSUE TITLE
Obsidian Event Registration - Fee options available when none remaining

### ISSUE THREAD

**Issue by gillcrockford** [SparkDevNetwork/Rock#5408] opened 2023-04-19 16:06 UTC
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

The Obsidian Registration Block continues to allow fees to be selected after no more are available & where there is no actual fee displays ($0.00) 
![Screen Shot 2023-04-19 at 11 46 13 AM](https://user-images.githubusercontent.com/36459209/233129801-e9f708ed-6aa3-4444-9e17-06a885233cb4.png) 

This happens for single and multiple fee types & when hide when no more available is checked (& allow more than 1) 

### Expected Behavior

Expected Behavior as per the previous registration block where the fees are greyed out and unavailable when the maximum available has been reached. Also where there is no fee no $ amount should be shown.
![Screen Shot 2023-04-19 at 11 47 03 AM](https://user-images.githubusercontent.com/36459209/233130005-ce837cd4-5f89-4007-ad5a-cd92666ada96.png)

### Actual Behavior

Actual Behavior 
The Obsidian Registration Block continues to allow fees to be selected after no more are available & where there is no actual fee it displays ($0.00) 
![Screen Shot 2023-04-19 at 11 46 13 AM](https://user-images.githubusercontent.com/36459209/233129801-e9f708ed-6aa3-4444-9e17-06a885233cb4.png) 

### Steps to Reproduce

On the demo site either create a registration event with optional fees, limit the fees so the maximum can be reached (eg 1) or set to 0 available, or use the summer camp event registration.
Duplicate the registration page (under CMS),set the page URL to eg regobsidian & replace the registration block with the Obsidian Registration Block
View the registration instance while using the Obsidian registration Entry block https://rock.rocksolidchurchdemo.com/regobsidian?RegistrationInstanceId=1 & also from the regular registraion block
https://rock.rocksolidchurchdemo.com/Registration?RegistrationInstanceId=1
![Screen Shot 2023-04-19 at 12 03 24 PM](https://user-images.githubusercontent.com/36459209/233134254-218107ea-241f-4e77-999f-2f9dade9d7ab.png)

### Rock Version

Rock McKinley 14.2 (1.14.2.1)

### Client Culture Setting

en-US

**Comment by dataCollegechurch** [comment] 2023-06-06 22:13
Note: Fee options remain available even after the maximum available quantity has been reached by existing registrations. The presence of this bug is not based the amount of the fee. It appears when the fee is $0 as well as when the fee is > $0.

**Comment by robotman3000** [comment] 2023-07-26 19:23
I was also looking into how to fix this myself and I went with the option of using `feeField.partial.ts`

Example:

```
  dropDownListOptions(): ListItemBag[] {
      return this.fee.items.filter(i => { return i.countRemaining == undefined || i.countRemaining > 0 }).map(i => ({
          text: this.getItemLabel(i),
          value: i.guid
      }));
  },
```

I added `.filter(i => { return i.countRemaining == undefined || i.countRemaining > 0 })` to `this.fee.items`. I did have to account for when there is no quantity on the fee. It seems to be `undefined` when that is the case.

**Comment by ethan-sparkdevnetwork** [comment] 2023-08-17 23:36
The issue is slightly different depending on the configuration of the fee.

**Single Option**
Control: Checkbox
Behavior: Works correctly

**Single Option, Enable Quantity**
Control: Number Up Down
Behavior:
Before the fee items are used the control restricts the amount selection to the number available.
However for fees that are already used up the control does not show any remaining info, and any number can be selected.
Fix: Use "??" instead of "||" when setting the max number. The "0" value is falsey and so the default is used instead of 0.

**Multiple Option**
Control: Single Select DDL
Behavior:
The control shows the number remaining correctly, but there isn't currently an option to "disable" an item in the Obsidian dropDownList.
This is an issue with the control and with the usage
Fix: Add the disable prop to the items in the dropdown list and implemnt in the feeField.

**Multiple Option, Enable Quantity**
Control: Number Up Down Group
Behavior: Before the fee items are used the control restricts the amount selection to the number available.
However, for fees that are already used up the control does not show any remaining info, and any number can be selected.
Fix: Use "??" instead of "||" when setting the max number. The "0" value is falsey and so the default is used instead of 0.

**Hide When None Remaining**
Problem: The feeField is configured to hide if there are no items to display. However the server side logic provides the items with their configuration.
Fix: Update the server-side logic to not send fee info that is not needed by the block.
Update RegistrationEntryBlockViewModel and add the prop "HideWhenNoneRemaining".
Update fee logic in RegistrationEntry.GetViewModel() to not include items that have 0 remaining and have HideWehnNoneRemaining set to true.

Fixed in commits:
- d6c488e5
- dcf3fafb
- 8d0ee776
- cfa3c9ec

**Closed** 2023-08-18 16:17 UTC
Labels: Type: Bug, Status: Confirmed, Fixed in v15.2
