### ISSUE TITLE
Registrant Workflows from Event Registration Tools

### ISSUE THREAD

**Issue by davidbelk** [SparkDevNetwork/Rock#5198] opened 2022-10-18 21:18 UTC
* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Steps to Reproduce

1. Go to a registration instance/registratns such as: https://rock.rocksolidchurchdemo.com/web/event-registrations/1/registrants
2. Try to launch a workflow. 
4. See error: 
InvalidOperationException in EntityFramework
Message
A specified Include path is not valid. The EntityType 'Rock.Data.RegistrationRegistrant' does not declare a navigation property with the name 'Person'.

Stack Trace

   at System.Data.Entity.Core.Objects.Internal.ObjectFullSpanRewriter.ConvertSpanPath(SpanPathInfo parentInfo, List`1 navPropNames, Int32 pos)
   at System.Data.Entity.Core.Objects.Internal.ObjectFullSpanRewriter..ctor(DbCommandTree tree, DbExpression toRewrite, Span span, AliasGenerator aliasGenerator)
   at System.Data.Entity.Core.Objects.Internal.ObjectSpanRewriter.TryRewrite(DbQueryCommandTree tree, Span span, MergeOption mergeOption, AliasGenerator aliasGenerator, DbExpression& newQuery, SpanIndex& spanInfo)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlanFactory.Prepare(ObjectContext context, DbQueryCommandTree tree, Type elementType, MergeOption mergeOption, Boolean streaming, Span span, IEnumerable`1 compiledQueryParameters, AliasGenerator aliasGenerator)
   at System.Data.Entity.Core.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at RockWeb.Blocks.WorkFlow.WorkflowLaunch.BindRepeater()
   at RockWeb.Blocks.WorkFlow.WorkflowLaunch.RenderState()
   at RockWeb.Blocks.WorkFlow.WorkflowLaunch.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Expected behavior:**

I should be able to launch a workflow from the registrants and it pass the entity of person. 

**Actual behavior:**

I get an error screen and cannot launch workflows. 

### Versions
13.6, 13.7, 14.0
* **Rock Version:** 13.6, 13.7, 14.0
* **Client Culture Setting:** US
![Screen Shot 2022-10-18 at 4 17 09 PM](https://user-images.githubusercontent.com/43145156/196546641-95ebb9d6-b5d3-4e26-82b4-7be36d7e022c.png)
![Screen Shot 2022-10-18 at 4 17 28 PM](https://user-images.githubusercontent.com/43145156/196546681-f68a6cb6-d1a2-4b7c-9514-acd21b08901e.png)

**Comment by nairdo** [comment] 2022-10-21 23:24
I believe this is a duplicate of #5031 -- but the good news is: we recently fixed this for v14.1 via https://github.com/SparkDevNetwork/Rock/commit/3baa19eeaf0c61815032b8f3fc5dcaa244e1bae5.

**Closed by nairdo** 2022-10-21 23:24 UTC
