### ISSUE TITLE
Personal Merge Templates showing for all users

### ISSUE THREAD

**Issue by BemaDavidBensen** [SparkDevNetwork/Rock#3113] opened 2018-07-09 12:35 UTC
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Merge Template dropdown shows all personal merge templates and not just the logged in users merge template 

### Steps to Reproduce

1. Go to a group
2. Click on Merge Records into Merge Template
3. Click on Merge Template dropdown
4. See dropdown list shows all person merge templates and does not honor the logged in person

**Expected behavior:**

The merge template drop down list should only show the persons merge templates in the person section

**Actual behavior:**

The merge template dropdown shows all users personal merge templates

### Versions

* **Rock Version:** [7.3]
* **Client Culture Setting:** [en-US]

**Comment by mikejed** [comment] 2018-07-09 13:53
I was able to reproduce this issue in v7.4, but not in my testing on the prealpha server and in my own v8 alpha instance of Rock. Indeed, admins are not able to see the personal templates (other than their own) populated on the tree view at all, so unless you know the TemplateId, they can't manage them at all. I'll look deeper into that to see whether that's its own bug, but it looks like this particular issue was already fixed in v8.

**Closed by mikejed** 2018-07-09 13:53 UTC
Labels: Fixed in v8.0

**Comment by mikejed** [comment] 2018-07-09 22:12
@BemaDavidBensen In case you're interested, I filed an issue regarding the personal merge templates that exists in 7.4 and has _not_ yet been fixed in 8.0. Find it here: https://github.com/SparkDevNetwork/Rock-v8-Alpha-Issues/issues/24

The short version is that personal merge templates should be able to be managed using the "My Settings -> Merge Templates" from an administrator account. However, that list does not list personal merge templates until the "Person" filter is cleared and applied.
