### ISSUE TITLE
Move Transactions to Batch could reset to '--Move Transactions To Batch --' on failure when no trans selected

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#5910] opened 2024-06-12 05:33 UTC
### Description

Thank you for the 'Move Transactions To Batch' functionality!  Flipping awesome, and very useful in my work process.
This is not a biggie, and you can close this issue if you don't care because it's an edge case, and there is an easy work-around.

Noticed that if there are no transactions selected, and I chose the batch to move to, that nothing happens, and I have to select the transactions(s) and then select '-- Move Transactions To Batch --' and then reselect the batch to move to.

Maybe the drop down could reset to '-- Move Transactions To Batch --' if there is nothing to do.
![MoveTran1](https://github.com/SparkDevNetwork/Rock/assets/4658177/a3df44e8-0113-4a2c-aa51-ba6f6f81941b)

![MoveTran2](https://github.com/SparkDevNetwork/Rock/assets/4658177/29588dea-b997-466c-85d3-5bf1e21ce830)

![MoveTran3](https://github.com/SparkDevNetwork/Rock/assets/4658177/560a35fe-2efa-4a28-9ebf-89278e8985a4)

### Actual Behavior

On Financial Batch Detail, Transaction List Block, the Move To Transaction drop down does nothing when no transactions are selected and a batch is selected, and '-- Move To Transaction --' has to be RE-selected, before the (now selected transaction) can be moved to a batch that is selected.  

### Expected Behavior

The 'Move Transactions to Batch' drop down could auto reset to '-- Move Transactions to Batch --' on failure to do anything when no transactions are selected and a batch on the drop down is selected.

### Steps to Reproduce

Open a batch, view the Transaction List.
Select a batch to move transactions to without selecting any transactions.
Now select the transaction(s) to move.
Clicking the already selected batch to move to does nothing.
You have to reselect '-- Move Transactions to Batch --', then reselect the batch you want to move the transactions to.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Version 16.5 16.5 (1.16.5.4), 

### Client Culture Setting

Client Culture Setting: en-NZ, Browser settings Language = English (New Zealand).

**Comment by sparkdevnetwork-service** [comment] 2024-06-12 21:17
@ElimAdmin From what we can tell, the feature has always operated this way, but thank you for the suggested change.   Although we're closing this here (since it's not a bug) we'd ask that you consider opening feature requests over on the [Ideas and Core Changes](https://community.rockrms.com/ideas-changes) page.

**Closed by sparkdevnetwork-service** 2024-06-12 21:17 UTC
