### ISSUE TITLE
Lava Where/Select Filter issue with Attribute Values (Person Property)

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#2591] opened 2017-11-09 17:37 UTC
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
AttributeValues Property doesn't work the way I had expected it to.

### Steps to Reproduce
1. Look up an Attribute Id of an Attribute the Current Person has an Attribute Value for
1. Dump the Following Lava into an HTML Content Block replacing the Attribute Id numbers with the numbers you looked up.
I used Alicia Admin and Ted Decker on the Demo site.

```
AttributeValues First To JSON :<pre>{{ CurrentPerson.AttributeValues | First | ToJSON }}</pre><hr>
AttributeValues Where First Attribute Id <pre>{{ CurrentPerson.AttributeValues | Where:'AttributeId',174 | ToJSON }}</pre><hr>
AttributeValues First, Property AttributeId<pre>{{ CurrentPerson.AttributeValues | First | Property:'AttributeId'}}</pre><hr>
AttributeValues First, Property Value<pre>{{ CurrentPerson.AttributeValues | First | Property:'Value' }}</pre><hr>
AttributeValues First, Property CreatedDateTiem<pre>{{ CurrentPerson.AttributeValues | First | Property:'CreatedDateTime' }}</pre>
```

**Expected behavior:**

I was expecting the `| Where` filter to work the way it normally does, and I was expecting the `AttributeValues` property to return an array of Attribute Value objects (complete with things like `CreatedDateTime` and friends). 

**Actual behavior:**

The `| Where` filter doesn't work in this case, and the returned items in the Array don't seem to be full AttributeValues

### Screen Shot
![image](https://user-images.githubusercontent.com/19762670/32620035-2aa891a0-c542-11e7-93cc-df485c4d4a20.png)

### Versions
* **Rock Version:** 6.5 (my production), 6.7 (demo site), 7.something (prealpha)
* **Client Culture Setting:** en-us

**Comment by edmistj** [comment] 2017-11-10 00:27
Research Note: AttributeValueCache object is not ILiquidizable

**Comment by arranf** [comment] 2018-06-20 15:34
Reproducible on 8.0

**Comment by jonedmiston** [comment] 2019-08-23 15:12
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.

**Closed by jonedmiston** 2019-08-23 15:12 UTC
Labels: Priority: High, Status: Confirmed, Topic: Lava, Type: Enhancement
