### ISSUE TITLE
Obsidian Registration Entry Block Does Not Work with JS <script> Injection

### ISSUE THREAD

**Issue by courtneycooksey** [SparkDevNetwork/Rock#5143] opened 2022-08-24 21:57 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![image](https://user-images.githubusercontent.com/58440371/186529605-c551ca5b-b5fe-431f-8602-427d231c5837.png)

### Description

If you have code in your Registration Instructions (or potentially also the Pre/Post HTML of an attribute, Jim Michael will add his thoughts) the block breaks and displays a JSON dump. 

### Steps to Reproduce

1. Create a registration
2. Add some JS code to the Registration Instructions
3. View registration entry block

This is what I set the Registration Instructions to in order to break the Pre-Alpha site or our version of 13 
```
<p>Adding some code...to see if it breaks</p>
<!-- Import a JS library -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/luxon/2.3.0/luxon.min.js" integrity="sha512-2j5fkjQ4q5ceXgfxi+kqrU2Oz234MrpyywZsQz1F5OGnfat7mOhjRr0oz5cpQ+YwwWB+hhDBSyxNGuL/tKWMFw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
// DO NOT CHANGE (Starting here)
    console.log('hello world')
</script>
```

**Expected behavior:**

Either it works and your custom code is supported. Or you are not allowed to enter code in the registration instructions. 

**Actual behavior:**

JSON dump, breaks the vue. This is what is rendered to the page, looks like maybe the `>` is the problem, because it is not being escaped? 
![image](https://user-images.githubusercontent.com/58440371/186530748-a16df37b-b4bf-41b6-b8e8-b06360851b16.png)

### Versions

* **Rock Version:** 13.4 or Prealpha
* **Client Culture Setting:** en-US

**Comment by MichaelAllen** [comment] 2022-08-25 00:37
We ran into the same issue when including javascript in the confirmation text to redirect to another page. 

I think the issue is that Rock is putting the instructions/confirmation/etc directly in the JSON object and when the browser sees `</script>` it thinks it is the end of the script even though it is in the middle of the JSON object.  This could possibly be fixed by encoding those fields before passing them as JSON, then decoding them when they are read by the block.

**Comment by nairdo** [comment] 2022-08-26 14:14
@courtneycooksey We reviewed this yesterday and due to the new JavaScript based architecture of the new Obsidian blocks and 'their need to control the DOM', it will not be possible to inject `<script>` tags using this approach.  I'm going to re-title this issue and close it since this will not be supported, but you can open a feature request on the Ideas board (http://community.rockrms.com/Ideas/) board to request an alternate mechanism be built into Obsidian blocks for this purpose.   I'm sorry about that!

Thanks again for helping us test these new Obsidian blocks in your environment.

**Closed by nairdo** 2022-08-26 14:14 UTC
Labels: Type: Bug, Status: Confirmed

**Comment by nairdo** [comment] 2022-09-06 16:21
> Loading the JS via AJAX. Here is one potential workaround

I just want to be clear that this is not something we recommend as a workaround.

**Comment by dataCollegechurch** [comment] 2022-09-06 16:46
@nairdo - is this due to the complexity it adds to the page and the probability it will make debugging difficult down the road?  Before I implemented a solution like this I would try to understand what is really driving the need to add js to the registration process. Is there a different way to accomplish this with css or there some change to your process that can eliminate the need for this. Is this really a must have or a nice to have scenario that is driving the need for the js.
