### ISSUE TITLE
Cannot select data view

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#3942] opened 2019-10-10 22:41 UTC
Submitted on behalf of [Northpointe Community Church ](https://www.northpointe.org/)

### Description
When using the data view item picker, you cannot select a data view if that data view happens to have a id that is equal to a category in the tree above the data view.

Northpointe has 606 data views, and 138 of them have an id equal to a category in the same tree view. Several of those data views cannot be selected using the data view item picker (i.e. in data automation settings, using an "Other Dataview" filter, etc. (It is hard to say exactly say how many of those though cannot be selected as it's difficult to determine from query if the category appears above the data view in the tree or not). 

### Steps to Reproduce
1. Run the following query on the demo database or a fresh Rock install. This will create two new data views under the "Group Requirements" category. The second data view (Test B Dataview), will get created with the same id as the "Foundational Views" category...

```
DECLARE @PersonEntityTypeId int = ( SELECT TOP 1 [Id] FROM [EntityType] WHERE [Name] = 'Rock.Model.Person' )
DECLARE @CategoryEntityTypeId int = ( SELECT TOP 1 [Id] FROM [EntityType] WHERE [Name] = 'Rock.Model.DataView' )
DECLARE @FoundationalViewsCatId int = ( SELECT TOP 1 [Id] FROM [Category] WHERE [EntityTypeId] = @CategoryEntityTypeId AND [Name] = 'Foundational Views' )
DECLARE @GroupReqCatId int = ( SELECT TOP 1 [Id] FROM [Category] WHERE [EntityTypeId] = @CategoryEntityTypeId AND [Name] = 'Group Requirements' )
DECLARE @FilterId int

INSERT INTO [DataViewFilter] ( [ExpressionType], [Guid] )
VALUES( 1, NEWID() )
SET @FilterId = SCOPE_IDENTITY()

INSERT INTO [DataView] ( [IsSystem], [Name], [Description], [CategoryId], [EntityTypeId], [DataViewFilterId], [Guid] )
VALUES ( 0, 'Test A DataView', '', @GroupReqCatId, @PersonEntityTypeId, @FilterId, NEWID() )

INSERT INTO [DataViewFilter] ( [ExpressionType], [Guid] )
VALUES( 1, NEWID() )
SET @FilterId = SCOPE_IDENTITY()

SET IDENTITY_INSERT [DataView] ON
INSERT INTO [DataView] ( [Id], [IsSystem], [Name], [Description], [CategoryId], [EntityTypeId], [DataViewFilterId], [Guid] )
VALUES ( @FoundationalViewsCatId, 0, 'Test B DataView', '', @GroupReqCatId, @PersonEntityTypeId, @FilterId, NEWID() )
SET IDENTITY_INSERT [DataView] OFF
```

1. Go to any place that a Data View Item Picker is used (Control Gallery, Data Automation Settings, etc.)
1. Try to select the "Test B DataView"

**Expected behavior:**

You can successfully select the data view.

**Actual behavior:**

You can not select the data view (nothing happens when you click the data view).

### Versions
* **Rock Version:** Rock McKinley 9.2 (1.9.2.5)
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment] 2019-10-10 22:50
This sounds like it might be a duplicate of #1632

**Comment by cabal95** [comment] 2019-10-11 00:32
I think Randy Reed also ran into this at HDC recently. FYI.

**Comment by randyjreed** [comment] 2019-10-13 15:02
Yes, I did. I could not figure out the relation. I still have the issue actually.

**Comment by azturner** [comment] 2019-10-16 16:31
@nairdo, I agree that it looks like it may be related to #1632, but not sure about the priority:low tag. Because the data automation settings only allow you to specify a single data view when configuring the settings for reactivating and inactivating, We're trying to create one new data view that combines results of several other data views, but we can't due to being unable to select those data views in the filter.

**Closed** 2020-02-12 12:20 UTC
Labels: Status: Confirmed, x-bugapalooza: Med
