### ISSUE TITLE
Attendance Analytic Exception

### ISSUE THREAD

**Issue by AdamSeaton** [SparkDevNetwork/Rock#3775] opened 2019-07-05 14:29 UTC
### Description
Using Attendance Analytics with a large number of groups creates an exception. We have almost 350 active groups in our Volunteer Check-in area. Changing the Show All Groups setting in the block properties will make Attendance Analytics work however the check boxes and headings is a much easier user interface. 

### Steps to Reproduce
1. Have a large number of active volunteer check-in groups
1. Go to the Attendance Analytics page
1. Select Volunteer Check-in from the Attendance Type drop down
1. Get Exception

**Expected behavior:**
Attendance Analytics works

**Actual behavior:**
![CityFirstAttAnalytics](https://user-images.githubusercontent.com/12735965/60595280-4b7ca700-9d6c-11e9-8693-393046165928.png)

### Versions
**Rock Version:** 8.7
**Client Culture Setting:** EN-us

**Comment by nairdo** [comment] 2019-09-18 19:38
If anyone in the community can reproduce this please let us know.  I've tried on an a live/production v8.9 and v9.2 system with over 1890 active volunteer groups without any problem.

@AdamSeaton Are you willing to share your block settings and UI settings (before the exception occurs)?

![image](https://user-images.githubusercontent.com/383807/65179946-a5f2de80-da10-11e9-959d-3eb391226ecf.png)

Here are the my block settings: 

![image](https://user-images.githubusercontent.com/383807/65180150-14d03780-da11-11e9-8f57-ed8a81e81691.png)

**Comment by JimMichael** [comment] 2019-09-18 19:44
I cannot dupe this on our 8.8 production db, with 386 serving team groups

**Comment by krallsm** [comment] 2019-10-16 20:54
I've got this same issue, spent probably all day trying different things to try and get rid of it. I've only come up with the same workaround that Adam found.

Mine is also in the the Volunteer Check-in Group that came with Rock although shifting into a different config doesn't work either. 

Same exact error, only 102 Serving Team groups. Same exact block settings.

**Comment by vineyardcincy** [comment] 2019-10-24 15:38
Testing on v10 on dev site I cannot reproduce this with 2,123 Attendance summaries.  Tried several combinations of group types and numbers of groups and never received any exceptions.

**Comment by krallsm** [comment] 2019-10-24 15:47
> I've got this same issue, spent probably all day trying different things to try and get rid of it. I've only come up with the same workaround that Adam found.
> 
> Mine is also in the the Volunteer Check-in Group that came with Rock although shifting into a different config doesn't work either.
> 
> Same exact error, only 102 Serving Team groups. Same exact block settings.
> 
> Running 8.9

Almost wondering if the issue is not the amount of groups - or if it is, maybe it has something to do with server size and resources it's trying to pull from to process the request? The biggest reason I semi-think it's related to Group Type size is that it's one of our largest Group Types that uses Checkin. Otherwise, I have trouble trying to reproduce the error on other Group Types.

**Comment by krallsm** [comment] 2019-10-29 21:06
I'm not entirely certain what I'm doing when it comes to debugging. I'm starting to explore a little bit of setting up a dev environment and learning some stuff. While doing so I decided to reproduce this in Version 9 with a copy of our database and the exception that I'm getting is saying that Rock.Model.Group.ParentGroup.get is returning null within the Attendance Analytics Block, line 2269

Dunno if that's helpful at all into helping you guys who know what they're doing.

**Comment by krallsm** [comment] 2019-10-29 23:04
Update: Through just reading the diagnostics a bit and using a little SQL to deduct different things. It appears that this error is caused by a Group within a Group Type being Archived. By Unarchiving the groups within that Group Type I was able to get the Attendance Analytics block to work properly. I'm assuming/guessing this was related to another Group History bug that was fixed in v9, I remember another location/attendance thing being an issue in another bug that was fixed.

The issue was produced because the groups within a Group were not archived when the Group was archived. When the Attendance Analytics tries to retrieve the Group that was within the Group that was Archived, it throws an error. 

Sooooo for example. I have a Group Type named Serving Team that checks in every Sunday. I have a tree of Groups in that Group Type that goes Relational>Kids Ministry>Nursery. I archived Kids Ministry. Because I didn't archive Nursery, Attendance Analytics throws the error. However if I Archive Nursery and then Archive Kids Ministry, the error goes away.

**Comment by andypullen** [comment] 2019-12-04 19:59
We are also having this issue with our Volunteer Check-in analytics. Our stack trace is below.
We are running 9.4, our block settings are the same as what @nairdo pasted above, and I cannot find any child groups that are active within an inactive parent group. I'd be happy to share anything else about our setup that would be helpful. 

```   at RockWeb.Blocks.CheckIn.AttendanceAnalytics.<>c__DisplayClass8e.<AddGroupTypeControls>b__83(Group g) in c:\inetpub\wwwroot\Blocks\CheckIn\AttendanceAnalytics.ascx.cs:line 2269
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at RockWeb.Blocks.CheckIn.AttendanceAnalytics.AddGroupTypeControls(GroupType groupType, HtmlGenericContainer liGroupTypeItem) in c:\inetpub\wwwroot\Blocks\CheckIn\AttendanceAnalytics.ascx.cs:line 2268
   at RockWeb.Blocks.CheckIn.AttendanceAnalytics.AddGroupTypeControls(GroupType groupType, HtmlGenericContainer liGroupTypeItem) in c:\inetpub\wwwroot\Blocks\CheckIn\AttendanceAnalytics.ascx.cs:line 2300
   at RockWeb.Blocks.CheckIn.AttendanceAnalytics.rptGroupTypes_ItemDataBound(Object sender, RepeaterItemEventArgs e) in c:\inetpub\wwwroot\Blocks\CheckIn\AttendanceAnalytics.ascx.cs:line 2229
   at System.Web.UI.WebControls.Repeater.OnItemDataBound(RepeaterItemEventArgs e)
   at System.Web.UI.WebControls.Repeater.CreateItem(Int32 itemIndex, ListItemType itemType, Boolean dataBind, Object dataItem)
   at System.Web.UI.WebControls.Repeater.AddDataItemsIntoItemsArray(IEnumerable dataSource, Boolean useDataSource)
   at System.Web.UI.WebControls.Repeater.PostGetDataAction(IEnumerable dataSource)
   at System.Web.UI.WebControls.Repeater.OnDataBinding(EventArgs e)
   at RockWeb.Blocks.CheckIn.AttendanceAnalytics.BuildGroupTypesUI(Boolean clearSelection) in c:\inetpub\wwwroot\Blocks\CheckIn\AttendanceAnalytics.ascx.cs:line 459
   at RockWeb.Blocks.CheckIn.AttendanceAnalytics.OnLoad(EventArgs e) in c:\inetpub\wwwroot\Blocks\CheckIn\AttendanceAnalytics.ascx.cs:line 290
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)```

**Comment by krallsm** [comment] 2019-12-05 21:56
> We are also having this issue with our Volunteer Check-in analytics. Our stack trace is below.
> We are running 9.4, our block settings are the same as what @nairdo pasted above, and I cannot find any child groups that are active within an inactive parent group. I'd be happy to share anything else about our setup that would be helpful.
> 
> ```
>    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
>    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
>    at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>    at RockWeb.Blocks.CheckIn.AttendanceAnalytics.AddGroupTypeControls(GroupType groupType, HtmlGenericContainer liGroupTypeItem) in c:\inetpub\wwwroot\Blocks\CheckIn\AttendanceAnalytics.ascx.cs:line 2268
>    at RockWeb.Blocks.CheckIn.AttendanceAnalytics.AddGroupTypeControls(GroupType groupType, HtmlGenericContainer liGroupTypeItem) in c:\inetpub\wwwroot\Blocks\CheckIn\AttendanceAnalytics.ascx.cs:line 2300
>    at RockWeb.Blocks.CheckIn.AttendanceAnalytics.rptGroupTypes_ItemDataBound(Object sender, RepeaterItemEventArgs e) in c:\inetpub\wwwroot\Blocks\CheckIn\AttendanceAnalytics.ascx.cs:line 2229
>    at System.Web.UI.WebControls.Repeater.OnItemDataBound(RepeaterItemEventArgs e)
>    at System.Web.UI.WebControls.Repeater.CreateItem(Int32 itemIndex, ListItemType itemType, Boolean dataBind, Object dataItem)
>    at System.Web.UI.WebControls.Repeater.AddDataItemsIntoItemsArray(IEnumerable dataSource, Boolean useDataSource)
>    at System.Web.UI.WebControls.Repeater.PostGetDataAction(IEnumerable dataSource)
>    at System.Web.UI.WebControls.Repeater.OnDataBinding(EventArgs e)
>    at RockWeb.Blocks.CheckIn.AttendanceAnalytics.BuildGroupTypesUI(Boolean clearSelection) in c:\inetpub\wwwroot\Blocks\CheckIn\AttendanceAnalytics.ascx.cs:line 459
>    at RockWeb.Blocks.CheckIn.AttendanceAnalytics.OnLoad(EventArgs e) in c:\inetpub\wwwroot\Blocks\CheckIn\AttendanceAnalytics.ascx.cs:line 290
>    at System.Web.UI.Control.LoadRecursive()
>    at System.Web.UI.Control.LoadRecursive()
>    at System.Web.UI.Control.LoadRecursive()
>    at System.Web.UI.Control.LoadRecursive()
>    at System.Web.UI.Control.LoadRecursive()
>    at System.Web.UI.Control.LoadRecursive()
>    at System.Web.UI.Control.LoadRecursive()
>    at System.Web.UI.Control.LoadRecursive()
>    at System.Web.UI.Control.LoadRecursive()
>    at System.Web.UI.Control.LoadRecursive()
>    at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)```
> ```

So if you go into your General Settings>Archived Groups, none of those groups are parents to any active groups?

**Comment by smross** [comment] 2019-12-06 04:04
I have experienced this when switching from the Attendance Type _Weekly Service Check-in_ to _Volunteer Check-in_.
It appears that I can reproduce this on our production system. We use AzureSQL for that system.
When I try to replicate on my sandbox system, it doesn't happen. We use SQL Server for that system, and the data isn't as 'fresh' on the sandbox system.
Block Properties are identical between the 2 systems.

The error I get on my production system:
**Error**
_Object reference not set to an instance of an object_
`   at RockWeb.Blocks.CheckIn.AttendanceAnalytics.<>c__DisplayClass8e.<AddGroupTypeControls>b__83(Group g)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at RockWeb.Blocks.CheckIn.AttendanceAnalytics.AddGroupTypeControls(GroupType groupType, HtmlGenericContainer liGroupTypeItem)
   at RockWeb.Blocks.CheckIn.AttendanceAnalytics.rptGroupTypes_ItemDataBound(Object sender, RepeaterItemEventArgs e)
   at System.Web.UI.WebControls.Repeater.OnItemDataBound(RepeaterItemEventArgs e)
   at System.Web.UI.WebControls.Repeater.CreateItem(Int32 itemIndex, ListItemType itemType, Boolean dataBind, Object dataItem)
   at System.Web.UI.WebControls.Repeater.AddDataItemsIntoItemsArray(IEnumerable dataSource, Boolean useDataSource)
   at System.Web.UI.WebControls.Repeater.PostGetDataAction(IEnumerable dataSource)
   at System.Web.UI.WebControls.Repeater.OnDataBinding(EventArgs e)
   at RockWeb.Blocks.CheckIn.AttendanceAnalytics.BuildGroupTypesUI(Boolean clearSelection)
   at RockWeb.Blocks.CheckIn.AttendanceAnalytics.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)`

(I also have the Exception bookmarked, so if you need the server variables, cookies, or form data let me know

### Of note:
I am working on tracking down a potential _Group Type Association_ issue on my production system. I suspect I have some circular references (so I'm unsure if that's related)

**Comment by nairdo** [comment] 2019-12-06 15:01
Thanks for the updates everyone.  Someone from the team will be investigating this again with the additional details you've all provided.

**Comment by MrUpsideDown** [comment] 2019-12-18 07:02
I was able to reproduce this issue using the method described by @krallsm - inactivating a parent group without inactivating the child group. Thanks to everyone who researched this bug and posted their observations, every bit helps!

**Closed by MrUpsideDown** 2019-12-18 07:02 UTC
Labels: Fixed in v9.5, Review, Topic: Check-in, Type: Bug, x-bugapalooza: Is Needed?
