### ISSUE TITLE
V9 Person Attribute Form Block

### ISSUE THREAD

**Issue by TheArkChurch** [SparkDevNetwork/Rock#3848] opened 2019-08-08 14:58 UTC
### Description
Updated to v9 Beta and had a few person attribute form blocks that had pre and post html set for some attributes. After the update all of the pre and post html was gone. The forms were still there and working.

**Expected behavior:**

That the html data would stay intact and be on the page still.

**Actual behavior:**

All of the pre and post html on the attribute forms was gone and it had to be recreated.

### Versions
* **Rock Version:** [Rock McKinley 9.0 (1.9.0.24)]
* **Client Culture Setting:** [en-US]

**Comment by JimMichael** [comment] 2019-08-08 17:23
Confirmed. I'll also clarify that we're using the stock Person Attribute Forms block, not the modified one from the Rock Shop.

**Comment by TheArkChurch** [comment] 2019-08-08 18:16
We are also using the stock block.

**Comment by JimMichael** [comment] 2019-08-11 19:05
Since this appears to be a data loss issue in v9 upgrade and (presumably) can't be addressed in a future update, is the best course of action to document any pre/post HTML used in instances of this block before upgrading to v9?

**Closed** 2019-08-14 20:20 UTC
Labels: Status: Attention Core Team, Status: Confirmed

**Comment by nairdo** [comment] 2019-08-14 20:22
@JimMichael We found the bug and corrected it.  This fix will be in v9.1.  As long as one updates straight past v9 to v9.1 without editing/saving those forms, the data is still preserved.  (In fact, the data doesn't get wiped out until you open and save it when on v9).

**Comment by TheArkChurch** [comment] 2019-08-14 20:38
Good to know it's fixed. Thanks's guys.
