### ISSUE TITLE
Reverse order when copying content into new communication

### ISSUE THREAD

**Issue by amberstefanski** [SparkDevNetwork/Rock#4477] opened 2020-10-28 14:29 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

_[Write a clear and concise description and include **full window** (non-partial) screenshots. FYI: You can just copy and paste an image directly into here and it will magically upload.]_

### Steps to Reproduce

1. Go to Chrome (v 84.0.4147.135) Google Doc (shared from a fellow staff member)
2. Copy content
3. Paste into WORD (v 16.16.27)
4. Edit content
5. Copy content
6. Begin new communication in Rock (v 11.2)
7. Paste content from Word using Word Paste option.
8. Everything appears in the reverse. Opening is at the bottom and feeds in reverse order to the top. 

**Expected behavior:**

_[A clear and concise description of what you expected to happen.]_

**Actual behavior:**

_[A description of what actually happened.]_

### Versions

* **Rock Version:** [11.2]
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by cabal95** [comment] 2020-10-28 15:26
May be duplicate of #4340

**Comment by ElimAdmin** [comment] 2020-10-29 05:40
Duplicate #4476?

**Comment by nairdo** [comment] 2020-10-29 20:24
Yes, let's close this and call it a duplicate of #4340

**Closed by nairdo** 2020-10-29 20:24 UTC
Labels: Type: Duplicate
