### ISSUE TITLE
Attribute Key Conflict Error With Content Channel Type/Content Channel Item Attributes

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#2572] opened 2017-11-04 14:48 UTC
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Creating attributes of the same key on a content channel type & content channel causes an error when editing blocks that are connected to the content channel (specifically `ContentChannelView`)

### Steps to Reproduce

1. Create an item attribute on any content channel type.
2. Create an item attribute with the same key on any content channel that utilizes the content channel type from the previous step.
3. Edit a `ContentChannelView` block that is configured for the channel you just added the attribute(s) to.

**Expected behavior:** 

If having multiple attributes with the same key causes an exception, is there a way we can block the ability to create multiple attributes with the same key? IE - when creating a content channel item attribute, first check the content type item attributes to verify an attribute with the key doesn't already exist.

Note: @MikeDPeterson mentioned that this file/line may be relevant to the issue:
https://github.com/SparkDevNetwork/Rock/blob/f5969710238a6fbe472bbb6fc69e2adf87e249fe/RockWeb/Blocks/Cms/ContentChannelView.ascx.cs#L975

**Actual behavior:** 

Rock currently allows you to create attributes with conflicting keys, which results in an exception.

![image](https://user-images.githubusercontent.com/2465823/32406376-ac0e882e-c14d-11e7-8aaf-7bf2d680dd86.png)

### Versions

* **Rock Version:** 7.0
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment] 2017-11-04 16:23
If I  am understanding your steps correctly, then step 2 is also where the bug is. If you have created an Item attribute at the Content Channel Type of `MyKey`, then it should **not** let you create another Item attribute at the Content Channel of `MyKey`. I don't have access to my Rock server to verify at the moment, but I believe this is how Groups work. If you used `MyKey` at the Group Type level, it won't let you use the same key at the Group level.

**Comment by briankalwat** [comment] 2017-11-09 13:22
@cabal95 👍  Yep. That's what I was trying to communicate with this: 

> If having multiple attributes with the same key causes an exception, is there a way we can block the ability to create multiple attributes with the same key?

**Comment by edmistj** [comment] 2017-11-09 14:17
Should be a fairly easy fix. I have this assigned to get it fixed.

**Closed** 2017-11-09 20:45 UTC
Labels: Status: Available, Status: Confirmed, Type: Bug

**Comment by briankalwat** [comment] 2017-11-10 14:31
@azturner I just noticed last night that this same issue is a possibility for Global Attributes as well. Would you like me to create a separate issue for that?

**Comment by azturner** [comment] 2017-11-10 15:36
@briankalwat , Not sure I follow how it's an issue with global attributes since they don't inherit attributes from any parent type entity

**Comment by briankalwat** [comment] 2017-11-15 14:44
@azturner Currently you're able to create multiple global attributes with an identical key. Since that causes problems when you then attempt to use that attribute, I thought it'd be good to prevent creating global attributes with a key that is already in use.

**Comment by cabal95** [comment] 2017-11-15 17:47
@azturner Confirmed. Global Attributes lets you create attributes with conflicting keys. I was able to create a new global attribute with they key name `UpdateServerUrl` even though there is already one.

**Comment by azturner** [comment] 2017-11-16 22:54
@briankalwat Can you create new issue for the global attributes (and assign it to me).

**Comment by briankalwat** [comment] 2017-11-22 03:46
@azturner #2605. Thank you!
