### ISSUE TITLE
GetCurrentContext not updating?

### ISSUE THREAD

**Issue by Tschrock** [SparkDevNetwork/Rock#1560] opened 2016-06-03 20:12 UTC
I have a CampusContextSetter and another block that gets the context using RockPage.GetCurrentContext(). If I set the campus context using a query string, my block doesn't get the new context until I do another refresh.

It seems that when calling RockPage.SetContextCookie() with refreshPage = false, RockPage.GetCurrentContext() doesn't get updated and returns the old context until the page is refreshed. This means that if, for ex, the context is set from a query parameter (Like with the CampusContextSetter block), the page will need an extra refresh for other blocks to update.

**Comment by arranf** [comment] 2017-09-09 07:20
@Tschrock Is this still an issue?

**Comment by Tschrock** [comment] 2018-03-29 16:26
Updating with a clearer description:

### Description

When using a block that sets a Context without refreshing the page (like the Set Campus Context block when using a url parameter), other blocks don't update to reflect the new context until the page is refreshed.

### Steps to Reproduce

1. Create a new page
2. Add a Campus Context Setter block
3. Add an HTML Content block with `{{ Context.Campus.Name }}` (to show the current campus context)
4. Use `?CampusId=X` in the url to change the currently chosen campus

**Expected behavior:** 

Both the Campus Context Setter and the HTML Content block should be in sync and show the newly set campus.

**Actual behavior:** 

The HTML Content block shows the previously set context instead of the new one until the page is refreshed again.

### Versions

* **Rock Version:** prealpha (1.8.0.13)
* **Client Culture Setting:**  en-US

**Comment by treyhendon** [comment] 2018-04-17 14:31
I'm seeing a similar thing with the Campus Context Setter.  We have a giving page, the context setter shows my campus because I'm logged in, but no context is actually set on the page and the Financial Accounts are not filtered.  I'm suspecting that the campus context isn't setting in the init so other blocks aren't able to use it.

Alternatively, It might be the opposite is supposed to happen - i.e. all other blocks are supposed to evaluate context on page load (rather than init).

**Comment by MikeDPeterson** [comment] 2018-05-04 17:43
I was able to reproduce this doing what @Tschrock outlined. It looks like it's a bug in both the CampusContextSetter and GroupContextSetter that can be fixed.

**Comment by winmastr** [comment] 2018-07-09 15:03
Whats the status on this? I'm surprised it hasn't been updated?

**Comment by arranf** [comment] 2018-07-09 15:12
@winmastr I recently sunk a lot of time into investigating this and whilst I can easily reproduce the issue navigating a fix is a little more tricky. Rest assured it's not been ignored.

**Comment by MikeDPeterson** [comment] 2018-07-12 19:48
Fixed with https://github.com/SparkDevNetwork/Rock/commit/d3d1c686c5793499bdd6fce61c7b7d4bfa80a30d

**Closed by MikeDPeterson** 2018-07-12 19:48 UTC
Labels: Fixed in v8.0, Priority: High, Status: Confirmed, Type: Bug
