### ISSUE TITLE
Label Merge Fields are including formatting in their output

### ISSUE THREAD

**Issue by tscrip** [SparkDevNetwork/Rock#2952] opened 2018-04-25 16:42 UTC
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When using new Label Merge Fields, I noticed that a previous 6.10 field was getting formatted differently on 7.3. After doing some investigation, I noticed that every \r\n and space were being rendered into the final output. For example:

```
{%- if Person.Gender == 'Male' -%}
    {%- if Person.Age > 10 -%}
        {{ Person.FirstName }}
    {%- endif -%}
{%- endif -%}
```

Would render: `<8 spaces>John`

Where as:

```
{%- if Person.Gender == 'Male' -%}{%- if Person.Age > 10 -%}{{ Person.FirstName }}{%- endif -%}{%- endif -%}
```

Would render `John`

### Steps to Reproduce
1. Create label merge field that has a lot of logic and white space like this:

```
{%- assign groupMembers = Person | Groups: '10' -%}
{%- for groupMember in groupMembers -%}
    {%- assign familyId = groupMember.Group.Id -%}
{%- endfor -%}
{%- groupmember where:'GroupId == {{ familyId }}' -%}
    {%- for gm in groupmemberItems -%}
        {%- if gm.GroupRoleId == 3 -%}
            {%- if gm.Person.Gender == 'Female' -%}
                {{ gm.Person | PhoneNumber:'Mobile' }}
            {%- endif -%}
        {%- endif -%}
    {%- endfor -%}
{%- endgroupmember -%}
```

1. Add merge field to label on far left side
1. Print label and notice that text is being rendered on far right side of label

**Expected behavior:**
No \r\n or whitespace should be interpreted into the merge field output.

**Actual behavior:**
Whitespace is being read and put into the output of the merge field output.

### Versions
* **Rock Version:** 7.3
* **Client Culture Setting:** en-US

**Comment by OnlyByGrace** [comment] 2019-10-24 20:58
Cannot reproduce this on 8.8.

**Comment by nairdo** [comment] 2019-10-25 16:16
Reported as resolved by the #bugapalooza event team.

If you test this is still not working on v9 or later, please let us know by reopening this issue with any additional details you can provide to help us pin point what we might have missed.

**Closed by nairdo** 2019-10-25 16:16 UTC
Labels: bugapalooza: Is Needed?
