### ISSUE TITLE
Defined Value Attribute Field Types Do Not Ignore Inactive Defined Values When 

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#5114] opened 2022-08-18 19:59 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
Did you know you you can simply copy and paste an image below?  Please do that. It really helps us quickly understand the problem.

### Description

_[Write a clear and concise description and include **full window** (non-partial) screenshots. FYI: You can just copy and paste an image directly into here and it will magically upload.]_

### Steps to Reproduce

**Expected behavior:**

_[A clear and concise description of what you expected to happen.]_

**Actual behavior:**

_[A description of what actually happened.]_

### Versions

* **Rock Version:** [Enter Rock version here]
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by nairdo** [comment] 2022-08-19 21:27
This looks like an incomplete duplicate of #5116

**Closed by nairdo** 2022-08-19 21:27 UTC
