### ISSUE TITLE
Communication Merge Fields Only Accept Text

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#802] opened 2015-01-26 18:15 UTC
I have a few custom Person Attributes and am trying to use them in a communication.  Only the attributes that are stored as text show up as available, though.  I have a day of the week and time attribute that do not show up in the merge field list.

**Comment by azturner** [comment] 2015-02-21 14:05
@BelAirIT , I haven't been able to reproduce this based on just the field type (i.e. only text attributes showing up). I did notice that if an attribute is secured in any way, the attribute won't appear in the list of available attributes, could this be the issue you are experiencing?  If so, that will be fixed for next update and until then, you can still use the attribute by typing the lava syntax directly into the communication ( e.g. `{{ Person | Attribute:'attributekey' }}` ).

**Comment by BelAirIT** [comment] 2015-02-23 17:53
Thanks @azturner, that does appear to be the case.  The Person Attributes that are secured don't show up in the list.  But I also can't manually reference them as you suggested either.  They simply do not populate the communicate like the unsecured ones do.  Hopefully this will be resolved in the next update.

**Comment by azturner** [comment] 2015-02-23 23:24
@BelAirIT , Yep, you're right, does look like even the manually entered ones won't work due to the send process not having knowledge of who the current person is in order to determine security. We've updated this also to work in the v3.0 update.

**Closed** 2015-04-13 17:51 UTC
Labels: Fixed in v3.0
