### ISSUE TITLE
Obsidian Registration Entry Block Errors with Signature Documents Enabled

### ISSUE THREAD

**Issue by ashleighearnest** [SparkDevNetwork/Rock#5783] opened 2024-03-08 20:30 UTC
### Description

When a signature document is enabled for an event registration, the registration can not be completed and an "Object reference not set to an instance of an object." exception is generated when a user hits "finish".

![DemoSite 16_3 Example 3](https://github.com/SparkDevNetwork/Rock/assets/137979286/950f5e46-95bf-41a6-87c1-d33bc7e0e170)

This does not happen in v16.2, but does happen in v16.3. I think it could be [related to this commit](https://github.com/SparkDevNetwork/Rock/commit/33cdbb3b21576a75d75f462fa7f1806798330c95).

### Actual Behavior

When a signature document is enabled in a Registration Template, using the Obsidian Registration Entry Block allows a user to register for a Registration Instance and sign the required signature document, but when the user attempts to hit "finish" to complete the registration, an "Object reference not set to an instance of an object." exception is generated.

Screenshot of document loading properly, and signature being accepted:
![DemoSite 16_3 Example 1](https://github.com/SparkDevNetwork/Rock/assets/137979286/c36020c9-7af6-49ed-afb9-efba488fb3a1)

Screenshot of last step before clicking "finish" to complete registration:
![DemoSite 16_3 Example 2](https://github.com/SparkDevNetwork/Rock/assets/137979286/42d2b80a-266e-4d58-b28f-7799ae228989)

Screenshot of last step after clicking "finish" to complete registration (and resulting error message):
![DemoSite 16_3 Example 3](https://github.com/SparkDevNetwork/Rock/assets/137979286/ddb22d64-ea90-4c53-895b-56fa4eca1b2e)

Screenshot of exception:
![DemoSite 16_3 Exeption Screenshot](https://github.com/SparkDevNetwork/Rock/assets/137979286/8382add6-edc5-4a92-9f23-cbea58de6c74)

Exception details (text):
**Exception Date**
3/8/2024 1:02 PM
**Description**
Object reference not set to an instance of an object.
**Page**
(https://www.rocksolidchurchdemo.com/api/v2/BlockActions/f7ca6e0f-c319-47ab-9a6d-247c5716d846/8a29cfd7-04b3-4e36-8764-abb80d65af88/SubmitRegistration)
<html>
<body>

Id | Exception Type | Source | Description |  
-- | -- | -- | -- | --
17372 | System.NullReferenceException | Rock | Object reference not set to an instance of an object. | Hide Stack Trace
at Rock.Pdf.PdfGenerator.GetPDFDocument(String html, String url) in \Rock\Pdf\PdfGenerator.cs:line 431    at Rock.Pdf.PdfGenerator.GetAsBinaryFile(Int32 binaryFileTypeId, String fileName, String html, String url) in \Rock\Pdf\PdfGenerator.cs:line 336    at Rock.Blocks.Event.RegistrationEntry.CreateSignatureDocument(SignatureDocumentTemplate signatureDocumentTemplate, SignedDocumentData documentData, Person signedBy, Person assignedTo, Person appliesTo, String registrantName, String registrationInstanceName)    at Rock.Blocks.Event.RegistrationEntry.UpsertRegistrant(RockContext rockContext, RegistrationContext context, Person registrar, Guid registrarFamilyGuid, RegistrantInfo registrantInfo, Int32 index, Dictionary`2 multipleFamilyGroupIds, Nullable`1& singleFamilyId, Boolean isWaitlist, Boolean isCreatedAsRegistrant, Boolean isNewRegistration, List`1 postSaveActions)    at Rock.Blocks.Event.RegistrationEntry.SubmitRegistration(RockContext rockContext, RegistrationContext context, RegistrationEntryBlockArgs args, String& errorMessage)    at Rock.Blocks.Event.RegistrationEntry.SubmitRegistration(RegistrationEntryBlockArgs args)

</body>
</html>

### Expected Behavior

If this were working properly, a user would:

- Be able to click "finish" to complete their registration, and their registration would be added to the corresponding registration instance
- The user's signed signature document would be emailed to them as a PDF copy
- The user's signed signature document would be accessible as a PDF from the user's submitted registration within the registration instance 
- The user's signed signature document would be saved and accessible from the signature document template

### Steps to Reproduce

- On the demo site, create a registration instance and enable a signature document on the corresponding registration template.
![rock rocksolidchurchdemo com_page_403_RegistrationTemplateId=4](https://github.com/SparkDevNetwork/Rock/assets/137979286/ba458264-9a8c-4c74-b1dc-9a57c38b9a81)

- Have a registrant register for the event that has a signature document required. Exception is generated when the user clicks "finish" at the end of their registration.
![DemoSite 16_3 Example 3](https://github.com/SparkDevNetwork/Rock/assets/137979286/32dae3fc-701c-40e0-8996-a77199036498)

_Note: signature documents with registrations were confirmed to work on the demo site on v16.2, prior to v16.3 install. Signature documents generated prior to update worked as-expected and are still accessible within registrations for the same event._

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.3 (1.16.3.5)

### Client Culture Setting

en-US

**Comment by mikedotmundy** [comment] 2024-03-08 20:36
Confirm this is happening for us too.

**Comment by jasonhendee** [comment] 2024-03-08 23:53
@ashleighearnest thank you for reporting this issue.

Turns out this was fixed by a commit added to address [a related issue](https://github.com/SparkDevNetwork/Rock/issues/5736): https://github.com/SparkDevNetwork/Rock/commit/99c6ea1100768b908c5e47aaf1c731cbf840cbb6. This fix will be in Rock v16.4.

**Closed by jasonhendee** 2024-03-08 23:53 UTC
Labels: Type: Bug, Status: Confirmed

**Comment by zackdutra** [comment] 2024-03-09 17:25
@jasonhendee any caution against us updating the files in that commit ourselves to do this in 16.3?  We keep holding off on updating from 15 because of critical issues for us in each of the 16 releases and this one is a deal breaker. We can’t really wait for 16.4 though because we need the signature document enhancement we funded in 16.

**Comment by jasonhendee** [comment] 2024-03-11 15:41
> @jasonhendee any caution against us updating the files in that commit ourselves to do this in 16.3? We keep holding off on updating from 15 because of critical issues for us in each of the 16 releases and this one is a deal breaker. We can’t really wait for 16.4 though because we need the signature document enhancement we funded in 16.

@zackdutra I'll discuss this with @nairdo this morning and get back with you through Rocket.Chat if that works for you?

**Comment by zackdutra** [comment] 2024-03-11 16:35
Yes, thank you!

**Comment by mikedotmundy** [comment] 2024-03-11 23:09
@jasonhendee I am wondering the same question. We have a few Registration Templates where I had to disable signature documents.

**Comment by jasonhendee** [comment] 2024-03-12 05:54
@mikedotmundy, @zackdutra, we've discovered another way to bypass this issue in Rock v16.3 **without** the need to merge the above code fix or recompile Rock:

By enabling Observability - even with a fake telemetry endpoint like _localhost_ in the screenshot below - the above error will not be encountered when registering for Events requiring a Signature Document. This issue arose because Rock was incorrectly expecting Observability to always be enabled, and is throwing an error when it's not enabled. Here's how to make those changes:

![image](https://github.com/SparkDevNetwork/Rock/assets/59710095/ac70f7e3-aae2-4878-a8d9-03952195165f)

### Better Yet
We recommend taking this opportunity to go ahead and sign up for your free New Relic account, so you can [start collecting telemetry data](https://community.rockrms.com/Rock/BookContent/9#observability) (instead of using the fake _localhost_ endpoint in the screenshot above). This will prevent the error from occurring while also providing some pretty cool insight into how your Rock instance is performing.

**Comment by zackdutra** [comment] 2024-03-12 05:58
Thanks @jasonhendee! I've passed this onto our team.

**Comment by mikedotmundy** [comment] 2024-03-12 19:50
Thank you @jasonhendee!

**Comment by emmyfriesen** [comment] 2024-03-18 20:24
@jasonhendee I'm thinking the fix in 16.4 will address this (but still wanted to let you know)- we are running into this same issue with the electronic signature workflow action in 16.3.

**Comment by jasonhendee** [comment] 2024-03-19 21:28
> @jasonhendee I'm thinking the fix in 16.4 will address this (but still wanted to let you know)- we are running into this same issue with the electronic signature workflow action in 16.3.

Thank you, @emmyfriesen!

- Confirmed: I was able to reproduce this workflow action issue in Rock v16.3 and verified that it's fixed in v16.4.
- The above Observability workaround will also temporarily bypass this workflow action issue in v16.3.

**Comment by ashleighearnest** [comment] 2024-03-20 15:50
@emmyfriesen just a heads up that we implemented the Observability workaround and have been running Signature Documents successfully for a week in 16.3
