### ISSUE TITLE
navbar-nav class has negative margin on small width screens

### ISSUE THREAD

**Issue by ghost** [SparkDevNetwork/Rock#1300] opened 2015-11-10 15:52 UTC
This causes the li within the ul to overflow to the left.  With different styling applied to the ul, the overflow issue is more obvious.

![navbar-nav-negative-margin-issue](https://cloud.githubusercontent.com/assets/8700223/11067122/005231ce-8799-11e5-85c8-f0331f47cb55.png)

Also note, there is a media query that applies `margin: 0;` for sizes 768px and up, which short circuits the problem for desktop sized screens.

**Comment by edmistj** [comment] 2015-11-10 20:22
Do you have a suggested fix, or do you want us to work on one?

**Comment by benwiley** [comment] 2015-11-10 20:27
Can we remove the -15px margin on the navbar-nav class?  I'm not sure if that is a bootstrap default or if it was added for some other reason.

**Comment by edmistj** [comment] 2015-11-10 20:48
Looked at it and it's a part of Bootstrap. I'd worry about globally overriding it in Rock as it's probably there for a reason. You might override it in your specific case with something like:

.parent .contextsetter {
    margin: 0;
}

You can see that in this situation on the CCV site (you'll need to pick a campus to move to the next screen to see that context setter).
http://rock.ccvonline.com/home

@sheck do you have any thoughts on this. Open to suggestions.

**Comment by sheck** [comment] 2015-11-14 00:07
I think the problem is that the context setter contains markup meant specifically for a bootstrap navbar component. Because of this, when it is not in a BS navbar, it can behave and look different than expected.

Is it feasible to use a lava template for this block?

**Comment by arranf** [comment] 2017-09-09 09:36
@edmistj I'm closing this as this is ancient and doesn't seem to have caused problems in my memory. If I'm wrong, feel free to open this back up.

**Closed by arranf** 2017-09-09 09:36 UTC
Labels: Topic: UI, Type: Bug
