### ISSUE TITLE
Group List Block Displaying Former Groups

### ISSUE THREAD

**Issue by bjacky** [SparkDevNetwork/Rock#5990] opened 2024-08-24 21:14 UTC
### Description

In Rock 15.5, the behavior of the **Group List Block** has changed to show former groups for people for which they have been archived and are no longer active or inactive members. This was not the case in Rock 14 and previously. I also don't believe it was an issue in 15.1 but it has appear for me after upgrading to 15.5. It doesn't make sense to show past groups in the Group List block the same way that current inactive group membership appears. Would like to see previous behavior restored. Having Rock Star access, I've used the Rock 14.4 TM demo to verify that it works as expected and I've verified that this issues appears in Rock 15 TM demo and continues on the Rock 16.6 demo server.

### Actual Behavior

Actual Behavior: Admin has been archived from the Marble Group but it appears to still be an inactive member.

![image](https://github.com/user-attachments/assets/d0f9df98-1bb8-4004-9518-9d66e32d7e77)

### Expected Behavior

Expected Behavior: Past membership appears in the Group History block above but the group should not appear in the Group List block. This correct image does not show the Marble Group in the Group List.

![image](https://github.com/user-attachments/assets/51b4572a-5d2a-4c9b-81d6-49f960d153a6)

### Steps to Reproduce

- Go to **Rock Demo**
- Run the **Process Group History** job > https://rock.rocksolidchurchdemo.com/admin/system/jobs
- Go to Alisha Admin's Groups tab > https://rock.rocksolidchurchdemo.com/person/1/groups?ToolboxActionType=0
- Archive her from Marble Group or Ushers team and see that group is still listed.
- See error

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock 15.5 and Rock 16.6

### Client Culture Setting

en-US

**Comment by chead4** [comment] 2024-08-26 16:22
@bjacky HI Bobby I will be closing this issue as, we’ve made an improvement to the Group List block with enhancement #5410 in v15.2. We've added a new block setting called "Limit to Active Status." This lets you choose which groups to display based on their active status. The default is [All] to let the user filter by active status,  To only have active groups display in the Group List block, you can either select the Filter Option of Active Status/Active or you can update the block setting "Limit to Active Status" setting to Active.

**Closed by chead4** 2024-08-26 16:22 UTC

**Comment by bjacky** [comment] 2024-08-26 23:26
@chead4 In doing data integrity work, I find it extremely useful to be able to see which groups a person is currently active and inactive within. There is now no way to view this information in this block because it is also shows past group participation when [All] is selected. If I use the Active or Inactive filters, I am only seeing half of the information I need so I have to keep switching it. Do I need to submit a feature request to give us the option to view both Active and Inactive to the block at the same time without showing the groups of which a person was formerly a member?

**Comment by nlabarbera** [comment] 2024-08-30 00:11
Hey @bjacky - I appreciate your input and agree that this would be a valuable enhancement. While we plan to implement it, we’ll keep this GitHub issue closed since it’s not a bug. We’ve documented the request internally as an enhancement. Currently, our team is deeply focused on the release of v17, so I can’t provide a specific timeline for when this enhancement will be available. 

That said, I’m excited for you to experience some of the great new features in v17 🚀
