### ISSUE TITLE
Event Registration Conditional Fields Filter Icon Missing

### ISSUE THREAD

**Issue by kkiserGH** [SparkDevNetwork/Rock#4378] opened 2020-08-27 12:53 UTC
### Prerequisites
* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

**Sorry!  This a duplicate of #4353**

### Description

Once you set a conditional field filter in an event registration template, the filter icon is not visible (see attached image).  It still functions so you can edit the fitler but you have to click in the area where the button image should be to do so.

### Steps to Reproduce

1.  Create a new Registration Template
2.  Add two Registrant Attribute fields.
3.  Add a Filter to the second field.

**Expected behavior:**

The filter is applied and filter icon is still visible

**Actual behavior:**

The filter icon disappears for the field that has the filter.  As you can see from the attached image, the filter field is still there as you can tab to it and you can click on it to edit the filter.  But the filter icon is missing once the filter has been set.

### Versions

* **Rock Version:** v 11.0
* **Client Culture Setting:** en-US
![Event Registration Conditional Fields Filter Icon Missing](https://user-images.githubusercontent.com/54817742/91444285-22ee2100-e83a-11ea-9730-7d2806616db7.PNG)

**Comment by nairdo** [comment] 2020-08-27 16:04
As @kkiserGH mentioned above, this is a duplicate of #4353. closing.

**Closed by nairdo** 2020-08-27 16:04 UTC
