### ISSUE TITLE
Certain System Communications Are Not Written To History

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4953] opened 2022-03-24 21:51 UTC
### Description

While troubleshooting some user problems around resetting their passwords, I noticed that I could no longer see certain system emails in Communication History, such as those with subject "Account Reset" or "Account Created".

### Steps to Reproduce

1. Create a new account or do a forgot password on your public website

2. You should receive the corresponding email

3. Go to the person's profile and look at their history, and see there's no record of this email being sent.

4. Go to People | Communication History and observe that this email doesn't show up there, either.

5. If you're on a instance with enough history, you can go back and search for subject "Account Created" and see they exist BEFORE a certain date, but not after. This date would be (I think) dependent on when the instance was upgraded to a different version of Rock. My best guess on our instance is that it stopped working somewhere between the 12.1 and 12.4 updates, which corresponds to May 2021 for us.
 
Observe how our history stops at 5/9/2021 even though I'm filtering for well beyond that date. If I switch the filter to 'Account Reset', they too stop on the exact same date.

![image](https://user-images.githubusercontent.com/3903408/160016096-99caef7b-645f-49a2-b5c7-4b619b0ba574.png)

**Expected behavior:**

Account created, Account Reset, etc System Communications would be written to history, which is a valuable forensics tool when tracking down user issues.

**Actual behavior:**

After a certain release, these communications stopped being written to history, or written in a way that they are not accessible via Communications History.

### Versions

* **Rock Version:** 12.4 (my current version) and subsequent releases.

**Comment by dataCollegechurch** [comment] 2022-03-24 22:00
Confirmed on 12.6 as well

**Comment by jennifertroeger** [comment] 2022-05-17 17:04
v13.4 alpha testing on my system shows that the Account Created email is still not logged in Communication History (from the person profile nor from the People > Communication History navigation).

**Comment by nairdo** [comment] 2022-05-17 18:05
Hi @jennifertroeger, sorry about the confusion here.  This is the short story:   Both the ForgotUserName and AccountEntry blocks were originally ([here](https://github.com/SparkDevNetwork/Rock/blob/6caee726161b78860b818d636ab2d497cebedbc0/RockWeb/Blocks/Security/ForgotUserName.ascx.cs#L139) and [here](https://github.com/SparkDevNetwork/Rock/blob/468158c895a7b16daf80da7d7acbd4f2ee3823fc/RockWeb/Blocks/Security/AccountEntry.ascx.cs#L888) respectively) **not** supposed to write a record to the communication history, but due to a bug, that setting was being ignored up until it was "fixed" in v12.1.  That change in behavior resulted in _this_ issue being opened.  

To deal with this, we just added a block setting ("**Save Communication History**" defaulting to false) to allow you to enable whether or not a communication history should be written.

I've updated the release note for this item but please do reply back once you confirm it is working when the block setting is enabled.

**Comment by jennifertroeger** [comment] 2022-05-18 19:41
Thanks @nairdo for the clarification - that definitely helps, especially since I didn't read the release notes before testing some of these fixes.

That being said, I've adjusted the setting on the Create Account block, indicating that it SHOULD saved, but still do not see it in the Communication History (I did receive the email, however).

**Comment by JimMichael** [comment] 2022-05-19 19:02
On 13.4 alpha I adjusted our new account block to "save to history" and created a new account, and can confirm that the email was not written to history (though it was received)

**Comment by croske** [comment] 2022-05-20 22:58
We have confirmed that this is from an issue that we identified internally and fixed (https://github.com/SparkDevNetwork/Rock/commit/5833116b6ea7212c0070f8850015db38f76d31e1) shortly after v13.4 alpha testing started.  This will be fixed in v13.4 beta.  Thank you!

**Closed** 2022-05-23 17:25 UTC
Labels: Status: Confirmed, Fixed in v13.4
