### ISSUE TITLE
Registrant Email Not Updating in Event Registration

### ISSUE THREAD

**Issue by alyssa-pathway** [SparkDevNetwork/Rock#2964] opened 2018-05-03 16:07 UTC
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When registering for an event, if a person adds or changes an email address within registration, the change does not take effect in the database. This is in the registrant form, not the registered by form. We were testing with people that are logged in to our external website (or their family members).

### Steps to Reproduce

1. Register a person for an event. 
2. Add or change an email address.
3. View person's profile to notice that the change was not made in the database.

**Expected behavior:** 

We expect that the email will be automatically added or automatically changed based off of what was entered in registration.

**Actual behavior:** 

The person is registered for the event, but the email address does not change in the database.

### Versions

* **Rock Version:** v7.3 
* **Client Culture Setting:** en-US

**Comment by rutledgek** [comment] 2018-05-04 17:15
On a related note.  If someone registers for an event, the email is coded into the registration.  If a different process changes their email(I.e online giving etc) the registration emails use the encoded email rather than the person’s current email. 

We had someone register and not provide an email.  We later added an email to their records but did not realize that they were not getting the emails because their registration still had a blank email field

**Comment by edmistj** [comment] 2018-05-04 18:49
Hi @alyssa-pathway! Are you referring to the email address on the Registrar (confirmation email) or the Registrant? The confirmation email on the registration isn't linked to a person but is tied to the registration itself. Is that something you see as an issue? Just looking for a confirmation to ensure we're on the same page.

@rutledgek Is this the same issue? Are you referring to the confirmation email also? If this is a different issue it probably deserves it's own issue.

**Comment by alyssa-pathway** [comment] 2018-05-04 18:52
Hey @edmistj, we are seeing this on the registrant. If the email field is blank (on the registrant) adding one will not populate it in the database. Editing an existing email will not change it in the database.

**Comment by rutledgek** [comment] 2018-05-04 19:15
I am talking about the email attached to the registration.  If the person ever changes their email address this doesn’t get updated.

**Comment by edmistj** [comment] 2018-05-04 22:39
@rutledgek this is a separate issue. Probably best to keep this separate so as not to confuse. That said the email you are describing is not a person email, but the confirmation email attached to the registration. Changing this behavior would be an enhancement request (but I'm not certain that would be a better change, more input from the community would be needed.)

**Comment by edmistj** [comment] 2018-05-04 22:46
@alyssa-pathway got it.

I can confirm that the email address is not being updated. We'll get this fixed. Just missed the boat for v7.4, but it will be in the next update after that.

**Closed** 2018-08-02 17:32 UTC
Labels: Priority: Critical, Status: Available, Status: Confirmed, Type: Bug
