### ISSUE TITLE
Workflow Buttons in Email Not Functioning as Intended

### ISSUE THREAD

**Issue by charlottedean** [SparkDevNetwork/Rock#4359] opened 2020-08-20 15:41 UTC
**Description**

When working in Assigned Workflows and Forms when and 'Workflow Form Notification' is sent and 'Include Actions in Email' is checked off the action buttons that are intended to-do items within the workflow actually don't work in the intended functionality.  

### Steps to Reproduce

1. Create a workflow with a form
2. Assign activity to a person
3. Create an activity with a form with the notification turned on and the include actions in email checked off
4. Have two different button commands (submit and deny as an example) that do different activities associated to them
5. Fire the workflow
6. Receive workflow form notification
7. Click on Submit, all it does bring the workflow up in a new window, it does the same thing as the View Details button, when it should do the assigned activity associated to it within the form activity.  

**Expected behavior:**

The Submit or Deny buttons should process the assigned activity, instead, they both are working like the View Details button. 

**Actual behavior:**

The buttons acted like the View Details button

### Versions

* **Rock Version:** 10.3
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1195883504053950">4359 Test_202009251145.zip</a>

**Comment by JimMichael** [comment] 2020-08-20 19:00
I can confirm seeing this behavior on our system (still 10.2). The links behind the buttons in the email _have_ the actions tacked on (e.g. `&action=submit` or `&action=delete` but they don't actually perform those actions. The workflow form simply appears as if you had clicked View Details.

**Comment by ethan-sparkdevnetwork** [comment] 2020-09-08 22:44
@charlottedean @JimMichael I am having trouble reproducing this issue in 10.2, 10.3, and 11.2. Can I get an export file of a workflow with the problem? Here are the activities/actions of my tests:

1. Create two workflow text attributes "Attribute 1" and "Attribute 2"
1. Create Activity called "Email Form"
   a. Create Action "Assign Activity" of type Activity Assign to Person and select Ted Decker
   b. Create Action "Email Form Action" of type Form.
       i. Select a system email and check "Include Actions in Email"
       ii. Check form fields as visible
       iii. Create two buttons, one to run activity "Update Attribute 1 Activity" and the other "Update Attribute 2 Activity"
2. Create Activity "Update Attribute 1"
   a. Create Action "Set Attribute 1 Value"  of type "Attribute Set Value" to update workflow attribute "Attribute 1" to "Attribute 1 Clicked"
   b. Create Action Workflow Complete
3. Update Attribute 2 Activity
   a. Create Action "Set Attribute 2 Value"  of type "Attribute Set Value" to update workflow attribute "Attribute 2" to "Attribute 2 Clicked"
   b. Create Action Workflow Complete

I run the workflow and get an email. Selecting a button does successfully set the corresponding workflow attribute and ends the workflow. I tried responded to the workflow as Ted Decker and the admin accounts, both worked.

**Comment by JimMichael** [comment] 2020-09-09 14:25
[jim.zip](https://github.com/SparkDevNetwork/Rock/files/5195819/jim.zip)

Here's a workflow I tried it on. It's a pretty simple 2-form thing where a workflow is submitted on the public website via a workflow entry block, then it gets assigned to a person. That person receives the email which has View Details, Complete, and Delete buttons. Clicking Complete should run the _Complete Workflow_ activity and clicking Delete should run the _Delete_ workflow activity, but in both cases I just end up on the second form as if I had clicked View Details.

**Comment by ethan-sparkdevnetwork** [comment] 2020-09-11 22:17
@JimMichael Your workflow functioned correctly for me. I did notice that you mentioned the query string parameters in the URL were for "action". Try the same URL but with **"Command"** instead of **"action"**.

Doesn't work:
/WorkflowEntry/25?WorkflowGuid=d8180157-3e73-417d-9125-f9b1715f7d12&ActionId=19&**action=Submit**

Works:
/WorkflowEntry/25?WorkflowGuid=d8180157-3e73-417d-9125-f9b1715f7d12&ActionId=19&**Command=Submit**

**Comment by JimMichael** [comment] 2020-09-11 22:36
Yes, switching to `Command=` made it work as expected! So... I guess the question is why the URLs my workflows are sending me have `&action=` for the buttons instead of `Command=`? I'm not aware of any place that controls this. Could I have the workflow configured incorrectly somehow? All I did on the second form is enable _Include Actions In Email_

**Comment by ethan-sparkdevnetwork** [comment] 2020-09-11 22:36
@JimMichael @charlottedean 
Make sure the email used has the correct parameter in the Lava:

{% capture ButtonLinkReplace %}{{ 'Global' | Attribute:'InternalApplicationRoot' }}WorkflowEntry/{{ Workflow.WorkflowTypeId }}?WorkflowGuid={{ Workflow.Guid }}&ActionId={{ Action.Id }}&**Command**={{ button.Name }}{% endcapture %}

So the whole code block for the command buttons looks something like this:
>
>     {% if Action.ActionType.WorkflowForm.IncludeActionsInNotification == true %}
>         {% if RequiredFields != true %}
>     
>             {% for button in Action.ActionType.WorkflowForm.Buttons %}
>                 {% capture ButtonLinkSearch %}{% raw %}{{ ButtonLink }}{% endraw %}{% endcapture %}
>                 {% capture ButtonLinkReplace %}{{ 'Global' | Attribute:'InternalApplicationRoot' }}WorkflowEntry/{{ Workflow.WorkflowTypeId }}?WorkflowGuid={{ Workflow.Guid }}&ActionId={{ Action.Id }}&Command={{ button.Name }}{% endcapture %}
>                 {% capture ButtonHtml %}{{ button.EmailHtml | Replace: ButtonLinkSearch, ButtonLinkReplace }}{% endcapture %}
>                 {% capture ButtonTextSearch %}{% raw %}{{ ButtonText }}{% endraw %}{% endcapture %}
>                 {% capture ButtonTextReplace %}{{ button.Name }}{% endcapture %}
>                 {{ ButtonHtml | Replace: ButtonTextSearch, ButtonTextReplace }}
>             {% endfor %}
>
>         {% endif %}
>     {% endif %}
>

**Comment by JimMichael** [comment] 2020-09-11 22:39
![image](https://user-images.githubusercontent.com/3903408/92978509-9789a800-f455-11ea-838e-f6fc1cbc86e2.png)
Bingo. Thanks! I wonder how long ours has been that way... we have an instance going back to 5.3 or something so I wonder if it got changed along the way but our System communication never did.

**Comment by ethan-sparkdevnetwork** [comment] 2020-09-11 23:10
Back in v7.1 the System email Workflow Form Notification was changed to use "Command" instead of "action" and also include an "actionId" parameter. There was a migration to make this change but if that section of lava had been altered at all then it would not have been updated. When you update your email make sure to also include the actionId parameter: `&ActionId={{ Action.Id }}`

**Comment by ethan-sparkdevnetwork** [comment] 2020-09-11 23:14
@charlottedean Can you check the email being used by your workflow to see if it is using "Command" instead of "action"?

**Comment by hbcpn** [comment] 2020-09-11 23:20
> @charlottedean Can you check the email being used by your workflow to see if it is using "Command" instead of "action"?

I will check that as well because I've also noticed these buttons not working and it's been some time. I just have a very non-communicative team that doesn't let me know when things aren't working as they should to notice sometimes. But this happened somewhere along the v10 point releases, but cannot pinpoint exactly.

**Comment by charlottedean** [comment] 2020-09-11 23:25
Hi, yes.  It is using "command" from what I can tell.   Below are lines 60-75 in the email:

`    {% if Action.ActionType.WorkflowForm.IncludeActionsInNotification == true %}

        {% if RequiredFields != true %}
    
            {% for button in Action.ActionType.WorkflowForm.Buttons %}
                {% capture ButtonLinkSearch %}{% raw %}{{ ButtonLink }}{% endraw %}{% endcapture %}
                {% capture ButtonLinkReplace %}{{ 'Global' | Attribute:'InternalApplicationRoot' }}WorkflowEntry/{{ Workflow.WorkflowTypeId }}?WorkflowGuid={{ Workflow.Guid }}&ActionId={{ Action.Id }}&Command={{ button.Name }}{% endcapture %}
                {% capture ButtonHtml %}{{ button.EmailHtml | Replace: ButtonLinkSearch, ButtonLinkReplace }}{% endcapture %}

                {% capture ButtonTextSearch %}{% raw %}{{ ButtonText }}{% endraw %}{% endcapture %}
                {% capture ButtonTextReplace %}{{ button.Name }}{% endcapture %}
                {{ ButtonHtml | Replace: ButtonTextSearch, ButtonTextReplace }}
            {% endfor %}
        {% endif %}

    {% endif %}`

**Comment by hbcpn** [comment] 2020-09-12 00:02
I thought it may be strange that maybe WF forms would possibly be using the System Email (Legacy) in v10 and beyond but the line in it is okay on ours, also confirming the Communication Template line that @charlottedean sent is the same.
Below is from the Legacy template:
`                {% capture ButtonLinkReplace %}{{ 'Global' | Attribute:'InternalApplicationRoot' }}WorkflowEntry/{{ Workflow.WorkflowTypeId }}?WorkflowGuid={{ Workflow.Guid }}&ActionId={{ Action.Id }}&Command={{ button.Name }}{% endcapture %}`

**Comment by JimMichael** [comment] 2020-09-12 16:49
I think one or both of you will also need to upload a workflow that doesn't work for you, as the bad lava was 100% my issue (and just for accuracy-sake... the Lava that was bad and I changed was in the _Workflow Form Notification_ under _System Communications_. I didn't even look at the Legacy communications.

**Comment by ethan-sparkdevnetwork** [comment] 2020-09-21 16:15
@charlottedean Can you send me a copy of a problem email that the workflow creates? I would just like to inspect the markup so I won't need to click on anything. Any old email that didn't work would be best. ethan@sparkdevnetwork.org.

**Comment by charlottedean** [comment] 2020-09-21 16:19
Yes, I will need to dig for one.


* Charlotte Dean**, **Data/Office Coordinator*
 6735 Crosswinds Dr. N., St. Petersburg, FL 33710
<https://maps.google.com/?q=6735+Crosswinds+Dr.+N.,+St.+Petersburg,+FL+33710&entry=gmail&source=g>
 Office Phone: 727-384-3400 <(727)%20384-3400>
 www.bridgepointfl.com  |  campuses & service times
<http://www.bridgepointfl.com/new>

**Comment by ethan-sparkdevnetwork** [comment] 2020-11-05 20:04
Thanks to Charlotte and Jim for hunting this one down! The issue was lava in one case and a non-core version of SendGrid in another. If anyone else runs into a similar issue check those two things and open a new issue if needed.

**Closed by ethan-sparkdevnetwork** 2020-11-05 20:04 UTC
