### ISSUE TITLE
Activity Types like 'Connected', 'Transferred', 'Assigned' showing as options in Connection Board block

### ISSUE THREAD

**Issue by sam-crisp** [SparkDevNetwork/Rock#4721] opened 2021-06-17 16:48 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

![Screen Shot 2021-06-17 at 11 42 19 AM](https://user-images.githubusercontent.com/44408754/122439383-3a310300-cf61-11eb-8954-f3deb2595c8c.png)
![Screen Shot 2021-06-17 at 11 26 46 AM](https://user-images.githubusercontent.com/44408754/122439395-3c935d00-cf61-11eb-8976-4239f22d5cda.png)

### Description

When adding a new Activity to a connection request from the Connections Board, I have the option to create activities for types like 'Connected', 'Transferred', and 'Assigned', even though these are not available on the regular Connection Request Detail block and should, probably, not be included here either. If a user creates one with one of the system types, they cannot delete the activity. 

### Steps to Reproduce

1. Go to People > Engagement > Connections. Select a connection request in the Connection Board view.
2. Click +Add Activity button
3. Under Activity Type dropdown, select 'Connected', add a note, and save.

**Expected behavior:**

Under Activity Type dropdown, only Connection Type activities are listed, and not Connected, Transferred, Assigned

**Actual behavior:**

Under Activity Type dropdown, the global types of Connected, Transferred, Assigned are listed alongside the correct Connection Type activities.

### Versions

* **Rock Version:** [1.12.4]
* **Client Culture Setting:** [EN-US]

**Comment by JimMichael** [comment] 2021-06-17 16:54
This appears to be a duplicate of https://github.com/SparkDevNetwork/Rock/issues/4692

**Closed** 2021-06-17 17:10 UTC
Labels: Topic: Connection, Type: Bug
