### ISSUE TITLE
[EN] Creating Layouts in Rock

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#1213] opened 2015-08-24 19:48 UTC
# How can we empower Rock users to create the layouts they need?
Hey guys! Below are some thoughts we've been formulating regarding layouts as we've been working on our Rock theme. They are by no means a "this is what we should do", but rather a conversation starter for us to discuss how we can improve layouts in Rock. It's fairly lengthy, so feel free to read it over, chew on it for a while and then ask questions, make suggestions, point out problems and the like. We, just like you, want to make Rock the best that it can be!

# **How Layouts Currently Work**
#### 1. Predefined layouts + Rock zones within an individual theme
```html
<div class="row">
      <div class="col-md-3">
                <Rock:Zone Name="Sidebar 1" runat="server" />
      </div>
      <div class="col-md-9">
                <Rock:Zone Name="Main" runat="server" />
      </div>
</div>

<div class="row">
      <div class="col-md-12">
                <Rock:Zone Name="Section A" runat="server" />
      </div>
</div>

<div class="row">
      <div class="col-md-4">
                <Rock:Zone Name="Section B" runat="server" />
      </div>
      <div class="col-md-4">
                <Rock:Zone Name="Section C" runat="server" />
      </div>
      <div class="col-md-4">
                <Rock:Zone Name="Section D" runat="server" />
      </div>
</div>
```

#### 2. Ability to extend/nest layouts with block-instance level lava template code
![image](https://cloud.githubusercontent.com/assets/2465823/9359158/a8074f8a-465d-11e5-82e8-032c6f14c6d1.png)

![image](https://cloud.githubusercontent.com/assets/2465823/9359174/bab8e918-465d-11e5-9d95-e32397523c24.png)

## **Issues**
* Users are unable to make changes/create new layouts without writing code.
* Changes to Lava templates at the block-instance level are not carried back to a source file, which will make maintaining the consistency of layout changes a major issue over time.
# **How can we make it better?**
#### 1. Adding a block width field

By adding a block width field to the [RockBlock class, ](https://github.com/briankalwat/Rock/blob/develop/Rock/Web/UI/RockBlock.cs) users can create custom layouts **without writing any code.** We would limit the number of options for the sake of simplicity (halves, thirds, and quarters), and make the decisions on what each block width changes to at various breakpoints (ex: a 3 column block would become 6 columns at the small breakpoint, and 12 at the extra small), so the user only has to worry about the layout of a single breakpoint. Each block would then be output within a grid column, set to the width chosen by the user.

![image](https://cloud.githubusercontent.com/assets/2465823/9361007/7347fc4a-4667-11e5-9832-273c2991184a.png)

```html
<div class="col-md-3 col-sm-6 col-xs-12">
      [ Block Contents ]
</div>
```

#### 2. Limit theme layouts to high-level page segmentation
In order for this to all work consistently, it'd be best to limit layout themes to high-level page segmentation (two columns, three columns, full width, etc). Also, the gutters between layout columns need to exist at the block level, not in the layouts themselves. This would introduce the use of the flush/hard helper classes for removing negative margins and padding from layout-level bootstrap grid elements.

```html
<div class="row flush">
      <div class="col-md-8 hard">
            <div class="row">
                  <Rock:Zone Name="Section A" runat="server" />
            </div>
      </div>
      <div class="col-md-4 hard">
            <div class="row">
                   <Rock:Zone Name="Section B" runat="server" />
            </div>
      </div>
</div>
```

#### 3. Limit Lava templates to non-layout customization
In order for this to work, our layout grid elements need to all be set at the same level (layout/block model/block instance). Making changes on multiple levels is what introduces inconsistency, so we'd want to emphasize **not** using lava templates to make layout changes. Also, to improve consistency at the block-instance level, it would be ideal to have a filename attribute added to the lava editor, so changes can be copied back to a static file that can be shared across block instances.

**Comment by edmistj** [comment] 2015-08-24 23:06
@briankalwat This is perfect timing. We were just talking with some of the web guys at Central on something very similar. They are wanting to create tools similar to the Visual Composer plugin for WordPress http://vc.wpbakery.com/.

This is something we'd like to get started on for v5.

**Comment by edmistj** [comment] 2015-08-24 23:18
@briankalwat One other thing... you can do what your describing somewhat today with a blocks 'Pre-HTML' and 'Post-HTML'. These are on the Advance tab of the block settings. Not quite as user-friendly as what you describe, but the same concept (I think).

**Comment by cabal95** [comment] 2018-03-15 17:49
Marking as confirmed as it's well described, but not sure if this is still something that would be on the roadmap for Rock?

**Comment by jonedmiston** [comment] 2019-08-23 15:04
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.

**Closed by jonedmiston** 2019-08-23 15:04 UTC
Labels: Status: Confirmed, Type: Enhancement
