### ISSUE TITLE
Exception when using a Merge Template from Connections

### ISSUE THREAD

**Issue by KelleyLangkamp** [SparkDevNetwork/Rock#3700] opened 2019-05-15 20:10 UTC
### Description
Trying to use a merge template from the Connections page throws an exception. Seen on both a church's install and reproduced on the demo site.

### Steps to Reproduce
1. The Connections page
1. The Merge Template button at the bottom of the Connection Requests grid
1. Get exception

![2019-05-15!UNITO-UNDERSCORE!15h05!UNITO-UNDERSCORE!41](https://user-images.githubusercontent.com/12735965/57805804-55e2d300-7723-11e9-8b32-4cdd798e969d.png)

**Expected behavior:**

Get taken to the page to choose the merge template

**Actual behavior:**

The above exception

### Versions
* **Rock Version:** [8.6 and 8.7]
* **Client Culture Setting:** [en-US]

**Comment by azturner** [comment] 2019-07-14 13:31
FYI, This can still be reproduced on demo site (when updated to v9). Steps...
1. Update Main Campus to have a leader.
2. Update the connection request for Helen Evans (under Children's) to have a Campus of 'Main Campus'.
3. Try to create a Merge Document using Merge Records icon at top/bottom of request list.

**Comment by azturner** [comment] 2019-07-14 13:44
Also, this is duplicate of https://github.com/SparkDevNetwork/Rock/issues/3195

**Comment by nairdo** [comment] 2019-07-19 15:43
We'll close this one and track the progress over at #3195

**Closed by nairdo** 2019-07-19 15:43 UTC
Labels: Type: Duplicate
