### ISSUE TITLE
Rock Cleanup Job not running again after Exception

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#880] opened 2015-03-06 17:56 UTC
I just realized that the Rock Cleanup job hasn't run in a long time. At one point it hit a System.OutOfMemoryException and it hasn't run since. (See attached pic)  I even created a brand new job of type Rock.Jobs.RockCleanup and it's not running either (I've tried lots of different cron expressions).  I don't see any errors in the Exception log related it it not running.  Any ideas?  Thanks!

![2015-03-06 12_52_16-jobs administration _ rock rms](https://cloud.githubusercontent.com/assets/1859094/6530590/132bf2a6-c400-11e4-91c7-a4569be05aa7.png)

**Comment by mikepetersonccv** [comment] 2015-03-06 18:52
I'm pretty sure this bug was caused by the same problems that was making slow, which was fixed in https://github.com/SparkDevNetwork/Rock/commit/3dc084a195f7d561e7077237c7dc47e0fc14146f.  So, this should be fixed in v3.0

**Comment by bwitting** [comment] 2015-03-06 19:06
Thanks Mike!

**Closed** 2015-04-30 12:29 UTC
Labels: Fixed in v3.0
