### ISSUE TITLE
Group Attendance Reminder Link Does Not Redirect Properly After Authentication

### ISSUE THREAD

**Issue by dataCollegechurch** [SparkDevNetwork/Rock#5615] opened 2023-09-28 16:18 UTC
### Description

The Group Attendance Reminder Email uses this lava to generate a link for leaders to quickly review and enter attendance.

`{% capture attendanceLink %}{{ 'Global' | Attribute:'PublicApplicationRoot' }}page/368?{{ Person.ImpersonationParameter }}&GroupId={{ Group.Id }}&Occurrence={{ Occurrence | Date:'yyyy-MM-ddTHH:mm:ss' | EscapeDataString }}{% endcapture %}`

Users with elevate privileges may have the Impersonation blocked and the sytem will end up generating a link that look something like this.

`http://www.rocksolidchurchdemo.com/page/368?rckipid=TokenProhibited&GroupId=117&Occurrence=2023-09-28T09%3A00%3A00`

After the user navigates to this link they will be redirected to the login page and the url will look like this: `https://www.rocksolidchurchdemo.com/page/207?returnurl=%252fpage%252f368%253fGroupId%253d117%2526Occurrence%253d2023-09-28T09%25253a00%25253a00`

After the user logs in they will not be redirected back to `http://www.rocksolidchurchdemo.com/page/368?rckipid=TokenProhibited&GroupId=117&Occurrence=2023-09-28T09%3A00%3A00` as desired. Instead they are redirected back to `https://www.rocksolidchurchdemo.com/`

### Actual Behavior

User are redirected to homepage instead of page specified in redirecturl

### Expected Behavior

User is always redirected to redirecturl's parameter value after logging if Redirect Page block setting is not set

### Steps to Reproduce

1) Find or Setup a Small Group whose leader cannot be impersonated.
2) Generate a Small Group Reminder Email that uses the Core Group Attendance Reminder Email Template
3) Click on the Enter Attendance Button after receiving the email
4) Login
5) See Issue

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

15.1

### Client Culture Setting

en-US

**Comment by dataCollegechurch** [comment] 2023-09-28 16:19
A couple addtional notes:

- This issue appears to be present in both the Legacy Login Block and the Obsidian Login Block.
- Using the OccurrenceId in the url instead of the Occurrence appears to be temporary workaround for resolving this issue

**Comment by rutledgek** [comment] 2023-09-28 17:00
Yup, if in your email, you remove the escape data string from the date you should get redirected fine.  The problem is that the data string is escaped here and then escaped again in the redirect to login steps. So when you try to login, the redirect url is unescaped once but again.

To fix the impersonation I also did this:

`{% capture today %}{{ 'Now' | Date:'yyyyMMdd' }}{% endcapture %}
{% capture occurrenceDate %}{{ Occurrence | Date:'yyyyMMdd' }}{% endcapture %}
{% assign personToken = Person.ImpersonationParameter %}
{% capture link %}page/757?GroupId={{ Group.Id }}&Occurrence={{ Occurrence | Date:'yyyy-MM-dd' }}{% endcapture %}
{% capture attendanceLink %}
{% if personToken contains 'TokenProhibited' %}
    {{ 'Global' | Attribute:'PublicApplicationRoot' }}{{ link }}
{% else %}
    {{ 'Global' | Attribute:'PublicApplicationRoot' }}{{ link}}&{{ Person.ImpersonationParameter }}
{% endif %}
{% endcapture %}`

Then use `{{ attendanceLink }}` in the email on the links.

I agree that the token creator should fail more graceully when the person cannot be impersonated, but there is a workaround.

**Comment by dataCollegechurch** [comment] 2023-09-28 18:21
Is there any reason an occurrence needs to have the time included?

**Comment by dataCollegechurch** [comment] 2023-09-28 18:24
my typical fix for the TokenProhibited issue looks like this: 
`{% assign attendanceLink = attendanceLink | RegExReplace:'rckipid=TokenProhibited&','','i' %}`

**Comment by shauncummings** [comment] 2023-11-28 18:52
@dataCollegechurch and @rutledgek Thank you both for your work on this issue.  There were two somewhat unrelated problems happening here:

1. The "TokenProhibited" value was causing a null reference error because the code attempted to decrypt this value as if it were a token.  That was corrected in https://github.com/SparkDevNetwork/Rock/commit/23e498160068af28b57b83c438e3772010d5f85b.
2. Additionally, certain (slightly overzealous) security precautions were preventing your attendance reminder links from working if you accessed them without already being logged in from your current device/browser.  The actual problem was not the URL escaping, but the fact that the default URL template included the time portion of the date, which is why @rutledgek's modified version works (because it omits the time).  This was resolved in https://github.com/SparkDevNetwork/Rock/commit/d090d7a261e4ca3a2f46ba3f8259bd67f2668abe.

These updates will be in the v16.1 release of Rock.

**Closed by shauncummings** 2023-11-28 18:52 UTC
Labels: Type: Bug, Status: Confirmed, Status: In Dev Queue
