### ISSUE TITLE
[Alpha 1.16.7.2]-NextGen Checkin-Kiosk Setup page accessible without being logged in

### ISSUE THREAD

**Issue by kimlongcr** [SparkDevNetwork/Rock#6081] opened 2024-11-14 23:50 UTC
### Description

The kiosk setup page is allowing you to go to it and interact with the page even if you aren't logged in even though the block settings say you "when allowed" for the Display When option. And, the error message that displays was not super intuitive on what I should do. I don't think updating the block settings (suggested in the error message) would solve this for me (may be wrong..). And, it isn't super clear that the login option is a hyperlink.

### Actual Behavior

The kiosk setup page is allowing you to go to it and interact with the page even if you aren't logged in. While you can't save a new configuration or open the kiosk for checkin until you login, upon login, it takes you directly to the kiosk mode, not setup which is where you were. 
![Screenshot 2024-11-14 at 6 45 08 PM](https://github.com/user-attachments/assets/a8fe56f8-31c7-4703-bc21-bfa75166d68b)

### Expected Behavior

When I try to go to the setup page and I'm not logged in, it redirects me to a login page.

### Steps to Reproduce

1. Open an incognito window
2. go to the kiosk setup page
3. select a campus and a kiosk 
4. Click on custom configuration
5. Enter all the data to create a new one
6. Click on Save - takes you to the error message
7. click on Login
8. Login ---> takes you to the kiosk page to start checkin. No idea if the configuration was saved or not, what configuration I am on, etc. 

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.7 (1.16.7.2)

### Client Culture Setting

en-US

**Comment by mikedotmundy** [comment] 2024-11-14 23:54
Similar to #6064

**Comment by kimlongcr** [comment] 2024-11-15 12:30
Additionally on this one, because they aren't redirected to a login page, sometimes when you go to the checkin/setup page and click on a configuration, you receive the error below. This error will continue no matter what configuration you click on. You have to manually refresh the screen and then it will work. This is intermittent and hard to recreate but it happened first thing for me this morning - in an incognito window, went to /nextgen-checkin/setup and clicked on a configuration. 
![Screenshot 2024-11-15 at 7 25 40 AM](https://github.com/user-attachments/assets/1c03c5d0-dcee-4955-8ebe-6739d03072d1)

**Comment by cabal95** [comment] 2024-11-19 15:06
Closing as duplicate of #6064, updates will be made on that issue.

**Closed by cabal95** 2024-11-19 15:06 UTC
