### ISSUE TITLE
Paste from Word into New Communication Inverts Paragraph

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#1990] opened 2017-01-26 22:02 UTC
### Prerequisites

* [ ] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

One of our staff members noticed when she copied text from a Word document and used the Paste From Word button in the New Communication, it would invert the paragraphs. So the last paragraph would be 1st and the 1st would be last. This has happened to her at least twice since we update to v6--the majority of the time it works fine for her. I played with it a little bit and was unable to figure out how to reproduce it. I will continue to play with it to see if I can. I will leave a new comment if I figure it out but figured I would post it in case someone else has noticed the same thing or knows how to reproduce it.

### Steps to Reproduce

**Expected behavior:** 

Paste as normal.

**Actual behavior:** 

Pastes with paragraphs inverted.

### Versions

* **Rock Version:** v6.1

**Comment by cabal95** [comment] 2017-02-02 21:57
This may or may not be related, but I noticed this week while moving over tons of static content pages to Rock from our old ChMS that, when using the Code editor, it would randomly move my cursor to the beginning of the text entry field when I pressed return.

Example, I begin with 3 paragraphs: A, B and C. I finish typing in paragraph C and hit return to begin a new paragraph. A new, empty, paragraph (D) is created as one would expect, but my cursor suddenly moves to the beginning of paragraph A.

This did not always happen and I could not figure out what the cause was, but it did happen about 80% of the time.

It is possible a similar thing is happening on paste. After the 1st paragraph is pasted and "return" is encountered the cursor moves to the beginning, paragraph 2 is pasted and "return" is encountered again it moves the cursor back to the beginning, causing an inverting of the pasted paragraph order.

**Comment by arranf** [comment] 2017-09-09 09:03
@MikeDPeterson I saw some changes in develop around pasting in Summernote. Do you suspect this is fixed by that?

**Comment by MikeDPeterson** [comment] 2017-09-11 16:14
@arranf Yep, it probably is fixed, but it was hard to reproduce so I can't say 100%.  The PasteFromWord was re-written quite a bit, so if it is still happening, I would be surprised.

**Comment by arranf** [comment] 2017-09-11 16:15
@MikeDPeterson I'll close this up, we can reopen if need be or start a new issue.

**Closed by arranf** 2017-09-11 16:15 UTC
Labels: Not Yet Reproduced, Topic: Communications, Type: Bug

**Comment by joshuahenninger** [comment] 2024-08-02 19:08
We have confirmed that this issue is resolved in the Obsidian HTML Editor control in the Next Generation framework.
