### ISSUE TITLE
Registrations not accepting payments over $2 when total cost is >$999

### ISSUE THREAD

**Issue by atodd66** [SparkDevNetwork/Rock#5998] opened 2024-09-04 18:29 UTC
### Description

When attempting to pay for an event registration, an error message shows up that says "Please correct the following: Amount To Pay Today must not be more than $2". This only shows up if the total cost of the event is greater than $999.

### Actual Behavior

If an event registration's total cost is $1,000 ore more, you will see a message when attempting to go to the final payment step that says "Please correct the following: Amount To Pay Today must not be more than $2". It will not let you continue unless you adjust your payment accordingly.

### Expected Behavior

Expected behavior would be that there is no error message and Rock lets you proceed with ANY payment amount. 

### Steps to Reproduce

This has been reproduced and is currently active on the demo site. It is on the calendar under the "Summer Camp" test event.

If you choose to not use an existing test event, follow steps 1-5

1. Create a new event template.
2. Set payment gateway to test.
3. Set cost on instance.
4. Create basic form and hit Save.
5. Create a new instance.
6. Set cost to $1,000 or greater. My current test on the demo site is set to $2,000.
7. Set default payment amount and hit Save. Current test is set to $200.
8. Go to Calendars and create a new calendar event.
9. Choose a name (Summer Camp).
10. Choose All Church audience and hit Save.
11. Create a new occurrence.
12. Choose a schedule to make it show on the public site.
13. Click Add Linkage.
14. Choose URL Slug (optional).
15. Click "Use Existing Registration Instance"
16. Choose the matching template and instance.
17. Set a public name and hit Save.
18. Click Save on the occurrence.
19. Go to the public site, then the calendar.
20. Register for the event (Summer Camp).
21. Once you get to the payment page and click "Next", it will show the error as mentioned above.
22. If you change the payment to $2 or less it will let you continue.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.6

### Client Culture Setting

en-US

**Comment by atodd66** [comment] 2024-09-04 18:48
I've just discovered that the minimum accepted amount is based on the first digit of the total cost. Ex: $1,000 = $1, $2,000 = $2, $3,000 = $3, etc. This has also been reproduced on the demo site.

**Comment by jsw-austin** [comment] 2024-09-04 19:42
might be same issue as https://github.com/SparkDevNetwork/Rock/issues/5997

**Comment by chead4** [comment] 2024-09-04 21:41
@atodd66 I will be closing this as it is a duplicate of #5997.

**Closed by chead4** 2024-09-04 21:41 UTC

**Comment by atodd66** [comment] 2024-09-05 13:04
Sounds good. Apologies for the duplicate.

From: Colleen Head ***@***.***>
Date: Wednesday, September 4, 2024 at 5:41 PM
To: SparkDevNetwork/Rock ***@***.***>
Cc: Andrew Todd ***@***.***>, Mention ***@***.***>
Subject: Re: [SparkDevNetwork/Rock] Registrations not accepting payments over $2 when total cost is >$999 (Issue #5998)

@atodd66<https://github.com/atodd66> I will be closing this as it is a duplicate of #5997<https://github.com/SparkDevNetwork/Rock/issues/5997>.
