### ISSUE TITLE
Required Multi-Select Field in Event Registration Sets Error Class

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2138] opened 2017-04-07 21:21 UTC
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When creating a required multi-select field on an event registration without a default value the form loads with a has-error class added to the multi-select field.

**Example:**
![screenshot 2017-04-07 14 15 14](https://cloud.githubusercontent.com/assets/374209/24820199/b5830d96-1b9c-11e7-88ca-dd49a34eee65.png)

### Steps to Reproduce

1. Create a multi-select field on an event template with no default value.
![screenshot 2017-04-07 14 20 48](https://cloud.githubusercontent.com/assets/374209/24820352/6ccb5058-1b9d-11e7-85b8-49ef55c5f633.png)

**Expected behavior:** 

Render the field with the required class, but not the has-error class

**Actual behavior:** 

Renders with has-error, turning the entire form input red.

### Versions

* **Rock Version:** 6.2
* **Client Culture Setting** en-US

**Comment by cabal95** [comment] 2017-04-07 21:35
Confirmed against local git installed version of Rock.

**Comment by garrettjohnson** [comment] 2017-04-07 22:26
For the fix, should the existing javascript validation be tossed in favor of server side validation? See https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Web/UI/Controls/RockCheckBoxList.cs#L262

**Comment by cabal95** [comment] 2017-04-07 22:29
It seems to be something specific to the registration page. I attempted the same test on a Workflow with an attribute configured the same way and passed to a User Entry Form. The `has-error` did not appear. So I am guessing something on that page is trying to validate too early (i.e. before postback).

Strangely enough, the UEF also did **not** require me to make a selection before continuing, but that is a bug report for another day.

**Comment by azturner** [comment] 2017-04-28 12:22
This pull-request might fix this: https://github.com/SparkDevNetwork/Rock/pull/2161

**Comment by arranf** [comment] 2017-09-09 11:37
@garrettjohnson Can you test to see if this is fixed on the [prealpha site](http://prealpha.rockrms.com/)?

**Comment by arranf** [comment] 2018-06-18 16:23
This has been fixed at some point in the past.

**Closed by arranf** 2018-06-18 16:23 UTC
Labels: Priority: High, Status: Available, Status: Confirmed, Type: Bug
