### ISSUE TITLE
SMS Conversation Block Fails to Load Conversations

### ISSUE THREAD

**Issue by Luke-Potter** [SparkDevNetwork/Rock#4919] opened 2022-02-08 20:05 UTC
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)? [Can't Test Due To No SMS Numbers Integrated, But Confirmed Community Issue]
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The issue: The SMS block will not load any conversations. The block will crash every time & the only thing that fixes the issue, occasionally, is to set Azure DTUs to a crazy high level. Our environment is typically happy running around 100 DTU, but to get the block to load it requires 200 or 300 DTU or more, even then it's only loading 50-70% of the time.

In talking with partners it appears there's an issue with some of the queries in the block that are timing out due to optimization issues.

### Steps to Reproduce

1. Add a SMS Conversations block to a clean page.
2. Set in block settings or choose a number to interact with the conversations
3. Failure.

**Expected behavior:** 

I would expect the block to load cleanly & show a conversation history.

**Actual behavior:** 

4 different errors with their Stack Traces appear instead of the block. (Stack Traces In Attached Image Files)

### Versions

* **Rock Version:**  12.6 (1.12.6.1)
* **Client Culture Setting:**  en-US

<img width="1670" alt="stack-2" src="https://user-images.githubusercontent.com/31108929/153066161-8aa42deb-936a-4103-952c-50e160653a05.png">
<img width="1682" alt="stack-1" src="https://user-images.githubusercontent.com/31108929/153066165-7fcc56c2-580f-474a-9136-60ee11be4eb8.png">
<img width="344" alt="stack-4" src="https://user-images.githubusercontent.com/31108929/153066168-08f0040f-e9bf-44be-9c21-9fee62b37cf2.png">
<img width="1655" alt="stack-3" src="https://user-images.githubusercontent.com/31108929/153066169-a344aa17-82cc-48fd-a146-9291449ca758.png">

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1201966551309474">exception_repro.gif</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1201966551309476">security_repro.gif</a>

**Comment by cwomack** [comment] 2022-02-14 17:54
@Luke-Potter what is your "Max Conversations" set to within the "**SMS Conversations**" block?

**Comment by Luke-Potter** [comment] 2022-02-15 17:35
@cwomack I've had it set from 1 - 1000, currently it's at 10. The conversation count doesn't change the ability for the block to load, that was one of our first steps for troubleshooting.

**Comment by notGerryMiller** [comment] 2022-03-07 18:57
@Luke-Potter we had something similar last week. I rebuilt a bunch of the indexes on the communication tables and we got it to load.

**Comment by crayzd92** [comment] 2022-03-14 23:05
@Luke-Potter flagging this as Not Yet Reproduced. Have you seen this again since the initial report?

**Comment by Luke-Potter** [comment] 2022-03-14 23:08
It's every day. In order to use the blocks we have to up our DTUs then drop them once we're done checking the SMS blocks. 

I know Pillars said they had a couple of clients that had the same issue when we reached out to them for assistance.

**Comment by crayzd92** [comment] 2022-03-14 23:37
@Luke-Potter, thanks, we will keep digging.

**Comment by notGerryMiller** [comment] 2022-03-15 00:30
@crayzd92 This happened to us again today.  I rebuilt indexes and it fixed it.  I can pull what ever data you want next time it happens. Happens almost daily.

**Comment by MikeDPeterson** [comment] 2022-03-17 00:46
Fixed in 13.3. Main fix was to improve how the query was joining with PersonAlias. With that issue fixed, it should speed it up significantly. Also added a block setting option to increase the database timeout, just in case.

**Closed** 2022-03-17 00:47 UTC
Labels: Not Yet Reproduced, Topic: Communications, Fixed in v13.3
