### ISSUE TITLE
Calendar exports don't work in Google Calendar at all

### ISSUE THREAD

**Issue by jacksojourn** [SparkDevNetwork/Rock#6095] opened 2024-11-19 15:40 UTC
### Description

When exporting an ICS file from the Rock and subscribing to it in Google Calendar, no events are shown.

Screenshot is from demo site:

![Screenshot 2024-11-19 at 10 35 55 AM](https://github.com/user-attachments/assets/158c12b0-10e5-4c99-87bb-3b77a54fc0fb)

### Actual Behavior

When exporting an ICS file from the Rock and subscribing to it in Google Calendar, no events are shown.

### Expected Behavior

ICS export should show events in Google Calendar

### Steps to Reproduce

- Create any calendar events on demo site
- Copy calendar link
- In Google Calendar, subscribe via URL

Result: no events shown

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.4

### Client Culture Setting

en-US

**Comment by jasonhendee** [comment] 2024-11-26 17:07
@jacksojourn, thanks for writing this up.

Unfortunately, I'm unable to reproduce, using the Rock demo site as the feed.

![image](https://github.com/user-attachments/assets/221c6897-d5b0-412f-80e2-83573a72a13c)
![image](https://github.com/user-attachments/assets/06ff8be3-d301-46cb-92ef-d12fa762c82e)

One thing I **have** seen when performing past iCalendar development work and testing with Google Calendar, is that they seem to very-heavily cache the results of a given calendar feed. Even if you go so far as to unsubscribe from a calendar and re-subscribe to that same URL, Google will use it's previously-cached results for an arbitrary time period; there doesn't appear to be any way to define this time period within the settings of a given calendar. Is it possible this is what you're seeing?

Here's a thread on a Google site where someone described this issue a few years ago: https://support.google.com/calendar/thread/41447964/why-does-google-calendar-cache-the-calendar-and-how-do-i-stop-it?hl=en

**Comment by jasonhendee** [comment] 2024-11-26 17:18
To be a bit more thorough, I also tested by using our Pre-Alpha site as the feed, which is running the latest version of Rock (since the demo site is currently running v16.2). You can see that this feed is also working correctly, but it's even slightly improved, as we've added some recent fixes that better-represent "all day" events. Note also that the Pre-Alpha site us using a different server time zone than the demo site, hence the differing start times for the events.

![image](https://github.com/user-attachments/assets/6038f052-708f-4b5c-8d38-5d4e1384b39a)

**Comment by jasonhendee** [comment] 2024-12-06 19:02
Thanks for your reply, @jackbrannen. We've internally discussed some ideas to try and prevent Google from caching so aggressively, but without investing some significant time here, we're not coming up with a great approach. You're welcome to add this to the [Rock Community Ideas board](https://community.rockrms.com/ideas) to see if the community up-votes it as something we should spend more time on. But since it's not an issue on Rock's end, we're going to go ahead and close this issue.

BTW, you probably already know this, but for others who might stumble into the issue: The `#2` URL fragment approach you're using the "bust the cache" is a clever, on demand workaround. But the problems is now that Google has saved your calendar URL with the `#2` fragment, so the only way to get it to refresh when you want it to is to drop and re-add with another arbitrary value.

**Closed by jasonhendee** 2024-12-06 19:02 UTC
Labels: Type: Bug, Status: Confirmed
