### ISSUE TITLE
AttributeValue not parsing the international date format

### ISSUE THREAD

**Issue by marcierempel** [SparkDevNetwork/Rock#3449] opened 2018-11-28 21:38 UTC
When an international user enters a date, that date is stored in the database as DD/MM/YYYY, but the AttributeValue block doesn't display the value.  This seems to be an issue with AttributeValue not parsing the international date format.
![<a href="https://user-images.githubusercontent.com/44587882/49184029-8bcdff80-f31b-11e8-8fc8-e493df2f1465.png">https://user-images.githubusercontent.com/44587882/49184029-8bcdff80-f31b-11e8-8fc8-e493df2f1465.png</a> 2018-11-28!UNITO-UNDERSCORE!14h51!UNITO-UNDERSCORE!35]()

**Comment by EthanW96** [comment] 2019-10-24 15:24
@marcierempel Can you confirm this server was running on an international date format (culture setting in System Information dialog)? The dates in your screenshot appear to be en-US. The documentation about international times and dates is here: https://community.rockrms.com/Rock/BookContent/9#datestimes

**Comment by marcierempel** [comment] 2019-10-24 22:18
It looks like it’s en-US. I have the Global Attribute for Support International Addresses set to Yes. What else to I need to change to correct it?

[cid:image003.jpg@01D58A86.DF2AC2F0]

[Signature]

**Comment by nairdo** [comment] 2019-10-25 15:52
@marcierempel Can you help us pin point to which block/entity (or area in Rock) that data belongs?  

Running this might give us a better clue:
```Sql
SELECT * FROM [Attribute] WHERE [Id] = 6174
```

Because, [as mentioned in our development guide](https://community.rockrms.com/documentation/BookContent/16#datetimeformatting), date data stored in the Attribute (AttributeValue) table needs to be stored in ISO 8601 to deal with this exact situation.

**Comment by marcierempel** [comment] 2019-10-30 15:44
When I run that it says Entity Type 15 in the grid. It looks like it is a person attribute.
![Capture](https://user-images.githubusercontent.com/44587882/67873935-dcd10f80-faf9-11e9-86b0-0c8fd0b8ab47.PNG)

**Comment by nairdo** [comment] 2019-10-31 15:57
Thank you.   Does that AP102-1ScreeningProcess attribute (created on 4/12/2018) give you any clue as to where that is in your Rock instance and what might be populating the values for that attribute on your system?  (I'm trying to pin point if that's a custom plugin that is handling the data or if it's a standard block/component in Rock that is storing data incorrectly.)

**Comment by nairdo** [comment] 2019-11-08 04:40
@marcierempel  What  @EthanW96 said was correct, so when you said:

> It looks like it’s en-US. ... What else to I need to change to correct it?

Rock will use the person's _browser's_ culture setting to determine what format the given date value is in.  In your case, it will use the US English date formatting when Rock is displaying dates to you for viewing or editing.  Here's an example of me using Firefox with the [en-GB culture setting (described here)](https://support.mozilla.org/en-US/questions/987697).

![image](https://user-images.githubusercontent.com/383807/68449565-df400300-01a4-11ea-9dbe-24e3239ea2c1.png)

...and the same record when viewed in another browser set using the en-US culture setting:

![image](https://user-images.githubusercontent.com/383807/68449721-8cb31680-01a5-11ea-99e3-119c2b2cb9fb.png)


But the data will always still be stored in the ISO 8601 format.  Culture en-GB:
![image](https://user-images.githubusercontent.com/383807/68449834-f3383480-01a5-11ea-9c73-0e1321906c4c.png)

Culture en-US:
![image](https://user-images.githubusercontent.com/383807/68449923-57f38f00-01a6-11ea-996d-7bffb790bffd.png)


However when you said this:
> we configured a learning management system... The attribute date is updated when a person watches a training video (updates on the date they watch when they click an acknowledgment button - through a custom content channel block).

This makes me think this is the likely suspect element in play here.  Can you add some details about this system that provides the "acknowledgement button" and the underlying code behind it that is writing the date to the person's attribute value?  You might want to engage a 3rd party partner to help you dig into this further if needed.

**Comment by marcierempel** [comment] 2019-11-08 14:33
Thank you so much for taking the time to describe this and look in to it. The custom code for that content channel using the personal attribute date updates was written by a 3rd party, they are the ones who suggested I post this issue to GitHub. I’ll take your response back to them.

Marcie

**Comment by nairdo** [comment] 2022-05-06 00:01
Since that original discussion, a few others have re-attempted to reproduce this but all have been unsuccessful. Because of that, and because we suspect it is coming from the 3rd party plugin (not saving [date data in ISO 8601 format](https://community.rockrms.com/documentation/BookContent/16#datetimeformatting)), we believe it would be best to close this issue for now.

**Closed by nairdo** 2022-05-06 00:01 UTC
Labels: Not Yet Reproduced, Type: Discussion, x-bugapalooza: Is Needed?
