### ISSUE TITLE
Block Configuration Menus can overlap & go off right side of page

### ISSUE THREAD

**Issue by stanalyst** [SparkDevNetwork/Rock#5145] opened 2022-08-25 20:51 UTC
### Description

When trying to access the Block Configuration menus there are certain scenarios when it is not possible to get to the full menu of items - either because the menus for 2 different blocks are too close together and they overlap - or because the zone/block is too close to the right side of the page and they are cut off.  
![image](https://user-images.githubusercontent.com/112125627/186766272-dfdd921a-9ece-4796-b523-6008fb9387d2.png)
![image](https://user-images.githubusercontent.com/112125627/186766361-81d54416-393a-41e6-8d0b-bb7714a3d08d.png)

### Steps to Reproduce

Noticed this on the new person profile layout specifically
Example of overlap: 
the Profile Navigation Left & Profile Navigation zones are close together (at least in our theme) - and in both the Block Confirmation and Page Zone modes - these menus overlap each other.
Example of the cutoff: both the Login & Profile Navigation Right zones are close to the right edge of the page - and these same 2 menus go off the right side of the page.

**Expected behavior:**

Would have expected the overlapping menus to either shift to allow access to both menus ... or have which ever menu is currently opened move higher in order on the page to you can always get to the active one.
For the right side problem would have expected the menus to shift in the page vs off side of the page.

**Actual behavior:**

see above

### Versions

**Rock Version:** 1.14.0.17

**Comment by nairdo** [comment] 2022-08-26 21:53
I was able to reproduce this on v13.4 too, so I've adjusted the title.

**Comment by abpena1979** [comment] 2022-08-31 14:53
HI @stanalyst.  

Thank you so much for your feedback.  Your finding has been an issue since v1.0 that we hope to address with our NextGen CMS version.  In the meantime, there is a workaround for editing this zone by using the internal page editor.  Documentation on page editing can be found here: https://community.rockrms.com/Rock/BookContent/14.  For now, I'm going to go ahead and close this issue.  

Once again, than you so much for your partnership and your feedback.  We greatly appreciate you.

**Closed by abpena1979** 2022-08-31 14:53 UTC
Labels: Status: Confirmed, Topic: UI, Priority: Low
