### ISSUE TITLE
Protect my Ministry updated report

### ISSUE THREAD

**Issue by kcirgjd** [SparkDevNetwork/Rock#1400] opened 2016-02-17 16:33 UTC
I submitted a background check for someone and initially the report returned as "needs review" because he had not completed his PA background check. Before doing anything I had him complete the required steps on his side and waited for those results to come back. I then in my tasks saw his review showing up twice. I approved updated report and assumed all to be well. I then went to his profile in Rock and it was the original report without the child abuse clearance. 

The workflow still has the updated files but does not override the original file that was returned. Currently this bug is nothing more than a nuisance but I am wondering if it will become an issue in 3 years when we are mandated to re-run all of our reports. Will the workflow override the checks then? I don't have a way to test or confirm anything with that.

**Comment by garrettjohnson** [comment] 2017-07-09 00:40
@kcirgjd Is this a duplicate of #1143?

**Comment by kcirgjd** [comment] 2017-07-11 11:47
@garrettjohnson it looks to be.

**Closed** 2017-07-13 00:18 UTC
