### ISSUE TITLE
Can only reference an Existing Data View from the same category?

### ISSUE THREAD

**Issue by FrankGrand** [SparkDevNetwork/Rock#938] opened 2015-04-12 11:47 UTC
Is this is a bug or feature?  When trying to use the filter of existing data view when creating another data view, I can only choose from the views within that same category.  For example, I have a category of giving data views and a category of people data views.  I'm trying to reference a people data view (attendees of x campus) and look at their giving, but since my attendee data views are in another category, I can't reference them.

**Comment by arranf** [comment] 2015-04-12 16:19
Frank what version are you on.

I'm on the 3.0 BETA and I'm seeing different behaviour to you.

**Comment by FrankGrand** [comment] 2015-04-12 19:26
@arranf I may have the 3.1 changes as well.  So you can choose any data view you created?

**Comment by arranf** [comment] 2015-04-12 20:22
Yes.

**Comment by FrankGrand** [comment] 2015-04-13 13:17
Ok, not sure what is going on, but here is a screenshot confirming that I can't pick all my data views:
![screenshot 2015-04-13 at 9 17 25 am](https://cloud.githubusercontent.com/assets/6911214/7116234/f9365c02-e1bd-11e4-826c-f34dba511efb.png)

**Comment by azturner** [comment] 2015-04-13 14:24
This is actually by design. All dataview filters are tied to a specific 'Entity' types. This is because they rely on being given a set of something they know about in order to filter that set. For example a 'Gender' filter would rely on being given a set of people (who actually have a gender). If it were given a set of financial transactions for example, it would have no idea what to do with that. 

However, this doesn't mean that a 'Person' filter can't filter a set of people based on giving data, it just needs to be programmed to query the financial data associated with each person in a set, and exclude people from the set based on some associated financial data ( this is what the 'First contribution date', and 'Giving Amount' filters do on when filtering a set of 'People'.

So, if you wanted a list of transactions tied to people who attend a specific campus, we ( or you ) would have to add a new FinancialTransaction filter that filtered transactions based on evaluating the person the transaction was associated with, and excluding those that didn't belong to a family associated with a selected campus.

Hopefully that all makes sense.

**Comment by edmistj** [comment] 2015-08-24 19:39
Closing as this is the intended behavior. Please re-open or post if I'm missing something.

**Closed by edmistj** 2015-08-24 19:39 UTC
