### ISSUE TITLE
Workflow Triggers Not Saving On Initial Connection Opportunity Creation

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#2390] opened 2017-08-08 07:50 UTC
### Prerequisites ###

* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description ###

I haven't dug fully into this but I can reproduce it. When adding two Connection Workflows to an Opportunity using the Connection Opportunity Detail for a new Opportunity only the second appears to be saved in the UI (when you hit save and then attempt to edit again). If you re-add the first then it becomes impossible for the first workflow (the one added twice) to fire (at least if it's an On Request Connected).

Could be related to #2029. 

[Description of the bug or feature. Include screenshots if applicable.]

### Steps to Reproduce ###

1. Create a new Connection Opportunity 
1. Add 'Request Connected' trigger
1. Add a manual workflow trigger
1. Press Save
1. Revisit the the opportunity, readd the missing workflow.
1. Create a Connection Request and connect it

**Expected behavior:**

The workflow for the Request Connected should fire

**Actual behavior:**

It never does and won't ever unless you make changes to the [ConnectionWorkflow] table.

### Versions ###

* **Rock Version:** 6.7
* **Client Culture Setting:** en-GB

**Comment by arranf** [comment] 2017-09-09 09:42
Duplicate of #2029

**Comment by jonedmiston** [comment] 2023-09-12 18:23
Closing as this is a duplicate of #2029 and that has been labeled as fixed since.

**Closed by jonedmiston** 2023-09-12 18:23 UTC
Labels: Type: Bug, Status: Confirmed, Priority: Low, Topic: Workflows
