### ISSUE TITLE
One-Click Unsubscribe does not change a person's preferences (email sent without communication list) (v16.3 beta)

### ISSUE THREAD

**Issue by kenmulford** [SparkDevNetwork/Rock#5769] opened 2024-02-27 16:58 UTC
### Description

When I send an email with one-click subscription configured and click the unsubscribe link, no action seems to take place. This is specifically when the email is sent from a selection rather than a communication list. In other words, the URL has a `CommunicationIdKey` but not a `CommunicationListIdKey`.

We tested this via email link and via the API tester using the encrypted URI parameter as well as the `CommunicationIdKey` value.

### Actual Behavior

No visible result is observed.

### Expected Behavior

Since an email was sent directly and not by way of a communication list, I expect the person's global preferences to be updated to "No Mass Emails Allowed".

### Steps to Reproduce

- Configure one-click unsubscribe.
- Send an email to a person whose inbox you can access. Do not send from a communication list - just from a report, a group, or some other list of people in Rock.
- Click the one-click unsubscribe link at the top of the email (not the bulk email unsubscribe link that's always been present).
- Go to the person's record in Rock and observe that they are still permitted to receive all email communications.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.3 (beta)

### Client Culture Setting

en_US

**Comment by joshuahenninger** [comment] 2024-02-28 17:33
Hello @kenmulford. To assist our investigation into this issue, can you please provide the following information:
* The email client used to reproduce this issue.
* The response code from the API tester.
  * The response code should be 204. Additionally, only the `personActionIdentifier` should be provided; the `communicationListIdKey` parameter should be left empty in this case. There is no parameter for `communicationIdKey` in the API tester, and that is intentional as it is not used (although it can be provided in the List-Unsubscribe header).

**Comment by waynehelsby** [comment] 2024-02-28 18:21
Ken is out today (not a common thing). I've been working with him on this.

The Email clients have been Gmail Web and Apple Mail. The endpoint likely wasn't even being reached because of the ordering in the other issue that you fixed today.

Thanks for clarification on communicationIdKey.

Using just the personActionIdentifier I'm getting a 204, but not seeing a change in email preferences.

<img width="709" alt="Screenshot 2024-02-28 at 12 55 16 PM" src="https://github.com/SparkDevNetwork/Rock/assets/555697/ca2c1532-65d9-4d06-aeb5-2b004f9d9acc">

**Comment by waynehelsby** [comment] 2024-02-28 19:23
we were able to get this to succeed using the correct testing approach

from what i gather this endpoint and the one click unsubscribe url will be changing before release, maybe even in a second beta

**Comment by joshuahenninger** [comment] 2024-02-29 17:08
@kenmulford @waynehelsby, I'm closing this issue, but please feel free to reopen it if necessary.

**Closed by joshuahenninger** 2024-02-29 17:08 UTC
Labels: Status: In Dev Queue
