### ISSUE TITLE
Sent Emails No Longer Contain Reply-To when using Lava in Email Form block "From" field

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3126] opened 2018-07-11 21:22 UTC
### Description

As of v7, emails sent via an Email Form no longer contain the `Reply-to` field, which means it's impossible to reply to a message sent "from" a non-Safe-Sender-Domain address and have it go back to the sender.

### Steps to Reproduce

1. Send an email via the EmailForm block that delivers to an address at your Safe Sender Domain, and make the from address in the form an address NOT in your domain (e.g. @gmail.com) We use `{{  FormFields.Email }}` in the From address block setting to let you enter any address on the form)

2. Rock will substitute the From: address to be the organization email, which is correct...

3. ...but observe that when you receive it, if you reply to the message it goes BACK to your organization email instead of the sender.

4. This is because there is no longer a Reply-to: field in the sent message containing the "actual" sender of the email. 

**Expected behavior:**

Replying to a Rock-sent email where the org address was substituted would reply to the original sender.

**Actual behavior:**

It can't, because there is no reply-to address. I'm not sure where this broke but I assume in 7.0 due to the (non working) _Safe To Send To_ functionality that was added.  I tested on an old 6.9 VM and Reply-to is there (and works), but it is NOT there in a message sent via v7.4. Also tested v8alpha and reply-to is missing there, too.

I'm also not sure how/if this intersects with this issue https://github.com/SparkDevNetwork/Rock/issues/3124

### Versions

* **Rock Version:** 7.x- 8.0
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by mikejed** [comment] 2018-07-11 23:20
Confirmed on v7.4

Note this _only_ appears to apply to the Email Form block, and then _only_ when you use Lava in the "From" field to permit the sender to enter their own email address. Regular communications work fine, and hardcoded external address in the block settings "From" field (instead of the Lava Jim notes they use) also allows reply-to to function correctly.

**Comment by JimMichael** [comment] 2018-07-12 15:36
It looks like Lava support was removed from the FromEmail and other fields at some point. 

Old (6.9) block: 
```
string message = GetAttributeValue( "MessageBody" ).ResolveMergeFields( mergeFields, GetAttributeValue( "EnabledLavaCommands" ) );
                string fromEmail = GetAttributeValue( "FromEmail" ).ResolveMergeFields( mergeFields, GetAttributeValue( "EnabledLavaCommands" ) );
                string fromName = GetAttributeValue( "FromName" ).ResolveMergeFields( mergeFields, GetAttributeValue( "EnabledLavaCommands" ) );
                string subject = GetAttributeValue( "Subject" ).ResolveMergeFields( mergeFields, GetAttributeValue( "EnabledLavaCommands" ) );
```

7.4 block:
```
                message.CCEmails = GetAttributeValue( "CCEmail" ).ResolveMergeFields( mergeFields, GetAttributeValue( "EnabledLavaCommands" ) ).Split( ',' ).ToList();
                message.BCCEmails = GetAttributeValue( "BCCEmail" ).ResolveMergeFields( mergeFields, GetAttributeValue( "EnabledLavaCommands" ) ).Split( ',' ).ToList();
                message.Message = GetAttributeValue( "MessageBody" );
                message.FromEmail = GetAttributeValue( "FromEmail" );
                message.FromName = GetAttributeValue( "FromName" );
                message.Subject = GetAttributeValue( "Subject" );
```
To work around it for now, we added `.ResolveMergeFields( mergeFields, GetAttributeValue( "EnabledLavaCommands" ) )` to `FromEmail` and `FromName` fields and replies now work.

**Comment by mikejed** [comment] 2018-07-12 16:11
It looks like MessageBody and Subject used to support Lava as well, to whomever works this issue:
https://github.com/SparkDevNetwork/Rock/commit/3fa546142a79f29b8f5e3797f77ed3c46d3a62d6#diff-8a93f1a8681da0c2664ddab1abe4d750L321

**Comment by JimMichael** [comment] 2018-07-12 16:24
The crazy thing, though, is that the message body (even the default content on a new EmailForm block) _does_ contain lava... and it works! (Even without the ResolveMergeFields stuff). <insert twilight zone theme>

**Comment by JimMichael** [comment] 2018-07-12 16:46
And while someone is changing the block, they can fix this super-minor spelling error
![image](https://user-images.githubusercontent.com/3903408/42647307-3f10b508-85c9-11e8-8fc6-1f2d87900a53.png)

**Comment by ethan-sparkdevnetwork** [comment] 2018-10-01 22:03
Lava is resolved by the SMTP component, so everything including the message and subject is being resolved there. Or at least attempted to resolve, which bring us to the From fields.

The Email Form block was acting like each recipient would have its own from address and so passed it along with other data into the recipient data. The SMTP component handled the from info before iterating through the recipients and so would never see the merge field stored in the recipient info and didn't event attempt to do it at that point anyway.

Added back the functionality on the EmailForm block to resolve the From email address and From Email name on the block. Also put the long default values for the attributes into string constants to clean up the attribute fields and make them easier to read.

Spelling error was already addressed.

**Comment by ethan-sparkdevnetwork** [comment] 2018-10-01 22:10
That is a long winded way of saying that by the time the email was checking the safe sender it has already been set to the global default. So essentially nothing to add into the reply to list.

**Closed** 2018-10-02 15:39 UTC
Labels: Fixed in v8.5, Status: Confirmed, Topic: Communications, Type: Bug
