### ISSUE TITLE
workflow corrupted

### ISSUE THREAD

**Issue by carriewhite** [SparkDevNetwork/Rock#5354] opened 2023-03-23 04:59 UTC
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

We have a couple of workflows that can no longer be edited.  We can't edit/save, copy the workflows, or import them.  At first it was just one large workflow, but now we're experiencing it on two other workflows.  

### Expected Behavior

Ability to edit, copy and import a workflow.

### Actual Behavior

When editing one of these workflows, it opens, but does not allow the edit, delete or addition of an attribute, activity or action. 

When copy the workflow, it appears to be working but redisplays without creating a copy.

When importing a workflow, it errs. 
[Rock Demo Import.txt](https://github.com/SparkDevNetwork/Rock/files/11047095/Rock.Demo.Import.txt)

### Steps to Reproduce

1) Open workflow
Try to edit, add or delete an item
2) Copy workflow
or 3) Import (see attachment)

### Rock Version

14.1

### Client Culture Setting

en-US

**Comment by ethan-sparkdevnetwork** [comment] 2023-03-24 22:38
@carriewhite Hello Carrie. Can you provide a bit more info? Which workflows are affected, any errors in the exception log, and a screen shot of this issue? Thanks!

**Comment by carriewhite** [comment] 2023-03-25 01:03
@ethan-sparkdevnetwork 
Hi Ethan. I see nothing in the exception log when trying to edit/save or copy the workflow.  It just doesn't execute.

https://rock.cornerstoneaz.com/admin/general/workflows?workflowTypeId=552
If I start the process to add or delete an attribute, activity or action, it spins as though it's going to, but then redisplays the workflow as it was. I see this in the JavaScript console. 
<img width="730" alt="Screenshot 2023-03-24 at 4 38 18 PM" src="https://user-images.githubusercontent.com/70244373/227661961-9ae85e7b-db26-4614-bcba-e1fbfaa29fe8.png">

Same if I click save for workflow.

If I click the copy icon, it appears to have created a copy; however, I have the same results when trying to edit or save. 

I can export the workflow but get the attached error if I import (also on demo site).
[Rock Demo Import.txt](https://github.com/SparkDevNetwork/Rock/files/11067305/Rock.Demo.Import.txt)

also https://rock.cornerstoneaz.com/admin/general/workflows?workflowTypeId=446
and https://rock.cornerstoneaz.com/admin/general/workflows?workflowTypeId=622

**Comment by jonedmiston** [comment] 2023-10-04 19:00
Hi @carriewhite !  I took a quick look at your import file (thanks for including that, it was very helpful, as was the details you provided in your write-up). In looking through the file the issue appears to be with a custom field type `rocks.pillars.FieldTypes.BirthdayFieldType`. 

Is it possible that the workflows that are having issues might all use this or other custom field types? You might reach out to Pillars => 9 Embers to see if they could look at it for you.

I'm going to close this issue as it seems likely that the fieldtype is the cause. If you get more information that points in a different direction don't hesitate to re-open this one for us to look at.

**Closed by jonedmiston** 2023-10-04 19:00 UTC
Labels: Type: Bug, Not Yet Reproduced
