### ISSUE TITLE
Non-auto-persisted Workflows Are Still Wonky

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3454] opened 2018-12-02 20:19 UTC
### Description
Just bringing this up again because I saw it in my 8.5beta testing. This has been brought up before (I think it started as of v7.0) but I'm not sure it's ever been thoroughly investigated or entered as an issue. In any case, I was able to observe a non-persisted core workflow that contains a User Form and Email action fail (to send the email) until I configured the workflow to auto-persist.

### Steps to Reproduce
1. Click Actions menu on a person profile and send a DISC request
1. Assuming the default DISC workflow has NOT been modified, it will be configured to NOT automatically persist.
1. Observe that the email may or may not arrive. You often have to try more than once. It seems to be a crapshoot, but I was able to induce the delivery failure the first time I tried sending the DISC workflow while testing 8.5beta.

**Expected behavior:**

Workflow would work even if it's not configured to auto-persist.

**Actual behavior:**

There's a better than 50/50 chance it won't send. I think this is somehow related to https://github.com/SparkDevNetwork/Rock/issues/2834 but I'm not sure how much they overlap. Honestly, since non-persisted workflows have been so flaky since v7.0 we've converted all of ours to auto-persist, which is fine due to the way workflows can be auto-cleaned-up these days... we actually prefer to have everything persist and then clean them up after x days and gives a nice log trail.

So while this doesn't affect us directly anymore (because we can't trust non-auto-persisted workflows that send email), I'm bringing it up because the UI still allows it to be set and could cause failures for others... we don't use DISC currently (which is why it's still at default settings) but if we did, it would be failing without modifying it to auto-persist. 

I'm actually wondering if auto-persist should be removed completely as an option since it's become so problematic, and ALL workflows would persist and you'd just have to configure the cleanup options appropriately.

### Versions
* **Rock Version:** 7.0 - prealpha.

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=929426139953849">image.png</a>

**Comment by cabal95** [comment] 2018-12-03 01:58
This is just a thought - would it be easier to fix this problem once and for all if we changed how workflows persist?  Perhaps change the logic so that every workflow is automatically persisted but with an `IsTemporary` column set to true. Then the logic of "persisting" a workflow as we know it now changes to set `IsTemporary = false`. When a workflow completes, if `IsTemporary` is true then it is deleted.

I think the biggest change from an end-user perspective would be that a "non-persisted" workflow might stick around forever - but I think it would be fair to make the Rock Cleanup job go through and delete any `IsTemprorary == true` workflows if they are more than 24 hours old. That would solve the issue of hundreds of "bogus" workflows sitting around because the first action is a User Entry Form and the user just closed the window.

**Comment by JimMichael** [comment] 2018-12-03 02:19
I really like that idea.

**Comment by edmistj** [comment] 2018-12-03 04:33
One of the reasons it's not good to persist workflows is the overhead of the persisting. The act of persisting requires a lot of database saves which are quite expensive. This is especially true of text to workflows where several hundred may be launch in a very short amount of time. I created this video in response to just that situation:

https://www.rockrms.com/rocku/video?VideoId=1089

Around the 8m mark we talk about what persisting entails.

We can look into the root problem here to see what might have changed. Can you confirm that this wasn't an issue until v7?

**Comment by JimMichael** [comment] 2018-12-04 19:48
<sad trombone>. As for confirming when it started... I _think_ it was v7, but now I'm second-guessing myself. Could have been one of the later 6.x releases, to. @cabal95, do you remember when you starting having these issues?

**Comment by cabal95** [comment] 2018-12-04 21:09
I thought it was v7 as well. That is I'm pretty sure when we had to switch every single one of our workflows to auto-persist.

In that light, I do get what Jon is saying about overhead. I'm just wondering if we are already there anyway. I never create a workflow without turning on auto-persist anymore, and when others have workflow issues I tell them to turn on auto-persist as the first-step in trouble shooting. I will probably never turn off auto-persist on any of my own workflows. I just can't risk that they suddenly stop working like they did in v7. That was a disaster of people filling out workflows that we never got, more-so because it sometimes worked and sometimes didn't.

**Comment by nairdo** [comment] 2018-12-07 13:50
Update...  I've tried at length to reproduce this issue:
- with the DISC request workflow 
- and with the Photo Request workflow
- used local dev system running 8.5
- used rock demo site running 8.5
- entirely disabling/removing the persistence action.
- tried running as admin and a non-admin (ted decker)
- tried multiple concurrent executions at once
- tried clearing cache during runs, etc.
- over 100 tests, all emails received
- in all cases, used SMTP Transport pointing to my local workstation running Smtp4Dev via ngrok.

For the record, neither of these workflow's SendEmail actions are dependent on persistence, so an email problem really has nothing to that, but since you're saying the emails are not received, perhaps the real issue occurs before that action, in the User Entry Form's execution/processing?

We really need some additional details about exactly what is being seen when this problem occurs.  As you can see in my screenshot, I see the "Your information has been submitted successfully" message each time and then the email appears in my collector.

![image](https://user-images.githubusercontent.com/383807/49651292-fc47e100-f9eb-11e8-86c1-1fde8843b44e.png)
_(sample of one of my 10 item runs)_

**Comment by nairdo** [comment] 2018-12-07 18:46
We're going to keep this issue open - as we want to continue to try to find a way to reproduce it.

**Comment by cabal95** [comment] 2019-02-14 21:52
I am currently on Rock 8.3, and just ran into this again. So worst case, I can export the workflow and send it to you, but I'll see if I can trim it down to the bare minimums to replicate.

**Comment by cabal95** [comment] 2019-02-14 23:07
Attached is a screenshot of the trimmed down workflow configuration that is still causing issues on our 8.3 install.

With Automatically Persist turned off, when you click the Next button on the first User Entry Form, it displays the "your data has been submitted" message - oddly enough it just appends it to the bottom of the page, it doesn't clear all the form fields off the page.

With Automatically Persist turned on, when you click the Next button on the first User Entry Form, it takes you to the second user entry form.

[Screenshot_2019-02-14 Workflow Configuration Rock RMS.png.zip](https://github.com/SparkDevNetwork/Rock/files/2867109/Screenshot_2019-02-14.Workflow.Configuration.Rock.RMS.png.zip)

**Comment by BemaDavidBensen** [comment] 2019-05-01 00:05
It looks to me like this might be more widespread. 

I can reproduce this 90% of the time on any User Entry form that isn’t persisted from start. On several clients, I’m seeing it happen 1/10 entries with no way to track which ones are not getting persisted.  

Steps to reproduce on demo site

- Change global attribute LegacyWithWarnings to  No Legacy 
- Create a workflow 
- Turn Automatically Persisted off
- Add one text attribute 
- Add a user entry form
- Add an action to persist 
- Save 
- load the form and hit submit
- Go back and look if it saved. 
- I got 3 persisted out of 10 tries.

**Comment by tstephens17** [comment] 2019-05-06 18:53
Just to throw my hat in the ring here. I saw this when we launched on Rock. Which was 6.10.

**Comment by JimMichael** [comment] 2019-05-06 19:00
Note I renamed this issue to remove the reference to "Email Send Action" because this appears to be happening on workflows without that action, too.

**Comment by BemaDavidBensen** [comment] 2019-06-11 14:05
Is there any update on this? Seems like a very critical issue.

**Comment by JimMichael** [comment] 2019-06-11 14:32
Just FYI in case it's not clear... all you need to do to make things stable is auto-persist the workflow, then it works 100% reliably. There's no downside to persisting other than potentially creating "abandoned" active workflows when someone visits a page with a UEF then doesn't submit it, but we've taken to auto-persisting pretty much everything and just adding another action to delete an abandoned WF if it's not completed within a defined timeframe that makes sense for that WF. The other potential downside is performance, but unless it's a Text2Workflow that needs to process thousands of incoming requests quickly (and those usually don't need forms, anyway), you shouldn't notice anything performance-wise.

**Comment by BemaDavidBensen** [comment] 2019-06-11 16:42
> Just FYI in case it's not clear... all you need to do to make things stable is auto-persist the workflow, then it works 100% reliably. There's no downside to persisting other than potentially creating "abandoned" active workflows when someone visits a page with a User Entry Form then doesn't submit it, but we've taken to auto-persisting pretty much everything and just adding another action to delete an abandoned WF if it's not completed within a defined timeframe that makes sense for that WF. The other potential downside is performance, but unless it's a Text2Workflow that needs to process thousands of incoming requests quickly (and those usually don't need forms, anyway), you shouldn't notice anything performance-wise.

100% understand, but its core feature that isn't working, and by default, several workflows are broken and people are not aware that copying those same methods will result in a lot of entries getting dropped.

**Comment by ethan-sparkdevnetwork** [comment] 2019-06-13 22:48
I found some issues with the WorkflowEntry block when RaisePostBackEvent() was called that didn’t end the workflow.

First problem. The WorkflowEntry block was comparing the IDs of workflow actions to determine if the action was new or not after the postback. If the workflow was not persisted then the IDs are all 0 and all comparisons were true. The result being the block didn’t try to load the second part of the workflow and just ended it.

I updated the block to compare GUIDs instead of IDs to resolve problem one.

Second problem. The block navigated to the next workflow interaction by reloading the page, passing in the workflow IDs as a parameter. For a non-persisted workflow the block would use ID 0, which is considered a new workflow and not a continuation of one.

I updated the block to automatically persist the workflow if it needs to reload using the workflow ID.

Notes:

- I was not able to reproduce the issue with the directions that David Bensen provided. I didn't see any issues with a single interaction workflow.
- This fix will be in the pre-alpha release on 2019-06-19 if anyone can test it out. Or you can fetch from the repo now.

**Comment by nairdo** [comment] 2019-06-17 21:03
@JimMichael We're slightly hesitant to close this issue until you (and a few others like @BemaDavidBensen ) have a chance to verify it resolves the cases you were able to reproduce.  Can you please put this on your list of things to try when the v9 alpha is out?  Thanks!

**Comment by JimMichael** [comment] 2019-06-17 21:14
Will do. Thanks for being so _persistent_ with this issue! (see what I did there?)

**Comment by ethan-sparkdevnetwork** [comment] 2019-06-19 16:51
This was auto-closed after merging v9 into develop. We want to do some community evaluation before closing.

**Comment by ethan-sparkdevnetwork** [comment] 2019-06-24 20:37
This is in pre-alpha right now. @JimMichael and @BemaDavidBensen, can you check to see if you can still reproduce the issue? @mkinyon, are you having any issues with workflow persistence since the pull? Thanks for all the help in hunting this one down.

**Comment by mkinyon** [comment] 2019-06-24 20:53
@ethan-sparkdevnetwork I tested this commit pretty thoroughly and it resolves the issue for us.  I haven't been able to reproduce it since then.  I'll let you know if I notice anything.

**Closed** 2019-08-09 21:06 UTC
Labels: Fixed in v9.0, Not Yet Reproduced, Status: Attention Core Team, Topic: Workflows
