### ISSUE TITLE
Dynamic Data Block Temp Table SQL Errors

### ISSUE THREAD

**Issue by waynehelsby** [SparkDevNetwork/Rock#5868] opened 2024-05-10 19:38 UTC
### Description

The use of temporary SQL tables in dynamic data block queries causes cluttered Azure SQL error logs, and causes extra load on the database server.

We have altered approximately 100 SQL queries in dynamic data blocks to eliminate temporary tables often using table variables instead.  Our remaining queries with temporary tables will be more difficult to alter because of more advanced SQL functions.

### Actual Behavior

When viewing a page with a dynamic data block that includes a temporary table in the query, the attempt to get the schema fails, and adds errors to SQL error logs.  The full query is run to get only the schema.  The query is run once again to get the results.
<img width="1541" alt="Screenshot 2024-05-09 at 2 06 49 PM" src="https://github.com/SparkDevNetwork/Rock/assets/555697/8abfb9f0-362c-445f-9b04-2f781fe5e8e2">
<img width="368" alt="Screenshot 2024-05-09 at 1 57 49 PM" src="https://github.com/SparkDevNetwork/Rock/assets/555697/86ef662d-f726-47ed-95de-392f4d3fd4c9">
<img width="369" alt="Screenshot 2024-05-09 at 1 58 18 PM" src="https://github.com/SparkDevNetwork/Rock/assets/555697/46539bca-9f0b-478e-9c29-178eb4cd5f4c">

<img width="1574" alt="Screenshot 2024-05-09 at 2 12 50 PM" src="https://github.com/SparkDevNetwork/Rock/assets/555697/7295e2ca-e5ef-4276-949b-85a1d421c30e">

### Expected Behavior

- No Errors
- Full query run once

### Steps to Reproduce

- Create a new page containing a Dynamic Data Block
- Add the following sample SQL query
```
SELECT * INTO #TempTable
FROM Campus

SELECT * FROM #TempTable

DROP TABLE #TempTable
```
<img width="1852" alt="Screenshot 2024-05-09 at 1 59 02 PM" src="https://github.com/SparkDevNetwork/Rock/assets/555697/17ed5994-1146-4a97-a980-727849970aaf">

- Run a SQL trace to view executions
- View new page
- View SQL Error logs

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.3

### Client Culture Setting

en-US

**Comment by chead4** [comment] 2024-05-13 17:54
@waynehelsby Hi Wayne - We have confirmed the issue and have identified what's causing it.  This is a known limitation within the Dynamic Data block when temp tables are involved.  It is due to building controls dynamically based on the query and executing the query twice to get the schema.  We will work on resolving the error in both the webforms and obsidian block.

**Comment by waynehelsby** [comment] 2024-05-14 13:08
that's great, thanks

**Closed** 2024-05-29 00:48 UTC
Labels: Type: Bug, Status: Confirmed, Fixed in v16.6
