### ISSUE TITLE
Interactions not Added to Streaks

### ISSUE THREAD

**Issue by asdf1nit** [SparkDevNetwork/Rock#5006] opened 2022-05-10 03:37 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
Exception Log. I think this is related to the issue below.
![image](https://user-images.githubusercontent.com/18108765/167532765-e82f53b5-d5c5-4a36-aafc-08a7be0c0006.png)

### Description

We have a Rock Mobile Application. During the 12.x releases (prior to 12.8 but not before 12.4 ) our Mobile App quit adding Streak Engagements for Interactions. I've been looking into this for a bit now; Rocket Chat with implementation details [here
](https://chat.rockrms.com/channel/troubleshooting?msg=txcPqYyt9QwhzwbAr). I have found an exception in my log that I think is related(in the above screen shot. )

On mobile we have a page that writes an interaction to a specific Interaction Chanel Id and Component Id. This interaction is also a linked activity via the streak setting. On web when you visit this page(if you are logged in) an Interaction is written, and a streak engagement is written, we've had no issues with website streaks. On mobile it has quit working. 

Using this code:
` <Rock:Interaction Operation="View"
                Summary="Bible 365"
                ChannelId="6"
                ComponentId="659"
                Data="https://ark.info/page/817?day={{ currentReadingDayClient }}&amp;mobile-app=true"
                MarginBottom="-16"/>`

An interaction is written, but the streak fails to mark an engagement for the person. If you manually rebuild the Streak data the correct engagements are written.

This was working prior to the beginning of the year and into the beginning of this year.

**Expected behavior:**

When an Interaction is logged, the person(if logged in ) would be added to the streak associated.

**Actual behavior:**

The person is not added to a streak.

### Versions

* **Rock Version:** [13.3]
* **Client Culture Setting:** [en-US]

**Comment by cabal95** [comment] 2022-05-10 18:43
@asdf1nit I tried to replicate this issue but wasn't able to.

I created a Streak Type that was synced to the interactions for a specific Rock (web) page. Then I loaded the page in the browser in order to verify that the streak did get updated when recording an interaction for that page. It did.

I wiped out all the streak data and interaction data and then used the `<Rock:Intereraction />` command in Mobile to record an interaction to that same channel and component so I could see if the streak updated. It did. I tried this a half dozen times using Rock 13.4 as well as Rock Mobile 2.1 and 3.0. It worked each time. In all tests, the user was logged in.

Do you have any more details that we can use to try and replicate the issue, or are you able to build (and document the steps) a reproducible test case on the demo site using the orange mobile  app?

I did occasionally get the exception, but I was able to narrow that down to what appears to be an unrelated issue because it happens on Web too. Basically, if two interactions get written at the same time (like if you view the page twice within a few seconds), both save operations will fire off a "create streak" operation. One of which succeeds while the other fails with the error you are seeing. But in all my tests, even when that exception did come up the streak was still created/updated. We will be looking into fixing this exception as well.

**Comment by asdf1nit** [comment] 2022-05-11 22:13
I will work on getting more details for you I'll just need some time to get this done. We're on Rock v13.3, not sure if that will make a difference. I'm not sure which mobile version we're on. I know it's not 3, and assume it's 2.1.

**Comment by cabal95** [comment] 2022-06-15 17:26
@asdf1nit Any chance you can attempt to replicate this on the pre-alpha or demo sites by building a small test app there and using the Rock Demo mobile app to test with? If you can keep a list of the specific steps you took and are able to replicate the issue there, then we would have a better chance of replicating it here to debug further.

**Comment by cabal95** [comment] 2023-02-13 18:06
@asdf1nit We are going to close this for now as we can't reproduce it in our development environments to proceed with any testing or fixing. Please feel free to re-open in the future if you find a way to replicate this on the demo site so we can attempt to replicate in the debugger.

**Closed by cabal95** 2023-02-13 18:06 UTC
Labels: Not Yet Reproduced, Type: Discussion, Topic: API
