### ISSUE TITLE
Unable to email em dash

### ISSUE THREAD

**Issue by tscrip** [SparkDevNetwork/Rock#2818] opened 2018-02-22 22:14 UTC
### Prerequisites ###

* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description ###

We are trying to send an email with some external content. The content occasionally has an em or en dash. When an email is generated from Rock, em dashed are always converted to a regular dash. I am not sure if it is strictly limited to em dashes, but that is all that I have tested with.

Troubleshooting steps taken:

* Tried with the dash formatted like the following: `&mdash;``&#8212;``&#x2014;`
* Tried sending through `MailGun` and `SendGrid`
* Tried receiving at both `Outlook` and `Gmail`
* Examined data in Communication table and can confirm it is stored in correct format

### Steps to Reproduce ###

1. Open New communication
1. Select recipient and template
1. Enter this in the body of the email: `HTML: &mdash; <br/>Decimal: &#8212; <br/>Hex: &#x2014;`
1. Click send
1. Review results in mail client

**Expected behavior:**

em dash is render correctly

**Actual behavior:**

em dash is being rendered as regular dash

### Versions ###

* **Rock Version:** 6.10, 7.2
* **Client Culture Setting:** en-US

**Comment by jgrabrian** [comment] 2018-02-22 23:06
Reviewed logs in Mailgun after testing and confirmed that it received the message with a regular dash.

**Comment by MichaelAllen** [comment] 2019-06-23 18:16
This appears to affects all communication transports, not just Email. However, I'm not sure if it is a bug or intended behavior. 

In Rock.Communication.TransportComponent the [ResolveText](https://github.com/SparkDevNetwork/Rock/blob/074fa4ffcca387a15c3f7f2903296b5a4388f659/Rock/Communication/TransportComponent.cs#L128) method is calling [Rock.Extension.ReplaceWordChars( )](https://github.com/SparkDevNetwork/Rock/blob/074fa4ffcca387a15c3f7f2903296b5a4388f659/Rock/Utility/ExtensionMethods/StringExtensions.cs#L901) to strip "special" characters (em dash included). This appears to be designed to cleanup text pasted in from MS word or similar.

I see 2 options for fixing this, if it is indeed a bug.
1) Don't "cleanup" the communication body, take whatever the user types.
Removing this line would accomplish that for all types of communications. (Alternative: add a conditional to only cleanup SMS messages since they have a limited charset.)
https://github.com/SparkDevNetwork/Rock/blob/074fa4ffcca387a15c3f7f2903296b5a4388f659/Rock/Communication/TransportComponent.cs#L131

2) Remove "em dash" and "en dash" from the list of things that get cleaned up. (Still clean up other things like smart quotes and ellipses)
Removing these 2 lines would accomplish that:
https://github.com/SparkDevNetwork/Rock/blob/074fa4ffcca387a15c3f7f2903296b5a4388f659/Rock/Utility/ExtensionMethods/StringExtensions.cs#L914-L915
(Not sure where else this method gets used, so this solution may have unintended consequences.)
It is probably better to make a new cleanup method that doesn't remove dashes and replace the line referenced in option 1 with a call to that method instead.

I'm willing to submit a PR for either solution, I'm just not sure which is the better option.

**Comment by jonedmiston** [comment] 2023-09-16 00:05
This issue is a duplicate of: https://github.com/SparkDevNetwork/Rock/issues/2818 

We will correct and test the fix for the characters described in #2818 when fixing this issue.

**Closed** 2023-09-28 19:55 UTC
Labels: Type: Bug, Status: Confirmed, Status: Available, Priority: Low, Topic: Communications
