### ISSUE TITLE
NMI Gateway not checking to make sure credit card and name on card is filled in

### ISSUE THREAD

**Issue by ToxicFume** [SparkDevNetwork/Rock#3757] opened 2019-06-20 17:50 UTC
### Description
We just setup our payment gateway with My Well Ministry. We noticed that when choosing the NMI gateway makes the "Give Now" page a 3 step process which is different from the other 2 gateways (including the test gateway) I believe that takes it out of of code that checks the the credit card holders name and credit card number are filled in. 

### Steps to Reproduce
1. [First Step] Setup a NMI Gateway as the documentation suggests.
1. [Second Step] Go to the Give Now page and enter information and click next
1. [and so on...] Leave all the fields blank in the credit card/bank page and click next. **Expected behavior:**

[What you expected to happen]

There should be a check to see if those fields are filled in.

[What actually happened]

It lets you advance to the Confirm Information and when you click finish then it throws a weird error saying its invalid information, so then you have to start completely over.

### Versions
* **Rock Version:** [Rock McKinley 8.8 (1.8.8.3)]
* **Client Culture Setting:** [en-US]

**Comment by EthanW96** [comment] 2019-10-24 18:25
Can confirm this is a bug on a production Rock v9.2 server using a NMI Gateway.

May involve this validation section only occurring for non 3 step gateways
https://github.com/SparkDevNetwork/Rock/blob/136e854a10d5bb3b664b1acdf3972e9b6db88f6f/RockWeb/Blocks/Finance/TransactionEntry.ascx.cs#L2147

and missing validation in the iframeStep2 JS area:
https://github.com/SparkDevNetwork/Rock/blob/136e854a10d5bb3b664b1acdf3972e9b6db88f6f/RockWeb/Blocks/Finance/TransactionEntry.ascx.cs#L3183

**Comment by nairdo** [comment] 2020-03-05 16:46
Since this is a duplicate of the older #2084 which has a bit more history, I'm going to close this one out as a duplicate.  Please follow that item if you want to get updated when that issue is addressed.

**Closed by nairdo** 2020-03-05 16:46 UTC
Labels: Status: Confirmed, Topic: UI, Type: Bug, Type: Duplicate, x-bugapalooza: Med
