### ISSUE TITLE
Obsidian Registration with redirect gateway doesn't "attach" transaction to the registration if past registration instance end date

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#5697] opened 2023-12-19 14:48 UTC
### Description

We are using the Pushpay Payment gateway with the Obsidian Registration Entry block and found this bug recently. Whenever someone pays an additional payment on their remaining balance using an external payment gateway (ours is Pushpay), and the registration instance's end date is in the past, the payment goes through however it doesn't get attached in the database to their registration. The person paying also receives a "registration closed" message, so they don't know if their payment even went through.

This issue **does not occur** with the NMI gateway. It also **does not occur** if the registration instance date is in the future and you are using the Pushpay gateway. It's the combination of the Pushpay gateway and registration instance end date being in the past.

![image](https://github.com/SparkDevNetwork/Rock/assets/66277785/5245bb1b-0796-4210-b5b7-8af4f1050423)

### Actual Behavior

Additional payments on a registration whose end date is in the past configured with a redirect gateway (we used Pushpay) does three things. This would be 1) the transaction is not immediately saved to the database, 2) the transaction is not correctly attached to the registration, and 3) the person making the payment receives a "sorry this registration is closed" error.

### Expected Behavior

I would expect that additional payments on a registration whose end date is in the past would still behave the same way as the initial payment and the way the internal gateway does. This would be 1) the transaction being immediately saved to the database rather than waiting on the Pushpay sync job, 2) the transaction would be correctly attached to the registration, and 3) the person making the payment  would see a successful payment message.

### Steps to Reproduce

> [!IMPORTANT]
> Because these reproduction steps require not only a payment but also configuration with a Pushpay gateway, I wasn't able to attempt reproducing this on the demo site. The reproduction steps are from our own instance. I had to check the box saying I did try to submit the bug, so I'm coming clean here that I couldn't do that 🫣

**Prerequisites**
- Rock instance running v16 (this is the version I tested on, however I believe you could probably test on an earlier version, i just don't remember which version Pushpay gateway support was released with)
- A configured Pushpay gateway
- The registration block on the /Registration page being the Obsidian Registration Entry

**Reproduction Steps**
- Navigate to Tools > Event Registration
- Pick any template category and create a new Registration Template
- Make sure the following are set:
   - Financial Gateway: Pushpay
   - Cost: $10
   - Minimum Initial Payment: $0
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/15f0cd3e-677e-4dfb-b4d9-83d19b1a5c7a">

<img width="1723" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/412d7646-b150-4567-9cdb-a391aae579bd">

- Create a new Registration Instance, giving it any name and leaving the rest blank
- Add a linkage to it (this is just to get the URL to test)
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/87cebb49-26d9-4cd0-b996-499290a7ace0">

- Copy the URL to your clipboard (should be https://DOMAIN.com/registration/URLSLUG)
- In a new tab, navigate to the URL you copied
- Complete the registration process as a logged in user (so that later on you can easily access the link to pay additional payments), setting your initial payment to $0 (really the goal is just to leave a remaining balance, just trying to minimize the # of test transactions)
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/adda353a-1674-458a-9055-35a99467b03f">

<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/74f60249-535d-4f00-a1d3-6e5eb9c30d3f">

<img width="1727" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/59794d25-1222-4742-8419-58e5c1509bfe">

<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/af55ae6a-d996-416a-9bdf-bc9624e187d3">

- On the internal side of Rock, go to Tools > Event Registration
- Click on the template created earlier, and then click on the instance
- Edit the instance so that the end date is yesterday then click Save
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/c908dd72-c0d7-4277-9f20-5c8e45b9b1c0">

- On the external side, go to your My Profile page of the user used to register
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/a9360dae-5a44-4fde-92c9-3ef24f5f8730">

- Pay $1.00 on the amount owed
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/937ca0c5-4e14-424b-a0d8-f309dd1197dc">

- You should be redirected to Pushpay's gateway to complete the payment process
- Complete the $1.00 payment
- You'll be redirected back to Rock's registration page (or whatever the URL redirect is configured on Pushpay's side)

Three things occur here that I believe are bugs:
1 - when the registration instance is past the "registration ends" date, you don't get a successful payment completion message, instead you get a "sorry this registration is closed". This has caused quite a few of people to try to pay again, thinking it didn't go through the first time.
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/7ac86106-d87d-4717-aea1-84be2bb74352">

2 - the payment doesn't immediately get synced to Rock transactions, instead it is only pulled into Rock when the Pushpay sync job runs. I verified that when you make an _initial_ payment on a new registration with Pushpay, the transaction immediately gets added to Rock with the summary, correctly attached to the Registration.

I imagine if #2 is fixed above, then this one will probably be resolved, but I am including it for clarity.
3 - the payment, when finally synced with the Pushpay job, doesn't get attached to the registration at all.
<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/b29769dd-1945-46d0-8c50-bdc95d2a7066">

<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/b0680861-6495-4a1e-a335-ff4f8fb6e11e">

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.0 (1.16.0.12)

### Client Culture Setting

en-US

**Comment by cabal95** [comment] 2024-01-02 21:17
@leahjennings I think I have a fix for this, but want to validate it against something that wasn't included in your original ticket. When you get the "Registration Instance closed on mm/dd/yyyy" message, can you tell me what the URL is in the browser address bar? i.e. what URL is PushPay sending you back to. Since it might have sensitive information in it, feel free to send it to me in a DM.

**Comment by cabal95** [comment] 2024-01-02 21:27
Loosely related to #5212.

**Comment by leahjennings** [comment] 2024-01-02 21:33
@cabal95 just sent you a DM on Rocket.Chat :)

**Comment by cabal95** [comment] 2024-01-02 21:35
Great, thank you. It looks like I was reproducing your original problem - just wanted to double check.  The core issue is that when the `RegistrationId` parameter was not available, it used the standard "is the registration instance closed" logic. We will update that to use the session Guid as a fallback to get that information when returning from a redirect gateway that can't include that value.

**Closed** 2024-01-02 21:56 UTC
Labels: Type: Bug, Status: Confirmed, Topic: Event Registration, Fixed in v16.2
