### ISSUE TITLE
Error Deleting attendance from Group Attenance Page

### ISSUE THREAD

**Issue by rutledgek** [SparkDevNetwork/Rock#3321] opened 2018-10-08 16:35 UTC
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When you click delete attendance on the group attendance you get the confirm dialogue and then an error:

"Alert
This Attendance Occurrence is assigned to a Attendance."

### Steps to Reproduce
1. Go to Group Attendance Page.
1. Click on Delete for an attendanc already entered
1. Confirm that you want to delete the attendance
1. Receive Error

**Expected behavior:**

I expect to be able to delete an attendance from that page without error

**Actual behavior:**

Attendance is not deleted and error occurs.

### Versions
Rock Version: Rock McKinley 8.3 (1.8.3.36)
Client Culture Setting: en-US

**Comment by pdonlevy** [comment] 2019-10-24 16:18
Tested with group type of small group and group type of serving group.  Could not recreate the error.
I tested both group types in dev and in the alpha site and could not recreate the error.

**Comment by nairdo** [comment] 2019-10-24 16:27
Reported as unable to reproduce in the #bugapalooza channel.
```
pdonlevy 9:24 AM
Tested #3321, could not recreate the error. I think this is no longer a bug.
```

Possibly fixed in v9-v11.

**Closed by nairdo** 2019-10-24 16:27 UTC
Labels: Not Yet Reproduced, bugapalooza: Is Needed?
