### ISSUE TITLE
Rock Project File Format

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#2418] opened 2017-08-30 03:38 UTC
## Goal
To discuss and agree on the specification of the proposed Rock project file format.

## Background
There's currently no way to discover community Rock projects created by the community. To improve discoverability and accessibility it was proposed today (RX2017 Day 2) that projects include a standardised Rock project file in their repository to describe their project. This file can then be parsed and displayed in an appropriate location on the Rock site. Repositories containing a Rock project file would be identified using the [Github Topic](https://help.github.com/articles/about-topics/) `rock-rms`. 

It was suggested that repositories could either contain a single project file at the repository root (if the repository corresponds to a single project) or multiple Rock project files for repositories containing multiple projects.

## Description
This issue is a place for developers to suggest and discuss what information should be included in the Rock project file and what structure the information should be stored in.

**Comment by arranf** [comment] 2017-08-30 03:40
@mikejed @chrismcgrath @cbump @trydyingtolive @cabal95 @garrettjohnson @Tschrock

**Comment by arranf** [comment] 2017-08-30 04:05
I think the [NPM package.json](https://docs.npmjs.com/files/package.json) is a good place to take inspiration.

I like the following information they track:
* name
* version 
* homepage
* license
* files
* dependencies

Additionally, on my way home, I was thinking in the long term this file could be used to decrease the friction (optionally) when submitting a Rock plugin. The contents of the `run.sql` and the `deletefile.lst` could be specified in the project file and we could also take the project description, name, required rock version, documentation URL, post install instructions, and screenshot URL from there too. 

I would suggest the following required fields:

* name
* description
* organization
* project version
* rock version
* license

And the following optional fields:
* screenshot url
* documentation url
* project url
* post-install instructions
* install (sql and file list)
* uninstall (sql and file list)

**Comment by cabal95** [comment] 2017-08-30 10:36
Part of my writeup will include a powershell script that takes various bits of information from the repository and automatically builds the .plugin zip file, including auto-generation of the `deletefile.lst`. It's not 100% but probably works enough generate the files for 90% of the plugins that will be submitted (Things like the room management plugin are probably complex enough to still need a manual packaging process)

**Comment by arranf** [comment] 2017-08-30 19:52
@cabal95 I've got one of those too. I was thinking more along the lines of the friction with the web UI, it'd be nice not to have to resubmit information that remains the same. Of course by no means is that necessary for what we're trying to achieve here, I just thought it'd be a useful extension of the file if we went down a JSON route.

**Comment by nairdo** [comment] 2017-08-30 20:27
@cabal95 I'm using the csproj msbuild to package the Room Management Plugin and version stamp it on "Release" build but I'm intrigued by your powershell approach.

**Comment by cabal95** [comment] 2017-08-30 20:49
Just spinning here, does it make more sense to use a keyword/label like `rockrms-plugin` to identify these? Not sure what kind of character limit we might have to work with.

**Comment by arranf** [comment] 2017-08-30 20:58
@cabal95 That might get confusing if the repo is a Rock fork (say like Newsprings) and it's tagged as a plugin. We could make the extension explicit though?

**Comment by edmistj** [comment] 2017-08-31 11:12
Thanks Arran for getting this started. I'd be inclined to start with the basic items. I'm not sure we'd want to take the step of having the store web UI pull from this file yet, though I can see how it would simplify the process. 

Are we landing on JSON or Markdown? Personally, I'm fine with either, though JSON seems more structured.

**Comment by arranf** [comment] 2017-08-31 15:28
@edmistj I agree! Just wanted to put the idea out there. I prefer JSON.

**Comment by cabal95** [comment] 2017-08-31 16:01
I would prefer JSON too. That would still allow us to use Markdown either inline in the JSON or as a file reference later if we want for some of the elements that could use a little prettification (like description).

The `documentation_url` I think would be useful too. Many plugins would probably just point to the repo README file, but larger ones (text 2 workflow, room management, etc.) would probably point to more nicely formatted PDFs and such.

Other UI related things (screenshots etc) I think will be useful, but better left until we discuss some of our other items in more detail. Once we hash out more of the meta-search and other discussions I think we'll get a more solid idea of what extra information would be good to scrape from this file.

> File reference example would be if `description` is < 100 chars and matches a filename in the repo, such as `.description.md`

**Comment by cabal95** [comment] 2017-08-31 16:09
Seeing Jon's comment on another discussion just now, another good field might be `status` to show if a repo is in `development` (i.e. pre-pre-alpha), `beta`, `stable`, etc.  Exact status names to be determined later.

This also brings to mind something I'll throw out just so we keep it in mind since I don't have any thoughts on how (or if) we deal with it. Possibility of having the scraper check different tagged versions of this file. Why: Say I finish version 1 of something in a repo. It's stable, works great. I want to start working on the next version, which through various commits is left in a state where it's not functional (yet). As I said, don't have any solid ideas on this, just wanted to toss it out as something for us to keep in mind in case we decide it is something we need to account for.

**Comment by arranf** [comment] 2017-08-31 16:13
@cabal95 I like the status idea. I wonder if we can tie that into the versioning or if it should be a separate field? 
I think there should definitely be a field for whether or not it's in the Rock Store.

**Comment by edmistj** [comment] 2017-09-01 01:05
woildnt having a master (default) and develop branch resolve this issue? We'd always pull the JSON from master while work could be done in develop. Tags would be used for completed versions.

**Comment by arranf** [comment] 2017-09-01 02:11
I think that only really works for projects once they hit 1.0, Github defaults to a master branch and I know I'm guilty of having an unstable single master branch until the first release and I think we want to broadcast project's that aren't quite ready for primetime. 

I do think that we should make it so it's easy for folks to keep their project up to date and I'm not sure I'd remember to update my project status.

**Comment by edmistj** [comment] 2017-09-02 20:40
I'd say that until you have a stable v1.0 your master would be your develop (or you could change the default to be develop). This is the site we used to create the standard for the core repo. http://nvie.com/posts/a-successful-git-branching-model/

**Comment by cabal95** [comment] 2017-09-02 22:13
I think if we have a zip file that can be expanded into an empty repo it will take care of most things. Zip file contains the basic recommended structure and any powershell scripts, .gitignore, .plugin.json, etc. files. So steps to starting a new plug-in would be:

1. Create repo on github.
2. Clone to local computer.
3. Download and unzip `plugin-template.zip` into the empty repo.
4. Edit the `.plugin.json` file to reflect the name, description, etc. of our plugin (default values for version 0.0.1, status of development, etc.)
5. Commit changes to master
6. Branch as develop and begin work.

As long as that is documented so we don't forget, I think we'll be okay.

**Comment by arranf** [comment] 2017-09-02 22:36
I think we should create a small program that can auto fetch from Spark and edit the files as necessary.

**Comment by cabal95** [comment] 2017-09-04 20:42
I like the idea of a helper tool. Though I think that should wait for a "version 2" state of everything so we can iron out the actual steps that need to be performed. Everything always sounds great on paper until the first time you try to do it. :)

**Comment by edmistj** [comment] 2017-09-05 16:06
Looks like consensus is made on a v1.0 approach. @arranf can you post a final proposal with a sample JSON file?

**Comment by arranf** [comment] 2017-09-06 18:58
So this is what I've got based off the discussion above. There are a couple of points that I think we need to clarify, either because they haven't been discussed or the ideas don't seem complete enough, I've put these as questions at the bottom.

# Proposal

## Repositories
Repos will use the Github tag `rock-rms` to identify that they're related to Rock so we can scrape the information out. 
Repositories are encouraged to use the Git flow (`master` / `develop`) convention for plugins. 

## Project File
I think the following fields are a good start:
```
{
    "name": "My First Plugin",
    "description": "This is a brief description of my first plugin. I can ~use~ *abuse* (markdown)[https://guides.github.com/features/mastering-markdown/] _syntax_ to my heart's content!"
    "plugin_version": "1.0.0",
    "documentation_url": "https://example.com/my-first-plugin",
    "organization": {
      "name":  "Rock  Solid Church",
      "website:" "https://www.rocksolidchurchdemo.com",
      "email": "ted@rocksolidchurchdemo.com"
    },
    "license": "AFL-2.1",
    "rock_version": ">=1.6.0"
}
```

### A Few Details:
I suggest we use [semver style syntax](https://docs.npmjs.com/misc/semver) for indicating which Rock Version a plugin is compatible with. I have plugin versions that are compatible `<1.6.0`, others which are just `1.6.*`, and some which are `>=1.3.0`.

I suggest the `organization field` should be either either an object or a single name as a string. I think more information is better but it's unnecessary. 

All fields are required.

## Ease of Use

It seems we can get a quick win by providing people with a template file. Once the project file is concrete a quick tool to generate a file would be useful too.

# Outstanding Questions
1. It's suggested that we use branching to indicate the status of a project, i.e. `stable` or `unstable`. I don't think this solves the use case of churches like NewPointe, SouthEast, and NewSpring sharing the projects in their monolithic repos but would be suitable for someone like myself who has a large number of individual repos. I think we need a better solution here. Suggestions include a `status` field in the file or encouraging people to use semantic versioning (<`1.0.0` is unstable and anything with `-beta` or -`alpha` is unstable).

2. I think we need to agree an naming convention for the file. `project.rock`, `my-plugin.rockproj`, `rockproject.json`?

3. We should think about how we might want to version the project file specification. Do we include a field inside the json `rock_package_version`?

**Comment by cabal95** [comment] 2017-09-08 17:23
My (out of order) thoughts.

2. If this is for plug-ins, I would say `rock-plugin.json`.  I think the term "plugin" can be used broadly enough to catch things that aren't technically plugins, but close enough (repo of workflow exports for example).

3. I think that can be added later.  When we need to go to version 2 we just assume the lack of that field means version == 1.

1. The `master`/`develop` branch would work for monolithic as well, as long as they properly adhere to it.  I think in the case of a monolithic repo they would have multiple `rock-plugin.json` files. One in each 'plugin' sub-directory. I would be good saying for the moment anything with a version < `1.0.0` is considered unstable AND anything not in `master` is considered unstable. I don't think we'll know exactly how well it works and if an explicit `status` field is required until we try it and see what we get. And if we do need to add `status` we can just assume a non-existant status means `unstable`.

One of the reasons I don't like monolithic myself is that, for me, it make things difficult to keep separate what is what. Because everything is in one giant directory tree then to do it properly you need to have a branch for each "project" in the repo anyway (so you can merge that one branch into `master` when it's stable without merging everything else). So monolithic would work with this `master`/`develop` model, they would just need to do `master`/`develop-plugin-a`/`develop-plugin-b`/`develop-plugin-c`/etc. If I'm going to do that I figure I might as well just have multiple repos.

But like I said, I think we won't know exactly how well this works until we all start tagging our repos and see what happens. Though I feel we are close enough to get started and tag a few repos and start building the back-end and see what data we get back and then what changes might need to be made before we build a "repo template" bundle.

**Comment by arranf** [comment] 2017-09-08 17:35
@cabal95 I agree we should start building ASAP and I agree with you on 2 and 3. I'm not super sure how 4. Would work. If I have Plugins A, B, and C alongside my Rock repo -- we can safely assume whatever is in `master` would be stable. However, what if only Plugin C is in development on `develop`, how could can we tell that plugins A and B are stable? I think self reporting (either from versioning or a status field) makes more sense there.

**Comment by cabal95** [comment] 2017-09-08 17:48
To be clear, I'm not against an explicit `status` field. Just know that Jon was thinking we didn't _need_ it. But just to clarify what I meant. Assume we have this repo structure:

- RockWeb
- PluginA
  - rockplugin.json
- PluginB
  - rockplugin.json

For the moment let's also assume that both those plugins are stable so that structure is in the `master` branch. Next I want to add a new plugin called `PluginC`. I would need to branch `master` and call it `develop-pluginc`. Once that plugin reaches stable I merge `develop-pluginc` into `master` and it shows up in the scraper.

If I want to make version 2 of PluginB, I again branch master to `develop-pluginb` (though in reality I probably already have that branch and just continue working in it); do my work, test, etc. and then merge `develop-pluginb` back into `master`.

What _doesn't_ work is to have a single `develop` branch because if PluginB is still under development but PluginC is ready for release, the only way to get it back into `master` is to merge the whole branch which puts PluginB there as well.

`status` field aside, I think the `master`/`develop` makes a lot of sense and we all need to start following it.  I'm too guilty myself of having my single-branch repos in a non-stable state because I'm working on a new feature and then have to help another dev figure out which revision to checkout from so they have a working plugin. With that in mind, I'm thinking that _for the moment_ we can skip the `status` field and see how things pan out over the next few weeks. We may find that we need something other than a simple `status` field anyway to deal with the various branches and whatnot.

**Comment by edmistj** [comment] 2017-09-08 21:15
@cabal95 This seems to be a problem when more than one plugin resides in a single repo. In these cases it's made even harder as a Plugin A and Plugin B will never be as clean in terms of directory structure. In these monolithic repos the files for a plugin can be in several places. For instance many of our plugins are just blocks so the only files are under RockWeb > Plugins > Org > Plugin.

For Mine Cart we're going to switch to a single repo per project, but others will probably be resistant to do that.

What if a single project file can support multiple projects? That might solve a lot of complexities.

**Comment by arranf** [comment] 2017-09-08 22:32
## What Kind of Repos Do We Need to Consider?

I've done a quick survey of repositories of churches I know that are using Rock who might be part of this conversation to see what we're dealing with. Here are a few observations.

Firstly, I don't think checking all branches is feasible. All repos I checked had 10+ branches some going as high as 20+.

There is no consensus on branch naming but there are similarities.
 
NewSpring uses an `alpha`, `beta`, `master` branch naming system.
Both CCV and Central kind of follows the Rock naming convention for branches but uses suffixes instead.
SouthEast does use the Rock naming conventions but their plugins and themes are in a separate repo to Rock.
Willow has no prefixes or suffixes on feature branches.
NewPointe actually seems to be using a Rockit with what I estimate is north of 20 separate things to share in a single repo.

**Comment by arranf** [comment] 2017-09-08 22:44
Whilst we've cracked discovery in single-project repositories using Github tags I think we need to come up with a solid solution for identifying all the individual projects in a single repository, for example [NewPointe's](https://github.com/NewPointe/Rockit). 

I think we can make a couple of assumptions for tracking down projects for a given Rock or Rockit repo. Any folder in the root that starts with a TLD (`org`, `church`, `com`, `cc`) is likely to be worth exploring. The `Plugins` folder is probably worth traversing too. Of course, this isn't likely to cover all projects, a church might want to share a Theme or a bunch of Lava files too so it might be worth creating a root file that lives in the default Github branch that contains a list of paths worth exploring. This file could also narrow down branches to be explored.

```
{
  "paths": ["RockWeb/Themes/Assets/Lava"],
  "branches": [{"rocksolid-beta": "unstable"}, {"deployed": "stable"}]
}
```

**Comment by cabal95** [comment] 2017-09-08 22:53
@edmistj: Arran and I did some discussion in Slack about this. I think we have a mostly workable solution for one-plugin-per-repo as well as "new" monolithic-repo. The issue is existing monolithic repos and how to bring them into the fold without too much headache for their owners.

@arranf It looks like unauthenticated we can do 60 requests per hour. We might be able to do more if we authenticate, but not sure how to do that off hand to see what the limits are. so I don't think traversing the tree is a good idea.  I would say we do something like require all `rockplugin.json` files to be in the root folder.  e.g. `/rockplugin.json`, `/rockplugin-PluginA.json`, etc.

Another option as a semi-short term solution is that we can allow for custom URL entry into the the scraper.  e.g. `https://github.com/ShepherdDev/rock-misc/blob/beta/org_shepherdchurch/Plugin/rockplugin.json`

**Comment by cabal95** [comment] 2017-09-08 23:26
I think we all agree that monolithic repos are going to take some extra TLC to automate gathering information from. We've had a few suggestions for how to deal with this.

1. Add a new file to the repo that identifies all the branches and paths to be scanned.
2. Multiple `rockplugin.json` files that each identify one plugin in the repo.
3. Put all plugins in a single `rockplugins.json` file as a JSON array of rockplugin.json data.
4. Manually register paths to be scraped in these repositories.

None of these really change the base format of what we discussed for the format of this "main" file. I think we are good to move forward with this file format while we discuss the best way to deal with monolithic repos - especially getting some input from the guys running those repositories and what they think about various options. (Converting to non-monolithic; converting branch names to a standard format; etc.)

**Comment by dcs619** [comment] 2017-09-09 00:03
FWIW, NewSpring has an old monolithic repo where plugins used to be, but I split each plugin to their own repo (including historical commits). See https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/.

So if we document the process to split monolithic repos, we could implement a much simpler solution.

**Comment by trydyingtolive** [comment] 2017-09-09 02:39
@arranf asked me to chime in so @cbump  and I discussed this a bit. First off our repo is currently not public, we are working on that. Our repository is setup to meet the needs of production and deployment systems. We have a monolithic repository which lets us use our continuous integration tools without constantly re-configuring them. In our system we don't think about version numbers outside of Rock's version. We think in terms of build numbers and branches. 

We keep a deploy branch with a name matching that of core. (Right now we are setting up a plugin branch named "hotfix-1.6.9" while maintaining a version for the current hotfix in production.) We also have a branch for development which goes into our staging server. On top of that we create branches for incubating new projects or features. The feature branches get merged into develop or hotfix. Develop and hotfix are actually pretty similar most of the time. Right now things we are developing further for consumption in the Rock Shop have a branch for public release.

I see two different focuses going on. One is folks making open source projects for public release, and the other is enterprise teams who open source their code base. Versions and stable/unstable branches are suited for the former. I could see us spinning off certain projects as separate repos as we see them as belonging in the rock shop, but if we spun off every project it would take 30+ repos. Moreover, we have projects in production no one will want outside of SECC, but have interesting solutions other developers may learn from. (I learned developing for rock from the NewSprings repo)

I would suggest that the project discovery system be as simple as possible offloading the format, versioning, Rock version requirement, etc to the README files. That way folks who want to standardize plugin development file structures can, but the enterprise teams don't have to change their systems to participate.

I would suggest a single file per repository that would work with both singles and monoliths, and with a focus on indexing and search-ability over CPAN like features. The details of the repo should not be in the purview of this discussion.  

Monoliths would look like this:

    {
      "organization": {
        "name": "Rock  Solid Church",
        "website": "https://www.rocksolidchurchdemo.com",
        "email": "ted@rocksolidchurchdemo.com",
        "organization_id": "1" // RockRMS organization id. Helps to link orgs with their code
      },
      "projects": [
        {
          "name": "PluginA",
          "description": "The A Team!",
          "path": "tree/master/Code/PluginA" //optional default is root
          "keywords": ["Mr","T","Van"] //keywords would help people find your project
        },
        {
          "name": "PluginB",
          "description": "The B Sides!",
          "path": "tree/develop/Code/PluginB" //you can even select your branch
        }
      ]
    }

And for one project per repo:

    {
      "organization": {
        "name": "Rock  Solid Church",
        "website": "https://www.rocksolidchurchdemo.com",
        "email": "ted@rocksolidchurchdemo.com",
        "organization_id": "1"
      },
      "projects": [
        {
          "name": "Public Plugin",
          "description": "Help us develop the next awesome plugin",
          "keywords": ["public"]
        }
      ]
    }

**Comment by arranf** [comment] 2017-09-09 06:48
@cbump @trydyingtolive I like the reduced version of the project format. I'm keen to tie READMEs to the format. Would specifying the README path be a sane addition to the format?

**Comment by trydyingtolive** [comment] 2017-09-09 12:15
I don't think the README(s) need to be referenced. Anyone who is trying to make a good public repo will add them in stratigic places anyway. Single projects will have one in the root. Monoliths will have one in root and additionally should have one in each project. Ive seen some projects that had one at each subfolder.  Maybe if you wanted to use the text of the README for search functionality it could be useful, but even then it would be easy enough to find without further burden to repo owners.

I could be interested in some optiontional informational flags that would help with aggregation and display. Something like "experimental", "mature", "devlopment", "stable" etc to signal to developers the overal state of the project. That way you could signal to the scraper with little overhead and again the README takes care of all the fine details.

**Comment by arranf** [comment] 2017-09-09 12:28
I take your point. Let's leave the README's out.

The fear with some of those flags is that when you branch a `stable` branch might become `unstable` and not get updated. After a night's rest I'm not sure how much that will matter though given this is going to have an audience of developers - ultimately, user discovery will occur via the Rock Shop.

**Comment by cabal95** [comment] 2017-09-19 20:00
Since most of the issues seem to be related to repos with multiple branches, and the concepts of which branch do we check for the master file and then dealing with having multiple copies of that file floating around in different branches; I'll throw out this idea - though I will admit I'm not in love with it but it might simplify the branch issues.

The idea is to use the simplified plugin format that @trydyingtolive posted a few comments back, but store the data in a Wiki page with a specific format (though I think the scraper could pretty easily deal with slight variations via a regex). This provides a single place for the scraper to check, and a single place for the admin to edit. It also doubles to give us as other users a nice way to view the data rather than a JSON blob when viewing their repository contents.

I've done a quick mock-up here: https://github.com/ShepherdDev/rock-misc/wiki/TestProjectList, and you can see the raw markdown here: https://raw.githubusercontent.com/wiki/ShepherdDev/rock-misc/TestProjectList.md

Again, not entirely in love with this but it might solve enough other issues to be worthwhile.

**Comment by edmistj** [comment] 2017-09-19 20:58
This is some great collaboration. Think though we need to bring it to a head. I propose that we go with the plan outlined by Mark (https://github.com/SparkDevNetwork/Rock/issues/2418#issuecomment-328249212) 

Next steps is to create a Rock job in the Spark Rock repo to harvest the data from the repos tagged with `rock-rms`. Arran has volunteered to tackle that. We load the projects into the Spark Rock database and then create some pages to view them.

Chime in with any last feedback, otherwise we'll consider this enhancement closed.

**Comment by edmistj** [comment] 2017-09-22 23:45
Closing as this collaboration has achieved it's goal.

**Closed by edmistj** 2017-09-22 23:45 UTC
Labels: Type: Discussion, Type: Enhancement
