### ISSUE TITLE
Check-In Printing Delay

### ISSUE THREAD

**Issue by CarlaFletcher** [SparkDevNetwork/Rock#3594] opened 2019-03-19 18:03 UTC
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When printing from the iPad App, occasionally a check-in printer gets turned off or drops off the network. When this happens, the check-in kiosk will hang at the last page for a considerable amount of time, and family will finally just get redirected back to the home screen and no helpful message is displayed.

### Steps to Reproduce
1. Setup up check-in to use Family check in
1. Configure the kiosk to print from the client (to a printer that is not configured with valid ip address or is simply turned off)
1. Check in a family with 3 or more people
1. Confirm that the last page when labels should be printed just hangs for a long time and will get redirected back to home page.

**Expected behavior:**

An error is displayed quickly indicating that labels could not be printed. (a custom error would be nice)

**Actual behavior:**

No error is displayed

### Versions
* **Rock Version:** v8.6
* **Client Culture Setting:** EN-US

**Comment by cabal95** [comment] 2019-03-19 18:08
Just for reference, the reason the redirect happens is part of the pages built-in "idle redirect". I.e. if the labels _do_ print correctly and the person just takes the labels and walks away without clicking the `Finish` button, it's designed to send it back to the home screen so it looks like it's ready for use.  This same logic is causing the redirect while waiting for the printer to respond.

**Comment by cabal95** [comment] 2019-03-29 20:26
@CarlaFletcher Just to let you know I have getting this fixed on my task list. It might take a few weeks before I can get to it as we need to fix it in the iPad application itself and not Rock.

**Comment by cabal95** [comment] 2019-05-20 16:05
@jonedmiston In fixing this I ran into a slight UI issue I wanted to run past you before moving forward. The JAvaScript code provided by the Rock Server causes a standard iOS alert dialog (rather than a web-based dialog) to pop up, as seen below:

<img width="989" alt="Screen Shot 2019-05-03 at 11 15 28 AM" src="https://user-images.githubusercontent.com/1119863/58035638-11b65080-7ade-11e9-950d-a2e956e38984.png">

The problem is, if the message is not dismissed then when the redirect sends them back to the home page, it gets all wonky and thinks it's in portrait instead of landscape:

<img width="989" alt="Screen Shot 2019-05-03 at 11 15 48 AM" src="https://user-images.githubusercontent.com/1119863/58035687-2bf02e80-7ade-11e9-92f6-63c3d72dd689.png">

Once you dismiss the message AND click the `Start` button to move to the next page then it fixes the display. To fix this we would have to make a change in Rock web server, so wanted to check with you before we move forward with deploying this change.

The screenshots are from the simulator, but I just finished checking on my physical device and had the same UI results.

**Comment by jonedmiston** [comment] 2019-05-20 17:58
@cabal95 what would you propose for the fix?

**Comment by cabal95** [comment] 2019-05-20 18:03
I rather feel like it should display the same way an error on server-side printing displays (which I think is just an `<li>` list).  Either way, the primary question is:

Do we apply this fix to the iPad app so it will report errors and deal with the above UI quirk or do we update Rock and table this iPad app fix for 9-12 months until the new version of Rock (with the core UI fix) is released and out of early access.

**Comment by jonedmiston** [comment] 2019-05-20 18:05
I'm fine with the error changing on the server to not be a pop-up. This error should only occur rarely when there's a printing issue. If it stays as is for now I think it's ok. We're releasing updates pretty often.

**Comment by cabal95** [comment] 2019-05-20 18:10
Sounds good. I'll push out a new beta of the iOS app to our testers with this final error reporting change in the app and if that goes good we'll release.

**Comment by cabal95** [comment] 2019-09-09 15:51
Version 1.6 has this change and was released to the App Store some time ago but this never got closed.

**Closed by cabal95** 2019-09-09 15:51 UTC
Labels: Priority: Low, Status: Available, Status: Confirmed, Status: In Progress, Topic: Check-in, Type: Bug
