### ISSUE TITLE
Content Channel Filters break if Attribute name changes

### ISSUE THREAD

**Issue by jhawkzz** [SparkDevNetwork/Rock#1263] opened 2015-10-08 23:15 UTC
If a person filters on a particular attribute and it's saved, and someone then changes that attribute's display name, the person that filtered will no longer be able to work with the list. Visually, they can still adjust or remove the filter, and see the correct list, but if they click on an item to edit it, it will reference an item from the old filter list.

Example:
Content Channel with attribute "Campuses"
Person A filters Campus A
Person B updates the Content Channel's attribute to be named "Mobile Campuses"
Person A returns. The filter appears to be working correctly.
Person A removes the filter to see all items.
Person A clicks on an item 2.
Person A will actually edit the second item in the FILTERED list, which was specific to "Campus A".

Restoring the attribute name fixes the issue. Please note, the KEY for the attribute never changed.

**Comment by cabal95** [comment] 2018-03-15 17:59
Confirmed still an issue on prealpha. The key (pardon the pun) seems to be that the **Name** of the attribute changes but not the **Key**.

**Comment by arranf** [comment] 2018-06-25 16:27
@cabal95 Can you confirm which block is being referred to here? I've had a poke around and I think I'm missing which one it is.

**Comment by cabal95** [comment] 2018-06-25 16:30
If I recall, it was the Content Channel View block.

**Comment by KelleyLangkamp** [comment] 2019-10-24 22:15
Since the description references editing the content channel item, I tested this on both the Content Channel Navigation block and the Content Item List block. I wasn't able to replicate it on either block on v 9.1

**Comment by nairdo** [comment] 2019-10-24 23:27
Reported as resolved (in v9.x) in the #bugapalooza channel:

```
Kelley Langkamp (Rock Star) 3:16 PM
#1263 has apparently been fixed. Couldn't replicate on the demo server.
```

Please let us know by reopening if you feel this is closed in error.

**Closed by nairdo** 2019-10-24 23:27 UTC
Labels: Priority: Low, Type: Bug, bugapalooza: Is Needed?
