### ISSUE TITLE
Beta V10.1 Test - Data View Verify each DateTime filter (Greater Than, Less Than, Equal, etc.) against a date time person field attribute

### ISSUE THREAD

**Issue by debbiethurston** [SparkDevNetwork/Rock#4025] opened 2019-12-10 18:20 UTC
### Description
_no description of the bug was provided_

### Steps to Reproduce
1. Create Person Dataview
1. Add Filter Attendance at Campuses (we have one campus so as expected, there was no campus to select)
1. Select Attendance Count
1. Select 4
1. Select Date Range Last
1. Change Hours to Years

**Expected behavior:**

I expected that the criteria would "stick" ([Editor: "be saved" or "retained"])

**Actual behavior:**

The Criteria ~~would~~ does not remain after hitting save, and going back, and it did not show in my Filter Summary

### Versions
* **Rock Version:** Beta Testing V10.1
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment] 2019-12-17 00:28
Hi @debbiethurston , We have a fix which should show up on the [pre-alpha server](https://prealpha.rocksolidchurchdemo.com/page/145) this Wednesday but I'm not 100% sure there isn't a secondary issue going on.  If you can, would you take a look over here before Wednesday https://prealpha.rocksolidchurchdemo.com/page/145 (to verify you see the problem) and also on-or-after Wednesday to see if the problem is fixed? 

I would just hate closing this issue if there was another thing going on that we didn't quite see/understand.

**Comment by debbiethurston** [comment] 2019-12-17 14:01
Happy to test again.  Here are today results.  If I select a campus (which
FG has only one so the 10.1 did not give that option) then the criteria
holds.  If I do not select a campus then the criteria does not hold. I had
a feeling when I first saw it that it may have had something to do with the
campus change.  Persons with Attendance Range NO CAMPUS
<https://prealpha.rocksolidchurchdemo.com/page/145?DataViewId=18&ExpandedIds=C232>

**Closed** 2019-12-17 17:26 UTC
Labels: Fixed in v10.2, Status: Attention Core Team, Status: Confirmed, Topic: Reporting, Type: Bug

**Comment by nairdo** [comment] 2019-12-18 00:07
@debbiethurston Ok, that's good.  Now we know for certain that you can reproduce the issue on the pre-alpha server **_before_** [the fix](https://github.com/SparkDevNetwork/Rock/commit/64406a3c2ed3bed6c5f25c68f1cc8185a073fe47) is there. 

We're updating that server tonight so by tomorrow afternoon, you should be able to confirm that the problem has been addressed.  Please re-open this issue if you find it is NOT fixed.

**Comment by nairdo** [comment] 2019-12-18 00:57
@debbiethurston change of plans. I just found out that the pre-alpha update is going to be delayed (by a day perhaps) so I'll let you know when you can re-test again.

**Comment by nairdo** [comment] 2019-12-18 20:04
@debbiethurston We just updated the pre-alpha site.  It's ready if you'd like to test.

**Comment by debbiethurston** [comment] 2019-12-18 21:03
Nick, I am not able to get any results.  I will keep trying for a while.
The criteria is holding, but not giving me any results.

**Comment by nairdo** [comment] 2019-12-18 21:13
@debbiethurston  Just realize the attendance data on that system is quite old (2013-2018).  You might need to increase the length of your criteria to find anyone.

**Comment by debbiethurston** [comment] 2019-12-18 21:26
This works for those who have main campus only.  That is what was broken.
But if you want attendance for specific campuses, then that criteria is no
longer showing.

**Comment by nairdo** [comment] 2019-12-18 22:15
@debbiethurston Can you explain what you mean by this?:
> if you want attendance for specific campuses, then that criteria is no
longer showing.

You can reference this example** data view on the pre-alpha server: https://prealpha.rocksolidchurchdemo.com/page/145?DataViewId=17&ExpandedIds=C213
![image](https://user-images.githubusercontent.com/383807/71127838-10025780-21a9-11ea-8ce5-675df5af4c94.png)

(**I added a second campus to that system so you can explain what you're referring to.)

**Comment by debbiethurston** [comment] 2019-12-19 12:28
Ah, my bad then.  I did not see the additional campus and as a result, I
made an assumption that they were no longer showing up.  Based on the
changes I see, you have fixed the issue.
