### ISSUE TITLE
SMTP Transport Issues

### ISSUE THREAD

**Issue by asdf1nit** [SparkDevNetwork/Rock#5001] opened 2022-05-07 01:12 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words

When trying to open an attachment you get this error in outlook. Other clients have similar errors, Tested in Gmail and Apple Mail.
![Screenshot 2022-05-06 195659](https://user-images.githubusercontent.com/18108765/167231613-c0b8ccc9-9847-4ea1-a9d3-1155e2e05d55.png)

### Description

When sending an email in Rock with a file attachment some people can't open the attachment. The attachment file is not corrupted before sending the email. I can verify that the attachment is fine on the server via viewing it on the communication history page.

This issue might be related to using a SMTP transport. It has been posted here [Q&A Troubleshooting](https://www.rockrms.com/page/1287?Question=2618) We use SendGrid and after changing to the HTTP API we've had no problem. It should be noted that I did get it to work(attachments with SMTP) earlier this week, but I received similar reports after that. Each time we had the issue the email was being sent to 40+ individuals. I also noticed that the file attachment size was wrong on the email's that couldn't be opened.
 
### Steps to Reproduce

1. Create a new communication Wizard or Simple Editor.
2. Attach a file and send the email. 
3. Have the recipients check to see if it can be opened

**Expected behavior:**

The file should open

**Actual behavior:**

The file doesn't open.

### Versions

* **Rock Version:** [13.3]
* **Client Culture Setting:** [en-US]

**Comment by jonedmiston** [comment] 2022-05-10 23:00
We are closing this issue with a 'Considered But Closing' as we have been intending to deprecate the SMTP transports for performance reasons. It's possible it's their poor performance that is causing this issue in a multi-treaded environment it's likely that the SMTP code is what is corrupting the sending.

We'll increase the velocity of getting this messaging out to the community. Thanks for the debugging on this, some very good research and communication of the issue.

**Closed by jonedmiston** 2022-05-10 23:00 UTC

**Comment by bmurphy-dev** [comment] 2022-05-10 23:06
@jonedmiston I would like to note that we use Amazon AWS's SES service via SMTP and this would greatly impact our church's ability to send email out: https://aws.amazon.com/ses/

https://community.rockrms.com/recipes/171/aws-ses-email-smtp-transport-for-rockrms

There are several reasons I've been hedging my bets on waiting to move up to the v13 versions...I thought that I'd push up once 13.4 releases, but if this isn't going to be considered then I'm at a loss.

**Comment by jonedmiston** [comment] 2022-05-13 17:31
@bmurphy-dev Using the SES API would be the modern way of implementing an integration vs SMTP. Our belief is that the issue is caused by the parallelization added to improve the speed of sending (drastic improvement). 

I would suggest testing with the SMTP component's 'Concurrent Send Workers' setting set to 1 and the 'Send Communications' job's 'Parallel Communications' setting set also to 1. This should effectively remove the parallelization.

Let us know if that solves the problem. If so there may be some things we can do to force the SMTP transport to always be 1 in these use-cases.
