### ISSUE TITLE
Interactions show blank in v7.4

### ISSUE THREAD

**Issue by kyeschung** [SparkDevNetwork/Rock#3093] opened 2018-06-26 03:07 UTC
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * [X] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

After updating to 7.4, when you go to Interactions, the numbers show but everything is blank.
![image 2](https://user-images.githubusercontent.com/25948194/41886910-38f3fdec-78b3-11e8-8576-3a665502e94b.png)

### Steps to Reproduce

1. Go to Interactions
2. Click on Anything
3. See the blanks

**Expected behavior:**

You should see the pages that each user visited.

**Actual behavior:**

You see the user, numbers but no pages.

### Versions

* **Rock Version:** [7.4]
* **Client Culture Setting:** [en-US]

**Comment by cabal95** [comment] 2018-06-26 03:15
Confirmed on my 7.4 server by looking at interactions for the RockRMS site.

**Comment by edmistj** [comment] 2018-06-26 05:31
Can you confirm that the run once jobs have run on your instance. This can take up to 24hrs after the update. These jobs don’t run on the demo site. I’ll make an internal issue to get that addressed.

**Comment by cabal95** [comment] 2018-06-26 15:17
I'm assuming mine has run (and removed itself). I looked through the jobs and don't see anything that looks like it would be related to a upgrade job.

**Comment by garrettjohnson** [comment] 2018-07-02 15:45
Fixed in 8.0

**Closed by garrettjohnson** 2018-07-02 15:45 UTC
Labels: Priority: High, Status: Confirmed, Type: Bug
