### ISSUE TITLE
Default Location not retained on Location Attributes

### ISSUE THREAD

**Issue by edmistj** [SparkDevNetwork/Rock#2544] opened 2017-10-16 14:56 UTC
### Prerequisites
* [ X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
When adding a location attribute with a default value the default value is not retained.
![location](https://user-images.githubusercontent.com/548178/31618628-4f3af246-b247-11e7-9a39-b00eb73122a9.gif)

### Steps to Reproduce
1. Add a new attribute to a workflow of type location with a default value
1. After saving it note that the default value was not retained

**Expected behavior:**

Default value would be retained.

**Actual behavior:**

Default value missing

### Versions
* **Rock Version:** v6.8 and develop branch 
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by DavidBensen** [comment] 2017-11-20 19:36
This seems to be an issue adding any location value to a location attribute, not just the default value. Address, Point, and Geo Fence appear to work correctly.

**Comment by nairdo** [comment] 2019-03-29 16:14
Greetings.  We've been unable to reproduce the issue in the 8x branch and we've spent time time tracking down what we believe is the fix.  We believe it was addressed in this commit https://github.com/SparkDevNetwork/Rock/commit/08d7ed13cb25d1e86196237ce9f6a50aef895cd6. But feel free to re-open if you are able to provide reproduction steps.

**Closed by nairdo** 2019-03-29 16:14 UTC
Labels: Priority: High, Status: Available, Status: Confirmed, Type: Bug, x-Fixed in v7.1
