### ISSUE TITLE
Content Channel View Block, Lava Command 'RockEntity' not working

### ISSUE THREAD

**Issue by nateh777** [SparkDevNetwork/Rock#2179] opened 2017-05-05 18:50 UTC
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

ContentChannelView block does not turn on "RockEntity" support with block setting. Get the error "The Lava command 'rockentity' is not configured for this template."

![image](https://cloud.githubusercontent.com/assets/2990519/25759472/e9b79448-318f-11e7-909b-357eb17cc276.png)

### Steps to Reproduce

1. Configure Content Channel View block to Enabled Lava Commands "RockEntity"
2. Add `{% campus id:'1' %}{% for campus in campusItems %}{{ campus.Name }}, {{campus.Location.Street1 }}, {{campus.Location.City}}, {{campus.Location.State}} {{campus.Location.PostalCode}}{% endfor %}{% endcampus %}` to any content channel view lava.
3. Refresh page

**Expected behavior:** 

Rock entity to work and campus info to display. Works fine on 6.2.

**Actual behavior:** 

Got the error: "The Lava command 'rockentity' is not configured for this template." on 6.3.

### Versions

* **Rock Version:** Rock McKinley 6.3
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment] 2017-05-05 18:52
@nateh777 you'll have to enable RockEntity support in the General Settings > Global Attributes > Default Enabled Lava Commands before you can use Lava's RockEntity commands anywhere.  This is a safety precaution.

**Comment by cabal95** [comment] 2017-05-05 18:53
@nairdo Aren't the values defined in the block setting supposed to override the global default setting?

**Comment by nairdo** [comment] 2017-05-05 18:54
No.

**Comment by nateh777** [comment] 2017-05-05 19:56
@nairdo so how come it worked fine on 6.2? And why is there even the setting to enable lava commands on the content channel view block? I disagree as I don't want them globally.

**Comment by nateh777** [comment] 2017-05-05 20:01
@nairdo ironically both installs I tested them on do actually have it enabled globally as well. Can you re-open the issue? Or could you not reproduce it?

**Comment by cabal95** [comment] 2017-05-05 20:03
@nateh777 I tried to reproduce on my v7-alpha and couldn't. So either it's a 6.3 bug that has already been fixed in v7 or it is something specific to your install.  Can you try another block, such as an HTML Content block and see if you have the same problem there?

As for the global setting, the core devs are going to discuss it I think. It seems it might not be behaving the way they intended.

**Comment by nateh777** [comment] 2017-05-05 20:11
@cabal95 most likely v7 fixed it as I was able to produce on two totally separate 6.3 beta installs. Which is unfortunate if we have to wait until v7 for the fix once 6.3 gets released if it is still there. Was just trying to get it reported before 6.3 release (if they are going to release it?) 
Thanks!

**Comment by nairdo** [comment] 2017-05-05 22:44
@nateh777 We had a side discussion in the #develop channel.  Let me explain further.   Because of the tremendous security/risk implications of the ultra-powerful Lava 2.0 commands, the original design intent of the Global Attribute setting was to have a global safety switch that would _allow blocks_ to enable the Lava entity 2.0 commands.  (In other words, you could disable it system wide.)  At that point, you (or your Web Admin in the case of Html Blocks) then got to decide if you wanted it enabled on any particular block.

This is not something one can disagree with because it was the intent, although there may be a bug that is allowing the block to bypass the global setting.  This is not good.  We have this on our team discussion board to decide how we're going to proceed since as @cabal95 pointed out, when we fix the bug it would stop an installs Lava 2.0 commands from working unless the admin has enabled them in the Global settings.

**Comment by nairdo** [comment] 2017-05-12 17:58
I discovered that my information is from a very old discussion and the final design is to behave the way it is currently [documented](https://www.rockrms.com/page/749).  This issue is being re-opened as a bug.

**Comment by cabal95** [comment] 2017-06-12 19:02
This should be fixed in 6.6 - If it is not working after upgrading to 6.6 please request a re-open of this issue.

**Closed by cabal95** 2017-06-12 19:02 UTC
Labels: Fixed in v6.6
