### ISSUE TITLE
Safari back button displays loading animation.

### ISSUE THREAD

**Issue by trydyingtolive** [SparkDevNetwork/Rock#1987] opened 2017-01-24 17:27 UTC
* [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
Using Safari under certain circumstances pressing the back button on will cause the loading animation to appear and stay on screen.

### Steps to Reproduce

1. Using Safari on macOS or iOS select a group with members in it.
2. Click on a group member.
3. Press back.
There are other places that this happens, but this is the easiest to reproduce.

**Expected behavior:** 
The page should load and be usable.

**Actual behavior:** 
The page loads but is unusable and has the round orange loading animation.

### Versions

* **Rock Version:**1.6.1
* **Client Culture Setting** EN-us

**Comment by cabal95** [comment] 2018-07-02 22:53
This appears to be fixed in v8 by completely unrelated changes. I can no longer replicate it in v8.

If by chance this comes up again, the cause seems to be a unique way that Safari does history navigation. Other browsers can do it this way too, but most do not. Under certain circumstances (which are no longer the case in v8 for some reason), Safari will not re-load the page but save the entire thing in memory, and I mean _everything_, not just the DOM information. So when the back button is pressed, it simply puts that in-memory state back up front - which includes the spinner spinning.

This can be detected by the `pageshow` event and checking the `persisted` property to see if it's true. So if this becomes a problem again, it can be worked around with:

```javascript
  $(window).bind('pageshow', function (e) {
    if (e.originalEvent.persisted) {
      setTimeout(function () {
         $('#updateProgress').hide();
      }, 500);
    }
  });
```

**Closed by cabal95** 2018-07-02 22:53 UTC
Labels: Priority: High, Status: Available, Status: Confirmed, Type: Bug

**Comment by jacksojourn** [comment] 2022-07-29 13:54
I can replicate this now on the demo site. Should I create a new issue?

**Comment by jacksojourn** [comment] 2022-08-12 13:15
Checking in on this… thanks!
