### ISSUE TITLE
Group scheduler not displaying correctly

### ISSUE THREAD

**Issue by Jennfotp** [SparkDevNetwork/Rock#6028] opened 2024-10-03 11:21 UTC
### Description

Not rendering correctly

### Actual Behavior

We have 4 service times and 10 locations we are trying to schedule in our kids department. But often times the group scheduler will not accurately display who is in each time slot. It will show that no one is scheduled.  It appears to be a rendering issue as when I narrow down to just one service time it will show correctly.

### Expected Behavior

For it to show names of people scheduled 

### Steps to Reproduce

People
Group scheduling
Group scheduler

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v15.4

### Client Culture Setting

En-us

**Comment by chead4** [comment] 2024-10-03 16:22
@Jennfotp To assist us in investigating the issue, please include screenshots of the issue you're experiencing and a screenshot of your Group Scheduler block settings.

**Comment by Jennfotp** [comment] 2024-10-03 19:22
The first picture shows what is displayed when all service times are
selected and you can see how room 1 at 11 shows no one scheduled.  If I
filter down to just select the 11 am service then it shows correctly.

**Comment by chead4** [comment] 2024-10-03 20:12
@Jennfotp Hi there, thanks for getting back to me.  It doesn't look like your screenshots were attached.

**Comment by Jennfotp** [comment] 2024-10-03 20:13
They are attached as PNG files do you need in another format? I have
attached again as well.

**Comment by chead4** [comment] 2024-10-03 20:19
@Jennfotp I am not seeing them.  Can you email me directly with the attachments?  My email is: colleen@sparkdevnetwork.org

**Comment by chead4** [comment] 2024-10-04 16:05
Attaching screenshots received from Jennifer.

All service times are selected and you can see how room 1 at 11 shows no one scheduled.
![image](https://github.com/user-attachments/assets/4337e91a-b4b7-4138-a744-53f62beea286)

When filtering  down to just select the 11 am service then it shows correctly.
![image](https://github.com/user-attachments/assets/f9e05113-a904-4f1a-abf1-bf8d7e303bd2)

Block Settings:
![image](https://github.com/user-attachments/assets/1249f4cb-f5ec-4d60-bbe8-ebfa7715fbe8)

**Comment by chead4** [comment] 2024-10-04 16:20
@Jennfotp Hi Jennifer, thank you for providing the screenshots.  At this time, I'll be closing this issue since you've confirmed that you were not able to recreate on the demo site (v16.6).  Please reach out if you experience the issue on v16.6+ and I can reopen the issue.

**Closed by chead4** 2024-10-04 16:20 UTC
Labels: Not Yet Reproduced
