### ISSUE TITLE
Cancel Button on Family Pre-registration Block Does Nothing

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#4973] opened 2022-04-09 13:33 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description
On the Family Pre-Registration Block, nothing happens when you click "Cancel".

#### A Picture Is worth a Thousand Words

<img width="1725" alt="Screen Shot 2022-04-09 at 09 23 10" src="https://user-images.githubusercontent.com/23226974/162576129-16905706-b7c9-4806-bad4-873a059f0289.png">

### Steps to Reproduce

1. Go to`https://rockrmslatest.com/FamilyPreRegistration`
2. Click "Cancel" (you could also enter some text in one of the fields first, like FirstName).
3. See button does not do anything.

**Expected behavior:**

Since it seems the button serves  no purpose, it makes sense to me to either remove it or change it to "Back" to go back a page.

**Actual behavior:**

Button does nothing.

### Versions

* **Rock Version:** [v13.2, v14.0]
* **Client Culture Setting:** [en-US]

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1202111244125444">image.png</a>

**Comment by azturner** [comment] 2022-04-18 18:15
This looks like duplicate of [#3909](https://github.com/SparkDevNetwork/Rock/issues/3909)

**Comment by mikedotmundy** [comment] 2022-04-18 19:46
> This looks like duplicate of [#3909](https://github.com/SparkDevNetwork/Rock/issues/3909)

Yep sure is, I missed that @azturner.

**Comment by crayzd92** [comment] 2022-04-18 20:32
Closing as a duplicate of #3909

**Closed by crayzd92** 2022-04-18 20:32 UTC
Labels: Status: Confirmed
