### ISSUE TITLE
Family Analytics Attribute counts do not reflect how eRA calculates counts

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#4146] opened 2020-03-05 15:12 UTC
Reported on behalf of [[https://www.sunvalleycc.com/](https://www.sunvalleycc.com/) Sun Valley Church ]()

### Description
The "Times Checked-In (16wks)", "Times Given (52 wks)", and "Times Given (6 wks)" attributes seem like they should represent the values used by the eRA calculation since those values are what the [[https://community.rockrms.com/Rock/BookContent/5#eraestimatedregularattender](https://community.rockrms.com/Rock/BookContent/5#eraestimatedregularattender) eRA documentation ]() mentions as the criteria. However when calculating eRA it appears to use distinct weeks, but the attribute values are including all values (multiple check-in and gifts on same week).

For example, if a person check's into three services during the last three weeks, the "Times Checked-in (16wks)" value will show 9, but the person will correctly not be considered an eRA (they haven't attended at least 8 times in the last 16 weeks). It's confusing though when looking at the Family Analytics values to determine why a person is not considered an eRA when the numbers displayed seem to indicate that they should be.

### Steps to Reproduce
1. Go to Demo Site.
1. Create a new Batch for last Sunday's date.
1. Add 2 separate transactions for Ted Decker with last Sunday's date.
1. Repeat steps 2 and 3 but for the previous Sunday.
1. Run the Family Analytics Job.
1. Navigate to the Extended Attributes tab for Ted Decker

**Expected behavior:**

The "Times Given" attributes should show a count of 2 and Ted Decker would not be considered an eRA

**Actual behavior:**

The "Times Given" attribute shows a count of 4 and Ted Decker is still correctly not considered an eRA, but it's confusing since eRA requirement says that they've given at least 4 times in 12 months and once being in the last 6 weeks, and that's what the attributes show.

### Versions
* **Rock Version:** 9.4 and 11.0 
* **Client Culture Setting:** en-US

**Comment by azturner** [comment] 2020-03-05 15:52
In testing this more, it appears that when calculating eRA, the giving count is actually grouped by unique date/times of the gift, and attendance is grouped by sunday date and the The attributes values don't reflect any grouping.

**Comment by nairdo** [comment] 2022-09-02 00:31
We are looking at this for v14.1 and believe we have spotted a bug that could be the cause for eRA not detecting giving correctly.  But I wanted to clarify something mentioned above about the 'expected behavior'...

As mentioned in [the documentation](https://community.rockrms.com/documentation/bookcontent/5/235#eraestimatedregularattender), the "attendance" for Family Analytics is associated with the "Weekend Service".  So it is true that the weekend check-in attendance is weekly based, but the giving does not have to be weekly.  So to become an eRA:

   * Have given at least 4 times in 12 months, once being in the last 6 weeks
   * (or) have attended at least 8 times in the last 16 weeks

Which means even if someone gave several times two weeks ago and twice this week, they should be flagged as eRA by the Family Analytics job.

![image](https://user-images.githubusercontent.com/383807/188034143-dc27a81f-bb17-4a03-87d3-9d31b7c77ebb.png)

![image](https://user-images.githubusercontent.com/383807/188034390-d1247c1f-bc18-4246-aa29-864556b3034f.png)

**Comment by abpena1979** [comment] 2022-10-14 22:38
Fixed in 14.1 by Commit f563ff9. Manually closing after reopened for additional context.

**Closed by abpena1979** 2022-10-14 22:38 UTC
Labels: Type: Bug, Topic: UI, Topic: Reporting, Fixed in v14.1
