### ISSUE TITLE
Workflow Buttons in Email Not Functioning as Intended

### ISSUE THREAD

**Issue by sparkdevnetwork-service** [SparkDevNetwork/Rock#4360] opened 2020-08-20 16:26 UTC
**Description**

When working in Assigned Workflows and Forms when and 'Workflow Form Notification' is sent and 'Include Actions in Email' is checked off the action buttons that are intended to-do items within the workflow actually don't work in the intended functionality.

### Steps to Reproduce
1. Create a workflow with a form
1. Assign activity to a person
1. Create an activity with a form with the notification turned on and the include actions in email checked off
1. Have two different button commands (submit and deny as an example) that do different activities associated to them
1. Fire the workflow
1. Receive workflow form notification
1. Click on Submit, all it does bring the workflow up in a new window, it does the same thing as the View Details button, when it should do the assigned activity associated to it within the form activity.

**Expected behavior:**

The Submit or Deny buttons should process the assigned activity, instead, they both are working like the View Details button. 

**Actual behavior:**

The buttons acted like the View Details button

### Versions
* **Rock Version:** 10.3
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment] 2020-08-25 19:08
Duplicate of #4359

**Closed by nairdo** 2020-08-25 19:08 UTC
Labels: Type: Duplicate
