### ISSUE TITLE
Webview2 Windows Check-in App Responsiveness Issues on Surface Pro Devices

### ISSUE THREAD

**Issue by billdeitrick** [SparkDevNetwork/Rock#5534] opened 2023-08-01 15:09 UTC
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

This issue is being reported on behalf of Faithbridge Church in Spring, TX. 

After the upgrade from Rock 12.9 to 13.8 and the corresponding Windows Check-in App upgrade to v13 (MSI verison 1.13.8.0), the Windows check-in kiosk app is significantly less responsive on Surface Pro 5, 6, and 7 devices. This can be reproduced with a fully updated Surface Pro 7 device running Windows 10 or Windows 11, the Rock check-in app, and the latest Webview2 runtime available for each OS version, pointed at the Rock demo site.

Increasing the refresh interval from the default 10 seconds to 180 seconds shows some improvement, but the issue is still disruptive for check-in kiosk users.

The problem becomes worse the longer check-in is open and running. The longer the check-in app runs, the less responsive it becomes.

The problem is only present when running the Windows check-in app. When running check-in directly out of the Edge browser on the Surface device, the problem does not occur.

The issue is present for both touchscreen and external mouse inputs when the Surface's touchscreen is enabled. When the touch screen is disabled, the issue is no longer present with external mouse input.

The issue does not appear to be tied to server-side load, as it can be reproduced during minimal load and against the Rock demo site.

This seems to affect only the Windows check-in app; no other applications are affected. The problem occurs across a fleet of approximately 25 Surface Pro devices.

This problem was not present with the same fleet of devices using the previous IE-based version of the Windows check-in app.

### Expected Behavior

The Windows check-in kiosk app is responsive to a user's touch inputs on Surface devices.

### Actual Behavior

With the touchscreen enabled on a Surface Pro device, the Webview2-based Windows check-in app fails to register touchscreen inputs consistently. Inputs sometimes require multiple touches to register, creating an experience for the end-user that is noticeably degraded compared to the previous version of the check-in app.

A video of the issue [can be seen here](https://bemaservices-my.sharepoint.com/:v:/p/bill_deitrick/EUtQTqwqkOpLvyeKTOgECvgBBBF2VDejqOj0pQB8Fuiicg?e=Et79Po).

### Steps to Reproduce

Install the Windows Check-in App on a Surface Pro 7 device and download the Webview2 runtime. Point the check-in app at the Rock Solid demo site.

### Rock Version

13.8, 15.0

### Client Culture Setting

en-US

**Comment by nairdo** [comment] 2023-08-03 00:07
Hi @billdeitrick ,  We've been trying to reproduce this here with our Surface Pro 7 -- but haven't been able to, however we're using an older version of Windows 10 (which hasn't been updated to 20H2 yet).  

Would you be willing to share some other details/screenshots to help us compare what else might be different in our environment than yours?

**System Information**
<img width="900" alt="SystemInformation" src="https://github.com/SparkDevNetwork/Rock/assets/383807/0353b0c3-081f-4087-a24b-befa0b8b0524">

**Rock CheckinClient Properties**
<img width="284" alt="RockClientProperties" src="https://github.com/SparkDevNetwork/Rock/assets/383807/c1428ff5-6d75-48e3-adf1-a93d9e030323">

**Rock Check-in Client Folder**
<img width="745" alt="RockCheckinAppFolder" src="https://github.com/SparkDevNetwork/Rock/assets/383807/e359c96c-4a46-4fde-b282-d9f7e484b383">

...and... probably less helpful, this:

**Microsoft.Web.WebView2.WinForms.dll Properties**
<img width="317" alt="Screenshot 2023-08-02 164456" src="https://github.com/SparkDevNetwork/Rock/assets/383807/97eb77b5-c02f-40de-9d97-1eaa31ba6063">

**Comment by billdeitrick** [comment] 2023-08-07 17:48
Hey @nairdo! Thanks for looking into this! The team has provided the screenshots below:

<img width="1098" alt="Screenshot 2023-08-03 at 12 51 31 PM" src="https://github.com/SparkDevNetwork/Rock/assets/4174527/0c8c056f-770e-4e92-bad3-2702c1b821ac">

<img width="341" alt="Screenshot 2023-08-03 at 1 23 30 PM" src="https://github.com/SparkDevNetwork/Rock/assets/4174527/912d0298-f870-4bde-8a74-f09ab868a7a3">

<img width="839" alt="Screenshot 2023-08-03 at 1 26 24 PM" src="https://github.com/SparkDevNetwork/Rock/assets/4174527/9533d9ec-ca97-4499-8330-cfb31406109b">

<img width="380" alt="Screenshot 2023-08-03 at 1 26 56 PM" src="https://github.com/SparkDevNetwork/Rock/assets/4174527/ef3258ab-cece-4dd7-85e5-5cb9ee158533">

I've requested the additional screenshot showing the entry in the Programs and Features list and will upload it here once I have it.

Thank you!

**Comment by billdeitrick** [comment] 2023-08-07 21:30
Adding some additional information here. We have a recording of the issue occurring against the Rock Solid demo site from a Surface device running Windows 10 22H2. We've noticed that the missed inputs become more pronounced the longer check-in is running.

The issue is observed at the following timestamps in the video below: 0:36, 0:57, 1:32, 1:46, 1:49

https://bemaservices-my.sharepoint.com/:v:/p/bill_deitrick/EUKBtLddeLpIiL840sastc8B0VqrpasZ_MNk6I4_1DS7uQ?e=MeocIk

The check-in app was launched with the following configuration:

![IMG_0180](https://github.com/SparkDevNetwork/Rock/assets/4174527/92dc41b5-8620-47b0-982b-440ff1820151)

![IMG_0181](https://github.com/SparkDevNetwork/Rock/assets/4174527/c8027e5d-03d7-4277-95de-891e0728a760)

**Comment by bkwelborn** [comment] 2023-08-09 15:03
Cottonwood Creek Church in Allen, Texas is experiencing similar issues where our guests are unable to touch the start button or the input field where you type to search for your family. The issues is random in severity and sometimes causes guests to move to another tablet thinking the unit is not working. We are not having this issues with our iPad app. 

Rock McKinley 14.2

**Comment by nairdo** [comment] 2023-08-10 19:22
@bkwelborn & @billdeitrick Thanks for the additional details.  How often do your kiosks get restarted on a normal basis.  At the moment, since we're also not able to reproduce it and have not heard this happening from many others, we're still leaning toward this being a hardware/driver/WebView2 issue -- but we are going to review our use of the WebView2 wrapper code to make sure we're not doing something that could somehow lead to a symptom you're seeing. 

Also, have you considered involving Microsoft by starting an incident report with them?  (I know from previous situations when I worked at my church many years ago -- prior to Rock --, we got them involved with a Zebra printer issue.  It only cost us a few hundred dollars, but within a few days the Microsoft engineer was able to track the problem down to a bug in the Zebra printer driver.  They eventually suggested we switch to a 3rd party driver by Seagull and it resolved our issue.  It was quite impressive.)

**Comment by billdeitrick** [comment] 2023-08-22 13:49
@nairdo Thank you for your attention to this and for reviewing the WebView2 wrapper code.

We're receiving additional information that, at least in some cases, this _can_ be reproduced in the Edge browser in addition to the check-in app. So, it seems we're landing fully with this being a hardware-specific issue. We're continuing to pursue that angle; I will recommend the team consider opening a case with Microsoft and will post an update here if we have additional helpful information to share with the community.

**Comment by nairdo** [comment] 2023-09-11 18:49
> So, it seems we're landing fully with this being a hardware-specific issue. 

@billdeitrick  Thanks for your work and investigation into this issue.  We're going to close this _here_ since there is nothing we can really do about it.  But if you or your team open a case with Microsoft, please do post an update here (case #, etc.).  Thanks again!

**Closed by nairdo** 2023-09-11 18:49 UTC
