### ISSUE TITLE
Obsidian Registration Entry Registrar Summary Field Arrangement in Mobile

### ISSUE THREAD

**Issue by frogydiak** [SparkDevNetwork/Rock#5457] opened 2023-05-27 03:43 UTC
Tell us what you see!![image](https://github.com/SparkDevNetwork/Rock/assets/1373815/b8e9df96-5512-4b6d-8031-e4da3ef0496b)It is a UI issue and does not affect functionality but do you notice that the email is in the middle rather than after the Last Name.## Expected Behavior
The email address field should be after the Last Name.## Actual Behavior
The Email field is in the middle of First and Last Name fields.## Steps to Reproduce
View the Obsidian Registration Entry in mobile device.## Rock Version
14.2## Client Culture Setting
en-US

**Comment by Jon-Corey** [comment] 2023-10-06 19:00
This looks like a duplicate of https://github.com/SparkDevNetwork/Rock/issues/5334.

**Closed** 2023-10-06 19:02 UTC
