### ISSUE TITLE
TransactionEntryv2 Scheduled Transaction is Always Required

### ISSUE THREAD

**Issue by markewampler** [SparkDevNetwork/Rock#4746] opened 2021-07-26 15:26 UTC
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Transaction Entry v2 block does not respect the "Don't Allow" Scheduled Transaction block setting.  If you turn off Scheduled Transactions it will give you an error message when you try and process a scheduled transaction at the end with the follow error message:

Error occurred when saving financial scheduled transaction for gateway scheduled payment with a gatewayScheduleId of and FinancialScheduledTransaction with Guid of 43152fa2-e429-499a-bd27-cace34eb5882.

I dug into the c# and it looks like the function is returning a date value instead of a false value and it is throwing off the if statement that happens later in the code

### Steps to Reproduce

1. Make a TransactionEntryv2 Block and set it to "Don't Allow" scheduled transactions
2. You will have to fill out where to view scheduled transactions right below it.  Point it to a random page. (This should not be required as an aside unless Allow is turned on for scheduled transactions)
3. Try and process a transaction for 1$
4. It will allow you to input a Credit Card and your home address, but will fail when you click the button to 'process" the gift.

**Expected behavior:** 

It should process the gift and move on excepting a 1 time gift/charge

**Actual behavior:** 

It fails unless you turn on scheduled transactions, but that requires additional screens that we do not want for our use case. 

### Versions

* **Rock Version:** [12.4]  
* **Client Culture Setting:** [EN-US]

**Comment by markewampler** [comment] 2021-07-28 13:22
The problem lies in this function.  We overrode it on our production server to get what we wanted out of this block in our use case until it is resolved.

It looks like the function is expecting a FALSE value, but on FALSE it actually gives it a DATE/TIME return instead so it returns the TRUE value instead of the FALSE value later on when it is run.

 /// <summary>
        /// Determines whether a scheduled giving frequency was selected
        /// </summary>
        /// <returns>
        ///   <c>true</c> if [is scheduled transaction]; otherwise, <c>false</c>.
        /// </returns>
        private bool IsScheduledTransactionOLD()
        {
            int oneTimeFrequencyId = DefinedValueCache.GetId( Rock.SystemGuid.DefinedValue.TRANSACTION_FREQUENCY_ONE_TIME.AsGuid() ) ?? 0;
            if ( ddlFrequency.SelectedValue.AsInteger() != oneTimeFrequencyId )
            {
                return true;
            }
            else
            {
                return dtpStartDate.SelectedDate > RockDateTime.Now.Date;
            }
        }


        private bool IsScheduledTransaction()
        {
            
                return false;
            
        }

and later on here is the function called:

  if ( this.IsScheduledTransaction() )
            {
                var earliestScheduledStartDate = FinancialGatewayComponent.GetEarliestScheduledStartDate( FinancialGateway );
                if ( dtpStartDate.SelectedDate < earliestScheduledStartDate )
                {
                    nbPromptForAmountsWarning.Visible = true;

                    nbPromptForAmountsWarning.Text = string.Format( "When scheduling a {0}, the minimum start date is {1}", giftTerm.ToLower(), earliestScheduledStartDate.ToShortDateString() );
                    return;
                }
            }
            else
            {
                if ( dtpStartDate.SelectedDate < RockDateTime.Today )
                {
                    nbPromptForAmountsWarning.Visible = true;
                    nbPromptForAmountsWarning.Text = string.Format( "Make sure the process {0} date is not in the past", giftTerm );
                    return;
                }
            }

**Comment by nairdo** [comment] 2021-07-28 15:37
@markewampler I don't believe we were supposed to have shipped that TransactionEntryV2 experimental block yet (but we're checking to see how/when that might have happened).  Sorry about that.  We'll let you know when it's ready for prime-time.

**Comment by nairdo** [comment] 2021-08-17 00:15
Update: We confirmed that this block is not in the any shipped release.  It's a semi-experimental block that one organization was testing.  So, for now, we're just going to close this issue out since it should not actually be in any regular installation of Rock.

**Closed by nairdo** 2021-08-17 00:15 UTC
Labels: Status: Confirmed
