### ISSUE TITLE
Exception Across Rock: Index Was Outside The Bounds Of The Array

### ISSUE THREAD

**Issue by sam-crisp** [SparkDevNetwork/Rock#4934] opened 2022-03-07 20:24 UTC
Submitted on behalf of North Point Ministries 

### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### Screenshots
![image](https://user-images.githubusercontent.com/44408754/157111990-8d3e639a-415b-4246-a3b4-23510708e6a9.png)
Exception Detail

![image](https://user-images.githubusercontent.com/44408754/157109926-cc2e481f-6393-4c68-9e28-085ccc210047.png)
Exception Detail (another kind)

![image](https://user-images.githubusercontent.com/44408754/157111556-9bfdefdc-d7fe-4746-8745-e9807198586e.png)
Edit Family (add new address, verify address, update SmartyStreets API key in system cache, error)

### Description

RockCache.AddOrUpdateObjectCacheKey and RockCache.RemoveObjectCacheKey caused exceptions across the stack on a Sunday and led to a cascading list of issues that were eventually corrected with a rock restart. 

### Steps to Reproduce

1. ( Corrupted Web Service )
2. Open Family Edit block
3. Add new address
4. Save Button
5. See Error

**Expected behavior:**
In our example, Edit Family block failed to process when the SmartyStreets API Key couldn't be removed from the cache with the RockCache.RemoveObjectCacheKey method.

Rock would clear cache or gracefully error out, probably triggered by a try-catch block on the[ AddOrUpdate code](https://github.com/SparkDevNetwork/Rock/blob/2e8abada958420c2ff57ce21e7f1b638fbc7dde8/Rock/Web/Cache/RockCache.cs#L759) and the [Remove code](https://github.com/SparkDevNetwork/Rock/blob/2e8abada958420c2ff57ce21e7f1b638fbc7dde8/Rock/Web/Cache/RockCache.cs#L775).
 
**Actual behavior:**

Edit Family block saved address changes but errored out for the end user. 

### Versions

* **Rock Version:** [12.2]
* **Client Culture Setting:** [en-US]

**Comment by cwomack** [comment] 2022-03-09 19:46
For anyone experiencing this issue, there's a possibility that Rock was still recompiling when you were viewing this (or any page) where the exception occurred.  A restart of Rock would normally be how this is resolved. 

We will close this issue since it cannot be reproduced but feel free to comment if anyone experiences this and has reproduction steps.

**Closed by cwomack** 2022-03-09 19:46 UTC
