### ISSUE TITLE
Address is not a required field for a Business, but leaving it out breaks rock

### ISSUE THREAD

**Issue by BrentPirolli** [SparkDevNetwork/Rock#3980] opened 2019-11-05 18:22 UTC
### Prerequisites
* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

We found our dev server running 9.3 is unable to show the https://rock.rocksolidchurchdemo.com/page/282 page. Some of this was due to business names in a conversion having bad characters (like &#39 instead of an apostrophe. Once we cleared those, we still were unable to load the page without it throwing an exception. I then started playing on the demo site and found if I added a new business and only entered a name (or any other info and left the address blank) it would allow me to add the business, but would now no longer load the business list block on https://rock.rocksolidchurchdemo.com/page/282 without throwing an exception. We found if we then converted the fake business to a person the directory page loaded fine. We could then load their person record, give them a work address, and convert them back to a business and the directory loads fine at that point.

So I guess the solution is to mark "address" as a required field for adding a business. You should also check that it is present to convert a record from a person to a business. And lastly, maybe fix it so the Business Listing block doesn't throw an error if the address is blank on existing entries.

### Steps to Reproduce

1. Go to https://rock.rocksolidchurchdemo.com/page/282
2. Click on add a business (or go here: https://rock.rocksolidchurchdemo.com/page/283?businessId=0)
3. Leave the address blank and submit the business
4. Try to repeat step 1 and see the exception.
5. To clear it, convert the business to a person here: https://rock.rocksolidchurchdemo.com/convertbusiness
6. Edit the record to add a Work Address and convert them back to a business.
7. See that step 1 now loads again.

**Expected behavior:**

It wouldn't throw an exception when loading the Business Listing block if addresses are blank.

**Actual behavior:**

It throws an exception.

### Versions

* **Rock Version:** Rock McKinley 9.3 (1.9.3.2)
* **Client Culture Setting:** en-US

**Comment by darringraham** [comment] 2019-11-05 20:00
I verified these on our install of Rock v9.3. 
1. If there is a non-standard apostrophe, Rock returns the exception referenced. If I remove the suspect character from the Person.LastName field the business is searchable. And if I add an apostrophe back it, all is still well and it is searchable.
2. I cannot search for a business that doesn't have an address. But if I go straight to that page (after looking up the Person.ID for the business in the Person table, I can add an address to that business and then it is searchable.

**Comment by MichaelAllen** [comment] 2019-11-06 13:24
This bug has been fixed in 9.4 (duplicate of https://github.com/SparkDevNetwork/Rock/issues/3954)

**Closed** 2019-11-06 14:58 UTC
