### ISSUE TITLE
Report Total Giving - To Date Auto Populates With Date When Typing In Date

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#1492] opened 2016-04-13 09:04 UTC
In the To Date on the Report Total Giving To Date Range field, if the field is empty, and you click into the field, and type '1' the field auto-populates with today's date.  You then have to clear the date field to enter a date.   

If you come back to the report settings and edit them, and click into the To Date field (into the middle part of the date (your day, our month in NZ) or the year part, and type anything or press delete, the date is auto set to today's date, or some other strange date.  Is this intended functionality?  This does not happen on the From Date.

![totalgiving7](https://cloud.githubusercontent.com/assets/4658177/14487836/f7be47d8-01b8-11e6-955f-9faa51ec17f7.jpg)

![totalgiving8](https://cloud.githubusercontent.com/assets/4658177/14487838/fb478c8e-01b8-11e6-99c4-cd99d81c81c2.jpg)

**Comment by mikejed** [comment] 2018-03-28 02:38
Confirmed on 6.x

By v7 though, the date range control was changed- the dates no longer try to auto-fill, and this behavior is not observed. I confirmed that the new behavior continues on the v8 prealpha (that is, the issues you point out are not observed).

Closing this issue since the issues have been independently indirectly resolved.

**Closed by mikejed** 2018-03-28 02:38 UTC
Labels: Fixed in v7.0, Status: Confirmed, Topic: Reporting, Topic: UI, Type: Bug
