### ISSUE TITLE
Cannot log into Windows Check Scanner Program

### ISSUE THREAD

**Issue by atorrance** [SparkDevNetwork/Rock#4475] opened 2020-10-27 17:29 UTC
### Description
The new version of the Windows Check Scanner External program in  V11 cannot be logged into. The same error happens on our server, on pre-alpha, and on the demo site. 

### Steps to Reproduce
1. Install the new version of the Windows Check Scanner program
1. Enter the correct credentials and try to log in. 

**Expected behavior:**

I should be able to log into the program.

**Actual behavior:**

I receive an error, the same on each server tried with correct credentials. 

### Versions
11.2, 11.3, and 12.0 en-US

[error](https://user-images.githubusercontent.com/34725020/97338823-3462a200-1858-11eb-95cc-667213b4fbee.png)

**Comment by ethan-sparkdevnetwork** [comment] 2020-11-16 17:37
Hello @atorrance!

I think I know what is happening but I can't reproduce it locally. Can you try adding an Assembly Binding to your app.config on the computer running the check scanner? The file is in Check scanner folder. If you're not technical then this sounds harder than it actually is. All we need to do is backup the current app.config file (copy and paste it somewhere) and then open the file using Notepad and make sure the the text matches below:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.1" />
  </startup>
  <appSettings>
    <!-- set the value to specify the full path and file name of the log file. Must be an existing directory. Leave blank to not log.-->
    <add key="DebugLogFilePath" value="" />
  </appSettings>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-11.0.0.0" newVersion="11.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Http" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```
Let me know how that works and if a different problem occurs (e.g. crashes without an error). If you do still have a problem can you attach the contents of the app.config backup?

Thanks,

Ethan

**Comment by atorrance** [comment] 2020-11-23 00:21
@ethan-sparkdevnetwork I replaced the contents of the file with the above and the error is slightly different now: 
![error2](https://user-images.githubusercontent.com/34725020/99921358-da8ab600-2cf7-11eb-9622-fad6f8a6ec35.png)
Here is what the original code looked like in the file:

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.1" />
  </startup>
  <appSettings>
    
    <add key="DebugLogFilePath" value="" />
  </appSettings>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-11.0.0.0" newVersion="11.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>

**Comment by ethan-sparkdevnetwork** [comment] 2020-11-24 17:23
That looks like the same error. Was the checkscanner running when you made the change to CheckScannerUtility.exe.config? If it was can you try it again but stop the checkscanner first.

In the bin folder there is a file called System.Web.Http.dll. Can you give me the version for that file? Right-click and select properties. Then click on the Details tab, the file version should be the third item.

**Comment by atorrance** [comment] 2020-12-08 14:57
Sorry for the delay, the check scanner was not running at the time I made the change.  The current version is 5.2.30128.0

**Comment by atorrance** [comment] 2020-12-10 20:27
I downloaded and ran the check scanner program on another computer that has a check scanner set up and it was working correctly so this can probably be closed now. Thanks

**Comment by nairdo** [comment] 2020-12-15 22:48
Thanks for the update @atorrance!  We'll close this out now.

**Closed by nairdo** 2020-12-15 22:48 UTC
