### ISSUE TITLE
Active=false save not allowed on blank Email Transport SMTP

### ISSUE THREAD

**Issue by joshcrews** [SparkDevNetwork/Rock#4047] opened 2020-01-03 16:11 UTC
### Description
I added a Mailgun transport, and wanted to turn off the SMTP transport even though I don't have any values filled out there. I'd love to have it clear that there's only one email transport active.

![Screen Recording 2020-01-03 at 10 03 AM](https://user-images.githubusercontent.com/87632/71734028-9311e780-2e10-11ea-8b9c-1327a31cee07.gif)

### Steps to Reproduce
1. Go to Communication Transports
1. Click on SMTP
1. Toggle to active false
1. Save

**Expected behavior:**

No required field objections to saving in Active False mode

**Actual behavior:**

Server input field required

### Versions
* **Rock Version:** 1.9.4.1
* **Client Culture Setting:** en-US

**Comment by joshcrews** [comment] 2020-01-03 20:48
Update: the inability to turn off the SMTP server caused a job to fail. I hooked up a Group to send a welcome email on joining, and a Job failed because the SMTP host was not specified

<img width="1311" alt="Image 2020-01-03 at 2 44 55 PM" src="https://user-images.githubusercontent.com/87632/71748364-ed726e80-2e37-11ea-8ddf-1402e38e76f7.png">

Now, I found a workaround, just entered the word "none" for server, the toggled Active=false, and it went through. But it'd be nice for future users to not need to discover that workaround

**Comment by cabal95** [comment] 2020-01-03 22:06
What you probably need to do is set the `Server` property to something, like `localhost` and then it should let you switch it to Inactive. The core team can decide if that is something that they want to address - but it's technically working as it should be (not letting you save if a required field is not filled in). Not sure if there is a way to override that required field logic when trying to inactivate something.

**Comment by jonedmiston** [comment] 2023-09-27 23:10
Closing as this is intended behavior.

**Closed by jonedmiston** 2023-09-27 23:10 UTC
Labels: Type: Enhancement, Priority: Low, Topic: Rock Internals
