### ISSUE TITLE
Issues with printing out Contributions

### ISSUE THREAD

**Issue by Jcarterigotfaith** [SparkDevNetwork/Rock#3112] opened 2018-07-07 22:11 UTC
Hello, for some reason when I go to print out the semi-annual contribution statement, the statement does not reflect event registrations. How can this be fixed?? Is there a setting that needs to be changed?

(Edited by @cabal95 to make the details show)

### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

A clear and concise description of what the bug is, include screenshots if applicable.

### Steps to Reproduce

**Expected behavior:**

**Actual behavior:**

A description of what actually happened.

### Versions

* **Rock Version:** [Enter Rock version here]
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by edmistj** [comment] 2018-07-07 22:50
@Jcarterigotfaith  your details appear to be missing.

**Comment by Jcarterigotfaith** [comment] 2018-07-07 22:58
I do apologize, I have updated the comments to reflect. Please let me know if I need to provide anything else.

**Comment by mikejed** [comment] 2018-07-09 03:23
I believe that the contribution statements only print transactions marked as a contribution, which registrations are not by default.

This should be "working as intended" since the contribution statements are intended to be tax-deductible transactions for tax purposes (which registrations are not)... Unless you are asking for an enhancement to be made to the software to provide the option to include transactions not marked as contributions.  But I think that the client behavior kind of keeps people out of trouble though, so they don't try to claim registrations as tax deductible.

Perhaps, if you wanted to include all transactions a person makes in a printable report, you could create a data view with a dynamic report (to select the person) and use a merge template on that... (just my thoughts).

If the core team closes this as "not a bug", please consider posting a question in the Q&A forums at https://www.rockrms.com/Rock/Ask

**Comment by ajfick** [comment] 2018-08-01 22:18
@mikejed I believe the Statement Generator includes a checkbox option to display Event Registrations. If this is not an intended behavior then maybe another fix would just be to remove the Event Registrations option in the Statement Generator as it is misleading. 

Also, depending on how your church does event registrations and the types of events that are being registered for Event Registrations can be tax deductible. For example our church takes some of the cost of a missions trip up front at registration (to make sure that people are very serious about going and willing to raise the money). So for those registrations they are considered deductible because they are part of the payment/travel expenses. Yet, even if the Financial Account that the registration points to is marked as Tax Deductible, the Statement Generator will ignore them. 

> According to IRS Publication 526, “Generally, you can claim a charitable contribution deduction for >travel expenses necessarily incurred while you are away from home performing services for a >charitable organization only if there is no significant element of personal pleasure, recreation, or >vacation in the travel.”  So, payments by participants are deductible as charitable contributions if >the trip involves "no significant element of personal pleasure, recreation, or vacation". This applies >whether the trip expenses are paid directly by the participant (for example, purchasing a plane >ticket) or indirectly by making a payment to the religious organization, with the organization paying >the travel expenses.

**Comment by mikejed** [comment] 2018-08-01 22:52
@ajfick thanks for the further details. I must confess, I was stopping at "Step 4" unintentionally and thinking that the issue was that the transactions were not marked as `Transaction Type=Contribution` ; previous behavior was that only contributions would be included.

However, I ran through once more in order to respond here, and found that in Step 6, `Transaction Types` is now an option. That renders my previous comment moot.

I can confirm however, that selecting `Event Registration` and being careful to check the correct payment type (non cash:credit card) and non-tax-deductible account (middle school camp) in the statement generator while asking for my wife's statement, and checking `Type=Event Registration` results in both of the transactions I know her to have made, being outputted in the statement generator.

Therefore, I don't believe there is a bug; event registrations are being included in the statements generated when they meet the other selected criteria.

I'm going to close this now. @Jcarterigotfaith please make sure that you've downloaded the latest version of the statement generator from your own Admin Tools -> Power Tools -> External Applications page, as it has the option to include event registrations and not just contributions. Please let me know if there are any other questions about this.

**Closed by mikejed** 2018-08-01 22:52 UTC
