### ISSUE TITLE
Editing/Saving a Step Type sets the 'Order' value to Zero

### ISSUE THREAD

**Issue by bezalelBU** [SparkDevNetwork/Rock#5200] opened 2022-10-20 19:50 UTC
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

![image](https://user-images.githubusercontent.com/59073587/197031484-e7ee2b24-74ba-43d2-97e3-7a94482da6ac.png)
![image](https://user-images.githubusercontent.com/59073587/197031559-ab6270c9-0354-4736-9f29-d3d59ceb76d9.png)
![image](https://user-images.githubusercontent.com/59073587/197031361-63219fba-a675-4d96-9ac8-cdfc94b0a552.png)

### Description

When a step type is edited and saved, the 'Order' property gets set to '0'. 

### Steps to Reproduce

1. Go to 'https://rock.rocksolidchurchdemo.com/steps/type/2'
2. Click on 'Edit'
3. Click on 'Save'
4. Go to 'https://rock.rocksolidchurchdemo.com/admin/power-tools/sql'
5. Paste and run: 
    `SELECT ST.Id, ST.[Order]
    FROM [StepType] ST 
    INNER JOIN [StepProgram] SP ON SP.Id = ST.StepProgramId
    WHERE 
    SP.Id = 1`
7. See error in Order column

**Expected behavior:**

Editing/saving the step type should not affect the order of the step.

**Actual behavior:**

Editing/saving the step type replaces the value of the order of the step with '0'.

### Versions

* **Rock Version:** 13.6
* **Client Culture Setting:** en-us

**Comment by NuclearTacos** [comment] 2022-11-02 14:36
I've also observed this issue and can confirm that it happens also in 13.7 and 14.0

**Comment by NuclearTacos** [comment] 2022-11-02 14:39
Digging deeper, it seems that this is a duplicate of a closed bug (it's easy to forget, but I recommend clearing `is:open` from the search so that you can find bugs if they're closed).

Duplicate of #5152

**Closed** 2022-11-02 14:58 UTC
