### ISSUE TITLE
Lava problem switching between Code Editor and Visual Editor

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#3308] opened 2018-09-29 00:58 UTC
Same issue as #3087 - can be closed as a duplicate
Related to #2927 ?

### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The lava {% for PhoneNumber in Person.PhoneNumbers %} {{ PhoneNumber.Number }}, {% endfor %}
prevents the email Editor from returning from the Code Editor back to the Visual Editor.

Once you're stuck - there is no way to recover except to delete that lava.

This affects both the Simple Editor and the new Editor.

### Steps to Reproduce

Create an email using the either Simple Editor or the new email editor.  Add the following Lava:

{% for PhoneNumber in Person.PhoneNumbers %} {{ PhoneNumber.Number }}, {% endfor %}

(which is test inserted when you select Phone/Number from the list of Person fields)

Switch to the Code Editor, and then attempt switch back to the visual editor.  

The screen gives an error message "The markup contains content that may not be compatible with the visual editor" and will not return to the visual editor.

![lava1](https://user-images.githubusercontent.com/4658177/46238978-38583780-c3e6-11e8-81af-db0c692207ca.jpg)

**Expected behavior:**

The lava should not prevent the switch between the Visual Editor and the Code Editor in the Simple Editor.

**Actual behavior:**

Cannot return to Visual Editor from Code Editor with the lava
{% for PhoneNumber in Person.PhoneNumbers %} {{ PhoneNumber.Number }}, {% endfor %}

### Versions

Rock Version: Rock McKinley 8.3 (1.8.3.36)
Client Culture Setting: en-NZ

**Comment by Tschrock** [comment] 2018-10-08 17:42
Closing as a duplicate of #3087

**Closed by Tschrock** 2018-10-08 17:42 UTC
