### ISSUE TITLE
Split checks to Fundraising Participants causes error

### ISSUE THREAD

**Issue by ajfick** [SparkDevNetwork/Rock#3009] opened 2018-05-21 22:34 UTC
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

If a check is donated to the church and split between more than one fundraising account, the individuals who split the amount of that check will seem to have received ALL of the check in the transaction entry block. However, the fundraising progress bar will display correctly. 
 
### Steps to Reproduce

1. Scan a check into Rock (For explanation purposes we'll say it's 100$)
2. During the "Match Transactions" process split the 100$ check equally into two different Fundraising Accounts
3. Enter Fundraising matching and assign each of the two halves of the check to a different Fundraising Individual.
![fundraising matching page](https://user-images.githubusercontent.com/19314419/40333186-38431bac-5d25-11e8-8854-f006ab1d1634.png)
4. View One of the Fundraising individual's Participant Pages and see the correct fundraising amount remaining in the progress par. 
5. Click to make a donation to the individual and note that the "Amount Remaining" is incorrect because the check donation will display as if the ENTIRE check was donated to each participant instead of half of the check amount.
![fundraising amount remaining error](https://user-images.githubusercontent.com/19314419/40333170-202b5e76-5d25-11e8-9914-394ee7771595.png)

**Expected behavior:** 

A check that is split and partially donated to more than one individual in fundraising groups will correctly display the amount donated. 

**Actual behavior:** 
A check that is split and partially donated to more than one individual in fundraising groups displays as if the whole check was donated to each person. This throws off the "Amount Remaining" that displays in the "Transaction Entry" block while making a donation and could cause some people to not donate to a person who still needs funds. 

### Versions

* **Rock Version:** 7.3
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by cabal95** [comment] 2018-05-22 16:42
@chrisfunk There are lots of other areas in Fundraising that don't support split checks. I think this particular would be seen as addressing the entire functionality of Fundraising needing to be modified to support split checks.

**Comment by ajfick** [comment] 2018-05-23 20:21
@chrisfunk Agreed. I must have searched for fundraising when looking to make sure I wasn't duplicating anything. 

Also, @cabal95 I'm not sure I follow that.. Because other areas of Fundraising display this information correctly like the Fundraising Participant Progress Bar. So it seems as though the logic is there for some blocks already.

**Comment by cabal95** [comment] 2018-05-23 22:10
I just meant it's not a duplicate issue, though I may have misunderstood Chris's meaning.

**Comment by ethan-sparkdevnetwork** [comment] 2018-06-07 21:38
This looks like a duplicate of 2933. I setup AJ's scenario and got correct dollar amounts for participants in the same account and different accounts.

**Closed** 2018-06-07 21:39 UTC
Labels: Fixed in v8.0, Topic: Finance, Type: Duplicate
