### ISSUE TITLE
Directory Block Always Displays Phone Types

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#1983] opened 2017-01-19 20:59 UTC
When un-checking phone types to include in the Directory block, unchecking all of them doesn't save and reverts back to all being checked. Verified on the Rock demo site.
1. Navigate to the new Directory page
2. Edit block settings
3. Uncheck all phone types
4. Refresh page and all phone types remain

No phone types should be displayed.
 

### Versions

* **Rock Version:** [1.6.1]  
* **Client Culture Setting** [en-US]

**Comment by cbump** [comment] 2017-03-24 15:34
This can be easily fixed by removing the default value of having all three checked on line 54 of PersonDirectory.ascx.cs.  Unfortunately, that breaks the default value but that's the easy fix.  A more complicated (probably correct) fix is to somehow figure out a way to differentiate between when nothing is checked and a empty string value being passed.  If nothing is checked, the DefinedValueField automatically uses the default value which is all 3 being checked. . .

**Comment by cabal95** [comment] 2017-03-24 21:57
This is a deep core level issue. The problem is in Rock.Attribute.Helper.LoadAttributes(), around line 580.

When loading attributes, it first tries to load all the values from the database. Then it checks all the keys and if any value for a key is null (not found in database) it sets it to the attribute's default value. Then it checks if the value is "null or whitespace" *and* checks if the attribute default value is _not_ null or whitespace, then it sets the value to a default value.

In short, currently there is no way to have an attribute provide a default value that can be erased by the user. The user can _change_ the default value, but they cannot erase it. So if a block had a TextField attribute called "Notice" that they displayed at the top of the block IF it was a non-empty string and they provided a default value ("Please be sure to fill out all fields carefully"). The intention would be that the user could erase the text if they didn't want a notice displayed. But the Helper code would ensure there is always a notice text by using the default value even if the user blanks it out.

One potential fix would be on line 578 of Helper.cs to change the `else` to `else if ( attribute.IsRequired )` - thus only setting the default value when null (no value has ever been set yet) or if the attribute is marked as required. But this would be a pretty massive change to functionality across the board with some major impact potential. Having said that, to me that seems like the logical solution but I don't know if now is too late to make that change as it could have some pretty big impact to plugins, workflows, person attributes, group member attributes, etc. etc. etc. etc.

For the Directory block I see two fixes:
1) Do as @cbump says for the easy fix and just change the default value to be blank. This would mean a user would have to intentionally go in to the block settings and turn on any phone types in the future.
2) Add another block setting called "Hide Phones" that is a boolean with a default of No that allows the user to hide all the phone numbers.

**Comment by azturner** [comment] 2017-03-25 01:12
Taking the easy route. There's a migration that sets the value to have all three, so setting the default to blank won't disable the value for existing blocks.

**Closed** 2017-03-25 01:24 UTC
Labels: Fixed in v6.3
