### ISSUE TITLE
Family Pre-Registration BirthDate

### ISSUE THREAD

**Issue by markewampler** [SparkDevNetwork/Rock#3928] opened 2019-10-01 21:55 UTC
### Prerequisites
* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When using the Family Pre-Registration block the Date value does not have flavor text or description text of what it is expecting and if a user types in just numbers for example a birthday of 01/01/2010 typed as 01012010 does not produce a valid result, but the block does not kick it back as a invalid entry upon clicking submit.  So people are inputting values that are not correct, but they have no idea that it is not working.

### Steps to Reproduce

1. go to https://rock.rocksolidchurchdemo.com/FamilyPreRegistration
2. Input different date formats.  It does accept "May 3rd 2010" and "05/03/2010" but does not accept straight numbers without delimiters such as 05032010
3. See if the newly created person has a date value based on your input values.

**Expected behavior:** 

Either translate the date, or give them a red this is not an expected value type thing around the box

**Actual behavior:** 

It accepts the input and makes them think everything is a ok.  It creates the person, but does not give them a birthdate.

### Versions

* **Rock Version:** [v9.2]  
* **Client Culture Setting:** [EN-US]

**Comment by JimMichael** [comment] 2019-10-01 22:13
This looks like a duplicate of https://github.com/SparkDevNetwork/Rock/issues/3651

**Closed** 2019-10-02 13:45 UTC
