### ISSUE TITLE
v10/10.1 alpha Delete Group Member - Spinner Never Goes Away

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3994] opened 2019-11-13 21:52 UTC
### Description

After upgrading a copy of production db from 9.4 to v10alpha, deleting someone from a group works, but the "spinner" (or whatever you call it) animation never goes away and you have to refresh the page to get rid of it. Reverting back to 9.4 and the animation goes away upon delete just as expected.

### Steps to Reproduce

1. Go to group viewer
2. Delete someone from a group
3. Watch it spin
4. User _is_ successfully deleted, though, so this appears to be a cosmetic issue.

Here's an example video https://drive.google.com/file/d/175i4nGwR8alyhgdk_e877W8gSH56-msO/view

**Expected behavior:**

Animation would go away upon deleting a group member 

**Actual behavior:**

Animation stays forever (well, I tired of watching it after 10min or so). This also happens if I further upgrade to v10.1alpha.

I was not able to dupe this on v11 (prealpha server) but it's repeatable-enough and weird-enough that I thought I should report it. Something about our database is not playing well with deleting group members on v10.

### Versions

* **Rock Version:** v10.0/v10.1alpha

**Comment by cabal95** [comment] 2019-11-13 21:55
I just re-tested on my v10.1 alpha and cannot reproduce - BUT I also never see the spinner because it happens fast enough. Maybe check the java console or network tab to see if there are any errors as well to provide more hints?

**Comment by JimMichael** [comment] 2019-11-13 22:21
Ok, more info... I only noticed this after A/B testing our production Rock vs. this updated copy... but on v10, it's not ASKING if I want to delete the group member like it should. It just "does it" and puts up the spinner. I also see this error in the console that I do not see on prod
![image](https://user-images.githubusercontent.com/3903408/68809503-b0f17600-0631-11ea-8508-3d3a3f59eab8.png)

**Comment by JimMichael** [comment] 2019-11-13 22:31
Also, I'm now noticing that ReferenceError is happening just by going to the Group Viewer page (not clicking on anything) and it messes up the page to the point that the leftside menu no longer works. Have to click the Rock logo upper left to get out of it as the entire menu is broken just by visiting the page.

**Comment by gonemob** [comment] 2019-11-14 17:16
I'm able to reproduce on pre-alpha ... https://rockrmslatest.com/page/113?GroupId=214&ExpandedIds=41.  Go to the GroupMemberList block > Custom Grid Options and 'Enable Sticky Header'.

Fixing that raised another issue on our server, `n.stickyTableHeaders` isn't a function. See last screenshot. 

![Screen Shot 2019-11-14 at 11 09 03 AM](https://user-images.githubusercontent.com/13141251/68879559-3bd47e00-06cf-11ea-9ad4-e0f889926700.png)

![Screen Shot 2019-11-14 at 11 11 15 AM](https://user-images.githubusercontent.com/13141251/68879738-848c3700-06cf-11ea-8ec0-95407636c9a7.png)

![image](https://user-images.githubusercontent.com/13141251/68880001-0b411400-06d0-11ea-9e5e-f4cd7474cd88.png)

**Comment by gonemob** [comment] 2019-11-14 17:46
The fix that Garrett added to line 22 of coreListner.js needs to be brought up to line 10.  `['position']` rather than `[position]`.  That will introduce the next error, the `.stickyTableHeaders()` isn't defined yet.

![image](https://user-images.githubusercontent.com/13141251/68882213-61b05180-06d4-11ea-977c-130375f42b70.png)

**Comment by JimMichael** [comment] 2019-11-14 18:39
Ok, so to summarize: It looks like the issue I reported only occurs if _Sticky Headers_ is enabled on the group grid (Verified on prealpha). Furthermore, the actual _Sticky Headers_ function does not work at all when set to Yes. Thanks @gonemob!

**Comment by gonemob** [comment] 2019-11-14 19:49
After poking around a little more, I think stickTableHeaders is looking for jQuery objects.  Not sure if this is the best practice or not, but the code below matches what was in the block earlier and will allow the page to load and the sticky header functionality to work

```
Sys.Application.add_load(function() {
    $(function() {
        $('[data-toggle="tooltip"]').tooltip();
    });

    var stickyHeaders = $('.js-sticky-headers');
    // var stickyHeaders = document.querySelector('.js-sticky-headers');

    if (stickyHeaders !== null) {
        var navbarFixedTop = document.querySelector('.navbar-fixed-top');
        // var navbarFixedTop = $('.navbar-fixed-top');
        if (navbarFixedTop !== null && getComputedStyle(navbarFixedTop)['position'] === 'fixed') {
            // stickyHeaders.stickyTableHeaders({ fixedOffset: navbarFixedTop });
            stickyHeaders.stickyTableHeaders({ fixedOffset: $(navbarFixedTop) });
        } else {
            stickyHeaders.stickyTableHeaders();
        }
    }
});
```

**Comment by BEGamache** [comment] 2019-11-15 16:06
Having the same issue in v10.1. With Sticky Heading on, the loading animation activates but does not disappear. And Jim is correct, doesn't ask for confirmation before deleting a member like it use to. Also, with Sticky Heading on it isn't being sticky. 

Not certain if this is related, but we add a custom column for Age and all it uses is {{Row.Age}}, unfortunately this isn't running the lava like it use to (I think it may have stopped in v9 though).

**Comment by nairdo** [comment] 2019-11-15 23:25
@BEGamache , @cabal95 , @JimMichael  or @gonemob -- if one or all of you feels comfortable with grabbing the raw file that Garrett fixed ([/Scripts/Rock/coreListeners.js)](https://github.com/SparkDevNetwork/Rock/blob/fa30042ce8064a9e9fecc9041e66b204ce4c448a/RockWeb/Scripts/Rock/coreListeners.js) to drop it in place to confirm that it solved the issue (after you do a browser shift-reload) in your environment, I would be grateful.

**Comment by cabal95** [comment] 2019-11-15 23:39
@nairdo That doesn't fix it. I'm getting a "position is not defined" error. I think this line needs to be fixed as well:

https://github.com/SparkDevNetwork/Rock/blob/fa30042ce8064a9e9fecc9041e66b204ce4c448a/RockWeb/Scripts/Rock/coreListeners.js#L10

However, once I fix that to be `['position']` I'm back to getting that stickyheaders error:

![image](https://user-images.githubusercontent.com/1119863/68983044-0e1a3280-07be-11ea-9bb0-ce9febfff094.png)

**Comment by cabal95** [comment] 2019-11-15 23:41
I made more changes, mostly wrapping various things in jQuery selectors, and got rid of all the errors. Here is my final file:

```javascript
Sys.Application.add_load(function() {
    $(function() {
        $('[data-toggle="tooltip"]').tooltip();
    });

    var stickyHeaders = document.querySelector('.js-sticky-headers');

    if (stickyHeaders !== null) {
        var navbarFixedTop = document.querySelector('.navbar-fixed-top');
        if (navbarFixedTop !== null &&  getComputedStyle(navbarFixedTop)['position'] === 'fixed') {
            $(stickyHeaders).stickyTableHeaders({ fixedOffset: $(navbarFixedTop) });
        } else {
            $(stickyHeaders).stickyTableHeaders();
        }
    }
});

$(document).on('enabledStickiness.stickyTableHeaders', function(event) {
    var navbarFixedTop = document.querySelector('.navbar-fixed-top');

    $(window).on('resize', function(event) {
        if (document.querySelector('.navbar-fixed-top') !== null && getComputedStyle(navbarFixedTop)['position'] === 'fixed') {
            $('.js-sticky-headers').stickyTableHeaders({ fixedOffset: $('.navbar-fixed-top') });
        } else {
            $('.js-sticky-headers').stickyTableHeaders();
        }
        $('.table-responsive').each(stickyRepaint);
    });
    let offsetLeft = $(event.target).offset().left;
    let twidth = $(event.target).parent('.table-responsive').width();
    $(event.target)
        .find('.tableFloatingHeaderOriginal')
        .css({ left: offsetLeft, right: $(window).width() - offsetLeft - twidth, clip: 'rect(0px, ' + (twidth + 2) + 'px, 140px, 0px)' });

    $(event.target)
        .parent('.table-responsive')
        .scroll(stickyRepaint);
});

function stickyRepaint() {
    let twidth = $(this).width();
    let scroll = $(this).scrollLeft();
    let offsetLeft = $(this).offset().left;
    $('.tableFloatingHeaderOriginal').css({
        left: offsetLeft - scroll,
        clip: 'rect(0px, ' + (scroll + twidth) + 'px, 140px, ' + scroll + 'px)'
    });
}
```

**Comment by nairdo** [comment] 2019-11-16 18:17
Thanks @cabal95 Since @garrettjohnson is out today, I took your suggestion and committed it: https://github.com/SparkDevNetwork/Rock/blob/c7375e1f26467cb55e2e1f672856ce2a3a98d78b/RockWeb/Scripts/Rock/coreListeners.js  

@garrettjohnson  Please follow up on this when you're back on Monday.

**Comment by cabal95** [comment] 2019-11-16 20:56
@garrettjohnson FYI it's still missing the fixes for wrapping the elements that need to be jQuery objects, specifically I think it's these:

<img width="877" alt="Screen Shot 2019-11-16 at 12 54 52 PM" src="https://user-images.githubusercontent.com/1119863/68999098-7e818c00-0870-11ea-8f9f-d114a94dd79e.png">

**Comment by garrettjohnson** [comment] 2019-11-18 20:33
Fixed via https://github.com/SparkDevNetwork/Rock/commit/915140fe98c2b2a7c73c6fcdaf4a7ae4ba35fd2c

**Closed by garrettjohnson** 2019-11-18 20:33 UTC
Labels: Fixed in v10.1, Status: Confirmed
