### ISSUE TITLE
Group Finder does not populate default values for multi-select attribute

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#3476] opened 2018-12-13 18:50 UTC
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When a default value for a Group Attribute is selected, the Group Finder page isn't selecting/rendering the default value.  Behavior reproduced in 8.5 demo (someone changed the theme to light blue).

![](https://user-images.githubusercontent.com/1210933/49959456-98398700-fedb-11e8-8a07-de5ba7ace703.png)

Here's the configuration of the Group Attribute (reproduced behavior regardless of Enhance for Long Lists selection): 

![](https://user-images.githubusercontent.com/1210933/49959394-6cb69c80-fedb-11e8-96e1-c253969cb603.png)

The toggle for Allow Multi-select is also broken since the user should only be able to select a single value:

![](https://user-images.githubusercontent.com/1210933/49960127-73461380-fedd-11e8-905a-9300a248a2f7.png)

The same behavior works fine when testing rendering a Person Attribute:

![](https://user-images.githubusercontent.com/1210933/49959357-57417280-fedb-11e8-86d2-842115424056.png)

![](https://user-images.githubusercontent.com/1210933/49959345-514b9180-fedb-11e8-98ba-a5fc7629297d.png)

### Steps to Reproduce
1. In 8.5 demo, add a default value for Small Group Topic
1. Enable the Topic filter for Small Groups
1. Refresh and the default value should be selected
1. The default value is not selected

### Versions
* **Rock Version:** 8.5
* **Client Culture Setting:** en-us

**Comment by nairdo** [comment] 2019-05-08 15:38
I David, I was not able to reproduce this on v9 (https://prealpha.rocksolidchurchdemo.com/page/236), but let me clarify exactly what I tested and explain a few behavioral items that may be unclear.

After creating a new small group called "Smith Group (no topic set)" and searching for it via the group finder, it does _not_ show up (correct behavior).  After changing and saving the Small Group _group type_ to have a default "topic" of "Women of the Bible", the Smith group now shows up in the filtered list (also correct behavior).  (_Like you, I also found the same correct behavior regardless of checking 'Enhance for Long Lists' on the Topic attribute._)

![image](https://user-images.githubusercontent.com/383807/57386553-69ad9880-7169-11e9-812c-867826149b5c.png)

The group finder Topic filter was enabled via configuration settings:
![image](https://user-images.githubusercontent.com/383807/57386808-fd7f6480-7169-11e9-8a2f-a96fe3e89e7b.png)

Regarding the **_filter_** allowing you to choose multiple items regardless of having "Allow Multiple Values" selected on the Topic attribute -- this is the intended behavior of the filter on the group picker.  Also note, the filter **does not default** to a particular value since it is not controlled by the configured default value of the attribute.  If that is what you were expecting, that would need to be opened as a feature request.

I also attempted to reproduce the problem with Person Attributes (I used the same Defined Type / Defined Values shown in the screenshot below) -- but it also functioned correctly:

![image](https://user-images.githubusercontent.com/383807/57387499-526faa80-716b-11e9-8f75-47024844dcc5.png)

Additionally, I created a Data View to verify that it would match people with the default topic (even if their record had not been edited), and it also works correctly:

![image](https://user-images.githubusercontent.com/383807/57387707-b2665100-716b-11e9-9cde-daf30019e06b.png)

I'm going to close this out but if you want to continue to discuss this more, feel free to re-open and add more details.

**Closed** 2019-05-08 15:39 UTC
Labels: Not Yet Reproduced, Topic: Group
