### ISSUE TITLE
Family PreRegistration Block: When Selecting Same Attribute Category for Adults and Children causes error

### ISSUE THREAD

**Issue by timlem** [SparkDevNetwork/Rock#3062] opened 2018-06-13 02:04 UTC
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When trying to choose an attribute category on the new Family PreRegistration block that is the same category for both the adult and the child section it causes an error on the page. Error says, "Multiple controls with the same ID '_rfv' were found. FindControl requires that controls have unique IDs."

### Steps to Reproduce

1. Put new Family PreRegistration Block on an external page.
2. Choose same "Attribute Category" on block settings for both the adult and child section.
3. Receive error message: "Multiple controls with the same ID '_rfv' were found. FindControl requires that controls have unique IDs."

**Expected behavior:** 

I expected to be able to add categories for both child and adult. One of our attributes under "Visit Information" category is "TShirt Size" - So I'd like for them to add their tshirt size as well as their children so we can have shirts ready for them. 

Get error message and the page won't work.

### Versions

* **Rock Version:** 7.4
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by timlem** [comment] 2018-06-13 02:11
Actually it seems it happens even if you just choose an attribute category for the parent?

**Comment by JimMichael** [comment] 2018-06-13 02:18
Confirmed... but looks like it's fixed in v8 (works on prealpha).

**Comment by edmistj** [comment] 2018-06-13 04:47
Closing based on Jim’s report of this being fixed in v8, the next release. Feel free to re-open if you find the issue still persists.

**Closed by edmistj** 2018-06-13 04:47 UTC
