### ISSUE TITLE
Communication Medium Pill Style Inconsistent

### ISSUE THREAD

**Issue by kkiserGH** [SparkDevNetwork/Rock#5002] opened 2022-05-08 21:55 UTC
### Description ###

The page styles change when moving between the Communication Medium selected pill.

Page Style with Email Pill selected:

![image](https://user-images.githubusercontent.com/54817742/167317184-92d20877-b1e3-4ce3-8de0-c3974d7a8404.png)

Page Style with SMS Pill selected:

![image](https://user-images.githubusercontent.com/54817742/167317199-6df1c490-95c4-4f35-b8ca-efe55323e593.png)

### Steps to Reproduce ###

1. Go to 'https://rock.rocksolidchurchdemo.com/page/495?CommunicationId=1'
1. Change the communication medium selected pill
1. As you move between the mediums, the page styles will change (page title, breadcrumbs, block title, pill text, etc.).  On our system we have more than 2 mediums so it is more obvious that the Email pill applies a different style than the other pills.

**Expected behavior:**

The style should stay consistent when moving between communication mediums.

**Actual behavior:**

The Email pill applies a different style than the other pills.

### Versions ###

* **Rock Version:** 13.2
* **Client Culture Setting:** en-US
![image](https://user-images.githubusercontent.com/54817742/167317356-4dc869b5-f697-4ab9-925a-2679eefaa3b3.png)

**Comment by jonedmiston** [comment] 2022-05-23 20:48
The issue is that the CSS is spilling out of the Summernote editor and effecting the page. We have a couple of ideas on how to fix it, but none of them a super-great.

**Comment by milescarmany** [comment] 2022-05-23 21:25
Ah, I see we have an empty email as the default for our Simple Communication editor. Once I pick a Template, the bug gets triggered. That would explain the difference!

**Comment by kkiserGH** [comment] 2022-05-25 13:50
Does this bug also impact the Communication Entry block showing and the Communication Detail block not showing?  On our test system with 13.3, we see both blocks defined on the page (same as our production system with 12.6), but the Communication Detail block doesn't show content whereas the Communication Entry block is shown like we are creating a new Communication with the contents of the selected communication from Communication History.

Production (12.6):
![image](https://user-images.githubusercontent.com/54817742/170277755-267a0b8d-ab18-4cc9-84d8-eeb1e1eb9551.png)

Test (13.3):
![image](https://user-images.githubusercontent.com/54817742/170277999-0fc21982-5b01-4f38-a817-26cf8f05b4eb.png)

I tried to replicate this on rocksolidchurchdemo.com but it appears the site is not working at the moment.  I can log in but nothing displays other than the header:
![image](https://user-images.githubusercontent.com/54817742/170277115-71d21a88-6cda-45c3-b762-39479dee2393.png)

**Comment by jonedmiston** [comment] 2022-05-25 14:34
@kkiserGH not sure I understand your question.

**Comment by kkiserGH** [comment] 2022-05-25 17:05
Sorry for not being more clear.  In your response above you mentioned "The issue is that the CSS is spilling out of the Summernote editor and effecting the page."

I was trying to ask if this issue could be the cause of the Communication Detail block on that page not displaying any data in our v13.3 test system.  Would the CSS issue just cause formatting issues or could it cause a block to not display its contents?

**Comment by kwabenaowusujnr** [comment] 2022-10-05 23:16
@kkiserGH the inconsistency is caused by CSS style overwritten by the EmailHeader template. 

![2022-10-05_22-56-05](https://user-images.githubusercontent.com/17472090/194180042-8621017a-546a-4d0a-81d8-4b8ea93ea75b.png)
![2022-10-05_22-56-20](https://user-images.githubusercontent.com/17472090/194180046-416281fe-39cb-45c4-a0f9-e144b893ad01.png)

This section of code overwrites the bootstrap header element style.
![image](https://user-images.githubusercontent.com/17472090/194180147-684f5fb8-1275-4144-85b5-f8d93472186b.png)

I guess we need to update the DefaultValue for EmailHeaher in the Attribute DB table.

**Comment by jonedmiston** [comment] 2023-09-15 18:49
The CSS bleeding out of SummerNote is not something we can cleanly fix as it's not in an `iframe`. Our plan is to use a different WYSIWYG editor in our next gen re-write. This is planned for v17. Leaving this open as it still is technically an issue. Will close when new block is completed.

**Comment by jonedmiston** [comment] 2023-11-09 22:25
We've change our process how how we process issues that are for external components that we are not able to update ourselves. I'm closing this because it is in a external component. That said we are currently working on a new Obsidian block to replace this one and we'll use a different component for that one.

**Closed by jonedmiston** 2023-11-09 22:25 UTC
Labels: Type: Bug, Topic: UI, Will Fix In Next Gen

**Comment by joshuahenninger** [comment] 2024-08-02 16:12
We have confirmed that the issue is resolved in the Communication Entry Obsidian block on the Next Generation framework. The new WYSIWYG editor is no longer in an iframe. Instead, it addresses the CSS bleed issue by scoping the CSS to the editor element. This is achieved by adding additional specificity to each CSS rule at runtime.
