### ISSUE TITLE
Lava Shortcode parameters cut off values with single quotes

### ISSUE THREAD

**Issue by Tschrock** [SparkDevNetwork/Rock#3605] opened 2019-03-24 00:29 UTC
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When using lava to pass a value that contains a single quote to a shortcode parameter, the value is truncated.

### Steps to Reproduce

1. Create a Lava Shortcode that uses a parameter:
    ```
    testparameter: {{ testparameter }}
    ```
    [Screenshot](https://user-images.githubusercontent.com/2406499/54873202-e5b17400-4da7-11e9-982c-2702282a2048.png)

2. Try passing a value that contains a single quote to that parameter:
    ```
    {% assign testvalue = "Testing 'single' qoutes" %}
    {[ SingleQuoteTest testparameter:'{{testvalue}}' ]}
    ```
    or
    ```
    {% capture testvalue %}Testing 'single' qoutes{% endcapture %}
    {[ SingleQuoteTest testparameter:'{{testvalue}}' ]}
    ```
    [Screenshot](https://user-images.githubusercontent.com/2406499/54873245-d979e680-4da8-11e9-8887-fa85720f14b7.png)

**Expected behavior:**

The entire value is passed through:
```
testparameter: Testing 'single' qoutes
```

**Actual behavior:**

The value is truncated at the first single quote:
```
testparameter: Testing 
```

### Versions

* **Rock Version:** v1.8.6.2 and 1.9.0.16 (prealpha)
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment] 2019-03-27 14:55
In general parameters are meant to be used for simple inputs (ints, short strings). If you want to get longer/complex strings you should use the body of the shortcode:

```
{[ singlequotetest ]}
   long complex string here
{[ endsinglequotetest ]}
```

We could though adjust the regex to allow for escaped single quotes `\'`. Below is the regex if someone wants to take a stab at it.

```
(\S*?:'[^']+')
```

**Comment by Tschrock** [comment] 2019-03-27 22:45
Unfortunately, the shortcode where this came up is already using the body, so we can't use that in place of the parameter.

I'm curious how that regex effects things, or why single quotes would need escaping - I was under the impression that since the text is already stored in a lava variable, there wouldn't need to be any extra escaping and that there was something deeper amiss. I haven't looked at how things are actually parsed, but my intuition tells me that specifying `{[thing parameter:'{{value}}' ]}` should take `{{value}}`, merge it, and then store the result in `parameter` - which means escaping wouldn't be necessary - but perhaps it's working backwards to how I think and merging the lava code before it even gets to parsing the shortcode? That would explain the results that I'm seeing.

**Comment by cabal95** [comment] 2019-03-27 23:12
From my previous experience, the issue is that Lava resolves merge fields in the ENTIRE `{[ ... ]}` line all at once rather than on a per-parameter basis.
So if you have:
```
{% assign value = "Jason's Baby" %}
{[thing parameter:'{{value}}' ]}
```

Then the second line will parse, see it's a shortcode and then parse the entire line to get `{[thing parameter:'Jason's Baby' ]}` which has problems because of the extra quote.

The solution would be to change how it parses the lines so that it parses the individual parameters one at a time.

The same problem exists with other `{% %}` blocks as well.

**Comment by Tschrock** [comment] 2019-03-27 23:51
Ah! That explains a lot of the little unexpected issues I see with quotes. Knowing that, a lot of the behavior starts to make more sense.

And building off of that, that means you can currently do something like
```
{% assign options = "where:'Id < 10' limit:'2' offset:'2'" %}
{% person {{ options }} %}
    {% for person in personItems %}
        {{ person.FullName }} <br />
    {% endfor %}
{% endperson %}
```
It's like, meta-templating, which is actually kind of cool - but I don't think it's what most people would expect and presents a lot of issues when dealing with quotes.

**Comment by cabal95** [comment] 2019-03-28 00:13
Another possibility would be to configure the code to allow direct variable passing, like we can do with filters, ala:

```
{% assign value = "Jason's Baby" %}
{[thing parameter:value ]}
```

**Comment by edmistj** [comment] 2019-03-28 14:05
The simplest approach might be to remove the resolving of the Lava in the shortcode definition from this line:

https://github.com/SparkDevNetwork/Rock/blob/1b96bb6edeb1f991721aab7cf169e5cee6586215/Rock/Lava/Shortcodes/DynamicShortcodeBlock.cs#L370

And then resolve the Lava for each parsed parameter around line 382. I think that would allow for Tyler's needs (didn't test it though). This would slow the shortcode down a bit as Lava would need to be run for each parameter. It would also not allow for fully dynamic parameters as Tyler notes above (that's more of a cool trick though than an intended feature.) 

The other option of ensure escaped single quotes. This would be faster but would require a replace filter to be run if you thought your parameter value would have a single quote.

**Comment by SteveSwaringen** [comment] 2021-04-05 19:27
Seeing a related behavior worth mentioning. If I pass `option:"I'm New Here"`, I get the behavior described above where only the "I" makes it into the shortcode. What's new to the discussion is that if I pass `option:"Im New Here"` (no single-quote, but still wrapping the string literal in double-quotes), the shortcode sees an empty string. Passing `option:'Im New Here'` (now declaring the string literal with single-quotes) works as expected. It looks like the section of the Lava parser that deals with the shortcode calling syntax has problems with string literals declared with double-quotes.

(I was able to work around my problem by declaring the string in an assign statement and passing that variable as the parameter.)

**Comment by jonedmiston** [comment] 2021-04-05 20:00
@SteveSwaringen to be clear shortcodes (and other Lava commands like entities https://community.rockrms.com/lava/commands/entity-commands) require that parameters be enclosed with single quotes. Double quotes are not valid syntax. 

Reading through this full discussion again we're going to close it as:
1. Parameters are meant more for simple inputs
2. Adjusting the code to run Lava on each parameter would slow it down
3. Inputs with blocks of strings should use the body when possible
4. The Lava author can work around this by encoding their inputs that may have single quotes.

**Closed by jonedmiston** 2021-04-05 20:00 UTC
Labels: Status: Confirmed, Topic: Lava, Type: Bug, x-bugapalooza: Low

**Comment by Tschrock** [comment] 2021-04-05 20:32
I'd like to mention that for @newpointe I had made some modifications to run Lava on each parameter, and it did not have any noticable effect on performance. 

IMO, as a programmer, the current behavior of lava command parameters is very confusing and unintuitive - parsed out of order, restricted to single quotes, no escaping, etc. Ideally they would work exactly like filter parameters, but with string interpolation. Saying they're "meant more for simple inputs" just feels like a cop-out - sure that might be how they were originally thrown together, but that's not how people think when learning about them and trying to use them. Also, sticking things in the body isn't a great solution when a lot of the time you run into this issue when you're already using the body for something. Encoding input is a usable workaround if your output is html and you can use html encoding, but that's still just a workaround and not the nicest solution.

All that said, I believe the current best workaround for people running into this is to assign to a variable and then pass that directly to the parameter. I don't know if it's actually documented anywhere, but I'm pretty sure you can do something like this now:
```
{% assign testvalue = "Testing 'single' qoutes" %}
{[ SingleQuoteTest testparameter:testvalue ]}
```
