### ISSUE TITLE
Payment Gateway Transfer

### ISSUE THREAD

**Issue by sanford-rock** [SparkDevNetwork/Rock#4850] opened 2021-12-07 01:14 UTC
* [X ] Put an X between the brackets on this line if you have done all of the following:

### Payment Gateway Transfer

_[Tried Rocket Chat and Q&A and have got no response. Testing the Transfer Gateway process in Manage Giving Profiles and it doesn't seem to be working. I click the Transfer button and it brings up the detail information for the payment, get the Confirmation page and finish with the Gift Information page but it doesn't change the Payment Gateway on the Giving Profile. 

We have 2 NMI>Transnational gateways. Gateway 1 (G1) is for General Giving and Gateway 2 (G2) is for Childcare only through a special registration going through a special recurring payment setup which uses G2. However initially quite a few registrations went through G1 and need to transferred to G2. The Manage Giving Profile page has the Transfer to Gateway option set to go to G2, and It all seems to work except that nothing changes when I look at the Scheduled Transaction History page. The Give Now page gateway is set to G1 as it should be. So I'm not sure what's not working...any ideas? .]_

### Steps to Reproduce

**Create new profile:**

_[I expect that the process is supposed to create a new giving profile for the scheduled transactions with the new gateway but it doesn't.]_

**Actual behavior:**

_[Doesn't work]_

### Versions

* **Rock Version:** [12.4]
* **Client Culture Setting:** [?]

**Comment by JimMichael** [comment] 2021-12-07 01:55
The payment transfer has been working fine for us for several months, as we transition from Payflow Pro to NMI. I think your  issue is a misunderstanding on how the transfer works. When you click the "Transfer" button on an existing scheduled payment, _it uses your normal Giving page and its associated Transaction Entry block to actually complete the transaction._

What this implies is that the _Scheduled Transaction List Liquid_ block on your Manage Giving Profiles page has the NEW (to-transfer-to) gateway set, and is pointing at your Give Now page (by default), thus the Give Now page must ALSO have the NEW GATEWAY you are wanting to transfer-to set within its Transaction Entry bock... or nothing will happen.

Here's what I mean:
If my Give Now Page is set to use NMI (G1) and I configure my _Scheduled Transaction List Liquid_ block to "transfer to" NMI, this will cause absolutely nothing to happen, because you're trying to "transfer" from/to the exact same gateway.

![image](https://user-images.githubusercontent.com/3903408/144950815-f2ec6896-b78f-4678-a584-71989a4d31c8.png)

This seems to be exactly your situation, where your Give Now page is using G1, and your existing transactions for G1 are trying to be transferred to G2, but the PAGE the block is pointing at is set to process transactions via the G1 gateway... and nothing changes.

I THINK all you need to do to fix this is create a new/different page with a Transaction Entry block set to G2 to handle these to-to-transferred transactions. Then set up your Scheduled Transaction List Liquid block to point at this new page. The only problem is that it will also offer normal G1 transactions (that are supposed to be G1) to be moved as well... so maybe you want an entirely separate Manage Giving Profiles page for this as well.

At least that's my best guess as to what you are seeing... as I said, the transfer has been working perfectly for us, since we're using it in the way it was designed where our Give Now page is using the NEW gateway we're transferring-to.

**Comment by sanford-rock** [comment] 2021-12-07 15:13
Thanks for the explanation @JimMichael that makes sense to me...I'll set this up today and give it a try.

**Comment by jonedmiston** [comment] 2021-12-07 15:23
Going to close this as this seems resolved with @JimMichael 's help. Please reopen if you believe this is still a bug.

**Closed by jonedmiston** 2021-12-07 15:23 UTC
