### ISSUE TITLE
Group Counts Missing from Group Tree View

### ISSUE THREAD

**Issue by SteveSwaringen** [SparkDevNetwork/Rock#5077] opened 2022-07-19 20:24 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
<img width="950" alt="image" src="https://user-images.githubusercontent.com/45042927/179840745-b6625e6f-0621-4719-b4ef-9e4d614f509e.png">

### Description

Group Counts (both Members and Child Groups) are no longer visible in the Group Tree View (13.5/13.6)

### Steps to Reproduce

1. Go to RockSolidChurchDemo.com/people/groups
2. Expand Section A
3. Select Alisha Marble's Group
4. See that this group has two members but no members are visible in the tree view of this group or any other group.
5. There are two different places (panel settings, block settings) where you can select whether Group Members or Child Groups are counted or nothing is counted. No matter what you set either of those controls to, no counts show up.

**Expected behavior:**

Count of group members (or number of child groups, depending on configuration) should be noted adjacent to the group name.

**Actual behavior:**

No counts are displayed.

### Versions

* **Rock Version:** [13.5, 13.6]
* **Client Culture Setting:** [en-US]

**Comment by nlBayside** [comment] 2022-07-19 23:17
![Screen Shot 2022-07-19 at 4 16 16 PM](https://user-images.githubusercontent.com/85907597/179863826-3aa1cadd-58fd-45f5-b295-e622a718e3f4.png)

On further examination, it looks like the attribute value does save; however, it gets saved with EntityId = 0. So it saves to the database, but not to the Metric correctly. This was examined using the SQL Profiler.

**Comment by karenn-ccbc** [comment] 2022-07-24 21:52
Confirmed--we just updated to 13.6 -- I noticed it right away :(

**Comment by nairdo** [comment] 2022-07-28 00:24
We do have a fix for this coming in v13.7.

**Closed** 2022-07-29 17:22 UTC
Labels: Type: Bug, Status: Confirmed, Status: In Progress
