### ISSUE TITLE
Failed to load viewstate on CMS Sidebar

### ISSUE THREAD

**Issue by craigmash** [SparkDevNetwork/Rock#3575] opened 2019-03-06 14:59 UTC
### Prerequisites
* [ X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
In CMS->Pages if you go to the Internal site Reports page, changing the Zone to Sidebar1 throws and error.
This happens on the demo server as well.

`Error
Failed to load viewstate. The control tree into which viewstate is being loaded must match the control tree that was used to save viewstate during the previous request. For example, when adding controls dynamically, the controls added during a post-back must match the type and position of the controls added during the initial request.

at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
 at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
 at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
 at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
 at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
 at System.Web.UI.Control.LoadChildViewStateByIndex(ArrayList childState)
 at System.Web.UI.Control.LoadViewStateRecursive(Object savedState)
 at System.Web.UI.Control.AddedControl(Control control, Int32 index)
 at RockWeb.Blocks.Cms.PageZoneBlocksEditor.AddAdminControls(BlockCache block, Panel pnlLayoutItem)
 at RockWeb.Blocks.Cms.PageZoneBlocksEditor.rptBlocks_ItemDataBound(Object sender, RepeaterItemEventArgs e)
 at System.Web.UI.WebControls.Repeater.OnItemDataBound(RepeaterItemEventArgs e)
 at System.Web.UI.WebControls.Repeater.CreateItem(Int32 itemIndex, ListItemType itemType, Boolean dataBind, Object dataItem)
 at System.Web.UI.WebControls.Repeater.AddDataItemsIntoItemsArray(IEnumerable dataSource, Boolean useDataSource)
 at System.Web.UI.WebControls.Repeater.PostGetDataAction(IEnumerable dataSource)
 at System.Web.UI.WebControls.Repeater.OnDataBinding(EventArgs e)
 at RockWeb.Blocks.Cms.PageZoneBlocksEditor.ShowDetailForZone(String zoneName)
 at RockWeb.Blocks.Cms.PageZoneBlocksEditor.OnLoad(EventArgs e)
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Control.LoadRecursive()
 at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)`

### Steps to Reproduce
1. Go to [https://rock.rocksolidchurchdemo.com/page/103?Page=149&ExpandedIds=12%2c105%2c144&Redirect=false]
1. Change zone to Sidebar1
1. See error

**Expected behavior:**

No error

**Actual behavior:**

See error above

### Versions
Rock Version: Rock McKinley 8.6 (1.8.6.2)
Client Culture Setting: en-US

**Comment by Tschrock** [comment] 2019-03-24 02:21
Closing this as a duplicate of #3354. Please follow that issue for updates.

**Closed by Tschrock** 2019-03-24 02:21 UTC
Labels: Type: Duplicate
