### ISSUE TITLE
Obsidian & Obsidian Blocks fail to build

### ISSUE THREAD

**Issue by jamessandison** [SparkDevNetwork/Rock#5257] opened 2023-01-02 07:39 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
Did you know you you can simply copy and paste an image below?  Please do that. It really helps us quickly understand the problem.

### Description

_[Write a clear and concise description and include **full window** (non-partial) screenshots. FYI: You can just copy and paste an image directly into here and it will magically upload.]_
![image](https://user-images.githubusercontent.com/43879953/210204273-97367e04-4925-4c10-ad3f-f8026222cfec.png)
The builds for Obsidian and Obsidian Blocks fail.

I'm not sure if its a different version of node (v16.13.2) that is the issue (I don't really see a way that it could be an issue) or some other build setting.

### Steps to Reproduce

1. Fresh Install of Visual Studio 2022 w/ ASP.NET, C# and Node.js development addons.
2. Clone develop branch

**Expected behavior:**

The build successfully completes.

**Actual behavior:**

The build fails due to Rock.Javascript.Obsidian and Rock.Javascript.Obsidian.Blocks failing to build.

### Versions

* **Rock Version:** [49fcc55](https://github.com/SparkDevNetwork/Rock/commit/49fcc55cd33bc17ad1a10352c2c35761a9a6919c)

**Comment by cabal95** [comment] 2023-01-02 15:00
Let me do some checking on a few things. I ran into this once before and it ended up being a wild goose chase as the problem was unrelated.

By chance are you trying to build from an SMB share?

**Comment by jamessandison** [comment] 2023-01-02 23:22
Nope, just building off my C:/Users/{user}/sources/repos/Rock

**Comment by cabal95** [comment] 2023-01-03 15:10
@jamessandison The only way I can replicate your problem is by manually updating rollup to the v3 line - which isn't the version we are using. Every way I have tried to install npm packages installs the requested v2 line specified in packages.config.  Can you try running the following from your developer powershell so we can see what version of rollup is installed?

```
npx rollup --version
```

and also

```
npm outdated
```

(You can trim the second command output to just the line(s) related to rollup if you wish).

**Comment by jamessandison** [comment] 2023-01-07 02:11
@cabal95 I'm currently running rollup v2.70.1 (I'm not sure if you've seen the pull request #5258)

After running npm outdated I saw a bunch of my packages were for versions which were below the 'wanted' version. I ran 'npm update', which upgraded them (including rollup to v2.79.1), which fixed that compile issue, but gave an issue with luxon

```
PS C:\Users\Sandi\source\repos\jamessandison\Rock\Rock.JavaScript.Obsidian> npm run build-fast

> build-fast
> node Build/build-fast.js


> build
> npm run build-core && npm run build-framework && npm run copy-webforms-core && npm run copy-webforms-framework && echo '' > dist/.buildstamp && echo DONE


> build-core
> webpack --no-color && lessc --js System/vendor.less dist/obsidian-vendor.css && cleancss --source-map dist/obsidian-vendor.css -o dist/obsidian-vendor.min.css

assets by status 466 KiB [cached] 2 assets
orphan modules 748 KiB [orphan] 15 modules
runtime modules 1.21 KiB 6 modules
modules by path ./node_modules/ 1.45 MiB
  modules by path ./node_modules/ant-design-vue/lib/ 425 KiB 121 modules
  modules by path ./node_modules/lodash/*.js 63 KiB 91 modules
  modules by path ./node_modules/@ant-design/ 52.4 KiB 32 modules

```

**Comment by cabal95** [comment] 2023-01-09 20:37
@jamessandison Thanks for the output on the outdated command. I did see the PR, but it makes a number of changes that appear to be unrelated and shouldn't be needed. Especially since you are apparently the only person running into this issue. None of the core developers are having this issue (and we all setup our own development environments so they aren't configured identically), our CI build server doesn't have this problem, and the handful of churches running pre-alpha and building their own deployments of Rock haven't reported running into this issue. I know there are a couple of community developers that have been playing with Obsidian too and I have not heard of any issues like this from them either.

Can you post the output of `rollup --version` (this should give an error as it will try to run a globally installed version) as well as `npm --version`. I know you said you are using rollup 2.70.1 in the repo, but what I'm trying to check is if there is a global rollup binary possibly getting in the way with a different version. And then with npm I want to see if maybe you have a vastly different version than we are using that might be doing something different during installation.

As a final test, could you clone the repo and checkout the develop branch to a clean directory, then run `npm ci` (ci instead of just i) and then `npm run build` in the Rock.JavaScript.Obsidian directory. Assuming you have a compatible version of npm that should install the exact same versions of the packages we are using on the automated build server.

**Comment by cabal95** [comment] 2023-02-13 18:10
@jamessandison Just following up if you were able to re-test with the instructions above. Since we haven't been able to reproduce this anywhere we will close in a few weeks if we don't hear back. Though you can always re-open if you get more detailed steps that might help reproduce the issue.

**Comment by taylorbrooks** [comment] 2023-02-14 21:39
@jamessandison Does `npm run build` work?

**Comment by cabal95** [comment] 2023-02-27 16:11
I'm going to close this for now. If you are able to get more detailed steps to help reproduce this we can re-open this to look into it further.

**Closed by cabal95** 2023-02-27 16:11 UTC

**Comment by rcleverlySBC** [comment] 2024-06-25 23:53
@cabal95 I'm having issues compiling a freshly cloned Rock solution (specifically version 14.5). I get the compile error `The command "npm run build" exited with code 1`. If I run `npm run build` separately in the VS console I get `npm error Missing script: "build"`. I've tried different rollup versions (4.18.0 and 2.7.0) and neither fixed the issue. I do not see `build` listed as a script in `package.json`, am I supposed to?
