### ISSUE TITLE
Recent Attendance filter in Data Views not Saving Correctly

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#816] opened 2015-02-02 19:13 UTC
I'm on McKinley 2.0

Whenever I create a new data view or attempt to update an existing one that uses a Recent Attendance filter, I can't change the "in last X weeks" number - it is always stays at 16 when I save it, no matter what other number I use in that field:

![2015-02-02 14_10_15-data views _ rock rms](https://cloud.githubusercontent.com/assets/1859094/6007069/86cf8120-aae5-11e4-9844-c451b0d25498.png)

(The "X times" number IS saving correctly)  There are no exceptions about this in the log

**Comment by mikepetersonccv** [comment] 2015-02-02 23:50
duplicate of #782

**Comment by FrankGrand** [comment] 2015-02-26 17:32
Not sure if this is useful or I'm just jumping the gun or missing something, but we have an instance of Rock using the develop branch. I see that changing the weeks now works, but now I'm running into I can't change the logic.  So if I change it to Less Than, when I save it just stays as Greater Than Or Equal To

**Comment by mikepetersonccv** [comment] 2015-02-26 17:42
@FrankGrand yep, you are right, there does seem to be a bug there! Thanks for letting me know.

**Closed** 2015-04-30 12:31 UTC
Labels: Fixed in v3.0
