### ISSUE TITLE
Communication Queue Alert job incorrectly firing on delayed-send messages.

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3038] opened 2018-06-01 20:36 UTC
### Description
The Communication Queue Alert job seems to fire on **any** messages that are delayed to send, if the delay is longer than the (default) 2hr Alert Period set on the job. 

### Steps to Reproduce
1. Make sure the Communication Queue Alert job is running, and set the Alert Period to something like 30 min if you don't want to wait too long.
1. Create a new communication set to deliver 45min from now (or 2hr, 15min if you left the alert period at the default)
1. Observe that at 30min, the Communication Queue Alert sends an email claiming "Your Rock communications are queuing up."
1. Panic until you realize what's going on.

**Expected behavior:**

Communication queue alert job would not incorrectly determine that intentionally-delayed emails are "queuing up" and would only alert you to situations where the queue is truly backing up for some reason.

**Actual behavior:**

@cabal95 might have more to add to this, but in Slack he described the issue like this: _With the Communication Queue Alert, we found that it checks if an e-mail is older than (e.g.) 2 hours from it's approved date, not from it's scheduled send date. So anything that is scheduled in the future at all gets flagged as an alert condition._

### Versions
* **Rock Version:** 7.x (can't check v8)

**Comment by nairdo** [comment] 2020-02-07 20:58
I am not able to reproduce this issue on v10. 

@JimMichael  I know this is an old one and there's been a lot of movement with the communication system and underlying `.GetQueued()` method (https://github.com/SparkDevNetwork/Rock/commit/ae55e72ff9e53eb95f7d701e2063f853cc18ae32#diff-16f48568f02eb4d880a47ef6126c4b21R181) so I'm closing this out but PLEASE re-open if you find this is still happening in your v9 or v10 environment.

**Comment by cabal95** [comment] 2020-02-07 21:16
Thanks @nairdo, we've run into this in the past too so we'll try to do some testing to see if it's still a problem for us too.

**Comment by JimMichael** [comment] 2020-02-07 21:21
It definitely happens on 9.4 here... I get alerts every day that our queue is backing up, and it's always for future send emails, such as:

**The following communications have been queued to send for longer than 2 hours...

KidsCrossing Reminder for This Weekend in the PreK Room from [obscured].
KidsCrossing Reminder for This Weekend in the K2 Room from [obscured].
KidsCrossing Reminder for This Weekend in the 3rd-5th Grade Room from [obscured]**

What's curious is that I *only* get the alert email at the exact same time the emails are scheduled to start sending. For example, the above email was scheduled to go out on 2/6 at 10am, and that's precisely the timestamp on the email I received above. In every case I've ever checked, the queue alert is not sent *until* the future send email is actually at its send-time. 

So perhaps the above description of the issue is not accurate, but there's definitely something going on with queue alerts and future-send communications.

**Comment by cabal95** [comment] 2020-02-07 22:06
@nairdo I have some tests queued up over the weekend to test since we are on 10.1 now, but I was poking through the code and I think I might see an issue that could be causing this if you care to check my logic.

This line https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Model/CommunicationService.Partial.cs#L253 has the following predicate (custom indentation for clarity):

```
    ( !c.FutureSendDateTime.HasValue &&
        c.CreatedDateTime.HasValue &&
        c.CreatedDateTime.Value >= beginWindow &&
        c.CreatedDateTime.Value <= endWindow )
    ||
    ( c.FutureSendDateTime.HasValue &&
        c.FutureSendDateTime.Value >= beginWindow &&
        c.FutureSendDateTime.Value <= currentDateTime )
```

In our case, `c.FutureSendDateTime.HasValue` is true so the first half of the predicate is not relevant. However, the discrepancy between using `endWindow` and `currentDateTime` is I think the relevant bit.

In our case, the queue alert job is set to 120 minutes, so `endWindow` would be "now minus 2 hours". But since the check is using `currentDateTime` it's instead saying "if there is a future send time and that value is greater than 3 days ago and less than now, throw alert" - when really we want to say "if there is a future send time and that value is greater than 3 days ago and less than 2 hours ago, throw alert" (implying it has been 2 hours since the e-mail was _supposed_ to have been sent).

I think the logic should be using `endWindow` instead of `currentDateTime`. However, I don't know if changing that logic would break other places the `GetQueued()` method is used so that additional logic might need to be applied in the Queue Alert job logic directly.

**Comment by nairdo** [comment] 2020-02-07 22:33
Thanks you two.  That makes sense now... it's popping up during the window when the older message is about to be sent, but hasn't quite been handled/sent yet (such as due to the delay setting on the SendCommunication job).

I also noticed that `currentDateTime` vs `endWindow` difference last night.  The only two places in core that use that `GetQueued()` method are this job and the SendCommunication job -- so I think we're going to fix/change that for consistency.

**Comment by cabal95** [comment] 2020-02-08 17:28
I know it sounds like we got it figured out, but just for completeness sake - We are on 10.1 and did indeed still run into this just now with one of my tests so for sure it still happens in 10.1.

**Comment by JimMichael** [comment] 2020-02-08 18:06
I’m also a little confused by Nick’s modified comment above. Does that mean it won’t be fixed, or that it will need a fix more complex than simply modifying the GetQueued() method so that it doesn’t break the other things that use it and might rely on the current behavior?

**Comment by cabal95** [comment] 2020-02-08 18:09
I think the fix is going to have to be made on the Queue Alert job directly.  i.e. after it calls `GetQueued()` it then checks if it's a FutureSendDateTime and applies a secondary filter on that.

**Closed** 2020-02-10 18:24 UTC
Labels: Fixed in v10.2, Priority: Low, Topic: Communications, Type: Bug
