### ISSUE TITLE
Report Total Giving - If To Date Reset when From Date Changed, Cannot Select Prior Dates in To Date

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#1491] opened 2016-04-13 08:35 UTC
In the Total Giving Report Date Range -

If the From Date is changed such that the To Date is automatically reset (e.g. a future date is entered), then no dates prior to this calculated date can be selected in the To Date date picker.  Then if the From Date is subsequently corrected (e.g. set to the correct year), the To Date still cannot be set to anything prior to what the To Date was set to by the system based on the earlier From Date.  (This does not happen on the first entry of a From Date.)

![totalgiving6](https://cloud.githubusercontent.com/assets/4658177/14487588/8947f49e-01b7-11e6-89a4-884222452623.jpg)

This happens when there is a From Date and a To Date, and the From Date is changed so that the To Date is reset.  IF this happens, then it does not matter what the Start Date is changed back to, the To Date cannot be set to anything prior to what the To Date was auto changed to.  
E.g. From Date 1/4/2015 To 1/4/2016.
Change From Date to 5/4/2016.  This sets the To Date to today's date.  Nothing prior to today's date can be selected.

If you can't reproduce this let me know and I'll give more detailed steps to reproduce.
There is a work around: clear the dates, save, edit and re-enter the dates.  Note that I'm using New Zealand date format: dd/mm/yyyy.

**Comment by mikejed** [comment] 2018-03-28 02:15
Confirmed on v6.x

However, by Rock v7 (unknown which precise version), the "From" input on a date range control no longer resets the "To" input when the former is set to a more advanced date than the latter. This new behavior continues on the v8 prealpha. I have confirmed that the "To" date can be set to any value, regardless of any value in the "From" input.

Closing this issue since it's been resolved

**Closed by mikejed** 2018-03-28 02:15 UTC
Labels: Fixed in v7.0, Status: Confirmed, Topic: Reporting, Topic: UI, Type: Bug
