### ISSUE TITLE
Signature Document lava limitations on the Obsidian registration entry block

### ISSUE THREAD

**Issue by bartbrueck** [SparkDevNetwork/Rock#5492] opened 2023-06-22 21:46 UTC
### Please go through all the tasks below

- [ ] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

The Obsidian Registration Entry block does not allow Signature document lava to access Registrant Attributes. 
It only allows accessing certain specific Registrant "properties". 
*See the lava debug list below. 
This works: {{ Registrant.MobilePhone }}
This does not work:  {{ Registrant | Attribute:'DescriptionOfActivities' }}
I can access the Registrant Attributes in the lava tester if I have the Registrant object. However, since RegistrantId is not one of the specific properties available in the Obsidian Registration Entry block, I cannot gain access to the Registrant object to be able to display registrant attributes. So this workaround option is not available either. 

The Obsidian Registration Entry block does not allow the Signature document lava to access Person Properties.
It only allows for accessing Person Attributes. 
This works: {{ Registrant.Person | Attribute:'EmergencyContactPhone' }}
This does not work: {{ Registrant.Person.Age }}

The block setting for Show Field Descriptions does not work when set to No. It still shows descriptions for Person Attributes and for Registration Attributes.

### Expected Behavior

See above

### Actual Behavior

See Above

### Steps to Reproduce

- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

### Rock Version

What Version of Rock: v14.2 and confirmed on pre-alpha 16.0 (1.16.0.6)

### Client Culture Setting

 en-US

**Comment by robotman3000** [comment] 2023-07-05 19:52
Hey, We encountered this issue ourselves and have developed a patch for Rock version 1.14.1.1. The issue is actually in `Rock.Blocks.dll` in the file `Event > RegistrationEntry.cs`. The core obsidian registration block doesn't populate the `LavaSignatureRegistrant` object with the registrant attributes. 

Since we have a fix, what would be the best way to submit it to the community?

**Comment by nairdo** [comment] 2023-08-01 17:01
@robotman3000  If you believe your fix follows Rock patterns and looks like our typical coding conventions, you can submit the [Pull Request over here](https://github.com/SparkDevNetwork/Rock/pulls) targeting the hotfix-1.15.2 branch (the latest unreleased hotfix branch which is still active).

**Comment by cabal95** [comment] 2023-10-02 20:26
This was fixed in commits https://github.com/SparkDevNetwork/Rock/commit/6240cc8e4f07a4f0410e92e4afd9b919923aba09 and https://github.com/SparkDevNetwork/Rock/commit/19e6fb0301fbe1d6bfa0c0c1f1b03434a5985267. Those changes should be in Rock 15.2.

Do note that in the case of accessing the Person object such as `{{ Registrant.Person.Age }}`, the Person will not always exist yet. Meaning, if no match was found then the Person object will be available, but it will be an in-memory Person only. There are some properties that are calculated when the Person object is saved so there may be a handful of things that can't be used.

**Closed** 2023-10-02 20:28 UTC
Labels: Status: Confirmed, Topic: Event Registration, Fixed in v16.0, Fixed in v15.2
