### ISSUE TITLE
[EN] REST API doesn't return resources for non-GET requests

### ISSUE THREAD

**Issue by taylorbrooks** [SparkDevNetwork/Rock#2306] opened 2017-07-09 16:43 UTC
When creating a resource such as `FinancialBatch` or `FinancialTransaction`, the return of the POST request is just the string value of the primary key identifier -- which is not valid JSON.

It would be great if the creation of a resource returned the same response that a GET method does. Additionally, PATCH requests return a 204 no content response. It would be nice for that response to also return the updated representation of that resource instead of no content.

I'm new to C# and ASP.NET, someone shows me how to do this for one resource, I'm happy to do it for all and open a PR.

**Comment by dcs619** [comment] 2017-07-09 19:10
That behavior conforms to [RFC 7231](https://tools.ietf.org/html/rfc7231#section-4.3.3) ([friendly version](http://www.restapitutorial.com/lessons/httpmethods.html)) and [RFC 5789](https://tools.ietf.org/html/rfc5789).

Relevant sections: 
```
On successful POST, the origin server should send a 201 (Created) response 
containing a Location header field that provides an identifier for the primary 
resource created (Section 7.1.2) and a representation that describes the status 
of the request while referring to the new resource(s).
```

```
On successful PATCH, The 204 response code is used because the response does
not carry a message body (which a response with the 200 code would have).
```

Regardless, to see this functionality you would need to modify the API at [the global level](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Rest/ApiController.cs#L159) to return the model instead of the HTTP service response.

**Comment by arranf** [comment] 2017-09-09 09:27
@taylorbrooks I'm going to mark this as won't fix as it's intended behaviour. I suspect the PR would be welcome though.

**Closed by arranf** 2017-09-09 09:27 UTC
Labels: Status: Won't Fix, Topic: API
