### ISSUE TITLE
Mobile Nav in Admin isn't scrollable.

### ISSUE THREAD

**Issue by JoshuaMaiorino** [SparkDevNetwork/Rock#3360] opened 2018-10-23 17:38 UTC
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When viewing the admin site on a mobile browser, The lefthand Nav is not scrollable.  If there are any additional sections/pages added, they're inaccessible.

### Steps to Reproduce

1. Go to Rock admin on a mobile device
2. Click on the menu button
3. Try to scroll

**Expected behavior:**

The Nav should scroll be scrollable

**Actual behavior:**

The nav isn't scrolling

### Versions

* **Rock Version:** [8.x]
* **Client Culture Setting:** [US-EN]

**Comment by JimMichael** [comment] 2018-10-23 18:12
This is a duplicate of https://github.com/SparkDevNetwork/Rock/issues/3331

**Comment by edmistj** [comment] 2018-10-24 01:31
Close since it’s a duplicate

**Closed by edmistj** 2018-10-24 01:31 UTC
