### ISSUE TITLE
Legacy Lava Found on demo of DISC Request

### ISSUE THREAD

**Issue by ToxicFume** [SparkDevNetwork/Rock#2018] opened 2017-02-11 18:41 UTC
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

While searching the demo site for Legacy, I noticed that the DISC Request still used Legacy Lava.

### Steps to Reproduce

1. Went to Global Attributes to turn on LegacyWithWarning
2. Ran DISC Request Workflow
3. Checked Exception List 
![discdemo](https://cloud.githubusercontent.com/assets/19920780/22856462/af33fb84-f05f-11e6-828d-fdece76ac259.png)

**Expected behavior:** 

I expected the Legacy to be cleaned out of new installs

**Actual behavior:** 

Legacy is still found in DISC Request

### Versions

* **Rock Version:** Rock Version: Rock McKinley 6.1

* **Client Culture Setting** en-US

**Comment by JimMichael** [comment] 2017-03-24 18:34
Confirmed on 6.2 demo site. Example: {{ Workflow.WarningMessage }}

**Comment by cabal95** [comment] 2017-03-24 22:02
@edmistj Because things like this are created by C# migrations (for example, this one is in the 1.2.0 migration area)... How should these things be resolved?  I assume it is a no-no to just go back and edit the 1.2.0 migration to fix the Lava syntax.

Is the only safe way to do this to have a new migration that checks the database value to see if it has been modified since the 1.2.0 migration first created it, and if not modified then update the value to what it should be?

**Comment by edmistj** [comment] 2017-03-24 22:08
You're right about having to check if the info has been updated in the migration. A lot of times you can check the LastModified date. Most initial migrations have null modified dates.

**Comment by arranf** [comment] 2017-09-09 11:28
@edmistj There are a couple of these issues that I've found that require a migration but have the available label. I think there needs to be something in the contributors guide about how to create a migration with a pull request.

**Comment by edmistj** [comment] 2017-09-09 17:51
@arranf Right, I'll take that as an action item to write something up. I'll also communicate the solution in the Rock Stars Channel to help communicate the solution.

**Comment by ethan-sparkdevnetwork** [comment] 2018-03-20 17:14
Fixed in 3e21ed58.

**Closed by ethan-sparkdevnetwork** 2018-03-20 17:14 UTC
Labels: Fixed in v8.0, Priority: High, Status: Available, Status: Confirmed, Topic: Lava, Type: Bug
