### ISSUE TITLE
Phone Types do not appear for family members in My Account block

### ISSUE THREAD

**Issue by dataCollegechurch** [SparkDevNetwork/Rock#5003] opened 2022-05-09 14:59 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![image](https://user-images.githubusercontent.com/54962439/167437131-3988a338-4b96-4ced-907e-f9117c0a20b9.png)

### Description

When viewing the my account screen on the external website, phone number types display for the first individual next to each phone number. They do not appear next to phone numbers for each additional family members in the household.

### Steps to Reproduce

1. Create or find a record where multiple family members in the household have a phone number.
2. Navigate to the my account page and login.
3. Ensure that Show Phone Numbers is set to true and the corresponding phone types in question are set to be displayed.

**Expected behavior:**

Phone types will show up wherever a phone number is displayed.

**Actual behavior:**

The phone type only shows up for the first person (the logged in person).

### Versions

* **Rock Version: Rock McKinley 12.6 (1.12.6.1)
* **Client Culture Setting: en-US

**Comment by jonedmiston** [comment] 2022-05-09 15:06
This is a duplicate of #4930 which was fixed in v13.4 with this commit.
https://github.com/SparkDevNetwork/Rock/commit/8d681bd19e4f0327b9122d5a643d4fc83a96f230

**Closed by jonedmiston** 2022-05-09 15:06 UTC
