### ISSUE TITLE
Communication Person select not responsive

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#3822] opened 2019-07-26 08:45 UTC
### Description
Checking if this is fixed in v9?

Selecting an individual person using Person picker on New Communication is not fully responsive.  Person picker results appear off the left of the screen making it difficult to see results and click Select.

![image](https://user-images.githubusercontent.com/4658177/61938080-5b428080-afe4-11e9-814a-36a6642b373c.jpg)

### Steps to Reproduce

V 8.8

1. Go to New Communication.
1. Click Select Specific Individual
1. Click Add Person
1. See error

**Expected behavior:**

Add Person should show person results so user can see them and click Select.

**Actual behavior:**

Results are off the screen and Select can not be seen.
(Unless I rotate the screen to landscape, then the keyboard fills the screen.)

### Versions
* **Rock Version:** 8.8 Android v 9 Chrome

**Comment by nairdo** [comment] 2022-07-27 00:40
Greetings @ElimAdmin  We had one of the developers take a look at this issue and after reproducing in v9, he was able to determine the problem was corrected in Rock v12 (via https://github.com/SparkDevNetwork/Rock/commit/79f2f7876e6bc3930f74ab9fd0c9a4ec295ca862).  I'm going to close this as Fixed in v12, but please let us know if you are still seeing this problem.

**Closed by nairdo** 2022-07-27 00:40 UTC
Labels: Type: Bug, Status: Confirmed, Topic: UI, Priority: Low
