### ISSUE TITLE
Giving as a business without a person record in Rock causes an error

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#3664] opened 2019-04-26 14:47 UTC
### Description
Giving as a Business asks for all the business info and then the person info, if the user is not logged in. When the payment is submitted an error is thrown saying there is an issue with the person record. When I am logged in, giving as a new business works fine but the issue arises when the user isn't logged in and the system tries to create a new person record for them.

I looked on the Exception List page to see if the error would be listed with more information but  I didn't see anything in the list so I'm not certain what is causing a person record to not be created. 

### Steps to Reproduce
1. Go to the Give page and make sure you are not logged in.
1. Select the Business option and give $1.00 to an account and fill out the business and person info.
1. Enter payment info and submit/finish.
1. See error

**Expected behavior:**

Should be able to create a new person record without error (or add a known relationship between the business and a person record with the same first name, last name, and email).

**Actual behavior:**

Error displayed when creating the person record if the person isn't logged in and isn't in the system.

### Versions
* **Rock Version:** 1.8.7.6
* **Client Culture Setting:** en-US ![](https://user-images.githubusercontent.com/5738650/56815781-c030e380-6807-11e9-91a9-e42baf2492dd.png)

**Comment by nairdo** [comment] 2019-07-30 23:27
There is a chance this was fixed via this v9.0 fix: https://github.com/SparkDevNetwork/Rock/commit/419a512222977ce26a918cef0b095a96aee4e092#diff-c645d0465c1839e2c65f8a31ced3d246  

It would be fantastic if someone could confirm that... (2 points to whoever confirms this).
If so, then this might be a duplicate of #3663

**Closed** 2019-08-06 20:40 UTC
Labels: Topic: Finance, Type: Bug

**Comment by ethan-sparkdevnetwork** [comment] 2019-08-08 17:10
This was an issue with the NMI gateway only. The TransactionEntry block expected a person to already exist and did not attempt to create one. Updated the code to create one in the same manner as the other gateways.
