### ISSUE TITLE
Mobile Checkin Does Not Honor Prevent Duplicate Check-In

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4525] opened 2020-12-17 19:41 UTC
### Description

I'm actually not sure if this would be considered a bug, or an enhancement... but it **seems** like buggy behavior... which is: when scanning a QR code at a kiosk to print labels after checking-in on mobile, you can scan the code and print a tag as many times as you want... the youth will have LOTS of "fun" with it! ;-)

### Steps to Reproduce

1. Check in via mobile
2. Scan QR code at an ipad kiosk to print tag
3. Lather, rinse, repeat!

**Expected behavior:**

I think the expected behavior is that the system would honor the _Prevent Duplicate Check-In_ setting on the Check-in config, and prevent repeat "check-ins" (which in this context are really just "label prints" from occurring. 

**Actual behavior:**

You can print as many labels as your heart desires... or until the youth director notices, whichever comes first.

### Versions

* **Rock Version:** 11.0+

**Comment by stewmystre** [comment] 2020-12-18 10:43
I will note the _Prevent Duplicate Check-In_ still works in that the system only records a single attendance record even if the user checks in via their mobile (or another family member does it as well on their mobile).  So this is as you say in your expected behavior just a duplicate label print issue related to Mobile Check-in. I think it would still be useful for a Check-in Manager to be able to override and re-print then tag when required though.

**Comment by JimMichael** [comment] 2020-12-22 19:35
Well, just to further muddy the waters... even when you have _Prevent Duplicate Check-in_ *disabled*, and you "check-in" mutiple times, you do not get multiple attendance records. It really does act only like a "don't allow person to get another tag" feature, since it's not possible to check into the same area/schedule multiple times, anyway.

**Comment by nairdo** [comment] 2021-06-08 19:13
I know you may have just been reporting this on behalf of someone else, but I wanted to let you know that we had a chance to discuss this with the team...

The printing via the Mobile Check-in QR code is not intended to prevent printing tags multiple times. Since it can be used in a self-serve situation (or perhaps even with an unskilled attendant) where anything could go wrong with printing/tearing/jamming labels, we took the approach to just allow printing/reprinting if you have the secret QR code.

Although we'll close this as 'not a bug', as always, you can submit an idea for community voting over at our Ideas board: http://community.rockrms.com/Ideas

**Closed by nairdo** 2021-06-08 19:13 UTC
Labels: Topic: Check-in, Type: Discussion
