### ISSUE TITLE
Content Channel {slug} not setting page title, Now {slug} not working starting with v6.6 at all

### ISSUE THREAD

**Issue by tommyprater** [SparkDevNetwork/Rock#2186] opened 2017-05-08 21:44 UTC
### Prerequisites
* [ x] Put an X between the brackets on this line if you have done all of the following:
    *x Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    *x Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    *x Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

***Update, starting with version 6.6 the {slug} for url does not work at all. When used the content channel will not display any results. If {item} is used it will.

When using the route or "slug" it would not change the page title on the page even though its been set on the content channel to "set page title".

<a href="http://s1067.photobucket.com/user/tommyprater/media/ContentChannelBug_zpsrxxlddwb.png.html" target="_blank"><img src="http://i1067.photobucket.com/albums/u423/tommyprater/ContentChannelBug_zpsrxxlddwb.png" border="0" alt=" photo ContentChannelBug_zpsrxxlddwb.png"/></a>

### Steps to Reproduce
"following the directions in the manual"
1. Added Item Attribute "slug" to content channel. 
2. Added the route on page "series/{slug}"
3. In the content channel view block check the set the page title checkbox.

**Expected behavior:** 

I expected it to load as it would if you loaded "/page/5405?item=xxx"

**Actual behavior:** 

When using the route or "slug" it would not change the page title.

### Versions

* **Rock Version:** 6.2 and 6.3
* **Rock Version: Update ** starting with 6.6
* **Client Culture Setting:** en-US

**Comment by tommyprater** [comment] 2017-09-07 15:28
***Update, starting with version 6.6 the {slug} for url does not work at all. When used the content channel will not display any results. If {item} is used it will.

**Comment by cabal95** [comment] 2017-10-10 03:10
I just ran into this on my server, so I can spend some time looking for a fix and submit a patch if @azturner hasn't had time to work on it.

@tommyprater I wasn't able to replicate the "not working at all" portion on 6.9. I am using a "slug style" filtered on an attribute value and it pulls up the content channel item correctly. Just still not setting the title.

**Comment by azturner** [comment] 2017-10-10 23:43
@cabal95 I have not looked at this yet, so feel free to take a look.

**Comment by cabal95** [comment] 2017-10-15 17:13
@tommyprater I believe this is working correctly in 6.9. Here is what I found.

1. The Page Route slug must match the attribute key in CaSe.  So `slug` != `Slug`.
2. The Set Page Title is also working, just maybe not as expected without a careful reading of the documentation. If `Item` is specified then it will set the Page Title to the title of the _item_; otherwise it sets the Page Title to the title of the _channel_.

Since I wanted the item title to be the page title, I ended up using `{{ Items | First | Property:'Title' | SetPageTitle }}` to set the page title to the title of the item.

**Comment by tommyprater** [comment] 2017-10-15 17:24
@cabal95 ok thanks I will test it and see. I'm on 6.9.

**Comment by cabal95** [comment] 2017-10-23 23:24
@tommyprater Any feedback on this?

**Comment by tommyprater** [comment] 2017-10-26 15:39
@cabal95 sorry for the delay I was out of the office for a death in the family. Getting back to this and testing. I will try to update in the next day or so.

**Comment by tommyprater** [comment] 2017-10-28 02:22
@cabal95 I tested changing the attribute key to "Slug" and set the page route to "watch/{Slug}" and its doing the same effect as if I was using "slug". Still not working at all.

**Comment by cabal95** [comment] 2017-10-31 17:25
Okay, with lots of help from @tommyprater I think we have found the problem, and it looks like it is fixed in v7 by this commit c4a073cad64c299c5b8e9ed8f16477247b68d27c and a few other related commits.

The problem is related to duplicate Attribute key's with different EntityTypeQualifierValues. Pre-v7 this causes the attribute names (for reporting/filtering purposes) to be renamed to things like `Slug1`, `Slug2`, etc. which obviously causes issues in the query string matching. As far as we can tell, this is fixed in v7 but since some of the fixes are in the core DLLs we can't test on his system. But doing the same setup on my v7 dev instance doesn't have the same problem and the code changes do appear to be intended to fix these issues.

**Closed by cabal95** 2017-10-31 17:25 UTC
Labels: Priority: Critical, Status: Confirmed, Type: Bug
