### ISSUE TITLE
Multiple messages received when using BCC

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#2753] opened 2018-02-08 22:52 UTC
### Prerequisites
* Put an X between the brackets on this line if you have done all of the following:
    [ ] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    [X] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When using the BCC field on the new communications module, the BCC recipient receives an individual message for each standard recipient

### Steps to Reproduce

1. Start a new communication to a group or list of more than one person
2. Provide your email address in the BCC field
3. Send the message

**Expected behavior:** 

I expected to receive a single copy of the message. I don't honestly know what would be in the "To" field; nothing? My address? Would the list of the recipients be at the top of the body on my message for my records?

**Actual behavior:** 

I receive one copy of the message for every recipient the message was sent to. So if I sent the message to seven people, I received seven copies of the same message to my address

Perhaps this is working as intended, so I know who all received my message. But it was very unexpected and I fear could confuse a lot of users

### Versions

* **Rock Version:** 1.7.2  
* **Client Culture Setting:** EN-US

**Comment by edmistj** [comment] 2018-02-09 14:25
This is an interesting issue. Since each email is personalized just to the recipient what should the BCC field (or for that matter CC field) be used for? 

It almost doesn't make sense to have them. 

I suppose one option would be to only CC/BCC them on the first message? 

Discuss!

**Comment by mikejed** [comment] 2018-02-09 14:34
Agreed. The "best" solution I could come up with (though it's problematic itself) would be to send the BCC/CC recipients the message, with To: blank. CC recipients could be in the CC field, and BCC recipients would obviously be invisible. Then the recipients the message was ACTUALLY sent to might be included in a list inserted at the top of the body. Which is difficult to correctly insert above any possible template the message may have been composed with. But not only is that difficult, it would break replies from CC recipients.

I did not check, but I'm curious whether the recipients see CC recipients in the messages they receive...

**Comment by mikejed** [comment] 2018-02-09 14:42
Or should there be a mode of emails where they're sent out as a single message instead of individuals? Then that would be the only mode with cc and bcc

**Comment by cabal95** [comment] 2018-02-09 16:35
Just noting this info.  Remember the TO and CC fields in an e-mail do nothing (except maybe with some spam filters) except display text. You can compose an e-mail with an e-mail address in the CC field and it won't send to that address.  The issue is that the system that actually SENDS the e-mail is taking the value passed for CC and putting it in the message header AND sending them a copy of that message. Normally this would be fine, but for the way we compose and send messages I think it would be considered incorrect behavior.

In the case of a CC, my thinking would be that the CC field should be filled in so that the recipient can see it and a reply-all works as expected; but the CC'd person would not actually be sent a copy of the message.

I'm not sure BCC ever makes sense for what we are doing. I think the use case for BCC is called "Send Test".

**Comment by JimMichael** [comment] 2018-02-09 17:57
It’s been a long time, but if I recall the original request (from me) to add CC/BCC functionality to Rock email revolved around the Email Form block, which we use extensively for inbound forms on the web site. We wanted the ability to have a form come in addressed to a distribution group (in our email system) but also cc/bcc another address. (Something we got used to with Arena’s Email form block) Ironically, the Email Form block didn’t get this enhanced functionality in v7 :-)

**Comment by nairdo** [comment] 2018-02-20 05:52
A BCC and CC *should* receive a copy of each email -- especially since the communications are personalized and sent to individual people. If this wasn't done, the CC couldn't reply-all back to the sender/recipient to discuss the matter of the email. If one doesn't want an email for each recipient then those fields should not be used.

Only in the case of an actual mailing-list (which Rock doesn't support today), which would be non personalized by definition would, there be only one email sent to the CC and BCC.  Then the recipients would each be on the [RFC-822] envelope of each message and the To: field would typically display the distribution list name.

**Comment by edmistj** [comment] 2018-02-20 15:14
Lot's of good input here. Let's wrap this up. I'd be inclined to keep this running as is (per Nick's comments) but add better help text to explain what is going to happen. 

Thoughts?

**Comment by JimMichael** [comment] 2018-02-26 15:56
I'd vote for leaving it as-is, but also implementing CC/BCC in the EmailForm block where it's more useful ;-)

**Comment by edmistj** [comment] 2018-02-26 18:05
Ugh, just realized we never added it to that block, which was a big driver to refactoring the email send methods. We'll add that to the task list.

**Comment by edmistj** [comment] 2018-02-26 18:57
@mikejed @nairdo Are we all OK with this approach? If so I'll close the item.

**Comment by mikejed** [comment] 2018-02-26 19:14
I think there are technically "neater" solutions but they would probably cause confusion. So for clarity and best UX I think a note informing the user of what it means to use those fields is the best use of time, yes. Though I agree that they may not be necessary here at all, since they aren't very useful.

Perhaps the ability to select a new list/group when choosing to "copy communication" would alleviate any remaining need for cc/bcc in the communicate block (I think that's already a black book idea)

**Comment by edmistj** [comment] 2018-02-27 00:20
Closing based on input (but I do like the details ;)

**Closed by edmistj** 2018-02-27 00:20 UTC
Labels: Type: Discussion
