### ISSUE TITLE
Connection Board Filtering Error

### ISSUE THREAD

**Issue by tikool17** [SparkDevNetwork/Rock#5040] opened 2022-06-08 20:50 UTC
### Description

On the Connection Board, filtering by "My Connections" also applies 3 additional filters: "Active" "Future Follow Up" and "Only Past Due"

### Steps to Reproduce

1. On the Connection Board clear all filters. 
<img width="1828" alt="Screen Shot 2022-06-08 at 4 14 57 PM" src="https://user-images.githubusercontent.com/32227063/172713591-02dda223-9f35-4510-bf27-0c16321c225a.png">

2. Change filter from **All Connectors** to **My Connections**
<img width="817" alt="Screen Shot 2022-06-08 at 4 15 16 PM" src="https://user-images.githubusercontent.com/32227063/172713638-fdbbf211-e989-4805-a127-408586cc0630.png">

**Expected behavior:** 

It should show Connections assigned to me.

**Actual behavior:** 

Three additional filters are automatically applied: "Active" "Future Follow Up" and "Only Past Due".
<img width="1832" alt="Screen Shot 2022-06-08 at 4 15 34 PM" src="https://user-images.githubusercontent.com/32227063/172713888-dea7684e-a261-449d-aee2-d272929bb102.png">

### Versions

* **Rock Version:** Rock McKinley 13.3 (1.13.3.1)
* **Client Culture Setting:** en-US

**Comment by leahjennings** [comment] 2022-06-10 02:42
@tikool17 thanks for submitting this! I see how this may appear to be a bug, however the _My Connections_ button is working by design. Even if no filters are set, the _My Connections_ button is intended to show you the the connection requests assigned to you _that currently need your attention_, which would be those that are Active, and past-due Future Follow-Up.

If you'd like to see _all_ the connection requests assigned to you, regardless of the connection state, you can instead choose your name from the same drop down menu where you would select _My Connections_.

Thank you for helping better the Rock community!

**Closed** 2022-06-10 02:43 UTC
Labels: Type: Discussion
