### ISSUE TITLE
Word Merge - Families where individuals have different last names

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#1815] opened 2016-10-18 19:02 UTC
### Prerequisites
- [x ] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
- [ ] Did you include your Rock version number and client culture setting?
- [ ] Have you attached your [environment and diagnostics information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
- [x ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?
### Description

I have a family that where the two individuals are married – but each kept their own last name. (both are Doctors)

When you do a word merge it seems to use the Family name as the last name instead of the individual persons last name

For example Ted Decker and Cindy Smith are married. The families name is Decker.  The word merge should address this as Ted Decker & Cindy Smith.

**Expected behavior:** [What you expected to happen]
The word merge should address this as Ted Decker & Cindy Smith.

**Actual behavior:** [What actually happened]
The word merge uses Ted & Cindy Decker.
### Versions
- **Rock Version:**  5.4

**Comment by nairdo** [comment] 2016-11-11 07:26
Unable to reproduce on the demo server (v5.3) nor on my dev system (v6.1) using the "Envelope - Home Address" template. Is your template using the correct merge field specifier ({{ Row.FullName }})?

![image](https://cloud.githubusercontent.com/assets/383807/20207570/6a60ec90-a7a5-11e6-8a0c-3b13381c26c4.png)

when merged, becomes:
![image](https://cloud.githubusercontent.com/assets/383807/20207532/1bfbddee-a7a5-11e6-88f6-9f0f003f0595.png)

**Closed by nairdo** 2016-11-11 07:26 UTC
