### ISSUE TITLE
HTML in Email Template Text Version

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#1384] opened 2016-02-08 18:17 UTC
If you attempt to save an Email Template with a HTML tag in the text version of the message the template will not save but no error message will be produced.

**Comment by azturner** [comment] 2016-02-16 14:29
@arranf , I couldn't reproduce this. Any time I enter HTML into any of the fields, it shows this message...
![image](https://cloud.githubusercontent.com/assets/548180/13078949/f334f85e-d47e-11e5-88ad-0db6e984fc84.png)

**Comment by nairdo** [comment] 2016-03-01 06:09
@arranf are we OK to close this issue now?

**Comment by azturner** [comment] 2016-06-10 13:23
@arranf , Closing this. If it's still an issue, please re-open.

**Closed by azturner** 2016-06-10 13:23 UTC
