### ISSUE TITLE
Upgraded to Rock McKinley 12.6 (1.12.6.1)- and Lost modules for Healing Center

### ISSUE THREAD

**Issue by white3tj** [SparkDevNetwork/Rock#4877] opened 2022-01-13 15:56 UTC
When I upgraded our Rock instance to Rock Version: Rock McKinley 12.6 (1.12.6.1) the Healing Center profiles lost the Future Stories, Future Story Files, and Future Story Links blocks on the Personal Profile page. I have attached an image and circled the modules that are missing in yellow. We need to have that data restored. Thanks

![futureStories](https://user-images.githubusercontent.com/85329759/149363682-43394cb7-e08a-4bb1-a500-9516fb66519a.jpg)

**Comment by smross** [comment] 2022-01-13 17:48
@white3tj that stinks! Welcome to Github. I don't think I've met you before, so it's good to meet you.

The _Future Story_ tab you're referencing looks like something that was added to your Rock instance (and not included 'stock' as part of Rock).
A couple questions:

- Do you know of any backups that you have for your Rock instance?
- Are you the primary 'point person' for Rock at your organization?
- Which organization do you serve at?

I know there are people in the Rock community (such as myself) that will help where we can, and the above information will help get you connected

**Comment by white3tj** [comment] 2022-01-13 17:54
Hi, To answer your questions, yes I am the primary contact. I am the IT Director for the Vineyard Cincinnati Church. The Healing Center sits on our campus both physically and virtually. The employees work for VCC also, even though they have a separate 503c. We took a backup when we moved our DB into Azure September 2021, but we may also have others

**Comment by smross** [comment] 2022-01-13 18:07
> Hi, To answer your questions, yes I am the primary contact. I am the IT Director for the Vineyard Cincinnati Church. The Healing Center sits on our campus both physically and virtually. The employees work for VCC also, even though they have a separate 503c. We took a backup when we moved our DB into Azure September 2021, but we may also have others

Thanks for the answers.

1. I'd recommend _also_ getting connected on Rocket.Chat
2. If you're using Azure SQL, you _should_ have point-in-time recovery options available
3. At first glance this probably is _not_ an issue with the Rock codebase, but something that is amiss in your Rock instance
4. Do you work with a partner, or someone that setup the Story functions? 
5. Did you happen to run the upgrade on a test instance of Rock before upgrading this Rock instance?

Do you have documentation on how the story functions were built, and what entities they are utilizing (notes?, entity documents, storage providers, atrributes, etc?)

**Comment by white3tj** [comment] 2022-01-13 18:16
Brock Zagel is my Triumph contact. He is more familiar with our environment. This is the message I received from him this morning ....

_Hi Tonya,

I am the main point of contact, so keep messaging me.

I can take a quick look at it this afternoon or tomorrow and try to see if it is an easy fix. If not, we may be able to do a mini-project under the reverse retainer that we still have with you for our normal hourly rate.

To help future-proof this, you can submit a bug in the github issues area so the core team can improve their update processes and scripts in future releases. They try to think of every instance that could be affected in an update, but sometimes they miss things.

https://github.com/SparkDevNetwork/Rock/issues You can create a free account if you don’t have one already. Then add a New Issue with as much detail as possible – i.e. what type of blocks were used on the pages, screenshots, etc.

Brock__

**Comment by smross** [comment] 2022-01-13 18:23
Great, then I'd continue on that path. Make sure (in particular) to include the details mentioned such as block data, etc.

I'm guessing this will be something you need to work on with Triumph (unless you want to attack it on your own).

**Comment by shauncummings** [comment] 2022-02-04 19:52
Resolved in https://github.com/SparkDevNetwork/Rock/commit/bb4f6ad945373cf934d01148f2b854fb06d3d999.

**Comment by shauncummings** [comment] 2022-02-04 19:58
For the benefit of anyone else who may be experiencing similar problems:  This is a JavaScript error caused by use of certain blocks that add a "quick return" link to your personal links.  If the Personal Links block is not present on the page, the JavaScript generated by these blocks will cause an error which may prevent other controls on the page from working.  In this specific case, they are using the Personal Attribute Value block with an HTML field, and the JavaScript error stops the HTML editor from loading correctly.

This is resolved in v13.1, but a temporary workaround is to add the Personal Links block to the page (probably in the site header zone).

**Closed** 2022-02-04 20:00 UTC
Labels: Type: Bug, Status: Confirmed, Topic: CRM, Fixed in v13.1
