### ISSUE TITLE
Previous year contribution statements

### ISSUE THREAD

**Issue by kevinkrugerCCV** [SparkDevNetwork/Rock#5677] opened 2023-11-14 21:56 UTC
### Description

In viewing a contribution statement from a previous year, selecting a statement option redirects the user to display a contribution statement but shows for the current person rather than the persons profile that was being viewed. 

![image](https://github.com/SparkDevNetwork/Rock/assets/91297818/44aab264-4ad0-4c74-9989-6b0a63c85355)

Because there is no contribution history in the rock demo site, I am not able to reproduce there. I did reproduce this in a v12 instance we still have running and it redirected to the appropriate persons statement.  I reviewed the code we have in that v12 and compared to what we have running in v14.2 and saw there was a notable change to the code in the version 12 compared to 14. 

### Actual Behavior

Logged in as a staff member, while viewing a persons contribution tab you are able to see previous year contribution statements that will open a PDF statement.  When selected the redirect seems to be using the "CurrentPerson" guid. 
 
Starting on this page - 
![image](https://github.com/SparkDevNetwork/Rock/assets/91297818/df1a34e4-c833-4909-afc2-9286f619d640)

After selecting "2020"
![image](https://github.com/SparkDevNetwork/Rock/assets/91297818/94368d21-710d-4afc-be7b-8f8bc2751100)

### Expected Behavior

The expected behavior would be when you select the year, the user is redirected to view that individuals contribution statement rather than the person that is logged in. 

### Steps to Reproduce

- Go to a persons profile that has prior year contributions. 
- Click on the contribution tab
- Click a button under the "Contribution Statements" that is labeled as the year. 
- See the page redirected to the statement for the person logged in rather than the person viewed. 

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

14.2

### Client Culture Setting

en-US

**Comment by chead4** [comment] 2023-11-15 21:14
@kevinkrugerCCV Hi Kevin.  I am not able to recreate this issue.  I have tried on v14.3, v16.0 (rocksolidchurchdemo.com Ted Decker's account), v15.3 and v16.1.  

![image](https://github.com/SparkDevNetwork/Rock/assets/134172019/7ddf7e84-c546-4683-b932-6718a6a13ba4)

**Comment by bmurphy-dev** [comment] 2023-11-15 21:37
@kevinkrugerCCV you need to switch out the old Contribution Statement Lava (Legacy) block to the new Contribution Statement Generator block for proper impersonation with the new Giving Configuration block which makes those yearly buttons.
@chead4 I can confirm that this is not a bug, but a user misunderstand when upgrading Rock from an older version which changed this area in Contribution Statements from v12 to v13+

@kevinkrugerCCV I did a deep dive on this at RX this past year and [you can get my slides and videos here](https://simpledonation.com/resources/rx2023-takeaway).

**Comment by chead4** [comment] 2023-11-15 23:13
@bmurphy-dev Thank you!  Closing this issue.

**Closed by chead4** 2023-11-15 23:13 UTC
Labels: Not Yet Reproduced
