### ISSUE TITLE
Upload Photo creates two files on the latest develop

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1204] opened 2015-08-19 16:01 UTC
@edmistj @azturner I'm getting an error "The '' component does not exist, or is not active" when I try to upload a photo based on the latest develop code.  It happens with the "Person Image" BinaryFileType regardless if the storage type is FileSystem or Database.

I've cleaned and done a full rebuild on a fresh database and still get the error:
![image](https://cloud.githubusercontent.com/assets/1210933/9361438/71dc1b3c-4669-11e5-8a8b-dc75c072c69d.png)

The file is also uploaded successfully, but created twice:

![image](https://cloud.githubusercontent.com/assets/1210933/9361443/75e4c616-4669-11e5-8a05-f74e64aa3d96.png)

I thought maybe one was a small thumbnail, but when I switched to the FileSystem storage type there are two files saved (with different guids) that are the same size.

**Comment by azturner** [comment] 2015-08-19 17:19
yeah, we don't allow cat photos, sorry ( I had to overrule @mikepetersonccv  on that one ).

**Comment by azturner** [comment] 2015-08-19 17:20
Seriously though... I wasn't able to reproduce this. When you go to the system settings > File Storage Providers, do you just see the two providers and are they both active?

**Comment by dcs619** [comment] 2015-08-19 18:22
I stepped through the DbContext.Save and realized the trigger for Person changes was trying to fire but didn't have any workflow actions to process.  I was hoping to find the exact object/component that was returning that error message but I kept getting recursive calls on this line: https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Model/WorkflowActivity.cs#L243

I'm guessing at some level "this" or the "Object entity" parameter was null so that's what's being referenced in the error message.  Sorry to interrupt!

**Comment by dcs619** [comment] 2015-08-19 18:34
In answer to your question, yes, both storage providers were active.

**Comment by dcs619** [comment] 2015-08-19 19:51
@azturner I'm still seeing the double creation when I upload a file.  Any idea why?

**Comment by mikepetersonccv** [comment] 2015-08-31 18:37
ok, so the double-creation is because a file is uploaded, and then it is presented to be cropped.  If it is cropped, both the uncropped original and the cropped image are in the database, but the cropped one is what is assigned to the Person's photo.  So it is actually working correctly :).  However, it is confusing, so I added code to clean up the uncropped photo if it ends up getting orphaned

**Closed** 2015-08-31 18:38 UTC

**Comment by edmistj** [comment] 2015-08-31 18:40
@mikepetersonccv do we need to add a sql statement in a migration to clean up these orphaned files in peoples databases?

**Comment by mikepetersonccv** [comment] 2015-08-31 18:43
@edmistj The orphaned files have IsTemporary=true, so the RockCleanup job will eventually delete those images. This fix just makes them cleanup right away vs waiting for RockCleanup to do it
