### ISSUE TITLE
Rock RMS license is not open source

### ISSUE THREAD

**Issue by ddevault** [SparkDevNetwork/Rock#5164] opened 2022-09-13 09:58 UTC
"Open source" is defined by the Open Source Definition, and the Rock license does not meet these criteria.

https://opensource.org/osd

It is wrong to portray your project as open source when it does not meet the qualifications for the term. A better term for this kind of license is "source available".

**Comment by ssddanbrown** [comment] 2022-09-13 14:16
Related to #5068

**Comment by ddevault** [comment] 2022-09-13 14:23
2 Corinthians 8:21

**Comment by jonedmiston** [comment] 2022-09-14 06:50
Duplicate of #5068

**Closed** 2022-09-14 15:37 UTC
