### ISSUE TITLE
Rock Image Browser Doesn't Add Image if the User Clicks "OK" Before the Image Data is Loaded

### ISSUE THREAD

**Issue by stphnlee** [SparkDevNetwork/Rock#4791] opened 2021-09-22 15:38 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

The Image Picker is written such that when an image is selected from the image browser, the image data isn't inserted into the form until an AJAX callback to the server for additional data about the image is received. If there is a long enough delay, the user can click "OK" before the image data is loaded, in which case the image is not inserted into the HTML Editor.

### Steps to Reproduce

1. Open an HTML Editor anywhere in Rock
![edit-html](https://user-images.githubusercontent.com/902855/134368132-883c5220-af12-4831-946e-3ac7eb061dfc.png)
2. Open the "Image Browser"
![image-browser](https://user-images.githubusercontent.com/902855/134368412-4b3dd87e-e2f7-4223-a128-7322fb154fde.png)
3. Select an image
4. Click "OK" before the call for the image data is returned.
![image](https://user-images.githubusercontent.com/902855/134368870-08a0377c-5fd0-4e9f-a53e-6d7f4b0b0753.png)

**Expected behavior:**

The user should be able to click "OK" as soon as they select an image and have it show up in the HTML editor.

**Actual behavior:**

If the user clicks "OK" before the call for the image data is returned, the image is not added into the editor.

The code that loads the image into the HTML editor is located here: https://github.com/SparkDevNetwork/Rock/blob/e9c5e5c1c72f68527e6481a7277cd17cfb753b44/RockWeb/Scripts/summernote/plugins/RockImageBrowser.js#L26

It gets the image by loading a hidden field with a class `js-filebrowser-result`. This isn't guaranteed to have a value if the user clicks "OK" before the data is loaded by this code: https://github.com/SparkDevNetwork/Rock/blob/e9c5e5c1c72f68527e6481a7277cd17cfb753b44/RockWeb/Blocks/Utility/HtmlEditorFileBrowser.ascx#L137

### Versions

* **Rock Version:** 12.5
* **Client Culture Setting:**  en-US

**Comment by cwomack** [comment] 2021-09-22 23:45
@stphnlee, we're throwing the "Available" tag on this to open up to the community to comment and see if there's ideas on a better solution to consider (via potentially a Pull Request). 

I had initially marked it as "Not Yet Reproduced" due to minimal/no impact seen on our side when trying to replicate this bug under normal circumstances.  However, I **did** see it happen if I throttled the brower's "Network" in the DevTools to "Slow 3G".  It's unlikely that this will impact most environments running Rock, but wanted to let you know it was confirmed if the network speeds are slow enough.

**Closed** 2021-11-02 17:14 UTC
Labels: Status: Confirmed, Status: Available
