### ISSUE TITLE
Event Registrations: First and Last Name Disabled

### ISSUE THREAD

**Issue by billdeitrick** [SparkDevNetwork/Rock#4942] opened 2022-03-15 19:29 UTC
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Description
When an Event Registration Template is configured with "Registrants in the Same Family" set to "Ask" and "Show Family Members" set to "Yes", as shown below, the "First Name" and "Last Name" fields on the registration are pre-filled with the logged in user and disabled when the Registration Entry block loads. 

![Snag!UNITO-UNDERSCORE!17f5dc9d](https://user-images.githubusercontent.com/4174527/158454546-d0687973-30c6-4f76-94c7-06196aa7d51d.png)

![Snag!UNITO-UNDERSCORE!17f5f14e](https://user-images.githubusercontent.com/4174527/158454561-f476e852-8fe2-4382-9aa7-35cce6460b18.png)

This changed in 12.8 and is different from the behavior in 12.7. In 12.7, the fields were not pre-filled until a family member was selected. In 12.8 and 13.x, even when selecting "None of the Above" the first and last name fields remain disabled. The only way to enable these fields in Rock versions >= 12.8 is by selecting the family, then selecting an individual, then selecting the blank dropdown entry to enable the first and last name fields as shown below.

![4D695BFE-0768-4047-B72C-F1363476AE68](https://user-images.githubusercontent.com/4174527/158454963-b71dce29-7413-4329-b17b-e6835ecf90e1.GIF)

### Steps to Reproduce
1. Sign in to the Rock demo site
1. Navigate to the Baptism event registration template
1. Set "Registrants in the Same Family" to "Ask" and check "Show Family Members"
1. Create a new registration instance that is currently active
1. Navigate to the event registration page on the external site (/Registration?RegistrationInstanceId=[INSTANCEID]
1. First and last name fields are prefilled and disabled for the registrant, even if the "...same immediate family as", and can't be enabled without selecting a family member and then setting the family member dropdown to the blank value

**Expected behavior:**

First and Last name fields would be editable immediately when loading the registration page on the external site even when the user is logged in, as they had been in 12.7.

**Actual behavior:**

First and last name fields aren't editable when a logged-in user loads the page containing the registration entry form, and don't become editable without selecting and then deselecting a family member as the registrant. This workaround isn't an intuitive process for a registrar to complete when registering someone not in their immediate family as the first registrant.

### Versions
* **Rock Version:** 13.0 (1.13.0.30)
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1202212304242303">4942-repro.gif</a>

**Comment by JimMichael** [comment] 2022-03-18 15:52
Just wanted to add that we are still seeing this in 13.2.

**Comment by crayzd92** [comment] 2022-03-22 18:04
Fixed in 13.3 with https://github.com/SparkDevNetwork/Rock/commit/2a7071d6da35530bf78083af5b7cea8100d6dd85

**Comment by CompassSkelly** [comment] 2022-03-28 15:57
Will this be a fix considered for v12?  If not will v12.8 be the last v12 release?

**Comment by jamrphy-bwd** [comment] 2022-04-14 21:37
[2a7071d](https://github.com/SparkDevNetwork/Rock/commit/2a7071d6da35530bf78083af5b7cea8100d6dd85) seems like only a partial fix - the "None of the above" option works, but there remains an issue with selecting Alisha Admin's family:

Looking at the above gif, even when Alisha Admin's family is selected, the Family Member selection is blank and the name is still disabled. Perhaps Alisha Admin has a new foster kid or her family's information is incomplete - the fields are disabled, so she cannot enter a new name:
![image](https://user-images.githubusercontent.com/44368014/163474822-2f03b7c6-d7c7-4964-ac7a-38fe40765801.png)

Instead, she has to go through the same selection/deselection process outlined above - select a name, then select the empty ListItem.

I think either one of these two options could be expected behavior:
1. Since "Show Family Members" is "Yes", do not prefill fields until a family member is selected. (related to [e7d633c](https://github.com/SparkDevNetwork/Rock/commit/e7d633c8e19731aa201973f648fd15d88b3f5065)?)
2. Since we select the Current User's family, default the family member field to the current user so that it is made consistent with the prefilled fields.

(Demo is 13.2 still. I tested on the Pre-alpha site, which was v14, but it had the partial fix.)

**Comment by lauweijie** [comment] 2022-04-30 02:47
Should this be reopened given the comment above?

**Comment by crayzd92** [comment] 2022-05-02 16:40
Reopening based on the family member drop-down behavior.

**Closed** 2022-05-05 22:08 UTC
Labels: Type: Bug, Status: Confirmed, Fixed in v13.4

**Comment by BemaDavidBensen** [comment] 2022-06-16 18:53
Bumping to ask if this Fix will be put into v12.
