### ISSUE TITLE
[Alpha 1.16.0.11] Rock Update Helper v16.0 - Update Media Element Default URLs Failed 

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5583] opened 2023-09-09 20:02 UTC
### Please go through all the tasks below

- [ ] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

The _Rock Update Helper v16.0 - Update Media Element Default URLs_ Job failed upon a fresh install of Rock v16.0.

This job did _not_ fail when updating to v1.16.0.10 but _did_ fail when updating to v1.16.0.11.

After running the job manually, it did complete successfully.

<img width="1601" alt="Screenshot 2023-09-08 at 23 24 58" src="https://github.com/SparkDevNetwork/Rock/assets/23226974/517d4585-bed5-4ea7-bbb9-9ec150fe9231">

<img width="1579" alt="Screenshot 2023-09-09 at 16 01 03" src="https://github.com/SparkDevNetwork/Rock/assets/23226974/adae7a0b-eb67-4d04-8583-ee6d43531803">

Stack Trace:
```
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
   at System.Data.SqlClient.TdsParserStateObject.TryReadUInt32(UInt32& value)
   at System.Data.SqlClient.TdsParserStateObject.TryReadPlpLength(Boolean returnPlpNullIfNull, UInt64& lengthLeft)
   at System.Data.SqlClient.TdsParser.TryReadPlpUnicodeChars(Char[]& buff, Int32 offst, Int32 len, TdsParserStateObject stateObj, Int32& totalCharsRead)
   at System.Data.SqlClient.TdsParser.TryReadSqlStringValue(SqlBuffer value, Byte type, Int32 length, Encoding encoding, Boolean isPlp, TdsParserStateObject stateObj)
   at System.Data.SqlClient.TdsParser.TryReadSqlValue(SqlBuffer value, SqlMetaDataPriv md, Int32 length, TdsParserStateObject stateObj, SqlCommandColumnEncryptionSetting columnEncryptionOverride, String columnName)
   at System.Data.SqlClient.SqlDataReader.TryReadColumnData()
   at System.Data.SqlClient.SqlDataReader.TryReadColumnInternal(Int32 i, Boolean readHeaderOnly)
   at System.Data.SqlClient.SqlDataReader.TryReadColumn(Int32 i, Boolean setTimeout, Boolean allowPartiallyReadColumn)
   at System.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at lambda_method(Closure , Shaper )
   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper.HandleEntityAppendOnly[TEntity](Func`2 constructEntityDelegate, EntityKey entityKey, EntitySet entitySet)
   at lambda_method(Closure , Shaper )
   at System.Data.Entity.Core.Common.Internal.Materialization.Coordinator`1.ReadNextElement(Shaper shaper)
   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.SimpleEnumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Rock.Jobs.PostUpdateJobs.PostV16UpdateMediaElementDefaultUrls.SetDefaultUrls() in \Rock\Jobs\PostUpdateJobs\PostV16UpdateMediaElementDefaultUrls.cs:line 98
   at Rock.Jobs.PostUpdateJobs.PostV16UpdateMediaElementDefaultUrls.Execute() in \Rock\Jobs\PostUpdateJobs\PostV16UpdateMediaElementDefaultUrls.cs:line 53
   at Rock.Jobs.RockJob.ExecuteInternal(IJobExecutionContext context) in \Rock\Jobs\RockJob.cs:line 162
   at Quartz.Core.JobRunShell.Run()
```

### Expected Behavior

Job would not fail.

### Actual Behavior

Job did fail.

### Steps to Reproduce

See above

### Rock Version

v16.0

### Client Culture Setting

en-US

**Comment by PraveenMathew92** [comment] 2023-09-11 19:12
Thanks for reporting this. After going through another similar discussion on the [Microsoft forum](https://learn.microsoft.com/en-us/answers/questions/558374/system-data-sqlclient-sqlexception-a-transport-lev), it seems that the cause was an intermittent network issue.


As you had mentioned, the job did succeed in the version 1.16.0.10 but failed in 1.16.0.11. There were no changes made to the Job between those two versions. Moreover, as the job did complete after you ran it manually, it does seem like an intermittent issue and so we are closing it for now.

However, please let us know if this issue persists with other jobs even after multiple retries and we will look into it further.

**Closed by PraveenMathew92** 2023-09-11 19:12 UTC
Labels: Status: In Dev Queue
