### ISSUE TITLE
Cannot delete phone number and save from Public Profile Edit

### ISSUE THREAD

**Issue by emdashes** [SparkDevNetwork/Rock#6027] opened 2024-10-02 00:29 UTC
### Description

Can add and edit phone numbers, but when I remove one from my public profile page and hit save, the removed phone number comes back, even though it is not required.

https://github.com/user-attachments/assets/104464d4-4508-4cfe-a477-c5e22d7c0d84

### Actual Behavior

Remove non-required phone number from Public Profit Edit page, hit save. It refreshes with the number still there. See description for attachment.

This happens in the Rock demo site as well.

### Expected Behavior

Expected when removing phone number and hitting save, to delete the phone number from the person's profile.

### Steps to Reproduce

- Go to https://rock.rocksolidchurchdemo.com/MyAccount
- Click on Update Profile
- Delete a phone number
- Click Save
- Look to see phone number saved in profile still.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.6

### Client Culture Setting

en-GB

**Comment by chead4** [comment] 2024-10-02 15:53
@emdashes After reviewing the issue, I'm happy to share that the issue has been resolved in v16.7 with [[commit](https://github.com/SparkDevNetwork/Rock/commit/967ecb8d02f3a7546be428829c92a62f934b2293)]. Since the issue is resolved, I will go ahead and close the issue.

**Closed by chead4** 2024-10-02 15:53 UTC
