### ISSUE TITLE
Phone Required on Group Registration Block does not display phone number field for input

### ISSUE THREAD

**Issue by timlem** [SparkDevNetwork/Rock#4492] opened 2020-11-12 15:33 UTC
### Description
If you use the group registration block and select Phone Number Required it does not give a field to enter phone number. I'm experiencing this on my 11.3 Instance and tested on Demo Site on 11.2 and saw the same thing.

### Steps to Reproduce
1. Add Block to public site of "Group Registration"
1. Chose Phone Number Required
1. Choose other settings required to save block
1. The form will show name and email field but will not display a phone number field.

**Expected behavior:**

I would expect there to be a phone number field since we selected phone number required

**Actual behavior:**

There is no phone number field available

### Versions
* **Rock Version:** 11.3
* **Client Culture Setting:** en-US

**Comment by JimMichael** [comment] 2020-11-12 22:21
If you're using _Simple_ mode, I don't think this is a bug, but a misunderstanding of how it works. The _Mobile Phone Required_ block setting is not intended to "make the phone input appear", but instead it makes the mobile phone input _required when it's visible_, and that only happens when the block is configured for _Full mode_.

Said another way... I don't think there's any way to input ANY phone number in Simple mode... it's meant to capture just name and email.

**Comment by nairdo** [comment] 2020-11-16 23:15
@timlem I can confirm what @JimMichael is saying. Phone numbers will not show up when the block is in simple mode.  (As seen in this [original commit](https://github.com/SparkDevNetwork/Rock/blame/d4aea2450aee41bacbcf76bfe4d57754b1769176/RockWeb/Blocks/Groups/GroupRegistration.ascx.cs#L427)).

**Comment by MicahO** [comment] 2020-11-18 16:13
@nairdo @JimMichael I ran into this today as well.

I understand what the block does currently, but it would be nice if there was some way for "simple mode" to be "name and phone number" which is, I think what both @timlem and I are after. The "require phone number" seems to imply that phone number will show up in the block.

**Comment by nairdo** [comment] 2020-11-18 18:13
(sorry about this -- I meant to close this out since it's working as designed.) If you want, I would recommend you add your idea to the http://community.rockrms.com/Ideas board)

**Closed by nairdo** 2020-11-18 18:13 UTC
