### ISSUE TITLE
Find Duplicates button on Pending Individuals report not working - v7.1 Beta

### ISSUE THREAD

**Issue by KelleyLangkamp** [SparkDevNetwork/Rock#2706] opened 2018-01-26 16:41 UTC
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The Find Duplicates button in the Action column of the built in Pending Individuals report isn't passing the person Id in the link.

### Steps to Reproduce

1. Go to the Pending Individuals report in Data Integrity
2. Click the button for finding duplicates
3. get sent to the internal homepage

**Expected behavior:** 

Get sent to the Duplicate Detail page

**Actual behavior:** 

Since there is no Person Id being sent in the link, you get sent to the homepage instead

### Versions

* **Rock Version:** 7.1
* **Client Culture Setting:** en-us

**Comment by MikeDPeterson** [comment] 2018-01-26 17:43
This is caused by the same bug that was identified in #2703, and is fixed with https://github.com/SparkDevNetwork/Rock/commit/886b4f67d05c7dd569f9ad209e2dd6a5170746f6

**Closed by MikeDPeterson** 2018-01-26 17:43 UTC
