### ISSUE TITLE
Finance Analytics Exceptions thrown.

### ISSUE THREAD

**Issue by drychlik76** [SparkDevNetwork/Rock#2960] opened 2018-05-01 16:49 UTC
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

I was not able to re-produce this on the demo site but was able re-produce it in my own dev environment.  

### Description

First of all, I realize that this issue is a rather odd one.  It's throwing exception messages, on a seemingly large data set, when attempting to filter by a data view.  I was able to re-produce an exception in my own local environment, but it's not the same as the the other at a particular client.  It seems to be a bit inconsistent.  

Attempting to run finance analytics and filter by data view, I receive a few different exception messages.  

### Steps to Reproduce

1. Navigate to Finance Analytics and begin filtering by selecting date range, and choose a data view.
2. Select  'Giver', and select 'All Givers'
3. Hit the update button.  

**Expected behavior:** 

Expected the result set to display without the exceptions being thrown.

**Actual behavior:** 

<img width="1801" alt="screen shot 2018-05-01 at 11 33 33 am" src="https://user-images.githubusercontent.com/20803057/39482399-882fc2d8-4d34-11e8-96cc-46947ffc6b1b.png">

<img width="2174" alt="screen shot 2018-05-01 at 11 37 19 am" src="https://user-images.githubusercontent.com/20803057/39482408-8d075276-4d34-11e8-8f9a-5ba9654852e2.png">

<img width="1872" alt="screen shot 2018-05-01 at 11 40 06 am" src="https://user-images.githubusercontent.com/20803057/39482414-905032a4-4d34-11e8-9e19-b3f272bb5dd9.png">

### Versions

* **Rock Version:** 7.2 
* **Client Culture Setting:** English

**Comment by ethan-sparkdevnetwork** [comment] 2018-06-08 23:34
This was fixed in v7.4. Duplicate of issue #2523.

**Closed by ethan-sparkdevnetwork** 2018-06-08 23:34 UTC
Labels: Fixed in v7.4, Type: Duplicate
