### ISSUE TITLE
GET request to the PersonAlias endpoint fails.

### ISSUE THREAD

**Issue by lancelotdaemion** [SparkDevNetwork/Rock#3165] opened 2018-08-03 20:12 UTC
### Steps to Reproduce
Issue a get request to the PersonAlias endpoint with the $expand=Person parameter.

**Expected behavior:**

I should received the PersonAlias JSON back with the Person information filled in.

**Actual behavior:**

An exception is thrown in Entity.cs in the ToDictionary() method because PersonAlias.AliasPerson doesn't have a visible getter.

### Versions
* **Rock Version:** 7.4 (1.7.4.58)
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1109768521967654">image.png</a>

**Comment by Tschrock** [comment] 2018-08-23 15:40
Confirmed on the prealpha server (v1.9.0.1)

I made a request to: http://prealpha.rocksolidchurchdemo.com/api/PersonAlias?$expand=Person&$top=5

And got the following response:
```json
{
  "Message": "An error has occurred.",
  "ExceptionMessage": "Object reference not set to an instance of an object.",
  "ExceptionType": "System.NullReferenceException",
  "StackTrace": "   at Rock.Data.Entity`1.ToDictionary() in C:\\Source\\Repos\\Rock\\Rock\\Data\\Entity.cs:line 316\r\n   at Rock.Utility.RockJsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, Encoding effectiveEncoding) in C:\\Source\\Repos\\Rock\\Rock\\Utility\\RockJsonMediaTypeFormatter.cs:line 216\r\n   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.WebHost.HttpControllerHandler.<WriteBufferedResponseContentAsync>d__1b.MoveNext()"
}
```

Nicely formatted stack trace:
```
System.NullReferenceException    Object reference not set to an instance of an object.
    at Rock.Data.Entity`1.ToDictionary() in C:\Source\Repos\Rock\Rock\Data\Entity.cs:line 316
    at Rock.Utility.RockJsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, Encoding effectiveEncoding) in C:\Source\Repos\Rock\Rock\Utility\RockJsonMediaTypeFormatter.cs:line 216
    at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Web.Http.WebHost.HttpControllerHandler.d__1b.MoveNext()
```

This is caused by this line, which doesn't check if `propInfo.GetGetMethod()` is null before using it:
https://github.com/SparkDevNetwork/Rock/blob/5d65e86df9750914735e837dc4deb214df09b76e/Rock/Data/Entity.cs#L316

**Comment by edmistj** [comment] 2018-08-24 17:59
@Tschrock are you open to doing a PR?

**Comment by vincespokesspark** [comment] 2019-02-14 18:43
Looks to have been fixed with on 10/30/28
https://github.com/SparkDevNetwork/Rock/commit/eea1e19f45512f28642d64c2617f04909861759f

**Closed** 2019-02-14 18:46 UTC
Labels: Status: Available, Status: Confirmed, Topic: API, Type: Bug
