### ISSUE TITLE
Check-in Exceptions - Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#912] opened 2015-03-22 15:14 UTC
I haven't seen this before on Check-in, but I saw about 40 of these errors in the log this morning:

>An error occurred on the Rock Check-in site on page: 
https://checkin.newpointe.org:443/checkin/search
HttpUnhandledException in System.Web
Message
Exception of type 'System.Web.HttpUnhandledException' was thrown.
Stack Trace
at System.Web.UI.Page.HandleError(Exception e)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest()
at System.Web.UI.Page.ProcessRequest(HttpContext context)
at ASP.themes_checkinnewpointeorange_layouts_checkin_aspx.ProcessRequest(HttpContext context) in c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\e22c2559\92c7e946\App_Web_5o41gygp.0.cs:line 0
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
-InvalidOperationException in mscorlib
Message
Collection was modified; enumeration operation may not execute.
Stack Trace
at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
at Rock.Workflow.Action.CheckIn.FindFamilies.Execute(RockContext rockContext, WorkflowAction action, Object entity, List`1& errorMessages)
at Rock.Model.WorkflowAction.Process(RockContext rockContext, Object entity, List`1& errorMessages)
at Rock.Model.WorkflowActivity.Process(RockContext rockContext, Object entity, List`1& errorMessages)
at Rock.Model.Workflow.ProcessActivity(RockContext rockContext, DateTime processStartTime, Object entity, List`1& errorMessages)
at Rock.Model.Workflow.Process(RockContext rockContext, Object entity, List`1& errorMessages)
at Rock.CheckIn.CheckInBlock.ProcessActivity(String activityName, List`1& errorMessages)
at Rock.CheckIn.CheckInBlock.ProcessSelection(ModalAlert modalAlert, Func`1 doNotProceedCondition, String conditionMessage)
at RockWeb.Blocks.CheckIn.Search.ProcessSelection() in c:\inetpub\wwwroot\Blocks\CheckIn\Search.ascx.cs:line 86
at RockWeb.Blocks.CheckIn.Search.lbSearch_Click(Object sender, EventArgs e) in c:\inetpub\wwwroot\Blocks\CheckIn\Search.ascx.cs:line 71
at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by edmistj** [comment] 2015-04-07 22:47
Is this still an issue?

**Comment by bwitting** [comment] 2015-04-08 15:21
Jon, I see 2 of theses exception in the log from 4/5 (after we updated to 3.1) but it's not been an issue like it was (it only happened twice, and the error screen wasn't shown in the check-in app).

**Comment by bwitting** [comment] 2015-04-30 12:53
@edmistj, I think this is still an issue.  I am getting 6 of this exception every morning at 12:31am, and the Rock Cleanup job runs at 12:30.  That is the only time it happens though, I have not seen it during actual check-in. (and I'm not sure why it's always 6...)

>An error occurred on the Rock Check-in site on page: 
https://checkin.newpointe.org:443/checkin/welcome
HttpUnhandledException in System.Web
Message
Exception of type 'System.Web.HttpUnhandledException' was thrown.
Stack Trace
at System.Web.UI.Page.HandleError(Exception e)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest()
at System.Web.UI.Page.ProcessRequest(HttpContext context)
at ASP.themes_checkinnewpointeorange_layouts_checkin_aspx.ProcessRequest(HttpContext context) in c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\e22c2559\92c7e946\App_Web_inlutuqk.0.cs:line 0
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
-InvalidOperationException in mscorlib
Message
Collection was modified; enumeration operation may not execute.
Stack Trace
at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
at System.Linq.Enumerable.d__81`1.MoveNext()
at Rock.Web.Cache.PageCache.get_Blocks()
at Rock.Web.PageReference.GetParentPageReferences(RockPage rockPage, PageCache currentPage, PageReference currentPageReference)
at Rock.Web.UI.RockPage.OnInit(EventArgs e)
at System.Web.UI.Control.InitRecursive(Control namingContainer)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by azturner** [comment] 2015-04-30 16:05
@bwitting, Those exceptions are because your IIS app-pool is configured to recycle each night at 12:30am, and check-in kiosks are re-querying server for any potential updated config information. You might want to change your cleanup job to run at 12:45 ( so its not at same time as the scheduled app-pool recycle).

**Comment by arranf** [comment] 2015-04-30 16:09
@azturner isn't it better practice to change the time the app pool recycles
so it's a irregular interval?

**Comment by bwitting** [comment] 2015-04-30 16:09
@azturner, ok, Gotchya.  Thanks!

**Comment by azturner** [comment] 2015-04-30 16:11
@arranf , absolutely! Bronson's was changed to recycle every morning at 12:30 am ( instead of the default of every 1740 minutes ).

**Comment by nairdo** [comment] 2015-05-10 08:06
I think I just accidentally replicated this issue while attempting something unrelated. As my Rock was recycling (after a simulated RockUpdate), I quickly clicked on one page and then another, and then I hit the InvalidOperationException because the blockIds collection was modified in the PageCache class: 
![image](https://cloud.githubusercontent.com/assets/383807/7553405/ccebab54-f6ab-11e4-9a36-238ad86567dd.png)

I've been able to repro the issue about 60% of the time by quickly clicking on two different pages (General Settings and then PowerTools - about .5 seconds apart) immediately after an app restart.  In my case the app_offline.htm file was just removed due to an update but I suspect the problem would occur after any app start/re-start.

I think simply enumerating over a copy of the list appears to fix the issue in my testing:

    var ids = new List<int>( blockIds );
    foreach ( int id in ids.Distinct() )

I'll submit this as a fix for this issue shortly...

Side Note: During a few attempts, I encountered a different but somewhat related exception in the CachedModel class during a set Attributes call:

```
System.IndexOutOfRangeException was unhandled by user code
  HResult=-2146233080
  Message=Index was outside the bounds of the array.
  Source=mscorlib
  StackTrace:
       at System.Collections.Generic.List`1.Add(T item)
       at Rock.Web.Cache.CachedModel`1.set_Attributes(Dictionary`2 value) in d:\Misc\Rock\Rock\Web\Cache\CachedModel.cs:line 236
       at Rock.Web.Cache.CachedModel`1.CopyFromModel(IEntity model) in d:\Misc\Rock\Rock\Web\Cache\CachedModel.cs:line 79
       at Rock.Web.Cache.BlockCache.CopyFromModel(IEntity model) in d:\Misc\Rock\Rock\Web\Cache\BlockCache.cs:line 221
       at Rock.Web.Cache.BlockCache.Read(Block blockModel) in d:\Misc\Rock\Rock\Web\Cache\BlockCache.cs:line 379
       at Rock.Web.Cache.PageCache.get_Blocks() in d:\Misc\Rock\Rock\Web\Cache\PageCache.cs:line 364
       at Rock.Web.PageReference.GetParentPageReferences(RockPage rockPage, PageCache currentPage, PageReference currentPageReference) in d:\Misc\Rock\Rock\Web\PageReference.cs:line 438
       at Rock.Web.UI.RockPage.OnInit(EventArgs e) in d:\Misc\Rock\Rock\Web\UI\RockPage.cs:line 895
       at System.Web.UI.Control.InitRecursive(Control namingContainer)
       at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
  InnerException: 
```

During another attempt I quickly clicked on about 6-10 pages and totally hosed my IIS and had to kill it to get my environment functioning again.  I was not able to reproduce this issue a second time.

**Closed** 2015-05-10 08:42 UTC
