### ISSUE TITLE
Unable to check out when checked in through override feature

### ISSUE THREAD

**Issue by chrisfunk** [SparkDevNetwork/Rock#3426] opened 2018-11-14 17:25 UTC
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When a person is checked in using the override feature to a location that they normally would not be able to be checked in to, they can't be checked out without an additional override. I am not sure if this is an actual issue or if it is by design.

### Prerequisites 
* Allow Check-out option must be enabled to support checkout.
* You will need to have a manager PIN code to test.

### Steps to Reproduce
1. Go to your check in site (i.e. {Your Internal Portal}/checkin)
1. Set the configuration screen to use a configuration that has check out enabled
1. On the welcome/Start screen click the gear icon to enter the manager screen.
1. Enter your PIN and click Login
1. Click the override button
1. On the phone screen enter the phone number of the person that you want to check in
1. Check the person in to a location that they would not normally be able to check in to (i.e. a 3 year old in a 2 year old room or a 3rd grader in a 2nd grade room).
1. Attempt to check them out. You will either not be presented with the action screen to choose checkout or they will not be available on the check out list.

**Expected behavior:**

I would expect that Rock will see that the person is checked in and present the option to check them out.

**Actual behavior:**

Depending on if other family members are checked in or not, you will not be presented with the action screen to choose the check out option or the person who was overridden will not show in the check out list on the check out person select screen.

### Versions
* **Rock Version:** 8.4 (1.8.4.40)
* **Client Culture Setting:** en-us

**Comment by jsw-austin** [comment] 2019-10-24 22:15
tested on demo site and couldn't reproduce

**Comment by nairdo** [comment] 2019-10-24 23:15
Reported as resolved (in v9.x) in the #bugapalooza channel:

```
Jeff Ward 3:16 PM
#3426 apparently has been fixed. Couldn't reproduce.
```

Please let us know by reopening if you feel this is closed in error.

**Closed by nairdo** 2019-10-24 23:15 UTC
Labels: Fixed in v9.1, bugapalooza: Is Needed?
