### ISSUE TITLE
System Communication From Field not accepting Lava

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#4314] opened 2020-07-25 15:28 UTC
### Prerequisites
* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When editing a System Communication, you have the option to use {{ Lava }} in the From Address field. However, when using Lava (example: {{ 'Global' | Attribute:'OrganizationFinanceEmail' }} ) it does not work.

<img width="1680" alt="Screen Shot 2020-07-25 at 11 20 05" src="https://user-images.githubusercontent.com/23226974/88460242-d85b3c80-ce68-11ea-86ab-aef1b2dd0fdc.png">

### Steps to Reproduce

1. Add a global email attribute (or just use one that already exists).
2. Go to System Communications and edit a Communication.
3. Enter the global email attribute with Lava in the From Email field.
4. Hit Save and see error.

**Expected behavior:**

Field should accept Lava so Global Attributes can be used.

**Actual behavior:**

Error message is displayed: "Email address is not valid". 

Replicated on Demo site [v10.3] and pre-alpha site [v12.0]

### Versions

* **Rock Version:** [v11.0]
* **Client Culture Setting:** [en-US]

**Comment by Tschrock** [comment] 2020-07-28 21:20
I believe this is related to the email validation code, which I already have an issue open for: #3976

**Comment by mikedotmundy** [comment] 2020-07-29 00:18
@Tschrock I do believe you are right... I did look but didn't catch the issue you created - sorry about that! I just confirmed that {{ CurrentPerson.Email }} did work for me, but the more complex ones (like linking to a Global Attribute) do not work.

**Comment by Pckool** [comment] 2021-04-05 17:25
Encountering the same issue here. I assume there is no workaround until the #3976 issue is fixed correct?

**Comment by nairdo** [comment] 2021-08-11 22:06
This is a duplicate of https://github.com/SparkDevNetwork/Rock/issues/3976 so we'll just close this out.

> I assume there is no workaround until the #3976 issue is fixed in v13, correct?

@Pckool  That is correct.

**Closed by nairdo** 2021-08-11 22:06 UTC
Labels: Type: Bug, Type: Duplicate, Topic: Communications
