### ISSUE TITLE
Orphaned Records when Payment Declined

### ISSUE THREAD

**Issue by dw-lc** [SparkDevNetwork/Rock#5154] opened 2022-08-30 19:06 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description
When a scheduled transaction has a saved payment method that gets declined at the gateway, an extra [FinancialPaymentDetail] record gets added to the database. No other records link to this extra record, so it’s not needed. Since it doesn’t even have all of the same data as the correct records, it’s bad data getting added to the database.

### Steps to Reproduce
1. Go to a person’s profile > Contributions Tab.
2. Add a new recurring scheduled transaction with a start date in the future, and provide a credit card number.
3. Once you see the Transaction Id and the option to save the payment method, you can pause and see some of the records we note below.
4. Once you have the confirmation of the records that you need, check the box to save the payment method and give it a name, then click “Save Account”.
5. You can now query the database to see additional records shown below.
6. If you can test with a credit card that will get rejected, then the bug will occur when the transaction attempts to process. Otherwise you may need to use SQL to update the saved card to have a past expiration date. Then when the transaction attempts to process (in testing it’s easiest to use the API) the issue will occur. In a production instance, examples of this issue will naturally happen over time as cards naturally expire and have their transactions declined.

**Expected Behavior:**

I don’t expect any new records in the FinancialPaymentDetail table when a transaction is declined.

**Actual Behavior:**

When a transaction is declined, a new FinancialPaymentDetail record is created. However, no records in the FinancialTransaction, FinancialScheduledTransaction, or FinancialPersonSavedAccount tables are linked to this new record, so it’s apparently orphaned/unused. Additionally, it doesn’t have all of the same property values as the original records which are still being used properly.

### Extra SQL Record documentation
When a giver sets up a scheduled transaction using a credit card, the Scheduled Transaction record references a FinancialPaymentDetail record by Id:
 
![image](https://user-images.githubusercontent.com/105749892/187521235-96d253fd-b6b7-4491-9f02-695d4a8f8a3f.png)
![image](https://user-images.githubusercontent.com/105749892/187521279-6b69e8e8-5739-48eb-a862-6f601ef47bc9.png)
 
During this process, the giver has the opportunity to save the payment method:
 
![image](https://user-images.githubusercontent.com/105749892/187521331-912f2ed3-8803-4e2c-a8e9-35a4a0c2ed5d.png)

If they do so, two additional records are created:

1.	An additional [FinancialPaymentDetail] record is created for the Saved Account.
![image](https://user-images.githubusercontent.com/105749892/187521367-a0ec9dcb-5bbb-4010-b19e-3ebcf6833a97.png)
 

2.	The [FinancialPersonSavedAccount] record is added and references the above FinancialPaymentDetail record.
![image](https://user-images.githubusercontent.com/105749892/187521390-4f662e7c-8f89-4e1c-8976-5f8171bb32b7.png)
 

(Additionally, the first FinancalPaymentDetail record is updated to store this record’s Id in [FinancialPersonSavedAccountId])

The bug occurs when the transaction is declined, so unless you can test with a one-time use card or something, we need to facilitate a rejection. Use SQL to update the expiration dates to a date in the past.
![image](https://user-images.githubusercontent.com/105749892/187521426-944dabee-07c4-4c27-8e6f-29ce2634d394.png)
 

Now when the transaction is attempted to be processed and gets rejected, you’ll see that a new [FinancialPaymentDetail] record is created. (we used https://rockrmslatest.com/api/FinancialScheduledTransactions/Process/2?enableDuplicateChecking=false&enableScheduleAdherenceProtection=false&idempotencyKey=test1 )
![image](https://user-images.githubusercontent.com/105749892/187521468-6b941706-2949-4edb-8d8c-d535111bd260.png)
 

### Versions

* **Rock Version:** v9.2 through PreAlpha 1.15.0.1 at least.
* **Client Culture Setting:** EN-US

**Comment by MikeDPeterson** [comment] 2022-09-02 21:45
@mikejed Were you able to reproduce this using the TestGateway? If not, which Gateway were you able to reproduce this with?

**Comment by mikejed** [comment] 2022-09-02 21:58
@MikeDPeterson Yes, I was able to reproduce this in PreAlpha 1.15.0.1 using the TestGateway. I had to use SQL as noted above to artificially "expire" the payment method to induce the failure event.

**Comment by MikeDPeterson** [comment] 2022-09-03 00:44
@mikejed  I wasn't able to reproduce this using the API.  Also, it looks like FinancialPaymentDetailId 436 is not orphaned. It is associated with FinancialTransactionId 433. Is that what you are seeing too? Or maybe I misunderstood what it takes to reproduce this.  However, I found a couple of other ways to produce FinancialPaymentDetail records:

- When Download Payments job processes scheduled transactions and the gateway says the transaction got denied, the denied transaction still records a FinancialTransaction record, but with whatever failed status the gateway recorded. Then this new FinancialTransaction has a new associated FinancialPaymentDetail record. If somebody or something goes thru and cleans up denied FinancialTransaction records, I see a bug where it is supposed to clean up the orphaned FinancialPaymentDetail record, but doesn't.  
- When an Saved Account contains an expired credit card, the RockCleanup job deletes those saved accounts. However, due to that same bug, the FinancialPaymentDetail  for that also gets orphaned.
- When a scheduled transaction gets deleted, same problem. It is supposed to clean up the FinancialPaymentDetail record but doesn't.

Do either of those sound like what you are seeing?

**Comment by taylorbrooks** [comment] 2022-09-06 00:58
> When an Saved Account contains an expired credit card, the RockCleanup job deletes those saved accounts. However, due to that same bug, the FinancialPaymentDetail would have gotten orphaned.

@MikeDPeterson Is there a way to prevent `FinancialPersonSavedAccounts` from being deleted by this job?

Most modern gateways automatically update CVC and Expiration Dates around the time a card expires and a new one is issued. I worry that the RockCleanup job unnecessarily deletes saved accounts when it shouldn't. (i.e. the "expired card" will continue to work because a new network token has been issued)

**Comment by MikeDPeterson** [comment] 2022-09-06 16:50
@taylorbrooks Thanks for asking about that! I looked and again and it turns out that RockCleanup of FinancialPersonSavedAccounts is off by default. 
![image](https://user-images.githubusercontent.com/2430748/188693649-6041ce2e-b087-40a1-b799-e9e937df398b.png)

**Comment by MikeDPeterson** [comment] 2022-09-06 22:02
@mikejed We think we have found the bug. It appears to be specific to the Stripe and MyWell gateways.

**Comment by MikeDPeterson** [comment] 2022-09-07 18:46
Fixed with https://github.com/sparkdevnetwork/rock/commit/4a4c485143b490ac70721648d76bb95b9472a789

**Closed** 2022-09-07 18:46 UTC
Labels: Status: Confirmed, Fixed in v14.1
