### ISSUE TITLE
SMS Communication Process Response Workflow Action Needs Person Attribute

### ISSUE THREAD

**Issue by tbunney** [SparkDevNetwork/Rock#4431] opened 2020-09-29 14:33 UTC
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

_The SMS Communication Process Response workflow action does not have a person attribute field, it has ToPhone and FromPhone only. This is a problem because every SMS conversation that is built from a workflow comes in to Rock as a Nameless Person, even if that person is already in Rock.
![image](https://user-images.githubusercontent.com/37702418/94571546-1c3e3980-023e-11eb-8f69-da0ed790db85.png)
_

### Steps to Reproduce

1. Go to 'Workflows'
2. Use the workflow action 'SMS Communication Process Response'
3. Run workflow
4. See the conversation come in as a Nameless Person.

**Expected behavior:**

_[A FromPerson attribute should be available so if that person is already in the database, the SMS conversation will match the name of the FromPerson to their record.]_

**Actual behavior: All people going to through the workflow are created as Nameless Persons.**

### Versions

* **Rock Version:** [Rock McKinley 11.1 (1.11.1.1)]
* **Client Culture Setting:** [en-US]

**Comment by cabal95** [comment] 2020-09-29 15:20
Hi @tbunney, the code that this action calls doesn't take a Person parameter, only the From and To phone numbers. So adding a Person attribute to the workflow action wouldn't help. The code behind the scenes is looking for an existing person with that phone number and will use them if an existing person is found. If it's creating a new Nameless person instead of matching the existing one there might be something peculiar about your data, maybe left over from an import or something.

Each phone number in Rock has a hidden "Full Number" field that contains a normalized version of the phone number to use for comparison. It's possible if you have imported data that this "Full Number" isn't in the correct format and thus not matching correctly when the action is called.

**Comment by tbunney** [comment] 2020-09-29 17:11
Thanks, Daniel. We will look to see what we can find.

**Comment by cabal95** [comment] 2020-09-29 17:18
Also just to clarify, that is what _should be_ happening. Obviously bugs happen, but I'd start with checking your data.

One way to somewhat easily test this is to search for your own phone number and make sure all person nameless people have been merged into your record (this is just in case any exist for you). Then edit your person record and change the phone number, save, then edit again and change it back. This would ensure that everything gets updated in case anything was the wrong format from an import.

Then try using the action with your phone number (remember it's expecting the full phone number, e.g. +18185551234) and see if it creates a new nameless record or matches to your existing record.

**Comment by eddieholeman** [comment] 2020-09-29 20:01
@cabal95 are you saying that the correct format that should be in the FullNumber field of the [PhoneNumber] table includes the +. In our data, the format is 18185551234 with no +.

**Comment by cabal95** [comment] 2020-09-29 20:58
@eddieholeman The person matching logic strips out the `+`, but I think other parts of the SMS process expect the `+` to be there.

So in the database the `FullNumber` field you are seeing is correct.

**Comment by eddieholeman** [comment] 2020-09-29 21:05
@cabal95 Thanks. Tiffany and I will keep digging into this issue.

**Comment by eddieholeman** [comment] 2020-10-01 17:57
@cabal95 Tiffany and I have found a workaround for this issue. Hoping you can help us understand why we needed a workaround. The workflow which includes the SMS Communication Process Response is fired from the SMS Pipeline when a text comes in. The FromPhone attribute in the workflow instance gets the sending number as 8644232650 and the ToPhone comes in as **1**8646794204. So the FromPhone in the SMS Communication Process Response is failing at looking up the person because the FullNumber field is in the form of 18644232650. Why are FromPhone and ToPhone different in format coming in from SMS Pipeline? Our workaround was to prepend the FromPhone attribute with a 1. Thanks for your help.

**Comment by cabal95** [comment] 2020-10-01 18:51
@eddieholeman Thanks for looking into it to find that.  As far as I know, it _should_ be including the `1`, so short term you might want to modify your logic to only add the `1` if it isn't already there.  And I'll take a look at that code and see why they are different. As far as I know they should be the same and I believe they should both be including the `1`.

**Comment by cabal95** [comment] 2020-10-01 20:39
The issue seems to be one in the text-to-workflow system (which the pipeline uses when you use the launch workflow action). So the same problem would happen in text-to-workflow.

That code is calling the standard Rock number formatting code _only for the From number_, which by default for all Rock installations will strip the `1` due to the way the defined value for the country code is configured.

https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Utility/TextToWorkflow.cs#L177

I feel like we should just remove that line of code, but that would potentially break a lot of peoples existing Workflows. So I don't think we could just make that change without breaking a bunch of existing workflows.

**We could add a new merge field available in Workflows of `RawFromPhone` and update the documentation to state that `FromPhone` runs through the number formatting system first.**

Thoughts @jonedmiston ?

**Comment by eddieholeman** [comment] 2020-10-01 20:51
> @eddieholeman Thanks for looking into it to find that. As far as I know, it _should_ be including the `1`, so short term you might want to modify your logic to only add the `1` if it isn't already there. And I'll take a look at that code and see why they are different. As far as I know they should be the same and I believe they should both be including the `1`.

@cabal95 Thanks for this feedback. In our Workflow we are using a Prepend to add a 1 to the FromPhone and stuffing that into a text Attribute. It works fine. Hope your ideas of RawFromPhone or some other option come together as, longterm, that would be a better solution, in my opinion.

**Comment by nairdo** [comment] 2020-10-22 14:55
@eddieholeman & @tbunney   Just to follow-up with the work and analysis that Daniel and Matt have done, we believe the issue is with the addition of this particular workflow attribute you have in the SMS Pipeline's 'workflow' action:

![image](https://user-images.githubusercontent.com/383807/96887695-afcbea00-1439-11eb-8c7e-31d26b04c358.png)

Because of that, the `FromPhone` which is normally automatically added to the workflow with the correct, 'raw' <sup>&dagger;</sup> value is overwritten with the 'formatted' value which does not have the 1 prepended to it.

Since we can't quite easily change certain behavior without breaking someone's workflows, we're going to try to clarify this in the setup instructions of the SMS Pipeline documentation.  Probably [here](https://community.rockrms.com/documentation/bookcontent/8#smspipeline) and [here](https://community.rockrms.com/Rock/BookContent/12#workingwiththesmspipeline).

Does that sound like a reasonable resolution to you?  If so, I'll close this issue out after updating the documentation.

<sup>&dagger; the one that normally has the 1 prepended to it</sup>

**Comment by tbunney** [comment] 2020-10-26 20:42
Sorry, it took so long to reply back, as I was out of the office. I took
out the FromPhone attribute in SMS Pipeline, and now the workflow action is
working correctly without the Prepend. Yes, what you have is a great
solution! Thank you for figuring this out for us!

**Closed** 2020-10-26 21:04 UTC
