### ISSUE TITLE
Registration Entry Block Produces Server Error if URL Doesn't Match a Registration Instance Linkage

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#4578] opened 2021-02-03 21:35 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

It looks like when visiting a page that contains the `RegistrationEntry` block - if the block can't find a matching regsitration instance, it produces an error instead of just 404ing.

https://rockrmslatest.com/Registration/baptism
![image](https://user-images.githubusercontent.com/2465823/106812186-4e710500-663d-11eb-9530-5076c0328e91.png)

https://rockrmslatest.com/Registration/stuff
![image](https://user-images.githubusercontent.com/2465823/106812248-65175c00-663d-11eb-93fa-51b19015babf.png)

### Steps to Reproduce

1. Go to 'https://rockrmslatest.com/Registration/baptism' (matches the existing baptism event registration instance linkage on the pre-alpha server)
2. See `RegistrationEntry` block successfully load form for registration.
3. Go to 'https://rockrmslatest.com/Registration/stuff' (does not match any existing registration instance linkage)

**Expected behavior:**

If the `RegistrationEntry` block is unable to find a registration instance that matches the route, it should cause a 404 error, not a server error.

**Actual behavior:**

If the `RegistrationEntry` block is unable to find a registration instance that matches the route, it produces a server error.

### Versions

* **Rock Version:** 13.0.5
* **Client Culture Setting:** en-US

**Comment by matthewmeekins** [comment] 2021-02-11 18:51
I'll add that even if the registration exists, but the start date is in the future it gives the same error. This is on 12.0 for me.

**Comment by carriewhite** [comment] 2021-02-11 21:52
We have the same issue with 12.0.
/registration as well as any invalid registration slug.

Additionally, we can no longer reuse a registration slug.  Is this a bug or by design with v12?

**Comment by kyeschung** [comment] 2021-02-23 18:43
Not sure if this is related but when you access the registration form outside of the registration period (start date and end date), it gives a Object reference not set to an instance of an object.. I just tested on Rock Demo site (https://rock.rocksolidchurchdemo.com/registration?RegistrationInstanceId=2).

**Comment by matthewbronkema** [comment] 2021-02-24 15:19
Duplicate of #4538

**Closed by matthewbronkema** 2021-02-24 15:19 UTC
Labels: Status: Confirmed, Type: Bug
