### ISSUE TITLE
Captcha Rendering Twice

### ISSUE THREAD

**Issue by tikool17** [SparkDevNetwork/Rock#6019] opened 2024-09-21 01:39 UTC
### Description

We recently enabled captcha via Cloudflare Turnstile on our site. On our giving page (Transaction Entry v2) we then noticed page reloads and errors in the browser console about turnstile being rendered twice. We were able to reproduce this on the demo site as well.
<img width="1231" alt="Screenshot 2024-09-20 at 9 35 10 PM" src="https://github.com/user-attachments/assets/9f452728-98d6-416c-b636-ca3c2ba6de8a">

There is some discussion of a similar issue on Cloudflare's forums here https://community.cloudflare.com/t/turnstile-ready-firing-twice/690171

### Actual Behavior

-Captcha is rendered twice.

-There's errors in the browser console.
<img width="1008" alt="Screenshot 2024-09-20 at 9 15 59 PM" src="https://github.com/user-attachments/assets/9f5406e0-a361-493f-9fab-46d7f45f7f45">
-also this console error reported in rocketchat _"112 warnings for Cloudflare Challenge cookies about how "Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox."_

-There also seems to be a page reload a a few seconds after each page load where the Rock loading icon appears.

### Expected Behavior

Captcha should only render once. Page reloads shouldn't happen.

### Steps to Reproduce

- On the demo site, enable captcha support. You can use Cloudflare's dummy keys for turnstile https://developers.cloudflare.com/turnstile/troubleshooting/testing/
- Go to a block that uses captcha to see the error. (I tested on Utility Payment and Transaction Entry V2 on the demo site)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.6, 16.5

### Client Culture Setting

en-us

**Comment by chead4** [comment] 2024-09-23 15:20
@tikool17 H iChase -  After reviewing the issue, I'm happy to share that the issue has been resolved in v16.7 with [[commit](https://github.com/SparkDevNetwork/Rock/commit/34747cfbc8952bda99200d1eea6c808ba0db877a)]. Since the issue is resolved, I will go ahead and close the issue.

**Closed by chead4** 2024-09-23 15:20 UTC

**Comment by dataCollegechurch** [comment] 2024-09-27 15:48
@chead4 - should this item be tagged with some sort of fixed in 16.7 tag?

**Comment by chead4** [comment] 2024-09-27 16:50
@dataCollegechurch Thanks for reaching out Tony, I have added the Fixed in v16.7 tag.
