### ISSUE TITLE
Pledge Analytics does not respect date range

### ISSUE THREAD

**Issue by raufrecht** [SparkDevNetwork/Rock#3478] opened 2018-12-14 22:33 UTC
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When viewing Pledge Analytics and want to look at pledges vs giving for a certain time period, the Total Giving Amount and Percent Complete reflect all giving to the account rather than just the time frame.

### Steps to Reproduce
1. Enter a single pledge for $1 on Ted Decker's account sometime in the current month.
1. On Pledge Analytics, select a Date Range of Current Month.
1. Click "Update"
1. Total Giving Amount shows $10,790 ![image](https://user-images.githubusercontent.com/45696078/50033324-ecf90280-ffac-11e8-9f22-2824a90e6901.png) ![image](https://user-images.githubusercontent.com/45696078/50033355-0c902b00-ffad-11e8-9ddf-d6bddc51f05d.png) ![image](https://user-images.githubusercontent.com/45696078/50033383-1e71ce00-ffad-11e8-9522-29856a8bec8c.png)

**Expected behavior:**

Since pledges have a beginning and end date, I would expect the Total Giving Amount to reflect the giving with the same beginning and end date of the pledge itself.

**Actual behavior:**

The Total Giving Amount shows all giving for the Account and does not respect the Date Range selected.

### Versions
* **Rock Version:** [8.4]
* **Client Culture Setting:** [Enter Client Culture here]

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=948963211853581">image.png</a>

**Comment by raufrecht** [comment] 2018-12-17 16:18
All of the screen shots I included were from the 8.5 demo server. I just
checked the 9.0 pre-alpha and I am getting the same issue.

Randy Aufrecht
IT Manager | 909-592-2282 x147

[image: Christ's Church of the Valley]
[image: Connect with us on the Web] <http://www.ccvsocal.com/>[image:
Facebook] <https://facebook.com/ccvsocal>[image: Instagram]
<http://www.instagram.com/ccvsocal>

**Comment by nairdo** [comment] 2018-12-17 17:55
Sorry @raufrecht , I was mistaken. Ethan worked on this fix (8046700b13ce885b8722782a552d24acea45ed79) for the 8.6 release.  Due to the timing of that fix (only 20 days ago) I don't believe it's made its way over to the pre-alpha site (which is only on v1.9.0.10 build).  It should be in the 1.9.0.11 release due out in about two weeks.

Having said that, I'd still be very interested in your feedback on the solution once you can test it on our pre-alpha server.

**Comment by raufrecht** [comment] 2019-04-04 19:51
I just went in and checked our server (8.7), the demo server and the prealpha server and the date range selected is still not be respected when "Total Giving" is totaled.

**Comment by daniellevos** [comment] 2019-07-02 16:41
I'm experiencing this issue as well on v8.8

**Comment by dylan-gregory** [comment] 2019-09-27 13:54
Also experiencing this on 8.9

**Comment by nairdo** [comment] 2019-11-15 17:52
@raufrecht Here is what I have discovered after discussing internally: the "Total Giving Amount" (and percent) shown in the Pledge Analytics _is intended_ to be the **total** giving amount for that person (without  date range limits).  The date range only applies to the pledge data.

I understand you and several out there would like it to either also show the giving total (and %) during the selected date range **or** to have an option to force the "Total Giving Amount" to be constrained to the selected date range... With our limited time resources, we have to ask that you open that as an _idea_ over at https://community.rockrms.com/ideas so everyone can appropriate votes to help us decide what core features/changes we make to the Pledge Analytics.

(I'll close this out here as we await the item to appear in the ideas board.  Thank you!)

**Comment by jrockman13** [comment] 2019-11-21 18:03
I this this is still broken. @nairdo what *should* change when adjusting the date parameters? Ok...spark didn't intend it up change the total given...what about the total number of pledges? that date range doesn't seem to impact anything.

For example, we had pledges given to our campaign dated 10/1/2018 and 12/1/2018. If I set the date range to start at 12/1, the pledged made prior appear. If I set the range to be 10/1 to 11/30, the pledges made on 12/1 appear. 

What is the expected behavior of the date range on the analytics page? When I change the date range, what should I expect to see change in the returned results?

**Closed** 2020-03-03 18:38 UTC
Labels: Status: Unable/Cannot Fix, Type: Enhancement, x-bugapalooza: Low
