### ISSUE TITLE
Check-In Manager Can't Move Children Between Simultaneous Configurations

### ISSUE THREAD

**Issue by bobrufenacht** [SparkDevNetwork/Rock#5892] opened 2024-06-04 17:59 UTC
### Description

On behalf of North Point Ministries - There was a change in v16.1 via this commit https://github.com/SparkDevNetwork/Rock/commit/2cea8e7b0a1cc801acbf6fec27b3b85f218103e1 that no longer allows checked-in kids to be moved between different configurations that use different schedules.  Only the schedules in the current child's configuration are shown.  This is a change that removes functionality that was being used in v15.4.

### Actual Behavior

In v16.1 and up, if a separate check-in configuration is used for different areas of ministry, a child cannot be moved across configurations.  Specifically, if Preschool (Waumba Land) is in one configuration and Elementary (Upstreet) is in a separate configuration, a child cannot be moved from an Preschool classroom to an Elementary classroom even though it is open and available.  The options are not displayed in the dropdown list to allow such a selection.  (This was possible in v15.). This is noticeably more problematic at promotion time when information about who is entering Kindergarten or not is often not accurate.  (While not specific to this problem as testing revealed, it is important to note that NPM uses different schedules for Preschool and Upstreet.  The dropdown needs to show the different schedules as well as allowing cross-configuration moves.)

### Expected Behavior

Children should be able to be moved to any other open classrooms at the currently available service times.

### Steps to Reproduce

1) On rocksolidchurchdemo.com, create a new Check-In Configuration called "Test Elementary."
2) Create a New Area in the configuration called "Test Elementary" with a grade based check-in.
3) Create a new Group called "4th Grade" and configure it for fourth grade criteria.
4) Add a location (Outpost Room).
5) Configure the Schedule to make the group active at the 4:30 test schedule.
6) Make sure Alex Decker is in the 4th grade.
7) Start Check-In and select only the Preschool and Test Elementary areas to be active.
8) Check-In Alex Decker (Phone 5553322) into the 4th Grade room.
9) Go to Check-In Manager.
10) Choose Room List and navigate to Alex's current attendance record.
11) Click Edit.
12) The only option present is the 4th grade room.  None of the classrooms in Preschool are available to move Alex into.

Same test on v15 allows selection of other active schedules, groups and rooms for the move.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

V16.3

### Client Culture Setting

en-US

**Comment by nairdo** [comment] 2024-06-12 22:42
@bobrufenacht Can you verify your reproduction steps above.  We're not able to reproduce the behavior you're describing with that particular setup.  Here is the final result of a reproduction attempt between v16.5 and v15.4:

![chrome_LcwKHonh4W](https://github.com/SparkDevNetwork/Rock/assets/383807/07e49dd1-f395-4fcd-bb0b-31ba6de12571)

Configured like this:
![image](https://github.com/SparkDevNetwork/Rock/assets/383807/817c16f8-50fe-4826-8431-3be867d61622)

Scheduled like this:
![image](https://github.com/SparkDevNetwork/Rock/assets/383807/7ae6a49b-415d-4895-8ed3-cef62828dab8)

Check-in configured like this:
![image](https://github.com/SparkDevNetwork/Rock/assets/383807/af7c9333-47b4-4134-941a-64e4b954cda4)

**Comment by chead4** [comment] 2024-06-18 17:27
@bobrufenacht Hi Bob We have tried several times to recreate this issue on the demo site (v16.5) and on v15.4 (see Nick's videos above) and have been unsuccessful.  

At this time, I will be closing this issue.  If you are able to recreate the issue on v16.5, we would be happy to reopen and kindly request that a video/screenshots are included that contain updated reproduction steps.

**Closed by chead4** 2024-06-18 17:27 UTC
Labels: Not Yet Reproduced

**Comment by bobrufenacht** [comment] 2024-06-19 12:58
@chead4 v15.4 already contained the new code with the issue.  v15.3 was the last version that worked as needed.  As a workaround, I reinstalled the v15.3 block on the 16.3 system and it works as desired with no issues.  I will try to record a video as well with the difference but may not have time this week.
