### ISSUE TITLE
emdash character converted to hyphen when sending e-mails

### ISSUE THREAD

**Issue by kenmulford** [SparkDevNetwork/Rock#4091] opened 2020-02-04 13:29 UTC
### Prerequisites
* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

Note: I could not test in demo because email is disabled.

### Description

Users are attempting to send e-mails that include the "emdash" character. When users paste their text from an external text editor (Word and Notepad were tested), the em-dash shows correctly. When the user clicks "send test email", the email is delivered with a hyphen instead of an emdash.

### Steps to Reproduce

1. Go to Person -> New Communication
2. Paste the following text in the editor for the email body contents.

`Talking about money can be awkward, but we hope you’ll find that this study’s approach makes it easier—and more fun—than you’d expect. `

3. Send a test to yourself

**Expected behavior:**

Emdash characters are correctly displayed in the email.

**Actual behavior:**

Emdash characters are converted to standard hyphens in the email.

### Versions

* **Rock Version:** 8.9
* **Client Culture Setting:** en-US

**Comment by jonedmiston** [comment] 2020-02-04 15:47
This is a duplicate of https://github.com/SparkDevNetwork/Rock/issues/2818

**Closed by jonedmiston** 2020-02-04 15:47 UTC
