### ISSUE TITLE
Schedule Exclusions Do Not Save

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#5674] opened 2023-11-13 17:33 UTC
### Description

When creating an exclusion for a schedule (see below) they no longer save and do not work
https://app.screencast.com/UVEbL1z8zqG8l

<img width="1511" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/657005/1161c7fe-aaed-48d3-a545-f271128cfd68">

### Actual Behavior

When you hit save, nothing is there (see video above)

### Expected Behavior

The dates you put in to exclude would be saved and work.

### Steps to Reproduce

- Go to Check-in / Schedules
- Click on a schedule
- Scroll down to excluisions
- Add an exclusion and hit save
- Hit edit again to see exclusion is not saved

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16

### Client Culture Setting

en-us

**Comment by bmurphy-dev** [comment] 2023-11-13 18:24
@austinspooner I can confirm this error on v16. It is however saving the exclusion because whenever I go to Group Scheduling that excluded occurrence drops from the scheduler. However as you showed, the exclusion is now longer displayed in the Schedule Builder making it almost impossible without SQL to remove the exclusion from the schedule.

So I'd say the bug is in the Schedule Builder display of the created exclusion itself. Not that the exclusion isn't saved and working as expected in other areas.

**Comment by chead4** [comment] 2023-11-13 21:30
@austinspooner and @bmurphy-dev  Thank you for the video and details.  I was able to recreate and confirm the issue.

**Comment by JimMichael** [comment] 2023-11-14 16:09
Please please try to get this fix into 16.1. We consider it a show stopper for upgrading to v16.

**Comment by chead4** [comment] 2023-11-14 20:12
@JimMichael This issue will be in the dev queue soon and the fix will be in v16.1.

**Closed** 2023-11-17 07:21 UTC
Labels: Type: Bug, Status: Confirmed, Fixed in v16.1
