### ISSUE TITLE
Registrant Form Campus Person Field isn't working.

### ISSUE THREAD

**Issue by JoshuaMaiorino** [SparkDevNetwork/Rock#4491] opened 2020-11-11 21:40 UTC
* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

Person Field of Campus isn't displaying properly on or for Registrants.  In Rock v11.3, the field doesn't even show up for the user to enter on the form.  In 10.3, the for field is showing up on the form, but is showing up blank on registrant grid.  I did find an old bug from v.7 that was fixed in 7.4.

I've found a related PR and Commit that fixed seemingly related issues here:
https://github.com/SparkDevNetwork/Rock/pull/4219
https://github.com/SparkDevNetwork/Rock/commit/348cd17279afe85f11e15b4f22ff0d6f35a6409d#diff-12baa2ba843bdfff8c28fc422fe24fce

### Versions

* **Rock Version:** 10.3, 11.13
* **Client Culture Setting:** en-us

Submitted on the behalf of Foundry UMC Church.

**Comment by ethan-sparkdevnetwork** [comment] 2021-04-02 00:11
@JoshuaMaiorino Hello Joshua. The Campus field appears to be working correctly in v11.4 and v12.4. I was able to view and use the campus field on the RegistrationEntry block. For the internal block the registrant is a person, so the campus won't be selectable, it is gotten from the family group.

There has to be more than one active campus for the campus to display, otherwise the single campus is chosen automatically and not displayed.

Can you Add any clarifications and/or screenshots?

**Comment by cwomack** [comment] 2021-04-26 16:25
@JoshuaMaiorino I was able to reproduce the "issue" you're referencing by ensuring only a single campus was active in my test instance for Rock on v11.3 (and really any other version).  Even if you add a "Campus" _Field_ and "Person Field" _Source Type_ to a Registrant Form, Rock won't populate it as something to select if there is only **one** active campus. 

Per Ethan's comment, I tested the exact same Registrant Form after making a second campus active and it populated the field to select one from a drop-down as expected (since there was more than one to pick from).  We'll close this issue out, but if you find anything else that points to a bug then feel free to reply back.

**Closed by cwomack** 2021-04-26 16:25 UTC
Labels: Status: Confirmed, Type: Bug
