### ISSUE TITLE
Error when disabling pin authentication

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#5030] opened 2022-05-31 14:59 UTC
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
<img width="896" alt="image" src="https://user-images.githubusercontent.com/657005/171204687-09e97b1c-9e70-42a8-8fed-44f4a7d2f183.png">

### Description
Disabling pin authentication causes an exception error.

### Steps to Reproduce
1. Go to security
2. Authentication Services
3. Pin Authenticaiton
4. Disable Pin
5. Save
6. Open Group Viewer
7. See error on Group Tree
8. Go to System Settings / Exceptions / See Error

<img width="1835" alt="2022-05-31_09-59-12" src="https://user-images.githubusercontent.com/657005/171205140-43d2186b-6db7-4131-8d95-84e609f44073.png">

**Expected behavior:**

You should be able to disable pin auth and still be able to use controllers that rely on the rest API

**Actual behavior:**
Does not work

### Versions

* **Rock Version:** v12 and v13
* **Client Culture Setting:** en-us

**Comment by MichaelAllen** [comment] 2022-05-31 15:23
Duplicate of https://github.com/SparkDevNetwork/Rock/issues/4977 which is marked as fixed in 13.4

**Comment by leahjennings** [comment] 2022-06-02 17:34
@austinspooner thanks for submitting this! Because this is a duplicate of issue #4977, which is labeled as fixed in v13.4, this one will be closed as such.

**Closed as completed** 2022-07-07 13:21 UTC
Labels: Type: Bug, Status: Confirmed, Type: Duplicate, x-Fixed in v13.4
