### ISSUE TITLE
View State Error When Add Meta Tag is added to HTML Content Block

### ISSUE THREAD

**Issue by rutledgek** [SparkDevNetwork/Rock#5451] opened 2023-05-20 20:32 UTC
When you use the | AddMetaTagToHead lava filter in an html block and then try to edit blocks on the page, you get the following error.【 code  】

Error

338|error|500|Failed to load viewstate. The control tree into which viewstate is being loaded must match the control tree that was used to save viewstate during the previous request. For example, when adding controls dynamically, the controls added during a post-back must match the type and position of the controls added during the initial request.|

【 end code 】

![](https://github.com/SparkDevNetwork/Rock/assets/24379548/91ba914e-9c93-4e99-80c9-713128b788b8)

## Expected Behavior
I expect to be able to edit the blocks on the page even when i use the | AddMetaTagToHead lava filter.

## Actual Behavior
error shown above

## Steps to Reproduce
Create an html content block on a page and add a When you use the | AddMetaTagToHead lava filter to add a description meta tag.  Then click to edit a block.

## Rock Version
15.0

## Client Culture Setting
en-US

**Comment by sparkdevnetwork-service** [comment] 2023-10-28 00:26
We've not been able to reproduce this issue, so we're closing it.  (It's also possible this was resolved in one of the patches since v15.0.) If you're still seeing that issue, feel free to reopen this with some additional details that might not be in the Steps to Reproduce above.

https://github.com/SparkDevNetwork/Rock/assets/6056081/85f8be2b-f0cd-4513-98a8-b60ab3c5a83f

**Closed by sparkdevnetwork-service** 2023-10-28 00:26 UTC
Labels: Type: Bug
