### ISSUE TITLE
[Alpha v14.0] - Obsidian Registration Entry Block does not honor Required Registrant Attributes

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5136] opened 2022-08-24 01:14 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description
When using the Obsidian Registration Entry block, _Registrant_ Attributes that are marked as Required are not actually required when completing the registration.

(Note: _Registration_ Attributes are working properly - issue is only with _Registrant_ Attributes.)

#### A Picture Is worth a Thousand Words
<img width="1728" alt="Screen Shot 2022-08-23 at 21 04 41" src="https://user-images.githubusercontent.com/23226974/186295588-6d5d8981-07dc-4b57-9468-6fea4dca068e.png">

See that they are required (functioning properly) on the regular Registration Entry block.
<img width="1728" alt="Screen Shot 2022-08-23 at 21 05 13" src="https://user-images.githubusercontent.com/23226974/186295596-54d9d4a2-98b2-4b4f-93c3-b3c18b2ed3b5.png">

They are not required on the Obsidian Registration Entry block.
<img width="1728" alt="Screen Shot 2022-08-23 at 21 04 28" src="https://user-images.githubusercontent.com/23226974/186295606-21032155-ed7d-40b0-b1d5-97afd479f6a1.png">

### Steps to Reproduce

1. Create a Registration Template with some required _Registrant_ attributes. Create the Registration Instance.
2. Add the Obsidian Registration Entry block to a page and proceed through the Registration process.
3. See the _Registrant_ attributes that you set to be required are not actually required.

**Expected behavior:**

_Registrant_ attributes marked as required should be required.

**Actual behavior:**

They are not required when using the Obsidian Registration Entry block.

### Versions

* **Rock Version:** [v14.0 (may also be an issue in earlier versions - unable to test)]
* **Client Culture Setting:** [en-US]

**Comment by nairdo** [comment] 2022-08-25 19:09
@mikedotmundy  Can you try testing this in another browser?  I'm not able to reproduce this on the pre-alpha site at the moment: https://prealpha.rocksolidchurchdemo.com/page/740?RegistrationInstanceId=2

![image](https://user-images.githubusercontent.com/383807/186748572-6a0c8c4b-3228-48eb-a318-58ab6d050e65.png)

**Comment by mikedotmundy** [comment] 2022-08-25 19:52
I have tried on Chrome, Safari, and Brave, and all three are showing the same thing. However, the behavior I am seeing is very odd and I am not sure what is going on. 

I took another screenshot that shows cabin preference as required, and then verified (in all three browsers) that it was NOT required in the form. 
![Screen Shot 2022-08-25 at 15 31 16](https://user-images.githubusercontent.com/23226974/186755014-3d8725ea-a73e-4c09-bb16-d2708ac346de.png)

![Screen Shot 2022-08-25 at 15 49 39](https://user-images.githubusercontent.com/23226974/186755127-aa62f52e-974a-4f3c-9eb5-0374468c5c67.png)

I then went back into the form settings, saw that the cabin preference attribute was NOT set to Required, and after setting it back to required, it seems to be functioning properly now. It was almost as if after editing it and saving it, it began to function normally.

Maybe I am going crazy, but it seems there is something strange going on with this...

**Comment by mikedotmundy** [comment] 2022-08-25 19:57
If we can't duplicate this currently then we can just close the issue. I'll keep researching it to see if I can't figure out what caused it. I would be curious to see what happens when the pre alpha-site is refreshed though.

**Comment by cabal95** [comment] 2022-08-25 21:56
@mikedotmundy Just a thought, maybe the first time you saved the attributes but didn't click the final Save on the registration template. I do that all the time myself and it takes me a few times going between tabs before it clicks that I didn't actually save it.

@nairdo and I both tried to replicate this and couldn't, so I'm going to close this. But if you run into it again please revisit this with us.

**Closed by cabal95** 2022-08-25 21:56 UTC
Labels: Not Yet Reproduced

**Comment by mikedotmundy** [comment] 2022-08-30 01:21
So I was able to duplicate this just now at this site: `https://rock.rocksolidchurchdemo.com/registration?RegistrationInstanceId=2` (I added the Obsidian Registration Entry block to the page).

I did NOT edit the attributes at all, leaving them as required, and they show as NOT required. I am assuming you must edit the attribute, save it, and then it will show as required on the form.

**Comment by jeremyhoff** [comment] 2022-10-24 14:52
All: I was able to reproduce this using Chrome and Safari on my production instance as well as on the Rock Demo site. 

**One additional note:**
If the field in RockRMS > General Settings > Person Attributes is set to "Required" then the field will be required in Obsidian Registration Entry. I.E. the Obsidian block honors "Required" when it is set in P.A. but not when "required" is set on the Registration Form.
