### ISSUE TITLE
Timed out error when adding New Family with Attributes on the New Family page (Add Group block)

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#3652] opened 2019-04-15 16:41 UTC
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When adding a new family or person through the New Family page (Add Group block), if an attribute category is added to the New Family process and one or more attributes are filled out when adding an individual, Rock will throw a timed out error. Removing the attribute category from the New Family process or leaving the attributes blank will allow the New Family process to complete.

![image](https://user-images.githubusercontent.com/383807/56155094-f3a18180-5f6e-11e9-8b33-e7858d2917d3.png)

### Steps to Reproduce
1. Go to the New Family page and edit the block to allow a Person attribute category. 
1. Fill in the needed info for an individual. Be sure to place information in the attribute(s) that shows up at the end of the New Family process. 
1. Timeout error will occur.

We didn't have this issue on v8.5 but noticed it when we update to v8.7. I have tested it on the demo server which is currently at v8.6 and v8.6 runs into the same issue.

**Expected behavior:**

The expected behavior is to successfully add an individual or family through the New Family block with additional attributes at the end, not resulting in a timed out error.

**Actual behavior:**

When values are entered for the attributes at the end of the New Family process, the process times out. 

I don't believe it is specific to an attribute's type. I have tried entering in a single text value and leaving the rest blank. The result is a timed out error. I have tried the same with just a date value attribute and just a single select value attribute and both instances result in a timed out error.

### Versions
* **Rock Version:** v8.6.2 and v8.7.6
* **Client Culture Setting:** en-US

**Comment by JimMichael** [comment] 2019-04-15 18:51
This sounds like the issue where you have _Allow Snapshot Isolation: No_ and _Is Read Committed Snapshot On: No_ set on the database instead of Yes for both. If you look at the i icon in Admin toolbar, then the Diagnostics tab, what are yours set to?

**Comment by nairdo** [comment] 2019-04-15 19:52
I was able to confirm the same thing and reproduce the issue locally.  Thanks Jim!

![image](https://user-images.githubusercontent.com/383807/56160984-54d05180-5f7d-11e9-945c-7ceea1369628.png)

**Comment by JimMichael** [comment] 2019-04-15 19:56
Thanks @nairdo ! Just for my own understanding... when some block like this does NOT work with the snapshot settings set to _No_, that means it's a bug because it _should_ (even though it works with them set to _Yes_?)

**Comment by nairdo** [comment] 2019-04-15 20:11
@JimMichael Yes, that's exactly right.  We are striving to make any/all wrapped transaction-based operations in Rock work even if someone has not yet set their database to `SET READ_COMMITTED_SNAPSHOT ON`.

**Comment by BEGamache** [comment] 2019-04-15 22:19
@JimMichael Correct, our settings are Allow Snapshot Isolation: No and Is Read Committed Snapshot On: No.

**Closed** 2019-04-23 17:50 UTC
Labels: Fixed in v8.8, Status: Confirmed, Status: Core Team, Type: Bug
