### ISSUE TITLE
Get NCOA Job fails in 12.6

### ISSUE THREAD

**Issue by edcylam** [SparkDevNetwork/Rock#4825] opened 2021-11-08 23:01 UTC
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)? Edmund> Not available to reproduce
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Rock fails to run the Get NCOA job on 12.6 and reports the NCOA API server is down.

### Steps to Reproduce

1. Go to System Settings > Spark Data Settings to set up NCOA:
- Choose a data view
- Set Minimum Move Distance to Inactivate to 50 miles
- Uncheck Mark 48 Month Move as Previous Addresses
- Check Mark Invalid Addresses as Previous Addresses
- Set Inactive Record Reason to Moved
- Uncheck Recurring Enabled

2. Click Save
3. Click Run Manually

I have been told the issue has been fixed on 12.6, but it doesn't work on my instance.

**Expected behavior:** 

The Get NCOA job is expected to run successfully.

**Actual behavior:** 

It fails with the error message, "Communication with NCOA server failed: Could not create address file on the NCOA server that is required to begin processing. Possible cause is the NCOA API server is down."

### Versions

* **Rock Version:** 12.6 
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1201413650149249">image.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1201413650149251">image.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1201413871506564">image.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1201413871506566">image.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1201259436153130">Screenshot_20211129-082752_Chrome.jpg</a>

**Comment by nairdo** [comment] 2021-11-24 22:07
@edcylam The problem is with the service vendor we use for NCOA.  We just wanted to let you know we've been working with them and they have confirmed the problem is on their side. They are estimating they will have an update to us by next week, so we will let you once we receive additional news.

**Comment by nairdo** [comment] 2021-12-07 21:43
Edmund (@edcylam).  The vendor has since resolved their API issue and the other reported corresponding Rock NCOA problems have also gone away.  

Can you confirm that you are working again too?

Then, also please let us know (at info @ spark dev network . org) if you believed you were erroneously charged so we can make a refund.

**Comment by edcylam** [comment] 2021-12-07 22:43
@nairdo Thanks for the update. Before I run the NCOA service, I have a question. If I simply want the service to update any address changes in all the profiles in my Rock instance without inactivating any profiles, can I set the "Minimum Move Distance to Inactivate" field to a large value (e.g. 3,000 miles)?

**Comment by nairdo** [comment] 2021-12-08 19:35
> can I set the "Minimum Move Distance to Inactivate" field to a large value (e.g. 3,000 miles)?

Yes, that's what I would do too.

**Comment by shauncummings** [comment] 2021-12-09 21:34
Hello @edcylam.  I'm just checking to see whether or not you have confirmed that the vendor's fix to their API has resolved your issue.  Please let us know if you're still having any trouble.

**Comment by edcylam** [comment] 2021-12-09 22:24
@shauncummings I ran it manually. The job status shows success and says, "Job complete. NCOA status: Pending: Report." How long does it take to complete updating all profiles? I have about 10K profiles to be updated.

**Comment by edcylam** [comment] 2021-12-09 23:25
@shauncummings It took 70 minutes to complete the job.

**Comment by shauncummings** [comment] 2021-12-09 23:59
> @shauncummings It took 70 minutes to complete the job.

I'm assuming that means it completed and you got results, so I'm gong to go ahead and close this issue.

The processing time is variable, and depends on the size of the file and other factors on the NCOA vendor's side.  The job typically runs every 20 minutes to check whether the report has been competed.

**Closed by shauncummings** 2021-12-09 23:59 UTC
Labels: Status: Confirmed
