### ISSUE TITLE
Additional Time Sign-Up Page can allow Max Capacity of Group Schedule Locations to be Exceeded

### ISSUE THREAD

**Issue by dataCollegechurch** [SparkDevNetwork/Rock#5440] opened 2023-05-08 18:48 UTC
## Please go through all the tasks below

* [x] Check this box only after you have successfully completed both the above tasks

## Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.
Concurrent users of the Additional Time Sign-Up page via the Group Schedule Toolbox v2 block can lead to Group location schedule max capacities being exceeded.## Expected Behavior
Group Location Schedule Max Capacities will not be exceeded as a result of multiple concurrent users of the Additional Time Sign-Up Page. ## Actual Behavior
Multiple concurrent users of the Additional Time Sign-Up Page can lead to Group Location Schedule Max Capacities being exceeded.## Steps to Reproduce

1. On the demo site set the Ushers Serving Location Min/Desired/Max capacity to 1 for Saturday 4:30pm schedule at the Main Campus Location. Make sure to save the group.
1. ![image](https://user-images.githubusercontent.com/54962439/236903026-944befc9-d799-4f53-b7ee-d3ece1f44c46.png)
1. Check to make sure Ted Decker and Jim Simmons are Usher Group members
1. Open the [Ted Decker Groups Tab](https://rock.rocksolidchurchdemo.com/person/4/groups)
1. Click on Sign-Up for Additional Times button
1. In a new tab Open the [Jim Simmons Groups Tab](https://rock.rocksolidchurchdemo.com/person/10/group)
1. Sign Jim Simmons up for the Users Saturday 4:30pm Main Location spot on a specific day
1. ![image](https://user-images.githubusercontent.com/54962439/236903659-ae5b710b-d643-403f-9863-404f30615f62.png)
1. On the Ted Decker tab in your browser sign him up for the Users Saturday 4:30pm Main Location spot on the same day Jim is signed up for
1. ![image](https://user-images.githubusercontent.com/54962439/236903736-6bb6e8eb-f9b6-4344-be5f-98a22178c3dc.png)
1. Click back to the homepage on both the Ted Decker and Jim Simmon tabs
1. Navigate to the group schedule page for Users and see issue: 
![image](https://user-images.githubusercontent.com/54962439/236904589-806f1d5e-792e-4d62-b72b-e4602f1c5ad9.png)

## Rock Version
14.2## Client Culture Setting
en-us

**Comment by jasonhendee** [comment] 2023-11-08 15:41
@dataCollegechurch Thank you for bringing this to our attention. We've confirmed it's an issue in the Web Forms version of the Group Schedule Toolbox (v2) block.

We're releasing an Obsidian rewrite of the toolbox block (to replace both the "v2" and "v1" versions of the existing toolbox blocks) in Rock v16.1, and have confirmed that this is not an issue there: if an individual attempts to sign up for a schedule/location that becomes unavailable as you've described, a friendly error message will be displayed and their list of available sign-ups will be refreshed on the page, giving them an opportunity to select a different slot.

Since the Obsidian block is the future direction, we will not be updating the behavior in the old, Web Forms block. We're also going to go ahead and close this issue. Please let us know if you have any additional questions or concerns.

**Closed by jasonhendee** 2023-11-08 15:41 UTC
Labels: Type: Bug, Status: Confirmed, Fixed in v16.1
