### ISSUE TITLE
Mobile Number not displaying in the Grid. Show in Grid enabled

### ISSUE THREAD

**Issue by EastviewBrandon** [SparkDevNetwork/Rock#4304] opened 2020-07-22 14:15 UTC
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
Mobile Number as a person field type on a registration doesn't show in grid or in export even though show in grid is enabled.
![Registration No Mobile Number](https://user-images.githubusercontent.com/68616090/88186159-75646e00-cbfa-11ea-8bd1-d6e0e913862f.PNG)
Its Shows on the registration. 
![Registration](https://user-images.githubusercontent.com/68616090/88187023-a1342380-cbfb-11ea-97dd-0070babd7a7e.PNG)
It was working in 10.2 Updated to 10.3 and this started. 

### Steps to Reproduce

1. Create A registration template with a registration form with Mobile Number Person Field
2. Input Registration include mobile number
3. Go to tools, Event Registrations, The Registration Template, The Registration, Registrants Tab
4. Look for Mobile Number Column 
5. Click on Registration Mobile Number on Registration

**Expected behavior:**

Mobile Number Should be listed in the column 

**Actual behavior:**

Mobile Number Not Listed in column

### Versions

* **Rock Version:** [Rock McKinley 10.3 (1.10.3.7)]
* **Client Culture Setting:** [en-US]

**Comment by EastviewBrandon** [comment] 2020-07-22 15:12
Here is a thread in rocket chat on this as well. [https://chat.rockrms.com/channel/events-registrations?msg=br8YwjgS4jM95mr3w](url)

**Comment by BEGamache** [comment] 2020-07-22 17:02
I can confirm this. I still have my v11 alpha instance up and can reproduce it there, not certain if it was corrected in v11 beta. It also occurs on the demo site (v10.3).

**Comment by nairdo** [comment] 2020-07-22 17:25
@EastviewBrandon @BEGamache We did make a recent change (c26e5be) for #4276 which _might_ be related.  Have either of you tried to reproduce on the pre-alpha site at?: http://rockrmslatest.com (we just deployed the latest pre-alpha yesterday)

**Comment by EastviewBrandon** [comment] 2020-07-22 18:23
it appears to be fine on pre-alpha
![Registration pre alpha](https://user-images.githubusercontent.com/68616090/88212575-18c67a80-cc1d-11ea-8a23-ab235f3053f7.PNG)

**Comment by nairdo** [comment] 2020-07-23 20:32
Since we've confirmed the bug was in v10.x and is not in v11.1, it's possible it was corrected by [this other commit](https://github.com/SparkDevNetwork/Rock/commit/348cd17279afe85f11e15b4f22ff0d6f35a6409d#diff-12baa2ba843bdfff8c28fc422fe24fce),  I'll close this out and label it as **Fixed in v11.1**

**Closed by nairdo** 2020-07-23 20:32 UTC
