### ISSUE TITLE
Merging People with Secured Attributes ( Values go away!)

### ISSUE THREAD

**Issue by markewampler** [SparkDevNetwork/Rock#3310] opened 2018-10-01 15:51 UTC
### Description
Secured Person Attribute values are dropped on a merge person if the person who is merging the duplicates do not have visibility to the secured attribute

### Steps to Reproduce
1. Add a Person Attribute and secure it to a specific role/user (add to category for visibility)
1. Add a value to the attribute
1. Try and Merge the person with someone who has merge security, but not security to the attribute
1. The attribute is not available for them to choose
1. The attribute is deleted on the record (stored in history that it was removed though thankfully)

**Expected behavior:**

Not sure honestly...  We want the attribute to be secured but at the same time we want people to be able to merge.  I don't know if this would trigger an approval process if the person has a secured attribute that the merger cannot see.  If the attributes that are secured have no value then move along like normal?

**Actual behavior:**
Attribute value is blanked out.  Stored in history table though as being removed.

### Versions
* **Rock Version:** 7.4
* **Client Culture Setting:** [en-us]

**Comment by nairdo** [comment] 2018-10-04 01:06
Hey Mark, this topic is covered somewhat in the [Person & Family Field Guide](https://www.rockrms.com/Rock/BookContent/5/125#mergingrecords)

> **Merging Records Without Enough Security Rights**
> If you have access to merge but don't have enough security access to view things such as attributes, you won't be able to choose which item survives when the records are merged. Rock will take the value from the primary person/family you choose at the top of the merge panel. This could lead to unintended data being selected during the merge so you should consider giving individuals processing merge requests full access to all person attributes.

So can you clarify... are you saying the values that were dropped were on the "primary" person's record?  If so, that is a bug, but if the values were on the non-primary person, then it is not a bug.  This is why it is recommended that the privileged people doing merges have all the needed security rights to see ALL attributes.

**Comment by markewampler** [comment] 2018-10-05 14:58
I agree, but where it gets interesting is the idea then that the only way to safely merge someone is to have a Rock Administrator do it, or for every secured attribute we create to add a specific role into visibility.  It just adds one more layer of complexity to creating a secured attribute.  Which we understand the value of doing that.  Just wondering if there isn't an idea there of throwing a flag on the record when you are on the merge screen that there is an attribute on one of these records that you cannot see so you shouldn't be doing this.  Then we could have a volunteer team take care of 90% of the merge cases and when they see the flag to notify the Staff team that this is a sensitive merge or whatever you want to call it.  So this may be more of a feature request than a bug if we look at it that way.

**Comment by winmastr** [comment] 2018-10-17 15:14
So, based on these last comments, its not  a bug, but if a person is placed in the Group Merge Person role, that role must be added to every attribute (for all intents) that exists and all future attributes created. That does not seem reasonable. Giving Rock admin roles to a regular employee who is responsible for merging isn't a solution either as giving the keys to the kingdom is a major issue. So, why not either create a merge person role ADMIN or simply add to that role, a similar code structure that automatically allows everything related to a person to be included in a merge selection. I see no other reasonable solution. As the current merge method now creates a reason to Not Merge. In our case, access to specific groups and attributes associated with them would be lost along with the majority of safety and security attributes.

**Comment by winmastr** [comment] 2018-10-17 15:17
I am in the process of testing an incident that we were just made aware of 28 days ago where a Rock Admin merged a record (as it turns out, it was an employee record). 86 groups that that person was a part of were removed from the remaining record. I suspect that the record selected to remain did not contain those groups, but since the merge function doesn't display groups or warn about loosing groups, they were deleted along with all accesses.

**Closed** 2019-10-15 17:11 UTC
Labels: Fixed in v9.4, Topic: CRM, Type: Enhancement

**Comment by nairdo** [comment] 2019-10-28 23:01
Just a related FYI. We're also going to change this once more in v9.4, adding a new _Security Verb_ "View All Attributes" so that the people/roles listed in this verb will have access to view all attributes.  Anyone else who tries to merge without that security key will be warned **IF** the records they are trying to merge contain conflicting values for attributes that they don't have access to view.
