### ISSUE TITLE
Javascript Error on Connection Opportunity Item with Apostrophe in the Title

### ISSUE THREAD

**Issue by frogydiak** [SparkDevNetwork/Rock#5625] opened 2023-10-05 22:33 UTC
### Description

Open Developer Tools in your browser and go to Console:

![image](https://github.com/SparkDevNetwork/Rock/assets/1373815/d2de30e0-21e0-4d6c-b797-145bf28b7286)

Clicking the link in he right of the error and you'll see:

![image](https://github.com/SparkDevNetwork/Rock/assets/1373815/8b3f7a7d-0ebd-4c0a-b4c3-5928cc751518)

I don't know if the javascript error affect anything but it is still functional.

### Actual Behavior

See description

### Expected Behavior

Shouldn't hany any console error.

### Steps to Reproduce

I'm working on Serving Opportunities and created an entry and titled "Children**'s** Ministries Volunteer".

- Go to the entry and open it
- Click on 'a request'
- Open your developer tools > console and you'll see an error

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

15.1

### Client Culture Setting

en-US

**Comment by nairdo** [comment] 2023-10-05 23:49
@frogydiak  I've tried reproducing this without success.  Am I missing something?

https://github.com/SparkDevNetwork/Rock/assets/383807/41964166-e78f-460a-8df5-919890663028

**Comment by Jon-Corey** [comment] 2023-10-06 18:52
This looks like a duplicate of https://github.com/SparkDevNetwork/Rock/issues/5595.

@nairdo, this issue is only caused by the single quote character (`'`), not by other similar-looking characters such as the apostrophe/smart quote (`’`). I can't tell from your video which character you are using, but that may explain why you can't reproduce this.

**Comment by frogydiak** [comment] 2023-10-06 18:58
@nairdo I just tested it in Rock Demo and there's an error:

Video capture: https://take.ms/0wMaf

**Comment by nairdo** [comment] 2023-10-06 19:31
> @nairdo, this issue is only caused by the single quote character (`'`), not by other similar-looking characters such as the apostrophe/smart quote...

I was just using the simple single quote also.  It might be that the issue still exists in the filter we wrote for Fluid but was fixed in the DotLiquid version.  I've put this into the developer pipeline to confirm/fix.

**Comment by MrUpsideDown** [comment] 2023-10-09 06:57
Confirmed and closed as duplicate of #5595.

**Closed by MrUpsideDown** 2023-10-09 06:57 UTC
Labels: Status: In Dev Queue
