### ISSUE TITLE
Registration Input on Conditional Fields is Cleared

### ISSUE THREAD

**Issue by kkiserGH** [SparkDevNetwork/Rock#4380] opened 2020-08-27 13:12 UTC
### Prerequisites
* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

**Sorry!  This is a duplicate of #4354**

### Description

When registering for an event that uses conditional fields tied to different source fields, any previous input for a conditional field is cleared when another conditional field is displayed.

### Steps to Reproduce

1.  Create a new registration template.
2.  Add a new registrant attribute field "Question 1"
3.  Add a new registrant attribute field "Conditional Question for Question 1"
4.  Edit the filter for "Conditional Question for Question 1" to make it show when the field "Question 1" is equal to "Yes"
5.  Add a new registrant attribute field "Question 2"
6.  Add a new registrant attribute field "Conditional Question for Question 2"
7.  Edit the filter for "Conditional Question for Question 2" to make it show when the field "Question 2" is equal to "Yes"
8.  Save the registration template.
9.  Create a new registration instance for this template.
10.  Register for this new event.
11.  Enter Name and then enter "Yes" for the "Question 1" field.
12.  See the "Conditional Question for Question 1" field appear.
13.  Enter some text in the "Conditional Question for Question 1" field.
14.  Enter "Yes" for the "Question 2" field.
15.  See the "Conditional Question for Question 2" field appear.

**Expected behavior:**

When the "Conditional Question for Question 2" field appears, the text previously entered for the "Conditional Question for Question 1" field should remain.

**Actual behavior:**

The text previously entered for the "Conditional Question for Question 1" field is cleared.

### Versions

* **Rock Version:** v11.0
* **Client Culture Setting:** en-US
![Registration Input is on Conditional Fields is Cleared - After  Question 2](https://user-images.githubusercontent.com/54817742/91446298-e8d24e80-e83c-11ea-8053-2cd5d63bd954.PNG)
![Registration Input is on Conditional Fields is Cleared - Before Question 2](https://user-images.githubusercontent.com/54817742/91446299-e8d24e80-e83c-11ea-9438-5699e00c38f7.PNG)

**Comment by nairdo** [comment] 2020-08-27 16:05
This is a duplicate of #4354. Closing this and marking that issue confirmed.

**Closed by nairdo** 2020-08-27 16:05 UTC
