### ISSUE TITLE
Event Item Photo Replaced when Editing Event Description

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#4656] opened 2021-04-08 19:16 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

If you paste content into the _Description_ section of an _Event Item_, it will update the Event's Photo to a "screenshot" of the description text, completely replacing the photo you have already uploaded. Also, if you have no photo and you do this process, it will create an image for you automatically of the description text (this part may be intentional). 

Looking into File Storage of the Unsecured File type, it will actually create a new file and upload it to whatever storage type you are using. In our case, we use Azure Blob Storage. So each time I paste content into the description area, I get a random file uploaded to Azure, and then I end up uploading the actual photo after. 

https://user-images.githubusercontent.com/23226974/114082527-db258280-987b-11eb-9588-efff9f4a744d.mov

### Steps to Reproduce

1. Go to `https://rockrmslatest.com/page/396?EventCalendarId=1&EventItemId=2`.
2. Click Edit.
3. Attempt to paste content into the description area.
4. See that the Event Photo is replaced with the description text.

**Expected behavior:**

I would expect that my Event Photo would not be replaced, creating a new file in my Azure Storage each time I do this.

**Actual behavior:**

The Event Photo is replaced.

### Versions

* **Rock Version:** [v12.2, v13.0]
* **Client Culture Setting:** [en-US]

**Comment by mikedotmundy** [comment] 2021-04-08 19:26
Ah!! I even did a search and missed it. I would assume it is similar if not the same. Thanks @JimMichael

**Comment by nairdo** [comment] 2021-04-09 16:17
Yep, this is a duplicate of #2994.  Thanks Jim (and Mike)!

**Closed by nairdo** 2021-04-09 16:17 UTC
