### ISSUE TITLE
Steps with Multiple Updates through Dataview

### ISSUE THREAD

**Issue by jcjones37** [SparkDevNetwork/Rock#4390] opened 2020-09-05 19:08 UTC
### Description
I have tried to update steps by data view multiple times, but for some reason, the job seems to update their step multiple times.  I asked about this in Chat and one other person experienced the same thing. However, I am unable to replicate the issue on the demo site. https://chat.rockrms.com/channel/engagement?msg=osTuEdBgzQbFMCghn

![](https://user-images.githubusercontent.com/41912840/92311874-12038500-ef89-11ea-9462-19948358bfec.png)

![](https://user-images.githubusercontent.com/41912840/92311876-15970c00-ef89-11ea-8d29-bea79472fef0.png)

### Steps to Reproduce
1. Go to 'People' - 'Steps'
1. Create a Step
1. Set the Step to Sync with a Dataview
1. Run the Job to update steps

I have the step to 'not' [Allow Multiple] and I have set the step to [Allow Multiple] and both produced the exact same results. (multiple completions)

The data view only includes each person once and I have only only run the job once... yet the step shows they have completed multiple times.

![](https://user-images.githubusercontent.com/41912840/92311896-598a1100-ef89-11ea-8e8d-4c16df424d6b.png)

**Expected behavior:**

I would expect that the step would only be completed once if they are being synced to a Dataview.  They would show as completed the first time the job runs after the person has been added to the data view.

**Actual behavior:**

The job seems to add multiple completions to the persons step record. (note: running the job multiple times does not seem to add any additional completions)

### Versions
* **Rock Version:** [11.0]
* **Client Culture Setting:** [en-US]

**Comment by azturner** [comment] 2020-09-09 22:23
This looks like it is due to how many times person has been merged. I was able to reproduce this on alpha site by creating duplicate Ted Decker record, merging the duplicate records and then running the Steps Automation job.  It created two steps for Ted.

**Comment by mikedotmundy** [comment] 2020-10-20 19:34
Confirming that I ran into this same issue on v11.2. I had a person have 5 steps created, with Allow Multiple turned off. I will also confirm what @azturner said. In my instance, it created steps based on the number of Alternate Identifiers on a person's profile. I could not duplicate this on the pre-alpha site v12.0.

**Comment by mikedotmundy** [comment] 2020-10-20 19:45
Confirm this is happening in v11.3 also.

**Closed** 2020-10-22 14:29 UTC

**Comment by smross** [comment] 2021-01-21 19:32
We definitely experience this in v11.2

After upgrading to v11.3 and v12.0 (in non-production environments), we're still seeing the (pre-existing) duplicates in place.
**Should this bugfix also 'clean up' duplicates from the person alias' pointing to the same person?** Or is the resolution for prior duplicates to remove the duplicate entries?

**Comment by mikedotmundy** [comment] 2021-01-21 19:50
Upgrading to 12.0 fixed the issue, but it did not delete the existing duplicates. I ran this SQL for each of the effected Step Types to clean them up. ```DECLARE @stepTypeId int = 5;
DECLARE @stepsNumbered table( [RowNumber] int, [Id] int );

INSERT INTO @stepsNumbered( [RowNumber], [Id] )
SELECT
    ROW_NUMBER() OVER ( PARTITION BY pa.PersonId ORDER BY s.CreatedDateTime ASC ) 'RowNumber'
    ,s.[Id]
FROM
    [Step] s
    JOIN [PersonAlias] pa ON s.[PersonAliasId] = pa.[Id]
WHERE [StepTypeId] = @stepTypeId;

SELECT p.FirstName, p.LastName, * --After you are confident in the results, replace this line with: DELETE s 
FROM
    @stepsNumbered num
    JOIN [Step] s ON num.[Id] = s.[Id]
    JOIN [PersonAlias] pa ON pa.Id = s.PersonAliasId
    JOIN [Person] p ON pa.PersonId = p.Id
WHERE num.RowNumber > 1```

**Comment by nairdo** [comment] 2021-01-22 21:47
> **Should this bugfix also 'clean up' duplicates from the person alias' pointing to the same person?**

The fix will only prevent creating duplicate steps (for people who have been merged multiple times).
