### ISSUE TITLE
Conflict with Safari 13

### ISSUE THREAD

**Issue by nathanp** [SparkDevNetwork/Rock#3916] opened 2019-09-23 21:27 UTC
### Description

After upgrading Safari to the latest version (13) on macOS, Rock is freezing and crashing the browser. Our staff is noticing it mostly on the Email Editor in the Email Wizard. This has happened to multiple users all running Safari 13 on macOS.

### Steps to Reproduce

1. Using Safari 13, create a New Communication in Rock.
2. Once you get to the Email Editor, try to use a Text block.
3. Once you're within the text block and begin to edit, the browser should freeze.

**Expected behavior:**

User should be able to edit the text.

**Actual behavior:**

The browser freezes and Safar must be force-quit.

### Versions

* **Rock Version:** 9.1 (1.9.1.3)
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1141403791959053">image.png</a>

**Comment by cabal95** [comment] 2019-09-24 03:01
Confirmed on both demo and pre-alpha.

I was also able to get the crash to happen (non every time) when trying to select Ted Decker from the person picker.

My stack trace of the freeze in Safari:

```
  11  start + 1 (libdyld.dylib + 91093) [0x7fff613193d5]
  11  NSApplicationMain + 777 (AppKit + 10984) [0x7fff3297dae8]
  11  -[NSApplication run] + 699 (AppKit + 79272) [0x7fff3298e5a8]
  11  -[BrowserApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 273 (Safari + 811231) [0x1084de0df]
  11  -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1361 (AppKit + 103563) [0x7fff3299448b]
  11  _DPSNextEvent + 1135 (AppKit + 108445) [0x7fff3299579d]
  11  _BlockUntilNextEventMatchingListInModeWithFilter + 64 (HIToolbox + 44150) [0x7fff345fcc76]
  11  ReceiveNextEventCommon + 603 (HIToolbox + 44773) [0x7fff345fcee5]
  11  RunCurrentEventLoopInMode + 292 (HIToolbox + 45483) [0x7fff345fd1ab]
  11  CFRunLoopRunSpecific + 455 (CoreFoundation + 237246) [0x7fff3539debe]
  11  __CFRunLoopRun + 1189 (CoreFoundation + 239029) [0x7fff3539e5b5]
  11  __CFRunLoopDoSources0 + 195 (CoreFoundation + 241643) [0x7fff3539efeb]
  11  __CFRunLoopDoSource0 + 108 (CoreFoundation + 357929) [0x7fff353bb629]
  11  __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17 (CoreFoundation + 358019) [0x7fff353bb683]
  11  WTF::RunLoop::performWork(void*) + 26 (JavaScriptCore + 14807962) [0x109fdd39a]
  11  WTF::RunLoop::performWork() + 237 (JavaScriptCore + 14807229) [0x109fdd0bd]
  11  IPC::Connection::dispatchIncomingMessages() + 759 (WebKit + 543383) [0x10ab55a97]
  11  IPC::Connection::dispatchMessage(std::__1::unique_ptr<IPC::Decoder, std::__1::default_delete<IPC::Decoder> >) + 223 (WebKit + 527301) [0x10ab51bc5]
  11  WebKit::WebProcessProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&) + 28 (WebKit + 3314136) [0x10adfa1d8]
  11  IPC::MessageReceiverMap::dispatchMessage(IPC::Connection&, IPC::Decoder&) + 126 (WebKit + 618836) [0x10ab68154]
  11  WebKit::WebPageProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&) + 62159 (WebKit + 5330497) [0x10afe6641]
  11  WebKit::WebPageProxy::fontAtSelectionCallback(WebKit::FontInfo const&, double, bool, WebKit::CallbackID) + 78 (WebKit + 3679952) [0x10ae536d0]
  11  WebKit::GenericCallback<WebKit::FontInfo const&, double, bool>::performCallbackWithReturnValue(WebKit::FontInfo const&, double, bool) + 43 (WebKit + 3680285) [0x10ae5381d]
  11  WTF::Detail::CallableWrapper<WebKit::WebViewImpl::updateFontManagerIfNeeded()::$_7, void, WebKit::FontInfo const&, double, bool, WebKit::CallbackBase::Error>::call(WebKit::FontInfo const&, double, bool, WebKit::CallbackBase::Error) + 93 (WebKit + 2966389) [0x10ada5375]
  11  +[NSFont fontWithDescriptor:size:] + 52 (UIFoundation + 210823) [0x7fff5c070787]
  11  +[__NSFontTypefaceInfo typefaceInfoForKnownFontDescriptor:] + 35 (UIFoundation + 211175) [0x7fff5c0708e7]
  11  _pthread_mutex_firstfit_lock_slow + 222 (libsystem_pthread.dylib + 5325) [0x7fff6150b4cd]
  11  __psynch_mutexwait + 10 (libsystem_kernel.dylib + 16134) [0x7fff61450f06]
 *11  psynch_mtxcontinue + 0 (pthread + 10172) [0xffffff7f827fa7bc]
```

It seems to be font related. My best, blind, guess is that maybe we have a JavaScript library that is trying to do some kind of font autosize or something and using an invalid font size? Like I said, wild, blind, guess.

Asana apparently had the same bug reported for their system, but they didn't say exactly what they did to fix it:

https://forum.asana.com/t/safari-browser-is-freezing-after-update/60583

**Comment by jeremyhoff** [comment] 2019-09-24 03:10
FWIW – MacOS Catalina (beta) w/ Safari 13.0.1 does not exhibit this behavior.

--
Jeremy Hoff, Administrative Pastor
Shepherd Church - Porter Ranch
(818) 831-9333 x2119
“To Lift Up Christ, That The World Might Believe!"

**Comment by garrettjohnson** [comment] 2019-09-24 17:04
It appears that this behavior is caused by a bug inside of Safari's text rendering system. 

If you need to apply an emergency fix copy the following code into your Rock theme CSS Overrides box. See screenshot below. I'm updating core themes for the next point release.

```
// Temporary Fix for Safari 13 Select Rendering Bug
select {
  text-rendering: auto;
  -webkit-font-smoothing: none;
}
// End Temporary Fix
```
![prealpha rocksolidchurchdemo com_page_443_EditTheme=Rock(iPad)](https://user-images.githubusercontent.com/374209/65533420-6a459200-deb2-11e9-917b-ef37f223e133.png)

**Comment by garrettjohnson** [comment] 2019-09-24 17:16
Fixed via https://github.com/SparkDevNetwork/Rock/commit/8c8fc7dd8c33bb4906c9d11e7b6509db146e6ea0

**Comment by cabal95** [comment] 2019-09-26 21:39
There are other places that this fix does not address.  One that we have found is the Communication Wizard.

1. Select `New Communication` from the Person menu.
2. Switch to `Select Specific Individuals`
3. Click on `Add Person` and add yourself.
4. Click Next
5. Set `Communication Name` to `test` and click Next.
6. Select `Blank` as your communication template.
7. Enter the `From Name`, `From Address`, and `Email Subject` as whatever you want and click `Next`.
8. Drag the `One` column placeholder into your communication.
9. Drag the `Text` placeholder into your communication.
10. Click on the Text placeholder so you can change the content.
11. Click into the Text detail section on the right.
12. Type anything.

In step 12, I can never get it to let me type more than 1 character before it freezes. Stack dump shows the same error with doing something Font related.

**Comment by garrettjohnson** [comment] 2019-09-26 22:53
I'll be committing shortly to fix the problem in the editor as well. If you need to apply an emergency fix copy the following code into your Rock themes, use the CSS Overrides box.

```
// Temporary Fix for Safari 13 Select Rendering Bug
html {
  text-rendering: auto !important;
}

select {
  text-rendering: auto !important;
  -webkit-font-smoothing: none !important;
}
// End Temporary Fix
```

**Closed** 2019-10-01 14:18 UTC
Labels: Fixed in v9.4, Priority: Critical, Status: Confirmed
