### ISSUE TITLE
"Add a family" dialogue- people being added as "inactive" in family groups

### ISSUE THREAD

**Issue by ccofnow** [SparkDevNetwork/Rock#1050] opened 2015-05-19 18:47 UTC
I'm finding, as I'm setting up a page to list first-time givers within a selected date range, that families created by our accounting volunteer (that is, those added to Rock because we received a contribution from them) are being added to the new families as "inactive" members. Not that their connection statuses with the church are set to Inactive, but rather their roles within their families. That wreaks havoc with some of the reports I have set up, and I'm not sure where that status is coming from.

Edit: I have confirmed that this is happening to ALL newly-created families, both from within the "Match Transactions" page link, and from the "regular" people menu link.

Thanks!

**Comment by nairdo** [comment] 2015-05-21 22:43
This is a duplicate of #1013 

Fixed in the develop branch a few weeks ago via commit https://github.com/SparkDevNetwork/Rock/commit/2643ad36f184bd112cc5859513e743decc4b860b by  @mikepetersonccv.

**Closed by nairdo** 2015-05-21 22:43 UTC
Labels: Fixed in v4.0
