### ISSUE TITLE
CMS Configuration Pages:  HTML Content Blocks Rendering Styles

### ISSUE THREAD

**Issue by nlBayside** [SparkDevNetwork/Rock#5385] opened 2023-04-12 00:19 UTC
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

I think this issue is related to #4121 but is slightly different.

Styles from an HTML content block are left in the DOM, and can show up unexpectedly on the page. This is jarring sometimes if the styles are drastic from the internal site. This doesn't happen with every HTML block, but is a surprise for sure. The HTML content within it still remains on the page despite closing the modal.
![Screen Shot 2023-04-11 at 5 12 36 PM](https://user-images.githubusercontent.com/85907597/231315170-c2849141-d5cc-48ef-b043-45faf49ebf8f.png)
![Screen Shot 2023-04-11 at 5 12 47 PM](https://user-images.githubusercontent.com/85907597/231315181-5be86042-0849-4fbf-a80b-57f27e5afa1d.png)
![Screen Shot 2023-04-11 at 5 12 53 PM](https://user-images.githubusercontent.com/85907597/231315189-58a815de-631a-4892-b31e-a6b74d1fd187.png)
![Screen Shot 2023-04-11 at 5 16 29 PM](https://user-images.githubusercontent.com/85907597/231315544-07950888-6e06-4237-bf7f-70c6de89ba88.png)

### Expected Behavior

The style for the admin page doesn't change when editing an HTML content block in the CMS configuration pages. Also, the modal content should disappear from the DOM after it has been closed, rather than persisting in the DOM.

### Actual Behavior

Styles and HTML content from the block persist after closing the modal and can override the styles of the admin page. Forcing the admin to refresh the page to clear away these styles.

### Steps to Reproduce

- Go to 'CMS  Configuration > Pages'
- Add HTML content blocks to a page.
- Add some styles to an HTML content block that would display on the page.
- Save.
- Open edit on that block.
- Close modal.
- Open edit modal again to see issue.

### Rock Version

v14.2

### Client Culture Setting

en-US

**Comment by nlBayside** [comment] 2023-04-13 15:58
Just tested this on the latest site as well, which is at v16 when I test it.
![Screen Shot 2023-04-13 at 8 56 17 AM](https://user-images.githubusercontent.com/85907597/231816938-fb501063-f78f-4850-983b-2e10d04215d0.png)
![Screen Shot 2023-04-13 at 8 57 15 AM](https://user-images.githubusercontent.com/85907597/231817069-468988fe-67a5-498c-9dc9-ebed018412e3.png)
![Screen Shot 2023-04-13 at 8 57 24 AM](https://user-images.githubusercontent.com/85907597/231817087-3b6a2d9c-b9d8-4502-83e7-192825224714.png)

(I deleted the page after testing it on the latest site since I'm not sure how quickly that one gets reset compared to the demo site).

**Comment by nairdo** [comment] 2023-10-06 20:31
@nlBayside We've reviewed this and confirmed this is essentially due to the underlying Summernote editor (library) that Rock is currently using in the Html editor block.  Since that bug is also currently an open issue for them, we're going to close this out here.  However, our plans are to move away from Summernote with the upcoming Obsidian version of the Html editor block.

**Closed by nairdo** 2023-10-06 20:31 UTC
Labels: Type: Bug, Status: Confirmed

**Comment by joshuahenninger** [comment] 2024-08-02 16:24
We have confirmed that the Obsidian version of the HTML Editor control resolves the CSS issue, and this issue should be fully resolved once the Obsidian version of the HTML Content Detail block is completed.
