### ISSUE TITLE
API $filter datetime does not seem to follow ISO 8601 for timezones

### ISSUE THREAD

**Issue by trouttdev** [SparkDevNetwork/Rock#4006] opened 2019-11-20 18:37 UTC
### Description
When sending a request to the /api/People endpoint with a $filter of `ModifiedDateTime ge datetime'2019-11-20T11:33:44Z' or CreatedDateTime ge datetime'2019-11-20T17:00:44Z'` the UTC timezone (Z) is not honored.

Additionally, we're not able to add a timezone offset at all, as specified in ISO 8601, so, for example, `2019-11-20T17:00:44-0600` fails with the following error:
Unrecognized 'Edm.DateTime' literal

What we're trying to do is pull any records that have been added/updated since the last time we checked. We store the "last checked" date as a UTC timestamp, but the RockRMS installation we're testing with has the timezone set to US Central (-6). This would be fine if the Z (UTC timezone indicator) was honored, but it is not in this case.

We also explored pulling the Rock system timezone via API, but had no luck there. If we could do that, we could convert the UTC timestamp to the correct datetime before doing the API query, but that doesn't seem to be an option either.

I was also able to reproduce this on the Rock demo site by modifying the email for "Alisha Admin" to "admin1@organization.com" and then sending this request to the API: https://rock.rocksolidchurchdemo.com/api/People?$filter=ModifiedDateTime ge datetime'2019-11-20T11:30:44'

The user has a modified datetime of `"ModifiedDateTime": "2019-11-20T11:32:04.053",`, which is the AZ (-7) timezone, which is expected. But when sending the same request with the datetime updated to the UTC timezone (adding 7 hours): https://rock.rocksolidchurchdemo.com/api/People?$filter=ModifiedDateTime ge datetime'2019-11-20T18:30:44Z'

No user is returned.

### Steps to Reproduce
1. Install Rock + add sample data + set timezone to something other than UTC (ours is set to US Central, -6)
1. Update one of the sample records (I changed the email address of one of the records to test)
1. Send API request to <site>/api/People?$filter=ModifiedDateTime ge datetime'2019-11-20T11:33:44Z' or CreatedDateTime ge datetime'2019-11-20T17:00:44Z' -- change the date to a UTC date just before the update you performed
1. It will not pull any records 

**Expected behavior:**

According to ISO 8601 you should be able to include either Z for UTC, or a +/- followed by the time zone offset in order to specify the timezone of the timestamp.

**Actual behavior:**

The ModifiedDateTime filter seems to ignore the timezone and only filters by the datetime with the offset given in the Rock config file.

### Versions
* **Rock Version:** Rock McKinley 8.9 (1.8.9.1)
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment] 2019-12-11 00:39
This is a known situation.  There are some limitations regarding date, time, datetime, datetimeoffset, and timezone with the OData V3 library Rock currently uses, and the data types we use for things such as ModifiedDateTime. (In fact we postponed moving to OData V4 due to [some breaking changes](https://github.com/OData/WebApi/issues/136) that were made from V3.)  We see that the WebApi OData 5.6 _appears to possibly_ support timezones now, but it's not on our immediate road-map to test and investigate the other breaking changes caused by that update.

**Closed by nairdo** 2019-12-11 00:39 UTC
