### ISSUE TITLE
Contribution Statement List on Business Page causes error

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2012] opened 2017-02-07 17:20 UTC
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

If a Contribution Statement List Lava block is added to a business page you cannot add a business because the person GUID is not set on the new business page. 

### Steps to Reproduce

1. Add a Contribution Statement List Lava block to a business page with the person context
2. Add a new business

**Expected behavior:** 

Business page opens without error

**Actual behavior:** 

Cannot create a business
![pasted_image_at_2017_02_07_09_38_am](https://cloud.githubusercontent.com/assets/374209/22702748/915bd916-ed16-11e6-87ac-b39b19785c29.png)

### Versions

* **Rock Version:** 6.2
* **Client Culture Setting** en-US

**Comment by edmistj** [comment] 2017-03-24 17:01
Probably just needs a null check.

**Comment by trevor-tart** [comment] 2017-03-24 17:26
Looks like this already got fixed but was never closed. Unable to reproduce on develop, and there is already a NP check for TargetPerson. 

Verified that when adding the ContributionStatementListLavaBlock and trying to add a new business, TargetPerson was indeed null, but the check prevents any exceptions from occurring.

![bug-2012](https://cloud.githubusercontent.com/assets/5816164/24306016/61b1c21e-1095-11e7-90b7-bb5eaf174528.PNG)

**Comment by edmistj** [comment] 2017-03-24 17:33
Closing  based on previous fix.

**Closed** 2017-03-24 17:34 UTC
Labels: Claim It, Fixed in v7.0
