### ISSUE TITLE
System.FormatException on Contact Page

### ISSUE THREAD

**Issue by maurice-ellis** [SparkDevNetwork/Rock#3275] opened 2018-09-14 17:21 UTC
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
 [x] Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
 [x] Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
Again, I'm not sure what is going on because Im not experiencing any issues. Sorry for the lack of details, but here is the stack trace. Believe it could be the URL in the page. I copied the contact page from 

System.FormatException: Invalid length for a Base-64 char array or string..

![screen shot 2018-09-14 at 10 12 44 am](https://user-images.githubusercontent.com/7678232/45564994-23d14800-b807-11e8-8ee9-086382bc9cb2.png)

### Steps to Reproduce
Not sure

**Expected behavior:**

For an error not to occuring

**Actual behavior:**

An error is occuring

### Versions
* **Rock Version:** Rock McKinley 7.5 (1.7.5.59)
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment] 2018-09-17 21:05
Duplicate of #3274

**Closed by nairdo** 2018-09-17 21:05 UTC

**Comment by maurice-ellis** [comment] 2018-09-17 21:17
Im not understanding why this is a duplicate of my other one when it is a different page and different issue

**Comment by cabal95** [comment] 2018-09-17 21:43
Unless this is an error that you can reproduce at will, I would consider it a non-issue. Basically, the error being reported is saying "Somebody tried to a view a page, but sent us a bunch of invalid data" which is usually from bots scanning your site.

If this is something that you can reproduce at will, please include _exact_ steps to reproduce the bug.
