### ISSUE TITLE
Cannot edit existing or create new content channel items

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#4875] opened 2022-01-12 19:36 UTC
### Description

In Version 13, if you try to create a new content channel item (in any content channel) or edit an exsisting content channel item- it fails and creates an exception error.

### Steps to Reproduce

1. Go to content
2. Click a content channel
3. Open an item

**Expected behavior:**

Content channel item would open and allow editing or in the case of a new content channel item it would open up the page for you to create a new item.

**Actual behavior:**

Content channel item does not open and creates exception. Same issue with new content channel items. 

### Versions

* **Rock Version:** V13

**Comment by austinspooner** [comment] 2022-01-12 19:37
Exception Error:

![image](https://user-images.githubusercontent.com/657005/149209746-fb61c7b6-7da4-4c77-8a45-9e0ae3005634.png)

**Comment by JimMichael** [comment] 2022-01-12 19:41
Confirmed on 1.13.0.29 (alpha 1) but can't reproduce on prealpha.rocksoludchurchdemo.com 

Unable to try it on v13 beta (of the build is different) at this time.

**Comment by nairdo** [comment] 2022-01-14 15:39
fixed via https://github.com/SparkDevNetwork/Rock/commit/e88e0f4380587e68e6331654a4691634a5088c2e

**Comment by ethan-sparkdevnetwork** [comment] 2022-01-14 15:39
This was fixed in commit:
https://github.com/sparkdevnetwork/rock/commit/63b2e193e2380cc5900a58d1a39609796e386847

https://github.com/sparkdevnetwork/rock/commit/dbe6123696622e30e858cd92be9ff265fe05d21e

**Closed** 2022-01-14 16:09 UTC
Labels: Status: Confirmed, Fixed in v13.0
