### ISSUE TITLE
Typo in registration thank you email

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#2791] opened 2018-02-16 22:21 UTC
The new user registration thank you email has 'Thank-you'.

It should be 'Thank you'.

![thankyou](https://user-images.githubusercontent.com/4658177/36331861-826cd3d4-13d4-11e8-9cc7-1cc5b9bf7105.jpg)

**Comment by garrettjohnson** [comment] 2018-02-16 23:52
Duplicate of #1711

**Closed by garrettjohnson** 2018-02-16 23:52 UTC
