### ISSUE TITLE
Non-recurring events not included in calendar iCal feeds

### ISSUE THREAD

**Issue by sichiriu** [SparkDevNetwork/Rock#4186] opened 2020-04-16 16:06 UTC
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
Calendar events with non-recurring schedules or with schedules that occur on "Specific Dates" are not included in the calendar iCal feed on 10.2.

### Steps to Reproduce
1. Create an event occurrence with a non-recurring schedule or with the recurrence set to "Specific Dates"
1. View the feed for that calendar

**Expected behavior:**

Non-recurring event occurrences should show up in the feed.

**Actual behavior:**

Those events are missing from the feed.

### Versions
* **Rock Version:** Rock McKinley 10.2 (1.10.2.3)
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment] 2020-04-17 23:16
@sichiriu This seems like it might be a duplicate of #4112 , would you agree?

**Comment by sichiriu** [comment] 2020-04-18 01:16
It very well could be related, but I think this one's a bit different. That issue seemed to indicate that the events were showing in the .ics file, but were just missing the RRULE property. In my experience, the _entire_ event was missing from the .ics file.

**Comment by sichiriu** [comment] 2020-04-23 06:29
@nairdo Might be different than #4112, but seems to be a dupe of #4158.

**Comment by nairdo** [comment] 2020-04-23 15:18
Ok, I'll close this one as a duplicate so you can track one of the other two issues.

**Closed by nairdo** 2020-04-23 15:18 UTC
Labels: Type: Duplicate
