### ISSUE TITLE
Group Requirements & Attendance Digest - Emails

### ISSUE THREAD

**Issue by jcjones37** [SparkDevNetwork/Rock#4583] opened 2021-02-05 19:21 UTC
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

When using the Emails provide within System Communications:

- Group Requirements Notification
- Group Attendance Digest

They run and include groups that are [Inactive].

For example, if you have a group marked as [Active] it will appear on both the Group Requirements Notification and Group Attendance Digest.  However if a Group is marked as [Inactive], it will ALSO show on both emails.

### Steps to Reproduce

1. Create a Job to run either the Group Requirements Notification or the Group Attendance Digest.
2. Create an 'Active' Small Group and run the corresponding job.
3. Notice that the Job/Emails operate as you would expect
4. Go back to that 'Active' Small Group and mark it 'INACTIVE'
5. Run your job again and notice that the group will still be included in your email

**Expected behavior:**

I would expect when the job runs and the email is created, the email would exclude any groups that are INACTIVE

**Actual behavior:**

Current the email that is generated from the job includes ACTIVE and INACTIVE Small Groups

### Versions

* **Rock Version:** [11.3]
* **Client Culture Setting:** [en-US]

**Comment by MikeDPeterson** [comment] 2021-02-09 21:31
@jcjones37 Thanks for finding this issue. I wasn't able to reproduce this issue in the Group Requirements Notification job, but there was a bug in the Group Attendance Digest, which is fixed with https://github.com/SparkDevNetwork/Rock/commit/5872ebe20148d799324df1399ca761bd1fd81658

**Closed** 2021-02-09 21:31 UTC
Labels: Fixed in v12.2

**Comment by jcjones37** [comment] 2021-02-17 17:13
@MikeDPeterson  Thank you so much! Do you think this is along the same lines as the Pending Member email?  We have Inactive Leaders receiving the Pending Member email.

**Comment by jennifertroeger** [comment] 2021-02-18 17:20
@jcjones37 and @MikeDPeterson I'm noticing something similar to this, where inactive group members (leaders) are still receiving the group requirements notifications. I was going to submit a separate Github ticket but Jim Michaels pointed me to this ticket. Could be related.

**Comment by nairdo** [comment] 2021-02-19 19:10
> Do you think this is along the same lines as the Pending Member email? We have Inactive Leaders receiving the Pending Member email.

@jcjones37  I believe you're describing the issue #4489 which is resolved in v12.

> I'm noticing something similar to this, where inactive group members (leaders) are still receiving the group requirements notifications.

@jennifertroeger  We're looking into this now also, and another fix may be coming shortly. Thank  you for letting us know.

**Comment by jcjones37** [comment] 2021-02-22 15:53
Thank you @nairdo you are correct. In addition, and maybe this is another ticket, I actually had a group leader email me yesterday.  She received the Group Attendance Reminder. Her group is 'Inactive'.  And has been for months.  Looks like the attendance reminder email also overlooked the 'inactive' status.  I hope this helps and please re-direct me if I need to open a new ticket or there is already a ticket.  Just wanted to touch base.  

I appreciate everyone working on these tickets so much!

**Comment by nairdo** [comment] 2021-02-22 19:06
> please re-direct me if I need to open a new ticket

@jcjones37 Yes, I think that might be best to open a new issue since a quick look at the code for v12 (and v11.3) shows inactive groups have been filtered out from the `Send Attendance Reminders` job emails for a while:
https://github.com/SparkDevNetwork/Rock/blob/58826b52bd892a5a43094f09310a9a46b1231830/Rock/Jobs/SendAttendanceReminders.cs#L248  But perhaps something else is going on.  You'll probably want to dig up the exact details of the situation (group, group type, email address->people records, etc) to double check everything on your end too.

**Comment by MikeDPeterson** [comment] 2021-02-24 17:35
@jcjones37 I was able to reproduce this in the Group Requirements notification after all. sorry about that. Just fixed it with https://github.com/SparkDevNetwork/Rock/commit/a90dfb8bf72d9178973b1787b4037c012ca7ceda.  I updated my comment above https://github.com/SparkDevNetwork/Rock/issues/4583#issuecomment-776257326 and crossed that out.

**Comment by jcjones37** [comment] 2022-08-03 23:08
@MikeDPeterson - we are currently running 12.7 in production and 13.5 in development. This problem seems to have re-appeared in both.  I apologize for missing this much earlier.  Can you verify?

**Comment by jcjones37** [comment] 2023-01-09 18:59
@MikeDPeterson - We are currently running v14.0 in production and this seems to still be an issue with the [ Send Group Attendance Digest ] Job. Let me know if there is any information I can provide to help with this issue.
