### ISSUE TITLE
Backtabbing into a dynamic data block page gives unending pulsing blob

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#1236] opened 2015-09-06 20:14 UTC
I have a dynamic block page from which I'm linking through to a detailed page.
If I try to backtab using the browser back button to the dynamic data block page, I get the unending pulsing orange blob.
If I click in the URL displayed for the page and press enter the page refreshes immediately.

**Comment by ElimAdmin** [comment] 2015-09-21 18:49
@azturner  David, I don't think this is limited to dynamic data block pages.

**Comment by azturner** [comment] 2015-09-22 18:17
@ElimAdmin, I can't reproduce this. Tried here: http://rock.rocksolidchurchdemo.com/page/5314. If this is happening on other pages besides the dynamic data block is there some common denominator, or are you saying you just see this whenever you navigate backward from any Rock page?

**Comment by ElimAdmin** [comment] 2015-09-22 20:06
@azturner Nor can I.  Maybe it happens after the page has been left open for a long time.  I'll see if I can reproduce it...

**Comment by azturner** [comment] 2015-09-28 17:05
Closing this for now, feel free to re-open if you're able to reproduce it.

**Closed by azturner** 2015-09-28 17:05 UTC
