### ISSUE TITLE
RegistrationInstanceDetail Does not have UI for Waitlist

### ISSUE THREAD

**Issue by DTS-Mike** [SparkDevNetwork/Rock#3337] opened 2018-10-16 06:06 UTC
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
When adding people to a registration waitlist the UI does not show the data.  The last section of code in RegistrationInstanceDetail.ascx is for GroupPlacement and not Wiatlist.

### Steps to Reproduce
1. Add People to Event Registration Waitlist
1. Click on Waitlist
1. At the top of the page you will see the error: ![image](https://user-images.githubusercontent.com/24752345/46995726-8b690480-d0df-11e8-9a60-906e025bbbcf.png)

**Expected behavior:**

Expected to see a list of people on the Waitlist

**Actual behavior:**

Error message "The given key was not present in the dictionary."

### Versions
* **Rock Version:** [1.8.3]
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by JimMichael** [comment] 2018-10-16 18:48
I can confirm this happens here, and hopefully this is one of those "just add this to the file" type fixes as it's pretty debilitating since we're in the middle of some signups that have waitlisted people and no way to manage them.

**Comment by ethan-sparkdevnetwork** [comment] 2018-10-18 22:51
This is a bug showing the mobile phone number on the waitlist. It has already been fixed on 8.5 in commit 7f0dc49f.

**Closed** 2018-10-18 22:52 UTC
Labels: Fixed in v8.5
