### ISSUE TITLE
Different Email Transports using different File Names for Attachments

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#5696] opened 2023-12-14 21:34 UTC
### Description

A workflow using the Create Contribution Statement action to generate contribution statements and then the Send Email action generates attachments on the emails with different names depending on the email transport used.

If the SMTP transport is used, the attachments are names as desired, using the following configuration items from the `Create Contribution Statement` action as part of the filename:

1.	The giver’s name
2.	The Document Type
3.	The Document Purpose Key

This is the desired outcome as it is using the File Name that you would see elsewhere the file is used in Rock.

If the SendGrid HTTP transport is used, the file name for any/all attachments will all be identical, using only the file type name and the extension.

### Actual Behavior

The workflow is configured to generate several statements with the settings like this (one action per statement) below, and stored in a `Binary File` workflow attribute as shown:

![image](https://github.com/SparkDevNetwork/Rock/assets/19762670/a31f44b8-ab86-42e8-9a3f-399e19292422)

And then email the statement using these settings:
![image](https://github.com/SparkDevNetwork/Rock/assets/19762670/a1884c8f-72f3-44f0-bf7d-280abcc20ab7)

If the email is sent using the SMTP transport the attachments will be named as expected:
<img width="563" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/19762670/da6bc128-31e7-415c-a16d-19a9ce64e1e5">

If the email is sent using the SendGrid HTTP transport every attachment will have the same name from the document type:
<img width="563" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/19762670/5bbef232-4a8c-46d9-8da7-1b2143904630">

### Expected Behavior

The files should be named using (at least) the Document Purpose key regardless of the transport used, so the attachments can be distinguished from each other.

### Steps to Reproduce

1. Create a workflow type that will generate giving statements and set the Document Purpose Key with lava to give additional information in the name of the file.
2. Add a send email action to email the file as an attachment
3. Send the email using the SMTP transport and then the SendGrid HTTP transport and compare the file names of the attachments.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

14.2

### Client Culture Setting

en-US

**Comment by nairdo** [comment] 2023-12-20 16:35
@NuclearTacos We're not able to reproduce this.  We tested all three of the Rock core transports (SMTP, Mailgun HTTP, and SendGrid HTTP) and they are all working the same.  Here is a screenshot from the final SendGrid test:

![image](https://github.com/SparkDevNetwork/Rock/assets/383807/6d14fd8b-24be-41d2-9513-9c15ad9be4fb)

...and here is a debug screenshot showing the filename being passed to the sendGridMessage library:
![image](https://github.com/SparkDevNetwork/Rock/assets/383807/c08d88e1-17a5-43d5-81a4-020dbe8ae044)

Would you confirm that you're using the core SendGrid HTTP transport and would you be willing to send me an export of the workflow type you're testing with.  (Perhaps there is something in there I'm doing differently.)

**Comment by nairdo** [comment] 2023-12-26 14:37
Also, can you check to see if you still have an old Bricks & Mortar SendGrid plugin installed (verify that you're not using it) and if you are not using it, you _might_ consider removing the DLLs that came with it.  

As per the `deletefile.lst` in the last version of that plugin, the files that come with it are:
 * `bin\com.bricksandmortarstudio.SendGrid.dll`
 * `bin\Sendgrid.Webhooks.dll` 
 * `Webhooks\SendGrid.ashx` 
  
These are not used by Rock core.  Rock core uses `bin\SendGrid.dll` and 'Webhooks\TwilioSendGrid.ashx`.

**Comment by nairdo** [comment] 2024-01-08 21:52
@NuclearTacos Chris, since we've not been able to reproduce this, we'll close it for now, but please do let us know if you find the other answers to those questions above.  In that case we can reopen this issue with the new information.

**Closed by nairdo** 2024-01-08 21:52 UTC
Labels: Not Yet Reproduced
