### ISSUE TITLE
Campus Context is not working on the Group Finder Block (until you refresh the page)

### ISSUE THREAD

**Issue by bartbrueck** [SparkDevNetwork/Rock#5037] opened 2022-06-06 16:35 UTC
#### A Picture Is worth a Thousand Words
No picture given.

### Description
Setting a campus context by passing the Campus Id via an URL Parameter is not working on the Group Finder Page/Block. We have a campus context setter block and are passing the campus Id in the url such as: https://churchbcc.org/greenlakegroups?CampusId=1

### Steps to Reproduce
1-On the demo site… Enable campus context in the block settings on the Group finder Page - https://rock.rocksolidchurchdemo.com/page/236 in the demo instance.

2-Access the page from an incognito window and pass campus Id in the url (eg: https://rock.rocksolidchurchdemo.com/page/236?CampusId=1). Make sure there is atleast one group with the campus selected.

2.1-Expected behavior -

2.2-Actual Behavior -

**Expected behavior:**

The result set of groups should be limited to the campus passed.

**Actual behavior:**

All groups are listed.

Comparison - Sign in as Alisha Admin and access the page. It will use her campus context to display the groups.

So Campus context seems to work when someone is logged in, but not through the url parameter.

Similar settings (passing campus id via url parameter and enabling campus context on the block) work for the Events Calendar Lava Block on the Events Page - https://rock.rocksolidchurchdemo.com/page/397.

### Versions
* **Rock Version:** 13.2
* **Client Culture Setting:** en-US

**Comment by leahjennings** [comment] 2022-06-07 02:20
@bartbrueck thanks for submitting this with the information necessary to get to the bottom of what you're encountering! I tried reproducing the issue, and while you are correct that passing a Campus Id via the URL doesn't work, the why behind that is different than what you may be expecting.

By design, the Group Finder block does support Campus Context however Campus Context and filtering results using a Campus Id via the URL are two different features. The Campus Context works by storing a cookie in the browser, and when a block on the page also supports Campus Context, whatever campus is stored in that cookie is what filters the content of the block. You can give the end user the ability to change the campus stored in the context by adding a _Campus Context Setter_ block to the same page as the Group Finder block.

If you'd like the ability to pass the Campus Id via the URL, you'll want to submit an idea for that [here](https://community.rockrms.com/Ideas). As an additional note, this seems to be related / duplicate of [#4355](https://github.com/SparkDevNetwork/Rock/issues/4355).

**Closed by leahjennings** 2022-06-07 02:20 UTC
Labels: Type: Enhancement, Type: Duplicate
