### ISSUE TITLE
Discount code deleted when making additional payments

### ISSUE THREAD

**Issue by ambermccoy** [SparkDevNetwork/Rock#3669] opened 2019-04-30 20:52 UTC
### Description
We have a registration with multiple discount codes that are auto-applied based on the date of registration.  We do not require full payment when registering. When the parent goes to make an additional payment at a later time, their discount code is gone and it is showing the full amount of the registration due. 

### Steps to Reproduce
1. Create Registration with discount code(s) that auto-apply based on date of registration
1. Person registers and doesn't pay the full amount
1. Person comes back at a later time to make additional payments
1. Check balance due and see that it is for the wrong amount. ![Screen Shot 2019-04-30 at 4 44 07 PM](https://user-images.githubusercontent.com/29762314/56992466-23a07580-6b68-11e9-8266-79828c65c478.png)

**Expected behavior:**

Once the person is registered and the discount code is applied, their registration amount should remained fixed. The person should be able to come back and make additional payments without the discount code disappearing off their registration.

**Actual behavior:**

Person comes back to make additional payments and the discount code is gone and the full registration amount is now showing due. 

### Versions
* **Rock Version:** Rock Version: Rock McKinley 8.4 (1.8.4.40) 
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment] 2019-04-30 22:02
If someone from the community can reproduce this issue, I'd be grateful.  I was unable to make this problem happen on the [v8.6 demo](https://www.rocksolidchurchdemo.com/page/12) site.

After registering two kids with 'staff' discount and making initial $110 partial payment during registration, then returning later in the day to pay $10 more:
![image](https://user-images.githubusercontent.com/383807/56995932-f8158f00-6b57-11e9-9a6c-8767e8d5030a.png)

The discount % remains:
![image](https://user-images.githubusercontent.com/383807/56995799-981ee880-6b57-11e9-8eb5-e79f8bbcb2c9.png)

And returning to pay again, the discount amount remains:
![image](https://user-images.githubusercontent.com/383807/56996008-2dba7800-6b58-11e9-85fd-ae055e0e0f45.png)

...even after a manual cash payment via the internal site...
![image](https://user-images.githubusercontent.com/383807/56996141-7e31d580-6b58-11e9-9e90-08f6afa93117.png)

The log shows:
![image](https://user-images.githubusercontent.com/383807/56996202-a3bedf00-6b58-11e9-9fee-1f70adba3215.png)

...and the discount remains:
![image](https://user-images.githubusercontent.com/383807/56996232-b507eb80-6b58-11e9-86ff-54b8aead3519.png)

**Comment by ambermccoy** [comment] 2019-04-30 23:00
Hi Nick, I believe this is only happening when you have the code Au͏t͏o-generate based on a specific day/date range. For example, we have $70 off if they registered on 3/21. Then $50 off if they registered between 3/22 and 4/1, etc. It seems like it re-Au͏t͏o applies (or doesn’t apply anything if the dates are out of range) whatever the current code is instead of what they originally received.

**Comment by cabal95** [comment] 2019-04-30 23:05
@ambermccoy Just for some extra clarification, are you saying the discount code vanishes *only* when the registrar goes in via the public portal to make an additional payment, or does it also vanish if you go in to add a manual payment via the internal/staff pages?

I haven't looked at the code, but I can see what you mention about the auto-applied via date ranges making sense if it is looking at "todays date" vs the "registration date". Just trying to determine if this is a potential issue with just that one block or across the board with the discount counts.

**Comment by ambermccoy** [comment] 2019-04-30 23:21
Both times they were on the external “my account” page.  In the instance I have on my screenshot she registered on 3/21and got $70 off. That code was only good for 3/21. She then came back on 3/25 (or some time around then) and made an additional payment and it changed the discount amount to $40 which was the code that was in effect at that time. She then came back and made an additional and final payment on 4/30 and there was no code applied because there was not one in effect at that time.  It appears that every time they login from the external site it’s changing the discount code to whatever is in effect for that date instead of just leaving it from what it was on the registration date. 
 I have the added a couple of manual payments on the backend and that does not affect the discount code that is on the registration.

**Comment by HansenGrace** [comment] 2019-04-30 23:23
Thanks for your input. We will add this into our pipeline for additional review and next steps.
--

**Comment by chrisfunk** [comment] 2019-05-02 12:11
@nairdo  it sounds eerily similar to #3532

**Comment by cj-walk** [comment] 2019-05-08 15:11
I'm having the same issue. We have several discount codes set up for summer camp and seem to have an issue with one of the codes. Parents register (cost is $550), and apply the code, reducing the cost to $450, and pay a deposit of $50. At the time they register the correct amount is shown. However, sometimes - and it doesn't happen every time - on my end it doesn't show that a discount code was used, and when they log back in to pay the balance the discount code is no longer reflected and there is no option to enter it again (which they shouldn't need to). I had tested last week and never could reproduce the problem on my end, but after reports from parents again this week I just tested and got the same result. What could be making this discount code disappear? It doesn't seem to be consistently happening because I haven't been able to reproduce the issue myself until this morning. Immediately after registering I checked internally and the discount code was not there. My discount code has no dates or use limits.

**Comment by TheCoreyHall** [comment] 2019-05-10 18:18
I have discovered the same issue at one of my clients. They are on 8.6.

**Comment by HansenGrace** [comment] 2019-05-10 18:27
Thanks for all your input. We’ll increase the priority on this and look for a solution.

**Comment by TheCoreyHall** [comment] 2019-05-10 18:42
Here is an example from one of my clients. Personal information blacked out. You can see at the bottom they added the discount code when the registered, then they added a first payment later. After that, the returned to pay again, and on the timestamps on the right, you can see that the discount was deleted at this time. The user it says who deleted it was the parent who was paying so we know that didnt happen manually.
![image](https://user-images.githubusercontent.com/38293092/57549439-26018d00-7329-11e9-8cf2-c30d3f84f342.png)

**Comment by TheCoreyHall** [comment] 2019-06-28 21:31
Still nothing found? My client on 8.5 experiences this issue every other week it seems.

**Comment by nairdo** [comment] 2019-07-01 16:57
Since I had no luck reproducing this issue on v8.8 or v9 (today), I created a Rock v8.4 system and **_was_** able to reproduce the issue there.  So, as @chrisfunk hinted at above, and as @mikejed mentions in issue #3532:

>  I want to note that this also fixes the issue of auto-applied date-dependent discounts ("early bird discounts") from being removed when payments are made after the discount expires.

...this appears to have been fixed in version v8.7 with this change: https://github.com/SparkDevNetwork/Rock/commit/7fcfe7f6ad3be3a26e0f8d1e7d8132887e14dac7. 

I'm going to close this issue but please feel free to open it once you've upgraded to v8.8 if you are still able to reproduce this bug.

**Closed by nairdo** 2019-07-01 16:57 UTC
Labels: Not Yet Reproduced
