### ISSUE TITLE
Unable to load Person Profiles with emojis

### ISSUE THREAD

**Issue by mattgeorgelc** [SparkDevNetwork/Rock#5855] opened 2024-04-29 19:29 UTC
### Description

When a user has and emoji in their NickName or LastName their profile fails to load. The issue appears to be related to generating their avatar.
![image](https://github.com/SparkDevNetwork/Rock/assets/158209049/b82bab6c-61e4-4a5b-b1e4-31402bd8ce69)

### Actual Behavior

We can confirm this behavior in a clean install of Rock v16.4 and the latest PreAlpha 1.17.0.17.

Note: the core New Family page (using the New Group block) does not allow emojis in the person name and will show an error on the page rather than creating the person record:
![image](https://github.com/SparkDevNetwork/Rock/assets/158209049/5b20777c-6718-47e6-a273-de10cf38dd5d)

However, the Person from Fields workflow action and a call to the POST /api/People endpoint do create the records with the requested names. Loading profiles created starting with emojis from either of these methods results in the exception.

**ArgumentException in System.Web**
**Message**

Error serializing value `<img src="/GetAvatar.ashx?PhotoId=&AgeClassification=Adult&Gender=Unknown&RecordTypeId=1&Text=&Size=400&Style=icon&BackgroundColor=E4E4E7&ForegroundColor=A1A1AA" alt class="img-profile">` of type 'System.String.'

**Stack Trace**
```
   at System.Web.UI.ObjectStateFormatter.SerializeValue(SerializerBinaryWriter writer, Object value)
   at System.Web.UI.ObjectStateFormatter.Serialize(Object stateGraph, Purpose purpose)
   at Rock.Web.UI.RockHiddenFieldPageStatePersister.Save() in \Rock\Web\UI\RockHiddenFieldPageStatePersister.cs:line 176
   at Rock.Web.UI.RockPage.SavePageStateToPersistenceMedium(Object state) in \Rock\Web\UI\RockPage.cs:line 719
   at System.Web.UI.Page.SaveAllState()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

**- EncoderFallbackException in mscorlib
Message**
Unable to translate Unicode character \uD83C at index 94 to specified code page.
**Stack Trace**

```
 at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(Char ch, Char*& chars)
   at System.Text.UTF8Encoding.GetByteCount(Char* chars, Int32 count, EncoderNLS baseEncoder)
   at System.Text.UTF8Encoding.GetByteCount(String chars)
   at System.IO.BinaryWriter.Write(String value)
   at System.Web.UI.ObjectStateFormatter.SerializeValue(SerializerBinaryWriter writer, Object value) 

```

However, it appears that only leading emojis cause the issues: a name that contains emojis in the middle of the name, or ending with an emoji creates the person in the New Family page as well as in workflows, and the resulting person profile loads successfully.

### Expected Behavior

The profile either loads with the emoji or the emoji is removed as the lead character

### Steps to Reproduce

- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.4

### Client Culture Setting

en-US

**Comment by chead4** [comment] 2024-04-29 22:03
@mattgeorgelc Hi Matt  After reviewing, I will be closing this issue as a duplicate of [#5850](https://github.com/SparkDevNetwork/Rock/issues/5850) and will include your use case of adding an emoji to the beginning of a person's name to our internal ticket. Keep a eye on [#5850](https://github.com/SparkDevNetwork/Rock/issues/5850) to stay updated on when the issue will be resolved.

**Closed by chead4** 2024-04-29 22:03 UTC
