### ISSUE TITLE
Event Registration Fee - Enable Quantity - Zero Value

### ISSUE THREAD

**Issue by BemaDavidBensen** [SparkDevNetwork/Rock#3382] opened 2018-10-29 14:37 UTC
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
Event Registration Fees only work for single quantity , If "Enable Quantity " is check marked, the fee will no longer be required. 

### Steps to Reproduce
1. Setup a Event Registration
1. Add a fee
1. Enable Quantity  and Required
1. Test event and see that a fee can have a Quantity  of "0"

**Expected behavior:**

A fee with "Enable Quantity " and "Required" should not allow a zero amount

**Actual behavior:**

A fee with Enabled Quanity and Required allowes you to skip the fee or put zero in the amount field

### Versions
* **Rock Version:** 8.4
* **Client Culture Setting:** en-us

**Comment by nairdo** [comment] 2019-10-24 19:26
Hi David @BemaDavidBensen We've gotten a report in the #bugapalooza channel as 'not reproducible' in v11.  There has been a lot of movement in Event Registration since v8.4, so if you feel like this is being closed in error please let us know by re-opening this issue.

**Closed by nairdo** 2019-10-24 19:26 UTC
Labels: Not Yet Reproduced, bugapalooza: Is Needed?
