### ISSUE TITLE
Communication Entry from Group Toolbox: Leader's From Email Address Is Not Honored In Sent Email

### ISSUE THREAD

**Issue by bmeeks-9embers** [SparkDevNetwork/Rock#6136] opened 2024-12-19 21:49 UTC
### Description

When a group leader sends an email from their Group Leader Toolbox, the from email address they set is not reflected in the sent email. The received email shows the church's default email address instead of what the leader entered.

As entered by the group leader:
![image](https://github.com/user-attachments/assets/ec919087-f0b6-4815-bde7-2d3e495a8bc0)

Received email:
![image](https://github.com/user-attachments/assets/229d0330-7036-4153-ae0d-aa79448f17ec)
![image](https://github.com/user-attachments/assets/03d2956a-8366-444c-b0c6-29e7c2a86fa9)

Communication in Rock:
![image](https://github.com/user-attachments/assets/92919648-f5c4-4ebf-984f-72efa5d1ab6e)

### Actual Behavior

The email received appears to be sent by the church's email and not the group leader. 

### Expected Behavior

The group leader's email address that is set when creating the communication is what is used in the sent email. As a leader, if I send an email to my group I would expect that if someone replies to it that it would be sent to me and not the church.

### Steps to Reproduce

- Go to /MyAccount page in rock as a person that is a group leader
- Click into the group
- Click "Email Roster"
- Enter Subject and Message
- Click "Send Communication"
- Check received email in inbox to see the From email address.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.6

### Client Culture Setting

en-US

**Comment by JimMichael** [comment] 2024-12-19 23:05
This is working as designed. Rock MUST substitute the from address for domains that aren't owned-by-your-organization (e.g gmail.com), otherwise it would be _forging_ the from address and the mail would 100% be dropped by the recipient mail server. Back in the day, forging an email address and sending it from your server "just worked", but in 2024? No way.

Your Rock server is **not** allowed to send mail pretending to be from gmail.com (or any other commercial email provider), with the exception being any domains you own that are also listed in the _Safe Senders_ list. 

So, Rock does the only thing it can and substitures the FROM address with the ORG address, to actually let it deliver. It does, however, make the REPLY-TO address that of the actual sender, so replies _from clients that honor reply-to_ will go back to the sender, not the org.

https://community.rockrms.com/documentation/bookcontent/8/298#safesenderdomains

**Comment by nairdo** [comment] 2024-12-20 15:13
We agree with Jim's (@JimMichael) assessment—it aligns with the intended design. Therefore, we’re closing this issue.

**Closed by nairdo** 2024-12-20 15:13 UTC
Labels: Type: Bug, Status: Confirmed

**Comment by JimMichael** [comment] 2025-01-14 20:26
@ThomasStephens17 This issue is not related to the 6149 bug. This issue has to do with the (necessary) substitution that happens when you send to a non-safe-sender domain. 6149 is dealing with broken reply-to.

**Comment by ThomasStephens17** [comment] 2025-01-14 20:30
@JimMichael I understand how the substitution happens. Reading between the lines here, I would imagine he is experiencing the bug referenced in that other ticket, without knowing exactly why.

The 3rd screen shot is a reply to with the wrong email address included.

Also, as other experience this issue, they may stumble upon this ticket.

**Comment by JimMichael** [comment] 2025-01-14 20:39
I see your point, but the initial screen shot literally shows it coming FROM someone@gmail.com and he says (under Expected Behavior) he expects the recipient to receive it FROM that address, which is impossible (because of the necessary substitution). 

It's also important to know that not all clients honor reply-to (even when it's not broken.) Some will always "reply to" the FROM address and ignore the reply-to.
