### ISSUE TITLE
[EN] Change Slingshot to handle multiple updates of person data

### ISSUE THREAD

**Issue by JoshuaMaiorino** [SparkDevNetwork/Rock#3530] opened 2019-02-06 13:47 UTC
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
There's a bug in the Update portion of slingshot.  If after doing an initial import, A person's family is changed in the legacy system, and then an update is attempted, and there's an address within that family it will throw an Insert error when trying to add the new address.

This bug is reported in the slingshot repot here, however the code is in Rock. https://github.com/SparkDevNetwork/Slingshot/issues/3

### Steps to Reproduce
1. Import data from a legacy system
1. Move an individual from there current family and add them to a new family with an address in the legacy system
1. Import with Update again

**Expected behavior:**

The import should add the new family prior to updating the person record.

**Actual behavior:**

Slingshot attempts to update the person, and add the new address to a family that hasn't been inserted yet, and thus throws an insert error.

### Versions
* **Rock Version:** [7+]
* **Client Culture Setting:** [EN-US]

**Comment by JoshuaMaiorino** [comment] 2019-02-06 13:52
```                    
                    if ( this.ImportUpdateOption == ImportUpdateType.AlwaysUpdate )
                    {
                        Stopwatch stopwatchPersonUpdates = Stopwatch.StartNew();
                        bool wasChanged = UpdatePersonFromPersonImport( person, personImport, attributeValuesLookup, familiesLookup, foreignSystemKey, importDateTime );
                        stopwatchPersonUpdates.Stop();
                        personUpdatesMS += stopwatchPersonUpdates.ElapsedMilliseconds;
                        if ( wasChanged )
                        {
                            personUpdatesCount++;
                        }
                    }
```

Instead of performing the actual update here, I wonder if it makes sense to store the people to update in a list, and then loop through them after the bulk inserts, which would add the families, prior to trying to add the locations.  The family lookup would also have to be updated post inserting the new records.  or just how the primary family is gotten would have to be changed.

**Comment by nairdo** [comment] 2019-05-09 05:02
I confirmed this today with the team and the original intent of Slingshot is a one time import of data -- it's not intended for continual syncing use.  Having said that, it sounds like we may adjust Slingshot in the future to deal with second import attempts (for only a very limited set of data however).  Slingshot is not intended to be used as a sync tool.

**Comment by jonedmiston** [comment] 2019-08-23 16:53
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/ideas) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.

**Closed by jonedmiston** 2019-08-23 16:53 UTC
Labels: Priority: Low, Type: Enhancement
