### ISSUE TITLE
eRA Status Ignores Current Week Check In

### ISSUE THREAD

**Issue by timlem** [SparkDevNetwork/Rock#3828] opened 2019-07-30 13:41 UTC
### Description
I included a video to better/fully explain. https://www.youtube.com/watch?v=mDwYgfH4QP0

But basically if someone doesn't check in for four weeks but checks in on the 5th week and the eRA job runs that week they lose eRA status. So it confuses people when I tell them yes they lost eRA status because they didn't check in for four weeks but they say they just checked in Sunday. :slightly_smiling_face:  Watch video for details please.

### Steps to Reproduce
1. Have a current eRA that doesn't give not check in for four weeks. Fourth week being July 28th for this example
1. eRA job runs on July 28th or anytime during the week of July 28th-Aug 3rd and they will not lose eRA status.
1. If eRA job runs on Aug4th-Aug 10th the person will lose eRA status even if they check in on Aug 4th.

**Expected behavior:**

I would expect the eRA job to run on a Sunday/Monday and take into consideration that Sundays status.

**Actual behavior:**

eRA runs and looks at the 5 weeks prior instead of four.

### Versions
* **Rock Version:** 8.8 (1.8.8.3)
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by nairdo** [comment] 2020-03-23 20:47
@timlem Based on the data for that family, we believe the calculation is working correctly.  

> Criteria for Exiting an eRA
>
> + Haven't given in over 8 weeks
> + (and) have attended less than 8 times in the last 16 weeks
> + (and) haven't attended at all in the last 4 weeks

Let's walk through the logic together to see if you agree. For example, looking at the data you provided in the video, up to but not including the 7/28 weekend it looks like this:

|Week # | Date | Attended/Missed | Rolling 16 Week Total |
|-------|------|------------------|-----------------------|
| 16    | 7/21 | Missed           |                       |
| 15    | 7/14 | Missed           |                       |
| 14    | 7/07 | Missed           |                       |
| 13    | 6/30 | Missed           |                       |
| 12    | 6/23 | Attended         |  3                    |
| 11    | 6/16 | Missed           |                       |
| 10    | 6/09 | Attended         |  2                    |
|  9    | 6/02 | Missed           |                       |
|  8    | 5/26 | Missed           |                       |
|  7    | 5/19 | Missed           |                       |
|  6    | 5/12 | Missed           |                       |
|  5    | 5/05 | Missed           |                       |
|  4    | 4/28 | Missed           |                       |
|  3    | 4/21 | Missed           |                       |
|  2    | 4/14 | Attended         |  1                    |
|  1    | 4/07 | Missed           |                       |

This is where the exit occurs.

As soon as the Family Analytics runs for that cycle, they will be considered "exiting" because:
 + [assuming there was no give in the last 8 weeks (5/26-7/21)]
 + and there was less than 8 attendance in the 16 weeks
 + and there was no attendance in the last four weeks (6/30 - 7/21)

If we look at the next week's attendance data on 7/28, they would then be working their way back toward becoming an eRA:

|Week # | Date | Attended/Missed | Rolling 16 Week Total |
|-------|------|------------------|-----------------------|
| 16    | 7/28 | Attended         |  4                   |
| 15    | 7/21 | Missed           |                       |
| 14    | 7/14 | Missed           |                       |
| 13    | 7/07 | Missed           |                       |
| 12    | 6/30 | Missed           |                       |
| 11    | 6/23 | Attended         |  3                    |
| 10    | 6/16 | Missed           |                       |
|  9    | 6/09 | Attended         |  2                    |
|  8    | 6/02 | Missed           |                       |
|  7    | 5/26 | Missed           |                       |
|  6    | 5/19 | Missed           |                       |
|  5    | 5/12 | Missed           |                       |
|  4    | 5/05 | Missed           |                       |
|  3    | 4/28 | Missed           |                       |
|  2    | 4/21 | Missed           |                       |
|  1    | 4/14 | Attended         |  1                    |

Does this illustration explain how it happened?

**Comment by timlem** [comment] 2020-03-31 17:15
Hi Nick thanks for taking the time out to explain that. Here's some thoughts.

Using that as the example - would it make more sense to have the eRA Job run on Monday instead of Sunday? Because our campus coordinator doesn't understand why they didn't lose eRA status on 7/21 but instead lost status on 7/28 after they had attended.

**Comment by nairdo** [comment] 2020-03-31 19:49
@timlem I would probably set it up to run as soon as the "week" has ended -- just at the start of a new week so all the past details can be accounted for (like closing Financial books after the end of the month).

**Closed by nairdo** 2020-03-31 19:49 UTC
Labels: Topic: CRM, Type: Bug

**Comment by JimMichael** [comment] 2020-03-31 20:13
Just for completeness-sake, I'll note that the default job fires on Tuesdays at 8pm. I assumed some thought had been put into that day/time, which now seems confirmed.

**Comment by azturner** [comment] 2022-07-08 09:49
@nairdo  This actually seems to be a valid issue. We saw someone lose their eRA when job ran on 7/4, even though they had attended on 7/3 and  they were still an eRA before 7/4. It's because the SQL in the job only looks at attendance records that have a date <= the previous sunday's date (2022-07-03 00:00:00) and person had checked in later than that (2022-07-03 11:19:16.223). 

When the spCrm_FamilyAnalyticsEraDataset is calculating the number of giving and attendance weeks, it is comparing the actual time of transactions and time of check-in to the duration's Sunday dates. It seems like it should use the calculated Sunday date of transactions and check-ins instead. For example, this line in that query is why our person lost their eRA even though they had attended the previous weekend:

https://github.com/SparkDevNetwork/Rock/blob/2327647a6ebb1deced052014aad1161d93b537f1/database/Procedures/spCrm_FamilyAnalyticsEraDataset.sql#L171

If that where clause used the check-in's occurrence or Sunday date instead (without the time), they would not of lost the eRA.  Here's history of family's attendance too since they last became an eRA on 9/27/2021 if it helps:

SundayDate
2022-07-03
2022-05-15
2022-05-08
2022-05-01
2022-04-17
2022-04-10
2022-03-27
2022-03-20
2022-03-06
2022-02-27
2022-02-13
2022-02-06
2022-01-30
2022-01-16
2022-01-09
2022-01-02
2021-12-12
2021-12-05
2021-11-28
2021-11-21
2021-11-14
2021-10-31
2021-10-17
2021-10-10
2021-10-03

**Comment by azturner** [comment] 2022-07-12 19:32
@nairdo, would you prefer I submit a new issue with details from comment above?
