### ISSUE TITLE
Connection Board does not show all assigned requests when filtered by connector

### ISSUE THREAD

**Issue by KelleyLangkamp** [SparkDevNetwork/Rock#4632] opened 2021-03-17 16:47 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

Connection Requests do not show on the connection board if the connector person alias is not their primary alias. i.e. Their record was merged after they were assigned but the other person record was chosen as the primary. All the connection requests show on the All Connectors view, this only happens when the connector is filtered to a specific individual.

![image](https://user-images.githubusercontent.com/12735965/111503624-e79f3b00-8714-11eb-9f66-887972f67259.png)
![image](https://user-images.githubusercontent.com/12735965/111503709-fd146500-8714-11eb-963b-15c6b06b43e4.png)

### Steps to Reproduce

1. Assign a Connection Request to Tom Miller
2. Create a new duplicate Tom Miller record
3. Merge the Tom Millers but choose the new one as the primary record (i.e. that is the one with the check at the top of the merge people block)
4. Go to the Connection Board and see that the request shows it is assigned to Tom Miller
5. Click on All Connectors at the top and filter to Tom Miller
6. No Connection Requests show in the block

**Expected behavior:**

Filtering by Connector would still show requests assigned after records are merged.

**Actual behavior:**

Only requests where the ConnectorPersonAliasId is the Connector's primary alias id show up.

### Versions

* **Rock Version:** [12.0]
* **Client Culture Setting:** [en-us]

**Comment by nairdo** [comment] 2021-03-19 00:24
@KelleyLangkamp  We're having a bit of trouble with this one.  Can you include a screenshot showing how you are "Filtering by Connector"?

**Comment by nairdo** [comment] 2021-03-23 18:20
Unable to reproduce on `Rock Version: Rock McKinley 12.0 (1.12.0.12)`.  If anyone else is able to reproduce, please let us know.

**Comment by marcierempel** [comment] 2021-05-05 19:13
We are experiencing the same issue, running on v12.2.  The Connector filter isn't showing all assigned requests when filtering by Connector. Some connectors work, some don't. 
![image](https://user-images.githubusercontent.com/44587882/117196375-a1c13380-ada3-11eb-9d9b-92a0cb701c7d.png)

**Comment by marcierempel** [comment] 2021-05-05 19:14
![image](https://user-images.githubusercontent.com/44587882/117196433-b43b6d00-ada3-11eb-862c-6e2bc030fec6.png)When filtered by Gerry Matheson, nothing shows up on the list.

**Comment by marcierempel** [comment] 2021-05-05 19:14
But when filtering by Betty Matheson, the list of requests assigned to her show up.
![image](https://user-images.githubusercontent.com/44587882/117196553-daf9a380-ada3-11eb-9484-a89e4896bc9f.png)

**Comment by tstephens17** [comment] 2021-05-12 16:48
We are seeing this in 12.3 as well.

**Comment by azturner** [comment] 2021-08-12 15:42
We are seeing this in v12.4 as well.

When filtering by connector of Anthony Borum in the new connection board, we only see 15 connection requests:

![image](https://user-images.githubusercontent.com/548180/129225975-cfaa3fa2-165b-4d43-b1f4-dc0fbe8852f6.png)

When using the legacy connection list, we see all 174 of his requests:

![image](https://user-images.githubusercontent.com/548180/129226062-35692b02-95ab-4fc5-a177-67bf4fb095a8.png)

It appears that the new board is only showing requests associated with one of his person aliases (and it's not the primary one):

![image](https://user-images.githubusercontent.com/548180/129226168-4086a9bb-4ba3-4c2f-a5cb-613a2d6650fb.png)

**Comment by timlem** [comment] 2021-08-12 17:05
I have noticed that I have two versions of myself when assigning connections, even though there is only one Tim Lemons in the database.  Could this be related?

<img width="1552" alt="Screen Shot 2021-08-12 at 1 04 46 PM" src="https://user-images.githubusercontent.com/1486523/129238415-69b41af0-168f-41a9-a4e6-582a6e25355a.png">

**Comment by JoshuaMaiorino** [comment] 2021-08-24 14:03
I've discovered the cause of this bug, and why you can't replicated in demo.

notice lines 401 - 402 in the ConnectionRequestSerive.partial.cs:
```// Filter by connector
            if ( args.ConnectorPersonAliasId.HasValue )
            {
                connectionRequestsQuery = connectionRequestsQuery.Where( cr => cr.ConnectorPersonAliasId == args.ConnectorPersonAliasId );
            }```

If a person record has been merged, their alias changes.  You should change this filter to look at the alias's person id on both sides.  Not the alias id.  As the same person record can have multiple alias ids.  @nairdo

**Comment by MikeDPeterson** [comment] 2021-08-24 16:33
@JoshuaMaiorino Nice job finding out the root cause of the bug!

**Closed** 2021-09-16 17:26 UTC
Labels: Type: Bug, Topic: UI, Topic: Connection
