### ISSUE TITLE
Obsidian Batch List Block | Name Filter - Equals Not Working

### ISSUE THREAD

**Issue by ThomasStephens17** [SparkDevNetwork/Rock#5987] opened 2024-08-19 18:45 UTC
### Description

Using the name filter with the setting of EQUALS does not work. I suspect it has to do with the Batch Id also being in the column and the HTML getting in the way of the filter.

![image](https://github.com/user-attachments/assets/64640d32-d4e2-4ae6-8f1e-973ed7ff3319)
![image](https://github.com/user-attachments/assets/884772a7-87d5-4e1d-bebb-9821dca038d9)

If you change this filter to Equals, no results are shown. 

### Actual Behavior

Using the Equals filter results in nothing being shown.

### Expected Behavior

Expecting some way to use the exact filter. I tried several ways, including leaving out the batch id.

### Steps to Reproduce

- Go to 'https://rock.rocksolidchurchdemo.com/finance/batches'
- Attempt to filter by Equals using the text that is in a cell.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.5

### Client Culture Setting

en-US

**Comment by chead4** [comment] 2024-08-19 20:21
@ThomasStephens17 Hi Thomas  Thanks for reporting the issue.  After reviewing the issue, I am happy to share that the issue has been fixed with #5841 in v16.6.  Since the issue is resolved, I will go ahead and close this issue.

**Closed by chead4** 2024-08-19 20:21 UTC
