### ISSUE TITLE
Unable to Checkout When Absolute Threshold is met

### ISSUE THREAD

**Issue by chrisfunk** [SparkDevNetwork/Rock#3424] opened 2018-11-14 15:55 UTC
### Description
Rock Check in is not able to check a person out of a location when the allow checkout feature is enabled and a location has reached it's absolute threshold.  This has been tested in our environment and on a clean instance of Rock.

### Steps to Reproduce
1. Go to the Check in Configuration block (Admin Tools -> Check in -> Check in Configuration)
1. Click on an existing configuration
1. Click the Edit button 
1. Check the Allow Checkout checkbox
1. Save the configuration
1. Go to Check in Named Locations (Admin Tools -> Check in -> Named Location)
1. Find a location that is used in check in (i.e. Bobcats Room) and select it 
1. Click the Edit button
1. Set the Threshold and Absolute Threshold to 1
1. Save the location
1. Clear Rock Cache for good measure (not sure if it is required)
1. Browse to the check in site {Your Internal Site URL}/checkin
1. Select the configuration that you modified and applicable kiosk/group types
1. Check someone in to the location that you modified
1. Attempt to check them out,  you will not receive an action prompt to check the person out. 

**Expected behavior:**

You would receive the action prompt screen with the option to check out the checked in individual, and then be able to proceed to check them out.

**Actual behavior:**

You are either presented with the person select screen to check the individual in or you are presented with the no classes available error message.

### Versions
* **Rock Version:** 8.4 (1.8.4.40)
* **Client Culture Setting:** en-us

**Comment by vineyardcincy** [comment] 2019-10-24 15:57
Testing on the rock.solidchurchdemo site I was able to reproduce this. Would get the Closed screen when attempting to check-out.  Tried to override with pin code and the same result.  Was not able to check-out once the absolute threshold was reached.  I tested to be sure it was just the absolute and not the regular threshold and confirmed that it was.

![image](https://user-images.githubusercontent.com/53190843/67502927-bbcd7200-f654-11e9-9b91-9b9060f6972f.png)

**Comment by nairdo** [comment] 2020-03-17 17:24
@chrisfunk We're just doing some follow-up cleanup and when one of our developers was unable to reproduce it, he thinks this was fixed in v10 via this commit: https://github.com/SparkDevNetwork/Rock/commit/31e552d7dc2e7106e1559790c25e509942251822 (which might be because I failed to mention any bug as a reference in the commit message).

Can you confirm that this feature is now working as you expected in v10?

**Comment by nairdo** [comment] 2020-03-20 02:22
We'll close this one out, but please re-open if you are still seeing this situation in Rock v10.

**Closed by nairdo** 2020-03-20 02:22 UTC
Labels: Status: Attention Core Team, Status: Confirmed, Type: Bug, x-Fixed in v10.0
