### ISSUE TITLE
Giving Type Context Setter doesn't always set context

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2811] opened 2018-02-21 02:04 UTC
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The giving type context picker doesn't always set the context for the current person.  Which leads to the available contribution statements not being rendered and the transaction report returning nothing.

When the transaction report is set to not use the person context it returns the correct transactions for the person.

### Steps to Reproduce

Not entirely sure; we're having it reported by couples where there giving was separated and we've changed their giving to combined giving. We're able to observe the issue via impersonation.

**Expected behavior:** 

Always set context, render error if no context is provided.

**Actual behavior:** 

No context is set which renders a blank giving history.

### Versions

* **Rock Version:** 7.2  
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment] 2018-02-23 20:04
@garrettjohnson From looking at the code, it seems like there are only 2 situations where it wouldn't set the context on initial page load:

1. No person logged in. (Unlikely)
2. Context is already set to the logged in Person or a Business they are associated with. (This doesn't seem to be the case you are running into either)

If you can impersonate somebody with the issue, I wonder if you can verify if the context is not being set, or if the problem is in the "usage of" the context by other blocks.  I was able to add an HTML block to the bottom of the Main section with this content to show that the context was indeed being set.

```
{{ Context.Person.FullName }}
```

If it is blank then that would show for sure that the context is not being set (for some reason) vs being set, but not used correctly.

**Comment by MikeDPeterson** [comment] 2018-02-23 20:23
this is fixed with https://github.com/SparkDevNetwork/Rock/commit/97c984b1fa09a34a6cbf8c773d0cf47d45e128ee is in 7.3

**Closed by MikeDPeterson** 2018-02-23 20:23 UTC
Labels: Priority: Critical, Topic: Finance, Type: Bug
